### ISSUE TITLE
汎用DB：投稿時にエラー

### ISSUE THREAD

**Issue by tabimoba** [NetCommons3/NetCommons3#1013]
#961 の2を修正した影響で、画像フィールド、ファイルフィールドのいずれかあるいは両方が１つ以上存在するとエラーになった。

**Comment by rs-ohno-tomoyuki** [comment]
次回commit/pushにて修正反映

**Comment by onozaki** [comment]
3.1.5で、画像フィールドがある状態で画像を投稿せずに「決定」を押したところ、内部エラーが発生しました。というメッセージが出て上手く投稿されませんでした。

**Comment by rs-ohno-tomoyuki** [comment]
こちら、#1135 と同様の問題でしたので、修正されていると思います。
改善しない場合は対応いたします。
