### ISSUE TITLE
ページ設定の画面で、ページが階層表示されない。ページ追加しても追加されたかどうか確認できない。

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1014]
添付画像 (NC 3.1.3) のように、「むさしルーム」内のページが階層表示されていません。（以前は階層表示されていたと思うが・・・）
#989 ←スクリーンショットあり

このため「+ページ追加」でページを追加しても、本当に追加されたかどうかが、この画面ではわからない。更に、むさしルーム内のページの表示順序を変更できない（むさしルームに移動後、セッティングモードON > ページ設定 という手順が必要で手間がかかる）。

更に^2、コミュニティスペースが「ページ設定」に表示されていないため、コミュニティスペース内のルームの表示順序を変更できません。
#885 （ルームの並び替えができない）
![default](https://user-images.githubusercontent.com/7931689/29738149-cc6ed552-8a56-11e7-8626-358ca8d6aade.png)

**Comment by akagane99** [comment]
> 添付画像 (NC 3.1.3) のように、「むさしルーム」内のページが階層表示されていません。（以前は階層表示されていたと思うが・・・）

https://github.com/NetCommons3/NetCommons3/issues/922

上記修正により他ルームの階層は表示しない方で修正されてますね。

### 追加修正

* しかし、他ルームのページ追加が残っちゃっていたのが混乱の元っぽいです。修正も必要そうです。
* ここから、パブリックの別ルームのページ設定に飛べるように修正するのがよさそう。(パブの別ルームのページ設定の編集、自分もちょっと煩わしいと感じてました)

### ルームのページ設定の考え方

* ルームのページ設定は、そのルームに飛んでからページ設定する方向のようです（コミュニティルーム、プライベートルームも同様）

**Comment by akagane99** [comment]
こんな感じに修正しました。
![image](https://user-images.githubusercontent.com/2756509/29919465-5d560d34-8e84-11e7-8ec4-ac900431669b.png)
