### ISSUE TITLE
WYSIWYGでパスワード付きPDFをアップロードできない

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#1015]
NetCommons3.1.4でキャビネット、汎用DBではパスワード付きのPDFもアップロードできるのを確認しているが、WYSIWYGからパスワード付きPDFをアップロードしようとすると失敗する。

WYSIWYGはAjaxでアップロード処理を行ってる（POST先は /wysiwyg/file/upload ）ようなので、他のプラグインとは異なるアップロード処理のためと思われる

他にもAttachmentBehaviorを使わずにアップロードしてる箇所があればそこでも同じことが発生する可能性がある。

## 関連

- https://nc2.netcommons.org/bbiohsrx2-18477/#_18477
- https://nc2.netcommons.org/bb81rbd67-18477/#_18477

**Comment by akagane99** [comment]
WYSIWYGのファイルアップロード、ここかぁ。
https://github.com/NetCommons3/Wysiwyg/blob/master/Controller/WysiwygFileController.php#L88

どう対応したらいいんだろう。
調査途中だけど、とりあえずここまで。

**Comment by RyujiAMANO** [comment]
https://github.com/NetCommons3/Files/commit/7901d0b7721445f4539a61fb9d424d4383376a8d

AttachMentBehaviorでこんなんやったんだけど、これをUploadFileModelでもやらんとあかんのかなっておもってます。

UploadFile::registByFileあたりでやるのがいいのかな。ちょっとそのあたりみてみます
