### ISSUE TITLE
移行ツール利用手順問い合わせ

### ISSUE THREAD

**Issue by cb21-dev** [NetCommons3/NetCommons3#1021]
キャッチボール・トゥエンティワン開発チームです。
移行ツールを使おうとしていますがうまく行っていません。

GitHubよりNc2ToNC3をダウンロードし、Cakeのライブラリで動作するという認識でapp/Pluginに入れ、
README.mdに沿ってコマンドを実行しましたが、エラーが出てしまいます。コマンド実行までの利用手順をREADME.mdに記述お願い出来ますでしょうか。

エラーには2種類ぶつかって解決していません。

* パーミッションのエラー
* マイグレーションのエラー

これらを解決する何らかの事前の手順が存在する認識です。

**Comment by akagane99** [comment]
移行はやった事ないけど、以下参考まで。

> * パーミッションのエラー

パーミッション付ければ解消すんじゃないかなぁ。
もし解決してその情報を書き込めば、同じ問題で困ってる人も助かると思いますよ。

> * マイグレーションのエラー

エラーログが判れば、他の人が回答しやすいかと思いました。

後は、NetCommons3もくもく勉強会で聞いてみるのも１つの手かと思いました。

**Comment by RyujiAMANO** [comment]
汎用DBとか施設予約の移行ツール開発中に何度か移行ツール動かしてるけど、パーミッションやマイグレーションでエラーおこしたことないので、詳しく状況おしえてもらえると手順なり、バグなりを修正できるかなと思います。

・どのコマンドを実行したときに
・どのようなメッセージがでたのか

また環境について分かる範囲でもよいので下記の情報もあると原因調べやすいかと思います。
・サーバOSは何か？
・PHPのバージョンはいくつか？
・MySQLのバージョンは？
・移行元のNetCommons2のバージョンは？
・移行先となるNetCommons3のバージョンは？

**Comment by akagane99** [comment]
> * パーミッションのエラー

とりあえずwikiにインストール後のパーミッション、書いてみた。

https://github.com/NetCommons3/NetCommons3/wiki/%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E8%A6%81%E4%BB%B6#%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E5%BE%8C%E3%81%AE%E3%83%91%E3%83%BC%E3%83%9F%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3

参考まで。

**Comment by akagane99** [comment]
上記のパーミッションじゃなさそうですね。
移行時のパーミッションエラーってこれかなぁ？
マイグレーション実行で対応できました。

### エラー

```
Welcome to CakePHP v2.10.1 Console
---------------------------------------------------------------
App : app
Path: 
---------------------------------------------------------------
Error: Permission denied
#0 [internal function]: PermissionComponent->startup(Object(Nc2ToNc3Controller))
```

### マイグレーション実行して必要なDBテーブル作成

```
$ ./Console/cake Migrations.migration run all -p Nc2ToNc3  -c master -i master
```

**Comment by RyujiAMANO** [comment]
あ、もしかしてNC3ファイルを配置しただけでインストールしてないとか？

1. NC3インストール
2. Nc2ToNc3配置
3. マイグレーション実行
4. 移行ツール実行

って手順になるか。

**Comment by cb21-dev** [comment]
ご説明ありがとうございます。
バグやエラーの報告というより、READMEに利用手順が書かれていないので手探りになってしまっているので操作手順が欲しいという問い合わせでした。手順はどこかに書かれていますでしょうか？

**Comment by akagane99** [comment]
書いてないようです。
https://github.com/NetCommons3/NetCommons3/issues/1012

**Comment by akagane99** [comment]
どこにも書かれてないようなので、もしキャッチボールさんが移行できたなら、その手順を公開するのが良いかもしれません。
同じように困ってる方がいたら、助かると思いますよ。

もくもく会で聞くのも解決策の一つですね。
