### ISSUE TITLE
キャビネット、未承認or ダウンロードパスワード付zip解凍時の動作

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1024]
* 未承認のzipを承認者が解凍すると、承認済みファイルで解凍される
  * 承認まだなので、解凍したファイルが承認されちゃうのは、まずい感じがする。

* ダウンロードパスワード付zipを承認者が解凍すると、パスワード不要で解凍できて、解凍したファイルにダウンロードパスワードは付かない
  *  解凍時にパスワード聞かれないのは、何か変な感じがするけど、仕様なのかなぁ。

### 対応案

* 未承認のzipは、解凍リンクを表示しない
* ダウンロードパスワード付のzipは、解凍リンクを表示しない

**Comment by RyujiAMANO** [comment]
> ダウンロードパスワード付zipを承認者が解凍すると、パスワード不要で解凍できて、解凍したファイルにダウンロードパスワードは付かない

NC2の動作をまだ確認できてないけど、NC2ってどうだっけ？そもそもダウンロードパスワードとかなかったっけ？
NC2にもダウンロードパスワードあればそちらに仕様あわせる感じかな。
NC2にダウンロードパスワードがなければ、これも「解凍できない」ほういいような気が。
パスワードを知ってる人だけがダウンロードできるようにしたいファイルなのだから、中身がダウンロードパスワードなしでキャビネットに登録されるのがNGになるのかなぁと。


未承認ZIPの取り扱いは「解凍できなくする」で反対意見なければ、解凍できなくします。

**Comment by akagane99** [comment]
> NC2の動作をまだ確認できてないけど、NC2ってどうだっけ？そもそもダウンロードパスワードとかなかったっけ？

確認してみたら、なかったです。
とりあえず報告まで

![image](https://user-images.githubusercontent.com/2756509/30411395-9ee59bf8-994b-11e7-8cbd-f336b25fc8b6.png)
