### ISSUE TITLE
コミュニティに作成したルームの順番が変えられない

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1028]
パブリックに作成したルームの順番は「ページ設定」から変更可能だが、
コミュニティのルームは作成した順番で並んでおり、変更することができない。
これを変更可能にしてほしい。
できたらその並び順変更の操作は「管理」＞「ルーム管理」で変更できるようにしてほしい。

**Comment by onozaki** [comment]
こちらのissue、なにか対応策お持ちの方いらっしゃいますでしょうか？

**Comment by akagane99** [comment]
やるとしたら、ページ設定でコミュニティルームを上下移動できるように、UIから変更かなぁ。

**Comment by onozaki** [comment]
ページ設定だと、参加しているコミュニティルームの名称しか並ばない気がしたので、ルーム管理でやるのかな？と思ったのですが、その場合、上下移動できるのは全コミュニティルームに参加してなくても出来る感じなのでしょうか？？

**Comment by akagane99** [comment]
確かに。
その理由で、ページ設定にコミュニティルームの上下移動ないのか。

となるとルーム管理に実装ですね。
ルーム管理には上下移動の機能自体ないので、UIからになるので、作り始めたとしても時間かかりりそうと思いました。

**Comment by onozaki** [comment]
なるほどー。時間がかかりそうという状況なのですね。
現状、順番が変えられないので、並べたい順番にもう一度ルームを作り直し、中身を移して、古いルームを削除している状況です。
この方法も状況によってはできない場合もあるため、注意しながらルーム順を並べていますが。

並べ替えをできるようになるとより使い勝手が良くなると思うので、いつかこの部分も実装されるよう願っております。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Rooms/pull/187#event-2045165856
対応されました。
