### ISSUE TITLE
新テーマのちょこっと表示不具合

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1040]
https://github.com/NetCommons3/NetCommons3/pull/1038

素敵です。
ちょっと試したところ、以下気づいた点です。
軽く触った程度で、他のプラグインやテーマまで見れてないです。
とりあえず報告まで。

#### テーマ「Michael the 2nd」、カレンダー、表示中のタブの文字が見えなくなってました。
![image](https://user-images.githubusercontent.com/2756509/30726681-4e02714c-9f87-11e7-89ac-d27787b02ec5.png)

#### テーマ「Michael the 4th」、スマホ表示でメニューボタンが見えなくなってました。
![image](https://user-images.githubusercontent.com/2756509/30726739-9d9c5a06-9f87-11e7-9c5d-0a8dd8176fcf.png)

**Comment by ghost** [comment]
おっと、いろいろありますねw 対応します💦

**Comment by ghost** [comment]
修正しました。結局 1st〜5thまで全て手を入れました。
pull requestしましたが、どこで travis CIをかけるのかわからず、travis CIせずにpull requestしてしまいました。

**Comment by akagane99** [comment]
プルリクエストのコメントと重複しますが、念のため。
プルリクエストすると自動的にtravisCI動きますよ〜。
参考まで。

**Comment by ghost** [comment]
え、そうなのですか!? NetCommons3/NetCommons3側で、travisさんに×マーク付けられてて、こりゃダメかなとシクシク泣いていたところなんですが(^^;

**Comment by akagane99** [comment]
travisさん、今回はどなたかがキャンセルしてバッテンになったみたいです。
https://travis-ci.org/NetCommons3/NetCommons3/jobs/281979443#L8

ほかの待ち行列してるtravisテストを早めに実行したい時とか、キャンセルしたりするのでお気になさらずです^ ^

**Comment by ghost** [comment]
プルリクエストにもコメント付けたので重複しますが、この修正したミカエルシリーズは NetCommons 3.1.5には同梱されないことが判明しました。マージいただいた後に3.1.5がリリースされたので、てっきり同梱いただいたと思ったのですが。

リリース前に２度プルリクエストすると、１度目のプルリクエストのみ次のNetCommonsリリースに反映され、２度目のプルリクエストは次々回のNetCommonsリリースに回されるということでしょうか?

**Comment by akagane99** [comment]
NetCommons3リポジトリのコミットログは、こんな感じになってました。

https://github.com/NetCommons3/NetCommons3/commits/master

不具合修正のマージが、3.1.5リリースの後になったため、
結果的に不具合修正の反映は次々回リリースになると思います。
ちょっと残念です。

単に3.1.5固めたタイミングと、プルリクのマージのタイミングが前後したためかと思います。
リリース担当は、 @kteraguchi さんなので、リリースのタイミング前後にプルリクエスト送る場合は、Skypeなどで連絡とった方が良いかと思います。

**Comment by ghost** [comment]
了解しました。ありがとうございます。
