### ISSUE TITLE
GIF画像の不具合

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1042]
GIF画像を貼り付けると背景が黒になる。GIFアニメーションは動かない。
![image](https://user-images.githubusercontent.com/30645702/30727879-faca3f34-9f8e-11e7-805a-ee2b8a09d1c7.png)　
＊NC2＊
![image](https://user-images.githubusercontent.com/30645702/30727856-d854848c-9f8e-11e7-999c-24ba6ae1d1c0.png)

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1210

上記で原寸大にすれば、解消されるようになります。
