### ISSUE TITLE
メニューの移行で、display_type 入力値が不正です。

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1047]
Nc2ToNc3MenuBehaviorで display_type 'main'をセットするパターンがありました。
MenuFrameSettingのdisplay_typeに'main'は無いので、validateで入力値が不正エラーになっていました。

どう直せばいいんだろう？
とりあえず報告まで。

### 詳細

Nc2ToNc3MenuBehaviorで display_type 'main'をセット
https://github.com/NetCommons3/Nc2ToNc3/blob/bab5ace003a6acdbea44cde2007d494761494039/Model/Behavior/Nc2ToNc3MenuBehavior.php#L284

MenuFrameSettingのdisplay_typeのvalidateにinListあり。
チェックするリストは`$this->menuTypes`
https://github.com/NetCommons3/Menus/blob/6a7b9e8204088aa8b4b3a8499e365f63fd8745bc/Model/MenuFrameSetting.php#L148

`$this->menuTypes`はここでセット
https://github.com/NetCommons3/Menus/blob/6a7b9e8204088aa8b4b3a8499e365f63fd8745bc/Model/MenuFrameSetting.php#L94

### debug.log

```
2017-09-27 06:13:58 Info: Menu Migration start. : Nc2ToNc3Menu on line 59
2017-09-27 06:13:58 Info: nc2MenuDetail block_id:286page_id:213
array (
  'MenuFrameSetting' => 
  array (
    'frame_key' => 'f9a1b5131f3d871fb795092727d9386d',
    'display_type' => 'main',
    'created_user' => '1',
    'created' => '2012-05-07 07:06:16',
  ),
  'Menus' => 
  array (
    1 => 

[省略]

    ),
  ),
)
array (
  'display_type' => 
  array (
    0 => '入力値が不正です。',
  ),
) : Nc2ToNc3Menu on line 131
2017-09-27 06:13:58 Info: Menu Migration end. : Nc2ToNc3Menu on line 77
```

**Comment by kteraguchi** [comment]
確かに、main なんて無いですね。。。。
デフォルト major を返すようにします。

それと、当件デバッグしてて、見つけた問題が2点あったので、一緒に直します。
１．NC2で、topic_pathといテンプレートが指定されていたケース漏れ
２．グループルームを非表示に設定されていたケース漏れ
