### ISSUE TITLE
移行ツールで移行した登録フォームの編集をすると内部サーバエラー

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#1055]
移行ツールで移行した登録フォームを編集して、
「(2)登録フォームの設定」で「決定」すると下記エラーが発生します。

> 	内部サーバエラーが発生しました。
> エラー: 内部エラーが発生しました。
> Stack Trace
> CORE/Cake/Model/BehaviorCollection.php line 238 → MailSettingBehavior->updateMailSetting(Registration, array)
> CORE/Cake/Model/Model.php line 829 → BehaviorCollection->dispatchMethod(Registration, array, array)
> APP/Plugin/Registrations/Model/Registration.php line 677 → Model->__call(string, array)
> APP/Plugin/Registrations/Controller/RegistrationEditController.php line 309 → Registration->saveRegistration(array)
> [internal function] → RegistrationEditController->edit()
> CORE/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(RegistrationEditController, array)
> CORE/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
> CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(RegistrationEditController, CakeRequest)
> APP/webroot/index.php line 106 → Dispatcher->dispatch(CakeRequest, CakeResponse)
> 

新規に登録フォームを追加すると、新規追加したフォームだけは正常に更新できます。

**Comment by akagane99** [comment]
承認メール設定が空のため、内部エラー出てました。
なので、承認メール設定すると、エラー解消します。

登録フォームのメール設定は、「承認メール通知」「登録メール通知」の2種類がありますが、
移行時には、「登録メール通知」のみ登録され、「承認メール通知」が空でした。

Registration::saveRegistration()時に、$this->updateMailSetting()でメール設定保存してるから、2種類同時にセットされるはずなんですが、現状移行時には「登録メール通知」のみ登録されてる。うーん。
とりあえず、ここまで調査しました。

### Registration::saveRegistration()
```
			// Registrationのステータスが公開なら登録通知メール設定を上書きする
			if ($status == WorkflowComponent::STATUS_PUBLISHED) {
				$this->updateMailSetting($saveRegistration);
			}
```
