### ISSUE TITLE
未ログイン時にはヘッダーメニューを表示しないこともカスタマイズでできるようにcss追加

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1063]
サンプル
https://sample.netcommons3.jp/fullwidth

**Comment by akagane99** [comment]
ヘッダーメニューの消し方、wikiにデザインTipsとして書きました。
https://github.com/NetCommons3/NetCommons3/wiki/デザインTips

**Comment by ghost** [comment]
テーマのうち Michael 4th と 5thでは システムヘッダーの高さを小さくしています。しかし、数カ所もいじって実現しており、あまりエレガントなCSSではないのが現実です。またその割にデザインへの寄与もあまりない・・・という(TT)

今回、システムヘッダーを非表示にできるようになるので、Michael 4th と 5thの高さはデフォルトに戻そうと思います。
