### ISSUE TITLE
setting mode ON→管理で現在の登録者数を把握できない

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#1066]
### 登録フォーム
setting mode ON→管理
の最初の画面で現在の登録者数を把握できない。
登録者一覧を見ても、番号がとびとびになっている（たぶん、
サイト全体で番号を一意に振っており、二つ登録フォームを
同時に動かすととびとびになってしまう）ため、何人本当に
登録しているかは、CSVをダウンロードしてExcelの機能で
数えないとわからない。
→登録のIDはサイトで一意でもいいが、登録者一覧のところの
番号は、その登録フォームに対して連番でつければ、問題は解決
（たしか、最初に話し合った仕様はそうだった。ここはNC2と
変更した部分。）
→登録者番号をサイトで一意にするのであれば、setting mode ON→管理
の最初の画面に登録者数を表示すべき。

### 小テスト、アンケート
setting mode ON→管理
の最初の画面で現在の登録者数を把握できない。
アンケート単独で回答結果を表示していない場合、何人登録しているかは、
CSVをダウンロードしてExcelの機能で数えないとわからない。

**Comment by RyujiAMANO** [comment]
登録フォームについて

> →登録のIDはサイトで一意でもいいが、登録者一覧のところの
番号は、その登録フォームに対して連番でつければ、問題は解決
（たしか、最初に話し合った仕様はそうだった。ここはNC2と
変更した部分。）

登録フォーム毎に連番となるようにしました。

既存登録フォームで登録データがすでにあるケースについては
登録済みデータの受付番号はそのまま、次の登録から最後の受付番号＋1されるようにしました。
例）今までの登録データで受付IDが1，3，5，10となっていたら、この修正適用後は既存登録データの受付番号は1，3，5，10となり、次の登録から11，12，13となります。

> →登録者番号をサイトで一意にするのであれば、setting mode ON→管理
の最初の画面に登録者数を表示すべき。

登録フォーム一覧に登録数も表示するようにしました

**Comment by RyujiAMANO** [comment]
登録フォームは対応完了してmasterにマージしました。次バージョンにて修正版リリースになります。

**Comment by RikaFujiwara** [comment]
小テストは対応完了してmasterにマージしました。次バージョンでのリリースになります
