### ISSUE TITLE
フォトアルバムでスライドショー表示にしたときのスマホ表示では画像の一部しか見えない

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1068]
ヘッダーをスライドショーにした場合
【PC表示】
![test](https://user-images.githubusercontent.com/30645702/31367488-9320e284-adb2-11e7-9467-2236ee9b263f.png)
【スマホ表示】
![2test](https://user-images.githubusercontent.com/30645702/31367508-b4c8da90-adb2-11e7-904f-ad3739c1f9bb.png)

上記画像のようにスマホでは全画像が表示されません。
縦横比が固定された状態でスライドショー表示して欲しい。

**Comment by onozaki** [comment]
スライドショーを使用してサイトを構築する状況が多く、こちらの不具合の解消見通しが知りたいのですが、現在のところどのくらいの見込みでしょうか？
わかる方、お答えいただけますとありがたいです。
#1006も同様

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1164
で対応済みです。
