### ISSUE TITLE
アンケート回答時に「アンケート一覧に戻る」ボタンが表示されるが、単独表示だと遷移先は一覧ではない

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#107]
フレームにひとつのアンケートだけを表示してるときに回答しても「アンケート一覧に戻る」というボタンが表示される。

「アンケートに戻る」かそもそもボタン無しでもいいのかも

**Comment by RikaFujiwara** [comment]
単に「戻る」というワードに変えて、どちらの場合も違和感がないようにする
https://github.com/NetCommons3/Questionnaires/commit/cd0ce60a484b457cf5d58bd6e749562d478d675c
