### ISSUE TITLE
WYSIWYGの中に書いた自サイト内リンクで相対パスで書いているところは移行されない

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1070]
WYSISYGの中に書かれたサイト内リンクは
href="https://hoge.hoge.com/?page_id=xx"
という形式であれば、NC3の該当ページへのリンクに置き換えられるが
href="/?page_id=xx"
というようにドメイン部分を書かない相対パス形式のhrefは変換対象になっていない

できれば「href="/?page_id=xx"」も対象にできないでしょうか？

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Nc2ToNc3/blob/master/Model/Behavior/Nc2ToNc3WysiwygBehavior.php#L261
ここら辺の修正でいけそうです。
手は付けられないのですが、情報提供まで。
