### ISSUE TITLE
掲示板への投稿通知メール中のURLが https になっていない

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1073]
https化したサイトで、掲示板に投稿したとします。
投稿内容がメールで通知されてきます。
最下行に「この記事に返信するには、下記アドレスへアクセスしてください。」とあり、URLが添えられています。

下図のように、HTTPS化したサイトであるにも拘わらず、URLが http となっているので https に変更して欲しい。
![2017-10-27 17 07 09](https://user-images.githubusercontent.com/7931689/32094278-28eac07a-bb3a-11e7-8be5-ca35625a5a87.png)

**Comment by ghost** [comment]
すみません、私のミスでした。
app/Config/application.yml の fullBaseUrl の指定で http のままでした。HTTPS化した後、ここをhttpsに変更しないといけないんですね。

**Comment by akagane99** [comment]
typoも問題なさそうでした

https://github.com/NetCommons3/Bbses/blob/master/Config/Migration/002_mail_setting_records.php#L96
