### ISSUE TITLE
汎用ＤＢ：登録したデータが削除できない

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1088]
登録したデータを削除しようとすると「内部エラーです」と表示され、削除できない。

**Comment by RyujiAMANO** [comment]
汎用DBというわけではないですが、NC2からの移行関係で不具合報告が多数あるので、以下の点について教えてください。
- NetCommons3のバージョンはいくつでしょうか？
- NC2から移行ツールで移行したサイトでしょうか？
  - 移行したサイトの場合、問題が発生したのは移行したDBでしょうか？それともNC3で新規に作成したDBでしょうか？

**Comment by onozaki** [comment]
・NetCommons3　バージョン3.1.5 にした後、さらに汎用データベースの最新パッチを適用しました。
・移行ツールで移行したサイトではありません。

**Comment by rs-ohno-tomoyuki** [comment]
本件確認をいたします。

**Comment by rs-ohno-tomoyuki** [comment]
@onozaki さん
以下確認させてください。
* 削除できないデータは特定のデータですか？全てのデータですか？
* 汎用データベースで作成された全てのデータが削除できない状態ですか？特定の汎用データベースで作成されたデータが削除できない状態ですか？
* 作成された汎用データベースのフィールド構成を教えていただけますか。（フィールド名とフィールドの属性、選択項目、オプション）
* 当該現象が発生しているOSおよびミドルウェア(PHP, MySQL, Apache または Nginx)のバージョンを教えていただけますか。

**Comment by onozaki** [comment]
取り急ぎ、わかる範囲でご連絡いたします。

●全てではなく１コンテンツです。
●特定の汎用データベースではないです。別サイトでも確認しましたが、削除できませんでした。
●・氏名
　・ふりがな（テキスト）
　・事務所名（テキスト）
　・支部別（選択式・択一）／県北支部・水戸支部【水戸ブロック】・水戸支部【太田ブロック】・水戸支部【鹿嶋ブロック】・県南支部
　・住所（テキスト）
　・専門分野（選択式・複数）／安全衛生・年金
　・TEL/FAX（テキスト）
　・Eメールアドレス（テキスト）
　・ホームページ（テキスト）
●Windows 7です。

**Comment by tabimoba** [comment]
現象確認しました。
添付ファイルが存在しないレコードを削除するとエラーになります。
（ファイルをアップロードするフィールドが存在しない汎用DBは無条件に発生します）
明日修正を反映します。ご迷惑おかけしまして申し訳ございません。
