### ISSUE TITLE
汎用データベースで「コメントをつけられる」、「いいねボタンを付けられる」をOFF にして決定しても、反映されない。

### ISSUE THREAD

**Issue by nagasheep** [NetCommons3/NetCommons3#1093]
汎用データベース ＞ 編集 ＞ ブロック設定
で「コメントをつけられる」、「いいねボタンを付けられる」をOFF にして決定しても、反映されない。
画面上に特にエラーなどは表示されない。

2017-11-14 確認
NetCommons 3.1.5
汎用データベース 3.1.5 (e1f2219428)
コモンズネット公式サイト (www.commonsnet.org)

以上、報告します。

**Comment by tabimoba** [comment]
確認をいたします
