### ISSUE TITLE
汎用DBを編集する度に新着が増えていく

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1104]
汎用DBに一度登録したものを編集すると、新たな項目として新着プラグインに記載されてしまいます。
（編集するたびに増えていく）
編集された際に追加された新着をクリックすると
「不正なリクエストの可能性があります。」
と表示されます。

**Comment by akagane99** [comment]
nc3.1.9で確認したところ、もう直ってそうだった。
解消済みかな？

**Comment by onozaki** [comment]
ご確認ありがとうございます。
3.1.9で解消しているということであれば、パッチをあてるかバージョンアップするかで確認したいと思います。
いつもご対応ありがとうございます！
