### ISSUE TITLE
コンテンツコメントの定数

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#111]
承認ステータスの定数があります。

https://github.com/NetCommons3/ContentComments/blob/136c2fafc5e091f7981e8ea1a2c5bf47d4f4a232/Model/ContentComment.php#L21-L33

ワークフローの定数を使用した方が良いと思います。
https://github.com/NetCommons3/Workflow/blob/6a4dd023de98c49a2eec7285ee20ce3c88d4f59b/Controller/Component/WorkflowComponent.php#L22-L48

**Comment by akagane99** [comment]
うーん。このままで良い気がしてます。

コンテンツコメント、簡易ワークフローなので、ワークフロープラグイン使ってないんです。
フラグも１，２しか使わないので、ここだけワークフロープラグインの定数を使うのって、どうなのでしょう？
ワークフロー定数にした場合、フラグ３，４もあると誤認されると思います。

**Comment by akagane99** [comment]
寺口さんと相談済み。
- ラベルでワークフローの使ってた。
- 中途半端いくない。ワークフロー使うなら使う。使わないならラベルも使わない。
  - コンスト、ワークフローの使う方向で対応する。

**Comment by akagane99** [comment]
対応しました。
