### ISSUE TITLE
一度投稿したものを編集し再投稿しようとすると内部エラーで投稿できない

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1115]
画像の項目ある汎用DBで、一度投稿したものを編集したとき、再度画像を上げ直さないと内部エラーが発生し、投稿できません。

**Comment by rs-ohno-tomoyuki** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1135 と同じ内容となります。
