### ISSUE TITLE
カレンダーの新着で、リンクをクリックすると「このアカウントでは、指定したURLにアクセスができません。」がでて、アクセスできないことがある。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#1116]
カレンダーの予定をマイルームでパブリック、コミュニティの予定を登録すると、登録した本人以外が新着リンクをクリックすると、「このアカウントでは、指定したURLにアクセスができません。」とエラーが発生し、予定を見ることができない。

**Comment by RikaFujiwara** [comment]
カレンダーの表示と登録画面にて、フレームIDなしでも動作するように改修します

**Comment by onozaki** [comment]
このような検証の仕方で合っているかわかりませんが．．
3.1.9で以下のとおり検証したところ、エラーが発生し、予定を見ることができませんでした。

・マイルームに設置したカレンダーに予定を登録しました（パブリック）
![default](https://user-images.githubusercontent.com/30645702/40763450-ead49d4c-64df-11e8-82a4-14f913eb6a6b.png)
・届いたメールのURLをクリック
![default](https://user-images.githubusercontent.com/30645702/40763465-f86578a0-64df-11e8-9ae1-a678d624fa92.png)
・登録した人以外でログイン
![default](https://user-images.githubusercontent.com/30645702/40763540-2c6cca0e-64e0-11e8-9637-6f384e943e00.png)
・エラーが表示される
![default](https://user-images.githubusercontent.com/30645702/40763561-3bae8610-64e0-11e8-826a-99652f5f2bcb.png)

**Comment by onozaki** [comment]
こちら、検証の結果まだ現象の解消を確認が取れていません。
上記状況を報告しているので、そちらの報告内容が間違っているかどうかご確認いただいてからのクローズが良いかと思うのですが、ご確認願います。

**Comment by akagane99** [comment]
> こちら、検証の結果まだ現象の解消を確認が取れていません。

ご報告の通りの状況かと思うので、とりあえず再オープンしちゃいますね。
