### ISSUE TITLE
MySQL 5.1.5 未満の環境ではインストールが通らない

### ISSUE THREAD

**Issue by mschibata** [NetCommons3/NetCommons3#1118]
INFORMATION_SCHEMA の ENGINES テーブルを参照している箇所がありますが、サポートされたのは MySQL 5.1.5 からです。
現状、判定だけしてその後の処理がコメントアウトされていますので、まだ煮詰まっていない部分だと思いますが、お知らせしておきます。

**Comment by akagane99** [comment]
* 公式サイトではMySQL5以上になってますね。
* けれども、NC3のTopicsプラグインで全文検索（InnoDBのFULLTEXT）を使ってるので、~~MySQL 5.6.4以降でないと、インストール時にTopicsプラグインのテーブル作る時に失敗するかなと思います。~~
* 対象のバージョンは少なくとも NetCommons3.1.5 以降かと思います。

### 公式サイト
https://www.netcommons.org/NetCommons3/download
> ● MySQL5以上（※sql_modeがSTRICT_TRANS_TABLESだと正常に動作しません）

### システム要件
https://github.com/NetCommons3/NetCommons3/wiki/%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E8%A6%81%E4%BB%B6#%E3%81%9D%E3%81%AE%E4%BB%96%E6%83%85%E5%A0%B1
> MySQL 5.6.4以降
> Topicsプラグインで全文検索（InnoDBのFULLTEXT）利用のため、使えるのは、InnoDBのFULLTEXTに対応したデータベースのバージョンです。

**Comment by akagane99** [comment]
すみません。
NC3のTopicsプラグインで全文検索（InnoDBのFULLTEXT）を使ってるけど、MigrationでMYSQL5.6より小さいバージョンであれば、FULLTEXT使わないようになってました。
https://github.com/NetCommons3/Topics/blob/3.1.5/Config/Migration/1462148437_init.php#L210

そのため、MYSQL5.5以下でもインストールできるみたいです。

**Comment by akagane99** [comment]
調べてみました。

* MySQL公式ページからダウンロードできる、MySQL Community Serverのバージョンは5.5以上
* EOLになっていない各OSで、サポートしているMYSQLのバージョンは5.5以上
* NetCommon3でテストしてるMYSQLのバージョンは、5.6

今から手に入るサポートされたMySQLは5.5からのようなので、NetCommons3が対応するバージョンも5.5以上でいいような気がしました。

### link
MySQL公式ページ ダウンロードページ　https://dev.mysql.com/downloads/mysql/
各OSのMYSQL対応リスト　https://www.mysql.com/support/supportedplatforms/database.html
テストしてるMYSQLのバージョン　https://travis-ci.org/NetCommons3/Auth/jobs/322798850#L83

**Comment by akagane99** [comment]
特に意見無かったので、公式サイトのMYSQL5.5以上に修正しましたので、クローズさせて頂きます。
ご報告ありがとうございました。

https://www.netcommons.org/NetCommons3/download#!#frame-83
