### ISSUE TITLE
リンクリストの表示方法変更で予期せぬエラー

### ISSUE THREAD

**Issue by nagasheep** [NetCommons3/NetCommons3#1121]
こんにちは。
永原です。

リンクリストの表示方法変更で、表示方法選択のラジオボタンが選択されていない状態だと、決定時に「予期せぬエラー」になります。

表示方法変更画面を開いたときに、表示方法選択のラジオボタンが未選択になっているので、それが原因かな。表示方法選択のラジオボタンを選択すると、登録できます。

**Comment by RikaFujiwara** [comment]
#1065 一覧、プルダウンの選択ラジオが消えてしまうのが原因なので、このISSUEの重複だと思います

**Comment by RikaFujiwara** [comment]
#1065 の対応でこちらも解決でいいのかな？
