### ISSUE TITLE
［要望／不具合］お知らせプラグインに画像を配置すると画像が劣化する場合がある

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1126]
お知らせプラグインでは画像を自動で処理する機能がありますが、せっかくデザイナさんに作ってもらったイラストが品質劣化して見劣りすることがあります。

例：[弊社サイトトップページ](https://www.akazawa.org/)のZawawa（弊社の竜キャラクタ）の赤いグラデーションがJPEGモヤモヤが発生し汚くなってしまってます。

画像を自動では処理しないオプションもあるといいのですが。基本、画像はPhotoshopなり別ソフトで加工し、サイズも品質もきちんとコントロールしたいです。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1210

NC3.1.8で原寸大が追加されましたので、お知らせで画像をアップロードする時は「原寸大」を選ぶと、画像の劣化はおきなくなりました。
クローズします。
