### ISSUE TITLE
［不具合］「回覧板」の表示

### ISSUE THREAD

**Issue by yukio-tachikawa** [NetCommons3/NetCommons3#1129]
「回覧板」を設置したのと同じページに「お知らせ」も設置したとします。
で回覧板を「全てのステータス」から例えば「回覧中」と変更すると、何故か「お知らせ」が見えなくなってしまうのです。（バージョン3.1.6で確認）
ページを表示し直せば戻るので致命的ではないですが、バグでしょうか？

**Comment by akagane99** [comment]
残念ながら仕様なんです。

NC2ではAjaxを使っていたため、「回覧中」などのステータスを変更した場合、その部分だけ表示を入れ替えていたのですが、
NC3ではAjaxを基本使わないため、ステータスを変更すると、ステータスのパラメータを付けたURLで遷移する事になり、おっしゃる通りのうごきになります。

**Comment by yukio-tachikawa** [comment]
そうでしたか。では、そういう前提でページの構成を考えなくてはいけないですね。
回答をありがとうございました。
