### ISSUE TITLE
javascriptやiframeなどのコードが反映されない

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1131]
NC2では、お知らせなどのWysiwygにjavascriptやiframe等のコードを記述した際、決定を押すと正常に表示されていましたが、NC3では表示されません。
正常に表示できるよう、修正して頂けますと非常に助かります。

**Comment by akagane99** [comment]
ルーム設定の「Javascript等のHTMLタグを許可する権限」を許可してないのではないかなぁ。

**Comment by onozaki** [comment]
ご回答有難うございました。許可設定をしたところ、出来ました。
