### ISSUE TITLE
汎用DBにてデータ登録時に内部エラーが発生する

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1132]
汎用データベースプラグイン(3.1.6)にて、
属性「日付」の入力項目を追加後、データ登録すると内部エラーが発生します。

現象を再現するには、
以下の４つの条件にした汎用データベースにデータを登録します。
①まだ１度もデータを登録したことがない状態（一度でも入れるとエラーは出なくなる）
②属性「日付」の入力項目を自分で追加
③属性「ファイル」の入力項目を自分で追加
④最後に【決定】ボタンを押す

調査した結果ですが、
メタデータを登録する際、一度に「ファイル」,「日付」,「画像」を追加すると、
カラムNoが重複してしまうことが原因と思われます。(DBで確認済み)

結果、問題となるメタデータを登録する際、
フィールド1項目追加ごとに【決定】ボタンを押して、
追加していくと問題なくデータ登録時にエラーが発生しなくなりました。

**Comment by tabimoba** [comment]
1/14頃に修正版をpush予定です。ご迷惑をおかけしまして申し訳ございません。
  （作業用PCが故障しまして対応が遅くなっております）

**Comment by tabimoba** [comment]
こちらについても、以下の課題と同様の対応にてご確認いただくものとなります。
https://github.com/NetCommons3/NetCommons3/issues/1135

**Comment by s-nakajima** [comment]
Closeにするのは、こちらでやりますので、Closeにしないでください。
ISSUEのReopenして、完了ラベル付けます。
