### ISSUE TITLE
汎用DBの属性「日付」入力仕様に関して

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1133]
汎用データベースプラグイン(3.1.6)にて、
属性「日付」の入力項目が複数存在している状態で、日付の入力を行ったところ、
属性「日付」の入力項目がすべて入力した日付に変わってしまいました。
これはこういう仕様なのでしょうか？

**Comment by tabimoba** [comment]
1/14頃に修正版をpush予定です。ご迷惑をおかけしまして申し訳ございません。
  （作業用PCが故障しまして対応が遅くなっております）

**Comment by s-nakajima** [comment]
Closeにするのは、こちらでやりますので、Closeにしないでください。
ISSUEのReopenして、完了ラベル付けます。
