### ISSUE TITLE
汎用DBにて、入力した内容がDBに登録されない

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1134]
汎用データベースプラグイン(3.1.6)にて、
データ登録を行い、詳細画面を表示すると、
入力したものと異なるものが表示される項目があります。

![a](https://user-images.githubusercontent.com/24466151/34401519-18d18acc-ebdf-11e7-95e9-db66d34eed9f.png)

DBのコンテンツ内容を確認したところ、
入力された内容が登録されていない箇所が見つかりました。

また、メタデータの内容を確認したところ、
カラム番号が重複されて登録されていました。
[sql結果.txt](https://github.com/NetCommons3/NetCommons3/files/1590546/sql.txt)

今回、入力項目を１つ追加するごとに【決定】ボタンを押せば、
カラム番号が重複しなくなり、登録は行えるようになりました。
ただ、今回のように項目が多いと、毎回【決定】ボタンを押すのが大変です。

**Comment by onozaki** [comment]
こちらでも、【複数選択】に設定したものにチェックを入れても反映されない（表示されない）事象がありました。

**Comment by tabimoba** [comment]
1/14頃に修正版をpush予定です。ご迷惑をおかけしまして申し訳ございません。
  （作業用PCが故障しまして対応が遅くなっております）

**Comment by tabimoba** [comment]
修正は行いましたので、本日1/15〜1/16にPushします。

カラムNoが不定（＝追加したばかりの）フィールドが保存時に複数存在すると当該現象が発生します。
カラムNoの存在チェックに問題がありました（新たなカラムNoが生成されない問題がありました）ので、これを修正しました。

なお、本件は次のIssueに関連しますので、これらも同時に修正されます。
https://github.com/NetCommons3/NetCommons3/issues/1140
https://github.com/NetCommons3/NetCommons3/issues/1133
https://github.com/NetCommons3/NetCommons3/issues/1132

**Comment by s-nakajima** [comment]
Closeにするのは、こちらでやりますので、Closeにしないでください。
ISSUEのReopenして、完了ラベル付けます。
