### ISSUE TITLE
汎用DBで、登録内容を変更したところ内部エラーが発生した

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1135]
汎用データベースプラグイン(3.1.6)にて、
データ登録後、その内容を変更しようとしたところ、「内部エラー」が発生しました。

＜オペレーション＞
１．登録データの詳細を表示
　　　　→問題なく表示できます。
２．ある一つのテキストの内容を変更
３．【決定】ボタンを押す

なお、#1134の対策で登録出来た内容を編集したときに発生しております。
削除は問題なく動作します。

エラーログにエラーが出力されていました。SQLのエラーです。
![error](https://user-images.githubusercontent.com/24466151/34401815-f7f975ba-ebe0-11e7-9f24-7d4025f3ddd7.png)

**Comment by tabimoba** [comment]
1/14頃に修正版をpush予定です。ご迷惑をおかけしまして申し訳ございません。
（作業用PCが故障しまして対応が遅くなっております）

**Comment by tabimoba** [comment]
こちらの原因については、おそらく本来はファイル

**Comment by tabimoba** [comment]
こちらは本来ファイルが入るべきフィールドにファイル以外がセットされたために問題が生じたものと思われます。検証中ですが、下記課題にて修正後、新規追加分については当該問題は解消されるものと思われます。既に追加されているものについては、再編集時に当該エラーが発生する可能性がありますので、お手数ですが当該データは削除および再入力いただくことになると思います。
https://github.com/NetCommons3/NetCommons3/issues/1134

**Comment by s-nakajima** [comment]
Closeにするのは、こちらでやりますので、Closeにしないでください。
ISSUEのReopenして、完了ラベル付けます。

**Comment by tabimoba** [comment]
Closeの件ですが、おそらくCommitの際に「Fix IssueID」とすると勝手にクローズされるようです。
コメントの記載方法について見直します。

**Comment by kteraguchi** [comment]
Fix for IssueID
とかにしてます。
