### ISSUE TITLE
コンテンツコメントのコメント未使用時

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#114]
Videoプラグインでコンテンツコメントの動作確認をしました。
Videoプラグインのブロック設定画面が動作しなかったため、video_block_settingsテーブルのuse_commentを直接0にしました。

コンテンツコメントを使用しないので、コメントが表示されないのが正常と思っています。
現状コメント入力とNoticeが数件表示されます。

https://github.com/NetCommons3/ContentComments/blob/2b63b3c42f705c8e72d322e697113a18313f80f2/View/Helper/ContentCommentHelper.php#L105
の判断が違う気がしていますが、意図をくみ取れませんでした。

**Comment by akagane99** [comment]
対応します。

**Comment by akagane99** [comment]
対応しました。
