### ISSUE TITLE
汎用DBで、選択式に設定したものが表示されない

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1140]
3.1.6で確認した不具合です。
属性を選択式（択一）と選択式（複数）の項目を作り表示を確認したところ、空欄のまま表示されています。

**Comment by tabimoba** [comment]
現在確認中です

**Comment by tabimoba** [comment]
確認しました。
まず、「項目を作成した直後」という解釈である場合は、何も選択されていない状態ですので仕様になります。
項目を作成→データを編集→編集後の表示結果が空欄になるという場合は、 以下のIssueに関連すると思います。こちらについては現在対応中です。
https://github.com/NetCommons3/NetCommons3/issues/1134
よろしくお願いします。

**Comment by s-nakajima** [comment]
Closeにするのは、こちらでやりますので、Closeにしないでください。
ISSUEのReopenして、完了ラベル付けます。
