### ISSUE TITLE
コンテンツコメントのコメント一覧対象抽出処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#115]
https://github.com/NetCommons3/ContentComments/blob/2b63b3c42f705c8e72d322e697113a18313f80f2/View/Helper/ContentCommentHelper.php#L130-L135
の処理は不要な気がします。

```
unset($contentComments[$idx]);
```

の処理に入ることはないと思われます。
入る条件としては、公開権限がなく、自分のコメントでもなく、承認待ちのコメントになります。

ContentCommentComponentの処理
https://github.com/NetCommons3/ContentComments/blob/8fbf5fd6d4e761fa594df979f6ce99bbda7fc9d9/Controller/Component/ContentCommentsComponent.php#L133-L169
でconditionを指定しているので、公開権限がなく、自分のコメントでもなく、承認待ちのコメントは取得されないと思います。

また、Paginatorを使用して取得しているので、取得後にデータの追加、削除を行うと改ページがずれるので、正常に動作しなくなると思います。

**Comment by akagane99** [comment]
あっ！片手落ちな対応でした。
修正します

**Comment by akagane99** [comment]
対応しました。
