### ISSUE TITLE
汎用DBで、個別に並べ替えしたい

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1157]
例えば、１、３、４、５と登録してしまって、後から２番目が抜けていることに気付いたとき、
現在は並べ替えができない状態なので、３、４、５をまた登録し直す必要があり、あまり効率的ではありません。
インポートもエラーが起きてしまうため、個々に並べ替えができれば使い勝手がよくなるかなと思いました。
よろしくお願いします。

**Comment by tabimoba** [comment]
個別並べ替えについて、実装見送りとなっています。
レコード数が少数の場合は問題となりませんが、レコード数が大量となった際に１画面上で並べ替え操作を行うのが困難となります。また、並べ替え処理は全てのレコードを１レコードずつ書き換えますので、レコードが大量になると非常に時間がかかるようになります。また、レコードの更新・削除処理を行っていたり、他の方が同時期に並べ替え処理を行っていた場合、データの不整合が生じる可能性が高くなります。
したがいまして、NC3の汎用データベースでは実装されておりません。
なお、NC3の汎用データベースにはソート機能がありますので、本来はそちらの機能で対応いただくものであると考えています。
申し訳ございませんが、以上ご了承いただければと存じます。

**Comment by akagane99** [comment]
実装見送りでクローズしちゃって良いのかな？
2,3日してお返事なければ、クローズしちゃおうと思ってます。

> 例えば、１、３、４、５と登録してしまって、後から２番目が抜けている

これくらいシンプルで、この数字がタイトルとかなら、タイトルを一覧表示、ソートの対象にする。
表示設定で、タイトルの昇順で設定しちゃえば、現在の機能で解決できそうだなぁと思いました。

もしくは並び順を、更新日時の昇順にして、各データを並べたい順に更新すれば、やりたい事は実現できそうかなと思いました。

**Comment by onozaki** [comment]
実装が難しいということであれば仕方がないと思いますので、クローズで良いです。
実際お客様が使用していて、登録件数が多い場合の並び替えにかなり手間がかかるという状況のため、意見として共有できればと思います。
ご検討ありがとうございました！
