### ISSUE TITLE
bootstrapが4でインストールされちゃう

### ISSUE THREAD

**Issue by horitada** [NetCommons3/NetCommons3#1158]
https://github.com/NetCommons3/NetCommons3/blob/06b702c44e46312249b785984e224ec6a3798eeb/bower.json#L19

**Comment by akagane99** [comment]
上記、3.3以下のバージョン指定と思ってた。
bower公式のどっかにドキュメントあるかなぁ。

でも4がダウンロードされちゃうのなら、バージョン指定間違ってて、見直しだろうなぁ。

**Comment by akagane99** [comment]
あ、この指定、3.3以下じゃなきて3.3以上でした。
4より小さいを指定かなぁ。

    "bootstrap": "<4.0",

公式ドキュメント
https://github.com/bower/spec/blob/master/json.md#dependencies
> dependencies
> Value must be a valid semver range,

でsemver range https://github.com/npm/node-semver/blob/master/README.md#ranges
> ‘<‘ Less than
> ‘>=‘ Greater than or equal to
> For example, the comparator >=1.2.7 would match the versions 1.2.7, 1.2.8, 2.5.3, and 1.3.9, but not the versions 1.2.6 or 1.1.0.

**Comment by akagane99** [comment]
bootstrap3系を使ってテーマやデザイン作成されているため、bootstrap4にメジャーアップデートすると
CSSの書き方も変わるようで、こんな感じに表示が崩れるようです。
現在の開発状況を考え、ひとまずはbootstrap3系で良いと思いましたので、プルリクエスト作成しました。

![image](https://user-images.githubusercontent.com/2756509/35179411-35651522-fddd-11e7-98fd-9583ad2e9a88.png)

将来的にはbootstrap4系もいいかもです。
それは別途検討するのがいいですね。
