### ISSUE TITLE
ContentCommentsComponent::settingsの値

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#116]
```
ContentCommentsComponent::settings['viewVarsUseComment']
ContentCommentsComponent::settings['viewVarsContentKey']
```

が配列になっています。
https://github.com/NetCommons3/ContentComments/blob/8fbf5fd6d4e761fa594df979f6ce99bbda7fc9d9/Controller/Component/ContentCommentsComponent.php#L125-L126

おそらく、コンテンツコメントを使用するプラグインで

```
public $components = array(
    'ContentComments.ContentComments' => array(
        'viewVarsContentKey' => array('video.Video.key'),
        'viewVarsUseComment' => array('videoBlockSetting.use_comment'),
        'allow' => array('view'),
    )
);
```

と指定すると思います。

ContentCommentsComponent::settings['allow']は使用するアクション名ということで、配列で良いと思いますが、
ContentCommentsComponent::settings['viewVarsUseComment']
ContentCommentsComponent::settings['viewVarsContentKey']
は、文字列で良いと思います。

**Comment by akagane99** [comment]
修正します

**Comment by akagane99** [comment]
対応しました。
