### ISSUE TITLE
新着に汎用DBで削除したデータが表示される

### ISSUE THREAD

**Issue by k-morisee** [NetCommons3/NetCommons3#1163]
汎用DBで作成したデータを新着で表示した所、
削除したデータまで表示されてしまい、DB削除するまで表示し続けます。

**Comment by rs-ohno-tomoyuki** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1104
と同じ内容となります。

**Comment by k-morisee** [comment]
直っていないようです。

#1104
と同じ内容とのことでしたが調べたところ根本が違います。
上記は、増えますが、こちらは削除がされないという内容です。

汎用DBでデータを作成すると新着にデータを生成しますが、
汎用DBでデータを削除しても新着のデータの削除をしている形跡がありません。

内容の確認お願いします。

**Comment by n0434-ndensan** [comment]
k-moriseeさんと、同じ症状です。

汎用データベースで記事を作成すると、テーブル「multidatabase_contents」と「topics」にデータが入ります。
汎用データベースの記事を削除すると、テーブル「multidatabase_contents」だけ削除されますが、テーブル「topics」のデータは削除されず、新着データが表示されたままになります。

テーブル「topics」のカラム「plugin_key」値が「bbses」（掲示板）だと削除時にデータが削除されて新着の表示が消えます。
テーブル「topics」のカラム「plugin_key」値が「multidatabases」（汎用データベース）だと削時にデータが削除されず新着の表示されたままとなります。

不具合の改善を望んでおります。

**Comment by n0434-ndensan** [comment]
こちらは「Closed」でしたため、後続の
https://github.com/NetCommons3/NetCommons3/issues/1575
へ記述いたしました。
