### ISSUE TITLE
フォトアルバムのスライダー表示がレスポンシブ（スマホ）の時に微妙な感じ

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1164]
https://github.com/NetCommons3/NetCommons/issues/467
より転記

**Comment by nagasheep** [comment]
株式会社オープンソース・ワークショップの永原です。
これ、フォトアルバムのスライダー表示が、横幅だけ縮められて、画像が切れて表示されてしまう。
という問題ですよね。

とりあえず、ウチの会社では解決してあります。
サンプルは以下のサイトのトップページのフォトアルバムを見てください。
https://netcommons3.jp/

実装方法がこれで良いのかな？とちょっと疑問なので、その辺を調整してから、プルリクエスしましょうか。
次にakagane99 さんと会った時に説明したいです。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1068
と同じ問題でした

**Comment by akagane99** [comment]
フォトアルバムについて調査しました。
NC2には、スライドの高さ指定ではありませんが、「写真のサイズ」指定があり「サイズ指定なし」がありました。
NC3には、スライド写真の高さ(px)のみでした。

## 調査内容
### NC2表示設定
![image](https://user-images.githubusercontent.com/2756509/36466761-0d6daaba-171f-11e8-92d3-c102364025ff.png)

### NC3表示設定
![image](https://user-images.githubusercontent.com/2756509/36466774-188a7856-171f-11e8-91b0-7414b538cfb6.png)

## 対応案

NC3の表示設定に、「スライド写真の高さ指定なし（高さ設定は自動）」を追加する。のがよさそうです。
文言は仮のものです。

とりあえずここまで。
毎週木曜のモクモク会の時に修正できたらしていきたいなぁ位に思っています。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/PhotoAlbums/pull/18#issuecomment-367534627
こんな感じに修正しました。
特になければ２，３日中にプルリクエストのマージしようと思ってます。
![image](https://user-images.githubusercontent.com/2756509/36520404-2b4a893a-17d4-11e8-957c-dad0df6b396e.png)

**Comment by onozaki** [comment]
ご対応ありがとうございます！
こちらをご対応いただいたことで、
#1006 の問題も解消したりしているのでしょうか？？

**Comment by akagane99** [comment]
#1006
そちらは対応してないですよ〜。

**Comment by onozaki** [comment]
そうでしたか、ご返答ありがとうございます！
そちらの解消も心待ちにしております！ありがとうございます！
