### ISSUE TITLE
汎用DBのリンク項目で表示するリンクは target=_blankにすべきでは？

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1167]
汎用DBの「リンク」項目で表示されるリンク
クリックすると別サイトへ移動してしまう。
ここはtarget=_blankにしておいたほうがユーザビリティとしては適切ではないか？

**Comment by rs-ohno-tomoyuki** [comment]
ご指摘のとおり、target=_blankの方が良いと思います。
変更したいとおもいます。（もし不都合となる場合はお知らせください）

**Comment by akagane99** [comment]
対応方法
https://github.com/NetCommons3/Multidatabases/blob/b49db40186eac4a8f75b8a804c711204516a9663/View/Helper/MultidatabaseContentViewElementHelper.php#L223

ここにtarget=_blank追加かな。

**Comment by akagane99** [comment]
対応しました。
次期バージョンnc3.1.10で解消すると思います。
