### ISSUE TITLE
お知らせを配置すると、セッティングモードから抜けてしまう。

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1169]

**Comment by akagane99** [comment]
とりあえずメモです。
return $this->redirect()が3箇所あって、ここのどれかの修正が必要そうです。

https://github.com/NetCommons3/Frames/blob/3.1.7/Controller/FramesController.php#L55

**Comment by akagane99** [comment]
NC3.1.10の修正で、お知らせを配置しても、セッティングモード抜けなくなりました。
クローズします。
