### ISSUE TITLE
コメント数について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#117]
現状公開されているコメント数を表示しています。
承認待ちのコメントを数に入れなくて良いのでしょうか？
要確認です。

あと、
承認待ちのコメントがある旨分かるような表現方法があると良いと思います。

**Comment by akagane99** [comment]
> 現状公開されているコメント数を表示しています。
> 承認待ちのコメントを数に入れなくて良いのでしょうか？
> 要確認です。

あれ？掲示板とかって、承認待ち入れてカウントでしたっけ？
他のプラグインの一覧表示と合わせたいですね。
もくもく会で確認させてください。

> あと、
> 承認待ちのコメントがある旨分かるような表現方法があると良いと思います。

あった方が分かり易いかも。
ですが、他のプラグインの一覧表示も同様かと思います。

画面に項目追加となると、先生確認とレビューが必要と思っています。
もくもく会で先生確認とさせてください。

**Comment by kteraguchi** [comment]
> > 承認待ちのコメントがある旨分かるような表現方法があると良いと思います。
> 
> あった方が分かり易いかも。

ですよね。

<br>

> ですが、他のプラグインの一覧表示も同様かと思います。

他のプラグインはコンテンツ一覧で
承認待ちのラベルがついているのでわかりやすくなっているのですが、
コンテンツコメントは、コンテンツ一覧だと件数しかないので、詳細まで飛ばないと承認待ちがあることが分からない状態です。
新着にのせれば良いのかなぁ。。。
まぁ、要確認です。

**Comment by akagane99** [comment]
### 皆様への質問

#### １．【再確認】他のプラグインのコンテンツ数はどっちでしたっけ？

　A）未承認のコメントを含まない数を表示（誰でも）
　~~B）未承認のコメントを含んだ数を表示   　　　　　　←動画はこっちでした。多分他のプラグインもこっちのはず。~~
　↓
　**B‘）今見えている件数を表示（未承認が見える人なら、その件数を表示）**

※ $this->Paginator->param('count')なら、B。
→ 結果：**B`**

### 先生への質問まとめ

#### １．コメント数はどっち？

　A）未承認のコメントを含まない数を表示（誰でも）　　←今こっちで実装
　~~B）未承認のコメントを含んだ数を表示　　　　　　　　←こっちな気がしてきました。~~
　　　~~・ゲストは、未承認のコメントを含まない数を表示~~
　　　~~・管理者など許可ありの人は、未承認のコメントを含んだ数を表示~~
　↓
　**B‘）今見えている件数を表示（未承認が見える人なら、その件数を表示）**
→ 結果：**B`**

#### ２．承認待ちのコメントがある旨分かるような表現方法があると良い？

寺口さん指摘です。
動画プラグインのコメント表示画面を見せて説明
**表示例）**

```
 3 コメント（1 未承認）
```

とかかなぁ。
→ 結果：**これでOK**

#### ３．【再確認】表示順なんですが、投稿日時降順で良い？

寺口さん指摘です。
現在、投稿日時降順で実装済みです。
youtubeを参考にしました。
→ 結果：**OK**

**Comment by kteraguchi** [comment]
もう一個、表示順なんですが、投稿日時降順で良い？

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/117#issuecomment-175347560
に追記しました。

追記②：結果を追記しました。

**Comment by akagane99** [comment]
対応済みのため、クローズします
