### ISSUE TITLE
フォトアルバムのスライドショーでの両端が黒のグラデがないほうが良い

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1177]
フォトアルバムのスライドショーにした時、
両端が黒くグラデーションがかったようになるのですが、こちらがないほうが良い気がします。

この効果は、写真の時はあまり違和感なくはいってはいますが、
例えば色のベタ塗りなどの時、色が暗く表示されてしまいあまり見栄えが良くない状況です。

他のフォトアルバムでの投稿を修正の際に、こちらも修正願いたいのですが、
要望になると思いますのでご意見お伺いしつつご検討願います。

#1006 
#1068 と　#1164　は同じことのような気がします。

**Comment by akagane99** [comment]
> #1068 と　#1164　は同じことのような気がします

ご指摘感謝です。
#1164 にコメント書かせてもらいました。

**Comment by akagane99** [comment]
> 両端が黒くグラデーション

この修正が欲しい方は、他にどの位いらっしゃいますか？
修正欲しい方は、簡単なコメント等(+1とか)でいいので、コメントして頂きたいです。
そうすると、この要望が目立って注目できるので、修正対象になりやすいかなぁと思いました。

また、修正できるかどうかは未調査です。

**Comment by nagasheep** [comment]
＋１します。

別テーマ作ってオーバーライドする際は、以下のようにして影を消しています。
.carousel-control.right,
.carousel-control.left{
    background-image: -webkit-linear-gradient(left,rgba(0,0,0,.0001) 0,rgba(0,0,0,0) 100%);
    background-image: -o-linear-gradient(left,rgba(0,0,0,.0001) 0,rgba(0,0,0,0) 100%);
    background-image: -webkit-gradient(linear,left top,right top,from(rgba(0,0,0,0)),to(rgba(0,0,0,.5)));
    background-image: linear-gradient(to right,rgba(0,0,0,.0001) 0,rgba(0,0,0,0) 100%);
}

以上、参考までに。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/PhotoAlbums/pull/18#issuecomment-367565530
修正しました。
特になければ２，３日中にプルリクエストをマージしようと思っています。

![image](https://user-images.githubusercontent.com/2756509/36520734-12657f0e-17d6-11e8-8ad9-3c2e4255d0e7.png)

**Comment by onozaki** [comment]
ありがとうございます！
是非是非よろしくお願いします。
それが完了しましたら、その部分のパッチを当てれば上記内容が反映されているということでしょうか？

その他のフォトアルバムのバグもこれからなおりそうであれば、そちらを含めてクライアントのサイトへパッチをあてたいと考えていますので、他のissueについても対応いただけるよう呼びかけたいと思います！
#1006 #1068 #1164 
ご対応、本当にありがとうございます。
今後もよろしくお願いします！
