### ISSUE TITLE
angularJSの依存性注入は配列アノテーション式がいいのではないか？

### ISSUE THREAD

**Issue by to-hashimoto-3** [NetCommons3/NetCommons3#118]
JSをかいていて、気になったのですが、
angularをつかってかいているところで、
controller('hoge', function($scope){ ...})  という
書き方を多くみました。

angularJS本やangularJS解説サイトだと、
jsファイルを、minify（xxx.min.jsにして圧縮する場合）
contoller('hoge',[ '$scope', function($scope){...}]);
と、変数と関数を[]でくくる「配列アノテーション」を使っておかないといけません、
と書いているのを見ました。

参考URL http://dev.classmethod.jp/client-side/javascript/angularjs-4/

> ～
> コントローラでDI
> コントローラはアプリの振る舞いを定義します。 コントローラ宣言では、配列を使用したDI方法がよく使用されます。
> someModule.controller('MyController', 
> ['$scope', 'service1', 'service2', function($scope, service1, service2) {
>  ...
>  $scope.someMethod = function() {
>    ...
>  }
>  ...
> }]);
> 
> このようにすることで、コントローラがグローパル関数化される事を防ぎ、JavaScript圧縮化への対処にもなります。
> ～

NC3もリリース時、JSをminify(xxx.min.js)してリリースすることが想定されるなら、
今の内にこの配列アノテーション記法に統一しておいたほうがいいとおもったのですが、
いかがでしょうか？

**Comment by RyujiAMANO** [comment]
＋1　やる方向でいいですよね

**Comment by kteraguchi** [comment]
はい。やりましょう！

**Comment by s-nakajima** [comment]
別のIssueにあげたので、Close
