### ISSUE TITLE
app/webroot/favicon.ico の削除依頼

### ISSUE THREAD

**Issue by nagasheep** [NetCommons3/NetCommons3#1182]
こんにちは。
株式会社オープンソース・ワークショップの永原です。

ドキュメントルートにCakePHP のfavicon があるのです。
この、ドキュメントルートのfavicon は削除して欲しいです。

ページを表示するときは、Netcommons のfaviconが表示されていると思います。
それはそのままで、ドキュメントルートのfavicon はなし。がありがたいです。

そうしておくと、faviconを変更したいときや、PDF などを新規ウィンドウで開いたときにも、favicon の内容を制御しやすくなります。
コアソースのドキュメントルート上におかれると、アップデートするときに、CakePHP のfavicon で上書きされるので、ちょっと良くなくて。

以上、ご検討をお願いします。

**Comment by akagane99** [comment]
favicon.icoが２つありますが、それぞれ表示される場所が違うようです。

### (1) app/webroot/favicon.ico

画像やPDFを開く時に表示されます。
消すとfaviconは表示されません。

### (2) app/Plugin/NetCommons/webroot/favicon.ico

ページを開く時に表示されます。

このため、(1) を消すのではなく、(2)を(1)に上書きするのが正しい形かと思うのですが、どうなんでしょうね。

**Comment by akagane99** [comment]
もくもく会で話してみたところ、(1) 削除でいいんじゃない？という事になりました。
これでプルリクエストなげようと思います。

**Comment by akagane99** [comment]
対応しました。
２，３日して問題なければプルリクエストをマージしようと思ってます。
