### ISSUE TITLE
汎用データベース、日付型で空を登録したら、表示が1970-01-01 00:00:00 

### ISSUE THREAD

**Issue by nagasheep** [NetCommons3/NetCommons3#1184]
こんにちは。
株式会社オープンソース・ワークショップの永原です。

NetCommons3.1.7です。
汎用データベース、日付型で空を登録したら、表示が1970-01-01 00:00:00 になってしまいます。

以上、報告です。

**Comment by akagane99** [comment]
対応方法
https://github.com/NetCommons3/Multidatabases/blob/b49db40186eac4a8f75b8a804c711204516a9663/View/Helper/MultidatabaseContentViewElementHelper.php#L129

値が空の場合、ここでセットさせない。

**Comment by akagane99** [comment]
対応しました。
次期バージョン（nc3.1.10）で解消すると思います。
