### ISSUE TITLE
新着情報・もっと見る押下で正常に表示されない

### ISSUE THREAD

**Issue by horitada** [NetCommons3/NetCommons3#1186]
表示方法が[ルーム毎に表示する]に選択されている新着で、
一覧（初期）表示画面のもっと見るボタンを押下しても続きが表示されない。

データは渡って来ている模様。
パスカルケース？キャメルケース？の指定ミスのような気がします。

**Comment by akagane99** [comment]
設定によって「もっと見る」が表示できる・できないがありました。
・フラットで表示：表示できる
・プラグイン毎に表示：表示できない（追記：＆指定したプラグインのみ表示するの時のみ、表示できない）
・ルーム毎の表示：表示できない

**Comment by akagane99** [comment]
対応しました。
