### ISSUE TITLE
ウィジウィグで消えるタグの属性がある

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1189]
ルームでスプリクトを許可されてるシステム管理者でも、消える。
単なる属性であれば、タグ書かせてもよいかと思います。

### 例）Chromeのvideoタグの拡張属性(controlsList). 

ダウンロードボタン非表示の時につかう。

```html
<video controlsList="nodownload">
```

### 例）bootstrapのbuttonタグの拡張属性(data-toggle data-target). 

折り畳みメニュー表示の時につかう。

```html
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
```

### 調査

・PurifiableBehaviorで消えるパターン
・ウィジウィグで書いた時点で消えるパターン(javascriptで制御)

の2パターンがあって、まだうまく整理できてないです。

#### PurifiableBehaviorで消えるパターン調査

部品
app\Plugin\Wysiwyg\Model\Behavior\PurifiableBehavior.php

部品からよびだしてるライブラリ
htmlpurifier

書けない属性
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
のdata-toggle、data-target

部品のおおもと
https://github.com/ezyang/htmlpurifier

部品のバージョン HTMLPurifier_Filter
/var/www/app/vendors/ezyang/htmlpurifier/VERSION
> 4.9.3

公式サイトのDOC
http://htmlpurifier.org/docs
http://htmlpurifier.org/live/configdoc/plain.html
http://htmlpurifier.org/docs/enduser-customize.html

解決策？
https://stackoverflow.com/questions/4464004/htmlpurifier-custom-attributes

costumtagはここらへんいじる？
https://github.com/NetCommons3/Wysiwyg/blob/3.1.7/Model/Behavior/PurifiableBehavior.php#L401
→ ここにタグ追加すればいける。

#### ウィジウィグで書いた時点で消えるパターン調査

ここらへんで制御してそう。ここは「許可するタグの設定」のみだけど。
https://github.com/NetCommons3/Wysiwyg/blob/3.1.7/View/Helper/WysiwygHelper.php#L138
→ ここにタグ追加すればいける。

```php
$constants['extended_valid_elements']
```

部品
/var/www/app/app/webroot/components/angular-ui-tinymce
/var/www/app/app/webroot/components/tinymce

バージョン
/var/www/app/app/webroot/components/tinymce/tinymce.js
> // 4.5.8 (2017-10-05)

公式サイトのDOC
https://www.tinymce.com/docs/configure/content-filtering/#extended_valid_elements

**Comment by akagane99** [comment]
ウィジウィグで画像追加の時のタグも一部消えてました。
そのため、画像の編集ダイアログで画像サイズは、data-sizeをみてるのですが、取得できず、原寸大が選択された状態になってます。

```html
<img class="img-responsive nc3-img nc3-img-block" title="" src="http://127.0.0.1:9094/wysiwyg/image/download/1/9/big" alt="" data-size="big" data-position="" data-imgid="9" />
↓
↓登録後
↓
<img class="img-responsive nc3-img nc3-img-block" title="" src="http://127.0.0.1:9094/wysiwyg/image/download/1/9/big" alt="" />
```

とりあえずここまで。

**Comment by RyujiAMANO** [comment]
HTML制限無しでもhtmlpurifierを通してるから色々おきてるんだろうかから、Current::permission('html_not_limited')がtrueなら何もしないように改修したらいいように思うんだけど、それじゃダメな理由って何かあるかな？

**Comment by ryu818** [comment]
りゅうじさんの発言しかみてなく、しかも、よく調べていないので、検討違いだったらながしてください。

タグが壊れた状態で登録された場合、画面が表示されなくなるからではないでしょうか。

**Comment by akagane99** [comment]
ダメな理由なさそうな。

いっぺん、動き確認したいとこですね。時間ないー＞＜
　・NC2の管理者（タグが消されない権限）使って、お知らせで壊れたタグ書いた時どうなるか。
　・NC3で、htmlpurifierを通して、壊れたタグ書いた時どうなるか。（タグ消えてくれるはず？）
　・NC3で、htmlpurifierを通さないで、壊れたタグ書いた時どうなるか。（画面表示されなくなるはず）

**Comment by akagane99** [comment]
動作確認しました。
壊れたHTMLの修復はJSでやってくれるので、問題なしでした。
htmlpurifier通さない方向でいいと思います。

## 詳細
### NC2.4.2.1ウィジウィグで壊れたHTML入力

システム管理者で。
```
<div><div><p>aaaabbbbee</div>
```
HTMLタブから切替で、JSで下記に修復された。
```
<div>
    <div>
        <p>
            aaaabbbbee
        </p>
    </div>
</div>
<br />
```

### NC3.2.1.1ウィジウィグで壊れたHTML入力

システム管理者で。

```
<div><div><p>aaaabbbbee</div>
```
HTML入力後、JSで下記に修復された。
```
<div>
<div>
<p>aaaabbbbee</p>
</div>
</div>
```

**Comment by akagane99** [comment]
CSRF対策についても検討してみた。

CSRF対策は、セキュリティコンポーネントで対応しているので、htmlpurifier通さなくても大丈夫でした。
![img_2564](https://user-images.githubusercontent.com/2756509/48539974-1fef9e00-e8fc-11e8-8eab-e4ad2d1d533a.JPG)

**Comment by akagane99** [comment]
対応しました
