### ISSUE TITLE
コンテンツコメントのエラー処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#119]
https://github.com/NetCommons3/ContentComments/blob/4670d7b0cdc43e6e46a98719b2a11908a835b6e0/Controller/Component/ContentCommentsComponent.php#L92-L94

のループ処理がちょっとわからないです。

https://github.com/NetCommons3/ContentComments/blob/4670d7b0cdc43e6e46a98719b2a11908a835b6e0/Controller/Component/ContentCommentsComponent.php#L181

でエラーをセットした結果

```
array(
    'ContentComment' => array (
        'field1' => array (
            'Error message01'
            'Error message02'
        )
        'field2' => array (
            'Error message3'
        )
    )
)
```

の様な配列になると思いますが、ループしているということはContentCommentのモデル以外もセットされるということでしょうか？

**Comment by akagane99** [comment]
> https://github.com/NetCommons3/ContentComments/blob/4670d7b0cdc43e6e46a98719b2a11908a835b6e0/Controller/Component/ContentCommentsComponent.php#L181

で`$this->_controller->ContentComment->validationErrors`をセットしているので、ループさせています。
特に他意はないです。

> の様な配列になると思いますが、ループしているということはContentCommentのモデル以外もセットされるということでしょうか？

NOです。

**Comment by kteraguchi** [comment]
了解です。
ちょっとこっちでループしないよう+α手入れます。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/ContentComments/issues/43#issuecomment-174968174
上記で対応して頂きました。
クローズします。
