### ISSUE TITLE
タイムゾーンおよび時刻書式を整えて表示する機能はPHP側処理だけでなくAngular側処理でも苦慮すべき

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#12]
タイムゾーンを考慮したり、出力の時刻書式を考慮したりする処理は、Angularのng-repeatで処理された場合も考慮して共通メソッドの提供が望まれるかと思います。
タイムゾーン変換はともかく、なんとか時刻書式のAngular-Filterの提供がほしいと思っています。
是非検討してください。

参考までに、いままのアンケートで組み込んでいた時刻書式フィルターの例を載せます

```
/**
 * ServerDatetime filter
 *
 * @param {string} filter name
 * @param {Array} use service
 */
QuestionnaireCommon.filter('ncDatetime', ['$filter', function($filter) {
  return function(input) {
    if (!input || input.length == 0) {
      return '';
    }
    var d = new Date(input.replace(/-/g, '/'));
    var nowD = new Date();
    if (d.getFullYear() == nowD.getFullYear() &&
        d.getMonth() == nowD.getMonth() &&
        d.getDate() == nowD.getDate()) {
      return $filter('date')(d, 'HH:mm');
    } else if (d.getFullYear() == nowD.getFullYear()) {
      return $filter('date')(d, 'MM/dd HH:mm');
    } else {
      return $filter('date')(d, 'yyyy/MM/dd HH:mm');
    }
  };
}]);
```

このコードはJqueryライブラリのmomenｔ、moment-timezoneが組み込まれていることに気付いていないときに作ったので、その辺を使うともっとスマートにできるかなと思います。

**Comment by RyujiAMANO** [comment]
ありがとうございます。

日時フォーマットはAngularのFilterでやって、タイムゾーンをユーザタイムゾーンに合わせるのは別途ヘルパーでと思ってます。

イメージですが、https://github.com/NetCommons3/Questionnaires/blob/master/View/QuestionnaireAdd/add.ctp#L19
のjson_encode前ぐらいのタイミングで配列の中身を再帰的にみて、指定した配列キーのデータをタイムゾーン変換できればなぁと思ってます。
