### ISSUE TITLE
混乱を招く「担当者への連絡」欄

### ISSUE THREAD

**Issue by yukio-tachikawa** [NetCommons3/NetCommons3#1204]
「掲示板」で承認機能は「不要」にしています。
この場合でも投稿画面では「担当者への連絡」欄が表示されています。
しかしここに入力されても担当者はその投稿を「編集」で確認しない限りそのことに気づかない状況です。
無用な混乱を避けるために、承認機能を使わない場合は「担当者への連絡」欄は非表示でよいのではないでしょうか？

**Comment by akagane99** [comment]
提案ありがとうございます。
毎週木曜のもくもく会で、相談してみますね。

「担当者への連絡」欄は、掲示板以外のプラグインにもあるので、やるとしたら、他のプラグインも承認機能は「不要」なら、「担当者への連絡」欄を表示しない方がいいのかなと思いました。

**Comment by yukio-tachikawa** [comment]
ありがとうございます。よろしくお願い致します。

**Comment by akagane99** [comment]
もくもく会で相談しました。
おっしゃる通り、承認なしなら「担当者への連絡」欄を表示しないように、修正する方向になりました。

**Comment by yukio-tachikawa** [comment]
ありがとうございました。楽しみにしています。

**Comment by akagane99** [comment]
### 修正予定メモ

1. WorkflowHelper.php inputComment() に引数 $useWorkflowFieldName 追加。
　https://github.com/NetCommons3/Workflow/blob/3.1.7/View/Helper/WorkflowHelper.php#L167

2. 各一般プラグインで呼び出してる箇所（$this->Workflow->inputComment()）の修正。21か所
　https://github.com/search?p=1&q=org%3ANetCommons3+%24this-%3EWorkflow-%3EinputComment&type=Code
