### ISSUE TITLE
新規登録で、項目の選択肢を「チェックボックス」にすると登録できない

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1209]
会員項目設定にて項目を新たに追加し、入力タイプを「チェックボックス」にしたものを作成すると
ユーザーがサイト右上から新規登録しようとした時、
チェックボックスの項目をきちんと選択しても「◯◯（項目名）を入力してください。」
というエラーメッセージが表示され登録できませんでした。

**Comment by akagane99** [comment]
対応しました。
