### ISSUE TITLE
phpDocumentのHTML出力結果をgithub上でみれそう

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#121]
http://qiita.com/Yuki_Yamashina/items/5d8208c450195b65344c

gh-pagesブランチを作成すると、
https://ユーザー名.github.io/リポジトリ名
でHTMLが解釈されて表示されました。

https://netcommons3.github.io/NetCommons3Docs/phpdoc/index.html

mdファイルいらない。。。。
前回の調査が足りてなかったです。
時間をみてMD→HTMLにしていきます。

**Comment by akagane99** [comment]
＋１
すげー！

**Comment by s-nakajima** [comment]
参考
https://1000ch.net/posts/2013/middleman-travis-ci.html

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3Docs のmasterブランチにPushすると生成するように修正。

各自、プラグインを修正したら、Travis上からリロードして、phpdocを更新する。
https://travis-ci.org/NetCommons3/NetCommons3Docs

ただ、Travisをリロードするのが、面倒な方は、各プラグインのmasterにPushした際に、phpdocも自動的に生成するには、下記を参考に設定してください。
https://docs.google.com/presentation/d/11fNKEVdp3q-fUK_Hkd9Xe3PEBhUf_a7kShCyLZOs6JM#slide=id.g867db8784_0_0
