### ISSUE TITLE
NetCommonsUrl::actionUrlとNetCommonsHtmlHelper::url

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#122]
通常アクションへのリンクであれば

```
$this->NetCommonsHtml->link('リンクタイトル', ['action'=>'action_name', 'key' => $data['Foo']['key']]);
```

でblock_id, frame_idが自動的に補完されたリンクになる。

ボタン等でリンクするためにURLだけ欲しいときはNetCommonsUrlを使うのかなぁと思ったが

```
NetCommonsUrl::actionUrl(['action'=>'action_name', 'key' => $data['Foo']['key']]);
```

としてもこれではblock_id, frame_idが補完されない

で、探してみたらNetCommonsHtml::url()があるのを発見。

```
$this->NetCommonsHtml->url(['action'=>'action_name', 'key' => $data['Foo']['key']]);
```

とするとblock_id, freame_idが補完される

で疑問。
- NetCommonsHtml::url()はNetCommonsUrlを使わないで内部でURL生成しちゃってる。Url生成部分はNetCommonsUrl使うようにしたほうがいいのでは？
- もしかしてNetCommonsHtml::url()があるとNetCommonsUrlは不要？

ってことでいずれリファクタリング必用そうなニオイがします

**Comment by akagane99** [comment]
+1

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3/issues/161 とサブディレクトリ対応時に、リファクタリングしたので、Closeする
