### ISSUE TITLE
ブログのWysiwyg入力後、決定時に「予期しないトークン」になる

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1222]
（１）タイムアウトの時間について

ブログの記事を投稿をする際、入力画面を開いた瞬間から10分くらい入力を行い「決定」や「一時保存」ボタンを押すと「予期しないトークン」という画面とともに入力内容がなくなってしまいます。
その間Wysiwyg内で記入を行っていますが、画面推移はない状態です。
正確な時間は計っていませんが、10分程度でタイムアウトしてしまうと記事を書く際のとても不便であり、NC3の場合はコピーをしても書式までコピーすることが不可能のため、他のところに書いたものをペーストするにしても再度書式設定などしないとならず、クライアント様からも要望が出ています。
こちらもう少し時間を長くすることは可能でしょうか？

（２）タイムアウト時のエラーメッセージについて

上記の状況でエラーになってしまった際、メッセージとして出る「予期しないトークン」という表記ですが、上記の状況でこのメッセージが出てもなにが原因でエラーになったか判別することができません。
「タイムアウトしました」など（これが適切かはわかりませんが）そのような表記にすることはできないでしょうか？

なお、こちらの問題のラベル付けがあっているかわからないので、間違っていれば訂正願います。

**Comment by RyujiAMANO** [comment]
> こちらもう少し時間を長くすることは可能でしょうか？

可能なはずですが、長く伸ばすほどワンタイムトークンとしては弱くなると思うのでどのぐらにするのが適当でしょうね。

一時保存機能があるので、タイムアウトの時間になる前に一時保存をうながすような機能（タイマーで通知とか) があればそれでも大丈夫ですかね？（アンケートとかでも必用になりそうだなこれ）

どういう解決策がいいか、いろいろアイディア出し合いたいところです

**Comment by RikaFujiwara** [comment]
これと同じですよね

https://github.com/NetCommons3/NetCommons3/issues/944

**Comment by onozaki** [comment]
#944と同じようですね。そちらにコメントします。
こちら（#1222）は閉じた方がよろしければ閉じます（もしくはCloseにしてください）

**Comment by akagane99** [comment]
#944 のissueが結構前なので、忘れられないよう（埋もれないように）にこのissueも残しておいていい気がしました。

**Comment by akagane99** [comment]
nc3.1.9には含まれていないため、issue再オープンします。
