### ISSUE TITLE
キャビネットコンテンツ通知メールの中に記載されているURLが不正のようです

### ISSUE THREAD

**Issue by mikikosatou** [NetCommons3/NetCommons3#1228]
キャビネットのコンテンツ通知メールの中に記載されているURLリンクが正しくないようです。

誤：
https://www.xxxxxxxx.jp/cabinets/cabinets/view/・・・・・

正しくは、以下とおもわれます。
https://www.xxxxxxxx.jp/cabinets/cabinet_files/view/・・・・・
(Ver.3.1.6)

**Comment by RyujiAMANO** [comment]
CabinetFileモデルでMails.MailQueueビヘイビアの設定不足があってそれが原因で発生してるようなので修正します。

以下修正用のメモ^^;
- embedTagsのX-URLを設定すること
