### ISSUE TITLE
一度、ランダム表示、横並びにチェックを入れると解除できない

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1229]

**Comment by RikaFujiwara** [comment]
小テストは対応完了

**Comment by onozaki** [comment]
3.1.9、小テストで確認しています。
確認なのですが、こちらはチェックを入れて決定を押した後、再度編集から入った時のことでしょうか？
検証をしているのですが、どの段階のことかわからず。。。

ちなみに決定を押した後だと内容の編集はできないままですが、これはデフォルトだと思うので、申し訳ないですがご教授いただければ確認します。
よろしくお願いいたします。

**Comment by RikaFujiwara** [comment]
「決定」ではなく、一時保存状態での再編集です。
一時保存だからON->OFFの変更もできるべきであるのに、それが以前はできなかったのです

**Comment by onozaki** [comment]
3.1.5のサイトでテストしたところ「一時保存」からの「編集」の再編集画面でチェックがはずせるのですが、この部分のことですか？
![a](https://user-images.githubusercontent.com/30645702/40640767-690d8938-6352-11e8-9612-f5f913963d7a.png)
