### ISSUE TITLE
キャビネットから全角文字のファイル名のファイルをDLしたら文字化け発生

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1232]
Edge、IE系のブラウザでダウンロードしたときにのみ発症する模様です。

https://github.com/NetCommons3/Cabinets/blob/master/Controller/CabinetFilesController.php#L285

ここでダウンロードファイル名に対して　rawurlencode　をかけておくべきではないでしょうか？

**Comment by nagasheep** [comment]
永原です。

以下、関係してそうですね。
https://nc2.netcommons.org/bbcbcjfav-6666/#_6666

キャビネットだけじゃなく、WYSYWYG もかな、と思っていました。
永原はとりあえず、CakePHP の該当部分をオーバーライドしました。

そこのソース、必要なら言ってください。
メールで送ります。

**Comment by RikaFujiwara** [comment]
おお、キャビネットだけじゃないでしょ、ってことですね。
それ聞いたら、変えるのこっちのほうがいいかもと。
https://github.com/NetCommons3/Files/blob/master/Controller/Component/DownloadComponent.php#L139-L146
この辺で$optionsのファイル名にrawurlencodeな気がしてきました。
CakePHPを上書きしちゃうと、外部ライブラリなので上書きはちょっと何かなあという気がするのですが。
Filesプラグインでrawurlencodeしたらまずいってプラグインありますかしら？

**Comment by nagasheep** [comment]
永原がやったのは以下の処理です。

app\Lib に
vendors\cakephp\cakephp\lib\Cake\Network\CakeResponse.php
をコピー
app\Lib\Network\CakeResponse.php
これでオーバーライド。

download関数を以下のように修正

	public function download($filename) {
		// mod by nagahara@opensource-workshop.jp ie11&Edge file name is Garbled characters.
		//$this->header('Content-Disposition', 'attachment; filename="' . $filename . '"');
		//$this->header('Content-Disposition', 'attachment; filename="' . $filename . '";filename*=UTF-8\'\'' . urlencode($filename));

		// mod by nagahara@opensource-workshop.jp - PDF is click to browser viewing. right click to file saving are file name is japanese file name.
		if ( strtolower( substr($filename, strrpos($filename, '.') + 1) ) == "pdf" ) {
			$this->header('Content-Disposition', 'inline; filename="' . $filename . '";filename*=UTF-8\'\'' . urlencode($filename));
		}
		else {
			$this->header('Content-Disposition', 'attachment; filename="' . $filename . '";filename*=UTF-8\'\'' . urlencode($filename));
		}
	}

DownloadComponent.php でどう書けばよいか、永原、まだわかっていないのですが、とりあえずこっちの情報は公開しておきます。

**Comment by nagasheep** [comment]
あ、PDF の場合はインラインで開きたいという要望も多かったので、pdf はinline にする。ということもしています。

**Comment by onozaki** [comment]
「完了」になっていたので3.1.9のバージョンアップに含まれているかと思うのですが、検証してみたところ以下のブラウザの場合文字化けが発生しました。
バージョンにより発生する可能性があるということでしょうか？
＜win＞
Firefox　→　文字化け
クロム　→　○
IE　→　○

＜mac＞
Firefox　→　文字化け
Safari　→　文字化け
クロム　→　○

**Comment by onozaki** [comment]
ちなみにこちら小テストでも発生しています。
アンケートは#985のほうに記載しています。

**Comment by RikaFujiwara** [comment]
WinのFFで発生すること確認しました。
申し訳ないです。Chrome,IE,Edgeしか動作確認してませんでした。。。
完了ではなく、修正中にします。

**Comment by RikaFujiwara** [comment]
https://tools.ietf.org/html/rfc6266#section-4.3

こちらの内容に従った処理に変更します
