### ISSUE TITLE
ヘッダでGIFアニメを表示できない

### ISSUE THREAD

**Issue by suprata** [NetCommons3/NetCommons3#1245]
ヘッダにGIFアニメを使って写真をスライドショー風に表示したいのですが、ちゃんと動きません。
方法はありますか？
NetCommons 3.1.8 にバージョンアップしましたが、うまくいきません。

**Comment by akagane99** [comment]
画像アップロードする時、画像サイズを原寸大にしたら出来ると思います。

**Comment by suprata** [comment]
素早い回答ありがとうございます。
ただ、「画像サイズを原寸大」にするとは、どうしたらいいのでしょうか？
![image-size-20180520](https://user-images.githubusercontent.com/39441600/40275307-e280b124-5c26-11e8-8911-6a9dbe08416f.PNG)
画像サイズの選択肢が、図の通り「標準サイズ」「最大」「中」「小」「サムネイル」しかありません。
ちなみに、ヘッダ用画像として、横1200ピクセルにして、「最大（1200px）」を選択してアップロードしましたが、GIFアニメのたぶん最後の1枚が見えるだけです。

**Comment by akagane99** [comment]
あれ？3.1.8だとこんな画面になるのですが、何だろう。

![cf15ce62-ef0c-48ba-b781-6e47c93b38a6](https://user-images.githubusercontent.com/2756509/40285368-1dbaa3bc-5cd6-11e8-9a2d-08d09161fcdb.png)

https://github.com/NetCommons3/NetCommons3/issues/1210

**Comment by suprata** [comment]
akagane99様
メニュー画面が違ったのですね！
実は、念のためこっちのパソコン（仕事用のノートPC）で試してみました。
出ました！　「原寸大」があります！
画像挿入してみました。うまくいきました。GIFアニメーションが動いています。
ありがとうございます。
仕事先で、今家のパソコンと比較できないですが、もしかしたらWindows のバージョンが影響しているかもしれません。
うまくいったのは、Windows10 です。うまくいかなかったのは、Windows7 です。
いずれにせよ、助かりました。ありがとうございます。
以上、お知らせします。

**Comment by suprata** [comment]
こんにちは suprata です。
今、家のパソコンで改めて編集画面を見ました。
すると、画像の挿入画面に「原寸大」の選択肢があります。
これって、修正が入った？　アップデートした覚えはありませんが。
いずれにせよ、システムとしてアニメーションGIFファイルの扱いが正常化されたということでしょうか。

**Comment by akagane99** [comment]
正常化されたようで良かったです。
原因よくわかりませんが、原寸大、3.1.8から入った機能なんです。
アップデートしてないとなると謎ですね(汗)

問題解消したようなので、ちょっとしたらissueクローズしようと思います。

**Comment by suprata** [comment]
もしかしたら、こちらのシステムを3.1.8にアップデートしたばかりだったので、まだちゃんと反映していない状態だったのかもしれませんね。
クローズして大丈夫だと思います。
ありがとうございました。
