### ISSUE TITLE
文字数制限がある？

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1249]
3.1.8のサイトにて、汎用データベースのWysiwygやテキストエリア属性に文章を入れたところ、途中までしか入りませんでした。
文字数制限があるのでしょうか。
その場合、文字数をどこで変更できますか？

**Comment by onozaki** [comment]
3.1.5のサイトを3.1.8にバージョンアップし、3.1.5の時に設置した汎用DBに文章を入れるとテキストが全て入りますが、違うフィールドにもHTMLタグ付きで全文入るという不具合も同時に発生しています。

**Comment by RikaFujiwara** [comment]
duplicate #1515

**Comment by RikaFujiwara** [comment]
#1515 と同根の問題と思うので、「完了」ラベルにします
