### ISSUE TITLE
新着情報の表示件数を変更すると、日数表示に変わってしまう

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1253]
新着プラグインの設定を「最新５件を新着とする」にしているのですが、
表示件数を変更しようとブルダウンより件数を選んだところ、
日数表示（３日分）に切り替わってしまい、その後、日数表示の変更しかできなくなりました。
　　**NetCommons **3.1.8**　【新着プラグイン3.1.7】**

![default](https://user-images.githubusercontent.com/30645702/41266782-7caad32e-6e33-11e8-8731-243bbcf92eba.png)
　　　　　　　↓
![default](https://user-images.githubusercontent.com/30645702/41266821-aaf564ec-6e33-11e8-846a-22d870fdeab9.png)

この状態で設定を見ると、「最新××日分を新着とする」に変わっており、表示項目も最初の設定と違い、すべてチェック☑が入ってしまいました。
![default](https://user-images.githubusercontent.com/30645702/41267490-a3c631da-6e36-11e8-877a-d363ecfb5da7.png)

　【最初の設定】
![default](https://user-images.githubusercontent.com/30645702/41267364-30c1ca0a-6e36-11e8-8226-0fa24b4bd099.png)

■  NetCommons **3.1.7**　【新着プラグイン3.1.7】で同じことを試したところ、
　上記のような現象はなく、件数表示の変更ができました。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/NetCommons/blob/master/View/Helper/DisplayNumberHelper.php#L178-L179
ここで件数切り替え後のURLを設定しているところでFrameIdの引数設定が漏れてるからじゃないかなと思うのですが、いかがですかね？

**Comment by akagane99** [comment]
掲示板でも報告あり。
https://www.netcommons.org/bbses/bbs_articles/view/778/6ceb88dd07b97dfa4e45b9879404d67a?frame_id=199

**Comment by schit55555** [comment]
あまり細かく検証はしておりませんが、下記のように設定したところできたようです。
他に影響があるかどうかわかりませんが、いかがでしょうか。

app/Plugin/NetCommons/View/Helper/DisplayNumberHelper.php

   
                     if (Current::read('Block.id')) {
                                $attributes['url'] = NetCommonsUrl::blockUrl($named);
                        } else {
                                #$attributes['url'] = NetCommonsUrl::actionUrlAsArray($named);
                                $attributes['url'] = NetCommonsUrl::actionUrlAsArray(
                                                        array(
                                                                'action' => 'index',
                                                                'block_id' => Current::read('Block.id'),
                                                                'frame_id' => Current::read('Frame.id'),
                                                        )
                                );
                        }

**Comment by akagane99** [comment]
情報感謝です^^
DisplayNumberHelper.phpという事で、共通部品の修正なんですね。
社内で聞いてみたところ、新着の件数切替や、ブログ、掲示板の件数切替はちゃんと動いたようです。
しかし、新着の「もっと見る」機能が動かなくなったと聞きました。

時間できたら見てみますね。

**Comment by schit55555** [comment]
ありがとうございます、お忙しいところすみませんがよろしくお願い致します。

**Comment by akagane99** [comment]
~~https://github.com/NetCommons3/NetCommons/pull/516/files~~
~~テスト中ですが、こんな感じで修正してみました。~~

> しかし、新着の「もっと見る」機能が動かなくなったと聞きました。

こちらは既存バグで、今回の修正とは無関係でした。失礼しました。
https://github.com/NetCommons3/NetCommons3/issues/1186

途中経過まで。

**Comment by akagane99** [comment]
~~修正プログラムをマージして、対応しました。~~

**Comment by akagane99** [comment]
修正内容見直して、新着のプログラムを修正するようにしました。
https://github.com/NetCommons3/Topics/pull/113/files#diff-5a273dc9ebacea1b836a2274d9fa22d2
