### ISSUE TITLE
汎用DBで、いったんテキスト型などでデータ登録した後、その項目の型を日付に変えると編集画面表示時にエラー

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1258]
日付型でない文字列が入っている場合に、そのデータを日付データとして扱えない、ということでエラーとなり画面が表示されなくなります。
以下のいずれかの対応が必要だと思います。

（１）日付型にならないデータが入っている場合は空欄扱いにして編集画面に表示
（２）項目を日付型に型変更されたときにすでに蓄積されている過去のデータを日付として扱えるものに変える
（３）汎用DBのメタデータ編集画面で「すでにデータが存在するので型の変更はできません」でガードしてしまう。

楽なのは（３）かな？

**Comment by akagane99** [comment]
対応するなら⑴かな。
データ入力あったものの、項目の型変更してるケースなので、無効な値は空でいいかと。

**Comment by akagane99** [comment]
対応しました。
次期バージョンnc3.1.10で解消すると思います。
