### ISSUE TITLE
汎用DBの詳細表示のTHの幅の定義が、そのDB項目名の中で最も長いものに合わせるようになっている。適切ではない。

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1259]
恐らくはTHで折り返しが発生しないように考えてのこととは思いますが、
横幅いっぱい使える第一セクション、第四セクションではいいけど、半分ずつの第二、第三セクションでこれをやってしまうと、表の幅のほとんどがTHでとられるという本末転倒になりかねない。

できればここはCSSで　THにwhitespace : nowrap 程度でとどめておくべき。

**Comment by akagane99** [comment]
修正ここかなぁ？
https://github.com/NetCommons3/Multidatabases/blob/cc5087470718aaa2f70b07d7cee07dd32a9cb0cb/webroot/css/style.css

なんか別件になりますが、`!important`もあるので、これも修正した方がよさそう。

**Comment by ghost** [comment]
&lt;th style="width:86rem;"&gt;と不要なCSS指定が入っており、私の事例では下図のようになってしまいました。幅を指定するのではなく、nowrapとかにすべきではないでしょうか。（表示が下図のように崩れますし、スマホにも対応できないしという理由で）

![db-ng2](https://user-images.githubusercontent.com/7931689/43395087-cf4df528-9437-11e8-82da-31cec6ba209e.png)

この一因として「タイトルだから入力必須。削除できない。データの属性を指定不能」のナゾの入力フィールドの存在があります。運用上、属性を指定できない「タイトル」なるものは使い道がないため、利用者には、「項目名」のところで、以下のような説明をせざるを得ず、ダミーデータを入力してもらうことにしました。（このナゾのタイトル項目は削除して欲しい・・・）
![db-ng1](https://user-images.githubusercontent.com/7931689/43395263-6b258c18-9438-11e8-86c5-014572774633.png)

**Comment by ghost** [comment]
うーん、&lt;th&gt;タグには全部、width指定がされてますね。スタイルシートで指定するのならともかく、これは悲惨です。
![th-width](https://user-images.githubusercontent.com/7931689/43432983-5c1884be-94b0-11e8-9d97-555217288f57.png)

**Comment by akagane99** [comment]
もし修正できそうだったら、プルリクエストやってみてください。

**Comment by ghost** [comment]
はい、トライします。とりあえずは、Defaultテーマをコピーして独自テーマを作り、style.css に以下を追記して対応中です。

> .multidatabase-contents .table th {
    width:30% !important;
    white-space:nowrap;
    text-align:left;
}

![th-width2](https://user-images.githubusercontent.com/7931689/43442594-5eb48cf8-94d9-11e8-96bd-9b5a3924a565.png)
