### ISSUE TITLE
汎用DB投稿時にメールを飛ばす設定にするが、登録内容が記載されずリンクも切れている

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1264]
汎用DBに新規投稿をした際にメールを飛ばす設定にした時、メール自体は飛んでくるが登録内容がメール内に記載されず、メール下部のURLリンクにも飛べない状態です。
バグかと思われるのですが、ご確認をお願いしたいです。

＜メールの内容＞
![p](https://user-images.githubusercontent.com/30645702/41700722-6af6a918-7564-11e8-84cb-37d6134af608.jpg)

＜URLリンクに飛ぼうとした時エラー＞
![p2](https://user-images.githubusercontent.com/30645702/41700736-7ead3b2a-7564-11e8-83b1-fccc009c397a.png)

**Comment by akagane99** [comment]
動作確認まだなのですが、飛べないurlがわかれば、原因特定に近づくと思います。
urlのドメインより後ろが、どうなってるか気になってます。

**Comment by akagane99** [comment]
調査しました。メモです。

汎用dbのメール定型文はここ。
'action' => 'detail',設定漏れてそう。ここを直せばいけるかも。
https://github.com/NetCommons3/Multidatabases/blob/master/Config/Migration/002_mail_setting_records.php#L99


登録時にメールに値セットしてる箇所
https://github.com/NetCommons3/Multidatabases/blob/master/Model/MultidatabaseContent.php#L406

メール組み込み方法
https://github.com/NetCommons3/NetCommons3/wiki/メール組み込み

メールプラグインのurl設定箇所
https://github.com/NetCommons3/Mails/blob/master/Model/Behavior/MailQueueBehavior.php#L760
https://github.com/NetCommons3/Mails/blob/master/Utility/NetCommonsExtentionTag.php#L61

**Comment by akagane99** [comment]
対応しました。
次期バージョンNC3.1.10にて解消すると思います。

**Comment by onozaki** [comment]
ありがとうございます！
次期バージョンにて確認したいと思います。
