### ISSUE TITLE
OriginalKeyBehaviorは何をしている？

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#127]
見てみたけど、よくわからなかった。
origin_idから察するにバージョン管理？
@s-nakajima に口頭で確認してみる。
### ドキュメント

https://github.com/NetCommons3/NetCommons3Docs/blob/master/phpdocMd/NetCommons/OriginalKeyBehavior.md
### ソース

https://github.com/NetCommons3/NetCommons/blob/master/Model/Behavior/OriginalKeyBehavior.php

**Comment by s-nakajima** [comment]
自動的にkeyの値をセットするビヘイビアです。afterSaveは、昔の名残。いまは、origin_idではなくkeyで統一されているので、afterSaveは後で消す予定です。

**Comment by akagane99** [comment]
感謝！
