### ISSUE TITLE
汎用DB：スマホ表示で、URLが折り返されない

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#1277]
汎用DBの属性「リンク」に長いURLを入れた時、最後の方が数字だと折り返されずに伸びてしまいました。
英単語のURLだと、折り返される時にハイフン（-）が入って折り返されました。

**Comment by akagane99** [comment]
ご報告ありがとうございます。
毎回助かってます。

対応方法は、CSSに追記かなぁ。
https://w3g.jp/blog/confusing_word-break_word-wrap
```css
  word-break : break-all;
  word-wrap : break-word;
  overflow-wrap : break-word;
```

所感
* 下記をどっかのCSSに入れれば解決しそう。
* 汎用DBに限らず発生しそう。

どこに入れるのがいいのかなぁ。
誰かわかりそうな人いますか？

**Comment by akagane99** [comment]
対応方法
https://github.com/NetCommons3/Multidatabases/blob/b49db40186eac4a8f75b8a804c711204516a9663/View/Elements/MultidatabaseContents/view/view_content_group_c1.ctp#L23

ここでメタデータがリンクなら、ワードブレイクのclass追加かなぁ。

**Comment by akagane99** [comment]
対応しました。
次期バージョン（nc3.1.10）で解消すると思います。

**Comment by onozaki** [comment]
ご対応、ありがとうございます！
次回のバージョンで確認をしてみます。
