### ISSUE TITLE
汎用DB：移行した汎用DB、メタデータを編集すると、タイトル以外の項目が強制的にタイトル指定になる場合あり

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1285]
NC3.1.9で確認しました。
移行した汎用DBのメタデータを編集すると、タイトル以外の項目が強制的にタイトル指定になる場合があります。

### 条件
* 移行した汎用DB
* 1番目以外をタイトルにしている
* メタデータを編集すると当現象が発生

### 確認したこと
* NC2ではタイトル指定を任意の項目に指定できます。
* NC3ではタイトル指定は、画面上から変更できません。

#### NC2メタデータ編集画面
![image](https://user-images.githubusercontent.com/2756509/42504737-9c2cef7a-8477-11e8-8f92-3bb6e63d0b72.png)

#### NC3メタデータ編集画面
![image](https://user-images.githubusercontent.com/2756509/42504748-a84aef00-8477-11e8-8794-7d9e9aea12c2.png)

### 原因

メタデータ編集時に1番目を強制的にis_titleに書き換えているため。
https://github.com/NetCommons3/Multidatabases/blob/5b65ffac1f228de98968b993805200608fe40698/Model/MultidatabaseMetadataEdit.php#L87

### 対応案

メタデータ内のis_titleを見て判定すればいけそう。

とりあえず報告まで。

**Comment by akagane99** [comment]
### 追加調査メモ

NC2でタイトル指定できる属性は、テキスト以外でもなんでもOKだった。
例えば、ファイルでもタイトル指摘できました。
その場合、タイトルは ファイル名 になってました。

https://github.com/NetCommons3/Multidatabases/blob/5b65ffac1f228de98968b993805200608fe40698/Model/MultidatabaseMetadataEdit.php#L87

上記のtype=textは、本来の仕様は指定しなくてよさそう。
しかし現状では、テキストのみタイトル指定を考慮してNC3の汎用DBを作られている、と思うので外すのちょっと迷う。

**Comment by akagane99** [comment]
対応しました。
次期バージョンnc3.1.10で解消すると思います。

**Comment by rs-ohno-tomoyuki** [comment]
タイトルですが、1行目がタイトルになるのは仕様となります。

開発の際、1カラム目をタイトルとするいうことで確認し、そのように実装していました。
（たしか新着情報のタイトルや検索機能での扱いやすさと、そもそも他カラムをタイトルとして扱う必要はあるのか等の判断があり、その結果タイトルは必ず1カラム目になった、ということだったと思います）

取り急ぎご報告します。

**Comment by akagane99** [comment]
> タイトルですが、1行目がタイトルになるのは仕様となります。

了解しました。

画面ではそのようになっていましたが、DBテーブルの構成上では、任意にタイトル指定できそうな作りになっていましたので、プログラムを柔軟なほうに修正させて頂きました。

修正後も1カラム目がタイトルなのは変わらずです。

またこの不具合、移行で必ず発生するのか、ちょっと微妙なとこです。
運用環境で、この不具合にでくわしましたが、移行ツールも、汎用DBもカスタムしてるため、原因の切り分けが厳密にはできない感じです。

**Comment by akagane99** [comment]
> タイトルですが、1行目がタイトルになるのは仕様となります。

改めて考えてみたところ、NC3作成上はそういう仕様なんだから、バグではなく、仕様追加になりますね。
bugタグ消して、仕様追加の意味と思って使ってるenhancementタグに変更しました。
