### ISSUE TITLE
汎用DBでCSVファイルインポートしても公開されない。

### ISSUE THREAD

**Issue by prado1996** [NetCommons3/NetCommons3#1289]
汎用DBでCSVファイルインポートしても公開されません。
インポート後、詳細を開いて決定しないと公開されません。
 @これは仕様でしょうか？
is_activeが0になっています。

**Comment by akagane99** [comment]
動作確認してませんが、不具合かと思います。
NC3のバージョンはいくつなんだろう？

**Comment by prado1996** [comment]
3.1.8と3.1.9で現象を確認しています。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Multidatabases/blob/master/Controller/MultidatabaseContentImportsController.php#L197

ここら辺でis_active=1セットすればいけるかも。

**Comment by prado1996** [comment]
>ここら辺でis_active=1セットすればいけるかも。
以前ためしたのですが、セットしてもsaveの結果は空になってしまいます。

https://github.com/NetCommons3/Multidatabases/blob/master/Model/MultidatabaseContent.php#L279

**Comment by akagane99** [comment]
```php
                //追記
		$commonDat['MultidatabaseContent']['multidatabase_id'] =
			$this->_multidatabase['Multidatabase']['id'];
                //修正
		//$commonDat['MultidatabaseContent']['status'] = 1;
		$commonDat['MultidatabaseContent']['status'] = '1';
```
でいけました。
とりあえず報告まで。

ここのstatusが型比較が厳密だったため。
こっちも直したいなぁ。
https://github.com/NetCommons3/Workflow/blob/master/Model/Behavior/WorkflowBehavior.php#L129
```php
		if ($model->data[$model->alias]['status'] === WorkflowComponent::STATUS_PUBLISHED) {
                // ↓↓↓↓↓
		if ((string)$model->data[$model->alias]['status'] === WorkflowComponent::STATUS_PUBLISHED) {
```

**Comment by akagane99** [comment]
対応しました。

### バグ内容詳細
・インポート後のコンテンツは、管理者ログインで見える。
・ログインしてないと見れない。
・statusフラグ未設定のため、「一時保存」等も表示もでてこない。

### 暫定対応
・【画面から対応】コンテンツを編集＞決定で、ログインしてなくても見れるようになる。
or
・【SQL直接で対応】変なstatusフラグのコンテンツをSQLでアップデートする。
