### ISSUE TITLE
施設予約 Firefox, IE11,エッジ で日表示の罫線がずれる

### ISSUE THREAD

**Issue by mschibata** [NetCommons3/NetCommons3#1292]
![2018-07-17_201745](https://user-images.githubusercontent.com/580571/42814299-54c77c2c-89b3-11e8-8400-26efe4e86b60.jpg)

Chrome だと大丈夫です。

IE はサポート対象外なんだと思いますが、同じ表示ずれを起こしますし、これ以外にも色々問題があってまともに動かないですね？
やたらとログイン画面に戻って変更がまともに反映できません。

一方 Firefox あたりは外せないと思いますが、本件かなりはっきりとわかるトラブルなのが気付かれていないということは、テスト環境に入ってないということでしょうか？

**Comment by akagane99** [comment]
テーマがdefault以外が設定されてそう。
他のテーマではどうでしょうか？

* 設定しているテーマは何だろう？
* NC3のバージョンはなんだろう？

**Comment by mschibata** [comment]
・ default テーマでも同様です。(表示拡大率で見え方は変わりますが)
![2018-07-18_115450](https://user-images.githubusercontent.com/580571/42856806-5c8be2b2-8a36-11e8-854f-67e4be9a2f4e.jpg)
![2018-07-18_115506](https://user-images.githubusercontent.com/580571/42856811-6042cf7e-8a36-11e8-9e51-0ffc780dd144.jpg)

もしやと思い、Chrome でも拡大してみたところ似たような状況は作れました。
![2018-07-18_120055](https://user-images.githubusercontent.com/580571/42856925-eeeb6312-8a36-11e8-8beb-66826ec8323f.jpg)


・ バージョンは、3.1.9 です。

ちなみに IE でやたらログインを要求すると書きましたが、
・ Chrome でも発生しました。
・ ただし、Nc2ToNc3 で変換をかけた場合に発生しており、イチから設定したものは正常に動いていそうです。(まだこれに時間をかけて調べていませんが)

本件とは別 Issue ですし、現状の変換精度を考えると Issue 化するかどうかは微妙です。

**Comment by RyujiAMANO** [comment]
龍司@RYUSです。
ご報告ありがとうございます。

レイアウト崩れ対応してたような気がしてたんですが、Edgeだけだったかも^^;
今、Edgeで見たら大丈夫だったけどIE11だとレイアウト崩れました^^;

現状だと表示中にリサイズするとレイアウト崩れ起きます。

リサイズ時にテーブルサイズの再計算するのと、IE11だとサイズ計算がうまいことあってないのかな、そこの修正が必用そう。

ついでにJavaScriptでエラーおきてたんでそれも修正しときたいな^^;

**Comment by akagane99** [comment]
あら？私が確認したら違った結果が。windows10です。
報告まで。

IE　ｘ
エッジ x
FireFox x
Chrome o

### IE　ｘ
![image](https://user-images.githubusercontent.com/2756509/43006466-c2ce49ac-8c70-11e8-9b62-7663c50c6016.png)

### エッジ x
![image](https://user-images.githubusercontent.com/2756509/43006491-d24a5358-8c70-11e8-9f5f-46e92f67f377.png)

### FireFox x
![image](https://user-images.githubusercontent.com/2756509/43006526-e0d75ee8-8c70-11e8-9165-10ef07be0885.png)

### Chrome o
![image](https://user-images.githubusercontent.com/2756509/43006552-ee4b03c2-8c70-11e8-9dde-ef35e0c73ef6.png)

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Reservations/commit/7ad02ff7984bba64007d6aa5ff0a0351f403f23b
PCやスマートフォンに対応するため、横幅をJQueryで計算してセットしてました。
横幅を-1すると、Chromeでも見た目損なわず、IE、Eage、FireFox対応できました。
