### ISSUE TITLE
カレンダ独特仕様のご相談（空間に最初に配置された時のblockのぶら下り方について）

### ISSUE THREAD

**Issue by to-hashimoto-3** [NetCommons3/NetCommons3#130]
お世話になります。カレンダー担当の橋本です。

いま、カレンダーpluginをページに配置する処理をコーディングしていて、悩ん出いる部分があり、
ご相談かねてNetCommons3のissueに記事POSTさせていただきました。

(詳しいやりとりは、カレンダーissueの方がいいのかもしれませんが。。）

相談したいことは、

「カレンダーの予定がぶらさがるblockの生成を、空間で最初の予定の登録まで遅延(delay)させる」案、

「カレンダplugin配置直後に、カレンダーがぶらさがるblock生成を実行するため、
 blockとCalendarCompRrule(カレンダーのtop)の間に、連結テーブル(仮名称:Calendars)を設ける」案、

 「Blockビヘイビアの__saveBlock()プライベートメソッドをpublicにしていただき、それをcallして
   カレンダーが空間でぶらさがるblock生成ほか一連処理を、直接実施する」案

の３案についてです。

----（カレンダ独自の仕様の経緯)---

 カレンダープラグインが最初にページ配置された時の処理
 カレンダーPluginにおいて「この空間・この言語」での最初のプラグイン追加となります。
 そして、カレンダーの親データである、CalendarCompRruleモデルは、［空間・言語」単位で、単一のBlockにぶら下がる必要があります。

```
    (補足：　カレンダーは、データ構成上、繰返しデータである、CalendarCompRruleモデルが親データになる)
```
## 

 一般的なplugin(ex.AccessCounter)は親モデルの登録(saveXXX)の際、saveXXX()メソッドの中で以下のような
 処理を行い、暗黙裡に、blockにぶら下がっているようです。

   (0) 自モデル, 自FrameSettingモデル、Blockモデルの３つをloadModels()する。
   (1) バリデーション
   (2) 自モデル->save()
   (3) BlockビヘイビアのbeforeSave()が呼ばれる。
       BlockビヘイビアのbeforeSave()[_1]の中で、
       (3)-1 BlockモデルとFrameモデルの２つ＋setting[loadModels]に指定あればそのモデル群をloadModels()する。
       (3)-2 Blockビヘイビアの「private」メソッド__saveBlock()[_2]でframe取得、block登録、frame更新、
             block_id,blok_keyの再帰セットの一連処理を行う。
   (4) (プラグイン名)FrameSettingモデルのsave()を呼び、表示設定の初期データを登録する。

 --

 しかし、カレンダーでは、plugin配置直後の表示設定変更画面表示の時点では、「この空間・この言語」では
 親データである予定の繰り返しCalendarCompRruleのsave()は発生していないので、Blockべヘイビアの beforeSave()を
 起動することができない。かといって、BlockビヘイビアのbeforeSave()[*1]を直接callすることは好ましくない。

 一方、BlockビヘイビアのbeforeSave()がcallしている__saveBlock()[*2]はこれを呼べば処理ができるが、これは
 プライベードメソッドなので、直接呼ぶことができない。

--(考えてみた解決策３案）

（解決案１)
 カレンダーPluginでは 親データCalendarCompRrule を登録(save)する時に、Blockをつかって
 「この空間・この言語」でのblock有無を調べ、存在しないケースはそのままsave() = BlockビヘイビアbeforeSave()を
 暗黙裡に発動.
 また、すでにblockが存在するときは、Blockを組み込まないで(unloadModulesして）CalendarCompRruleのみ登録(save)する.

 長所： blockと カレンダーPluginの親データCalendarCompRrule が直接結びつく。
 短所： 登録時、Blockのfind()処理は必ずやり、かつ 存在しない場合は BlockのunloadModulesをやるので、オーバーヘッドが大きい。

（解決案２)
 Blockデータと、カレンダーの親データであるCalendarCompRruleデータの間に、中間のモデル（仮名：Calendar）を
 １つ用意し、カレンダーplugin配置時、空間・言語単位でblockが無い時だけ、１レコードを作る(save)するようにする。
 (カレンダーには、Block一覧がないので、表示はされない、内部テーブル、である）
 そして、その後、予定の登録(save)する段では、予定の親データ(CalendarCompRrule)は、中間モデル(Calendar)を経由して
 Blockにぶら下がるようにする。

 長所： 配置直後の（中間モデル）のsave()でblock生成、frame更新,block_key,block_idがされるので、他の
pluginに倣った仕組みとなる。
 短所： 画面表示のない中間テーブルを設け得るので、なんとなく冗長な気がする。

(解決策３）
 Blockビヘイビアの__saveBlock()プライベートメソッドをpublicにしていただく。
 カレンダーplugin配置時、空間・言語単位でblockが無い時だけ、__saveBlock()をCALLして、
 カレンダーが空間でぶらさがるblock生成ほか一連処理を、直接作成することができる。ｄ

 長所： blockと カレンダーPluginの親データCalendarCompRrule が直接結びついたまま、かつ、
中間テーブルの存在も省略できる。
 短所： __saveBlock()をprivateにして隠蔽されたい意図があるとおもうので、その意に反する恐れあり。

**Comment by RyujiAMANO** [comment]
すみません、全文読んで無くてざっくり目を通した程度での感想です(^^;

解決案2の短所が下記ぐらいしか無いのであれば、これが他のプラグインの構造と似てるし一番良さそうに思えます。

> 短所： 画面表示のない中間テーブルを設け得るので、なんとなく冗長な気がする。

**Comment by kteraguchi** [comment]
まだレビューしてないですが、自分のイメージは解決案2で思ってました。

アンケートが近い処理をしています。
フレーム追加処理で、コールバックがあります。
https://github.com/NetCommons3/Frames/blob/03ab64ed1c1016af580b8d15ecad3f784f145795/Model/Frame.php#L171

んで、
https://github.com/NetCommons3/Questionnaires/blob/2044f282893e96dbccb58f16b35ea0297aa02103/Model/Questionnaire.php#L308
でアンケートのブロック用データを作っています。

参考まで。

**Comment by to-hashimoto-3** [comment]
ご意見、アドバイス。ありがとうございます！
お二人とも案２押しですね、、案２の短所はためたるほどのものでもなく、ぎゃくに、今後このテーブルがやくだつかもしれないので、、アンケートみながら、案２で検討すすめてみます。
ありがとうございました。
