### ISSUE TITLE
フレームタイトルを変更して決定で、フレーム（の参照？）が増殖する。

### ISSUE THREAD

**Issue by nagasheep** [NetCommons3/NetCommons3#1302]
永原です。

フレームタイトルを変更して決定で、フレーム（の参照？）が増殖する。

3.1.10 です。
「お知らせ」と「カウンター」で試して確認しました。
おそらく、プラグインは関係なく発生するのでは？と予想します。

以上、報告です。

**Comment by akagane99** [comment]
7/29のGitHub最新版（おそらくNc3.1.10）で確認しました。

### 再現手順

・お知らせをプラグイン配置。
・フレームタイトルを変更して決定。で２つ同じ内容のお知らせが表示
・1個「×」で消そうとすると、両方消える

### 画像
1個のお知らせ
![image](https://user-images.githubusercontent.com/2756509/43360900-64be01bc-92fc-11e8-9277-e080b4d1a020.png)

フレームタイトルを変更して決定
![image](https://user-images.githubusercontent.com/2756509/43360903-7f6e18ee-92fc-11e8-9d79-f6c49b502b25.png)

2個表示される。フレームタイトル変更前/変更後のが１つづつ表示されてました。
![image](https://user-images.githubusercontent.com/2756509/43360905-91dda030-92fc-11e8-9b21-b65c2c2aeb64.png)

1個「×」で消そうとする
![image](https://user-images.githubusercontent.com/2756509/43360917-ba2e2d0c-92fc-11e8-845e-93bc76e5afe3.png)

2個とも消えた
![image](https://user-images.githubusercontent.com/2756509/43360921-cbb7b494-92fc-11e8-8c85-1b7adbed724f.png)

**Comment by akagane99** [comment]
・フレームタイトル変更時に、フレーム言語データ（frames_languages）が2件になる。
・そのデータをゲットするけど、本来は1件取得のはずが2件とってきていた。
・さて、そのゲットしてる処理はどこだろう？

とりあえずここまで。

### 問題のSQL

```sql
SELECT 
    `Frame`.`id`,
    `Frame`.`room_id`,
    `Frame`.`box_id`,
    `Frame`.`plugin_key`,
    `Frame`.`block_id`,
    `Frame`.`key`,
    `Frame`.`header_type`,
    `Frame`.`weight`,
    `Frame`.`is_deleted`,
    `Frame`.`default_action`,
    `Frame`.`default_setting_action`,
    `Frame`.`created_user`,
    `Frame`.`created`,
    `Frame`.`modified_user`,
    `Frame`.`modified`,
    `Box`.`id`,
    `Box`.`container_id`,
    `Box`.`type`,
    `Box`.`space_id`,
    `Box`.`room_id`,
    `Box`.`page_id`,
    `Box`.`container_type`,
    `Box`.`weight`,
    `Box`.`created_user`,
    `Box`.`created`,
    `Box`.`modified_user`,
    `Box`.`modified`,
    `Block`.`id`,
    `Block`.`room_id`,
    `Block`.`plugin_key`,
    `Block`.`key`,
    `Block`.`public_type`,
    `Block`.`publish_start`,
    `Block`.`publish_end`,
    `Block`.`content_count`,
    `Block`.`created_user`,
    `Block`.`created`,
    `Block`.`modified_user`,
    `Block`.`modified`,
    `Room`.`id`,
    `Room`.`space_id`,
    `Room`.`page_id_top`,
    `Room`.`parent_id`,
    `Room`.`lft`,
    `Room`.`rght`,
    `Room`.`active`,
    `Room`.`in_draft`,
    `Room`.`default_role_key`,
    `Room`.`need_approval`,
    `Room`.`default_participation`,
    `Room`.`page_layout_permitted`,
    `Room`.`theme`,
    `Room`.`created_user`,
    `Room`.`created`,
    `Room`.`modified_user`,
    `Room`.`modified`,
    `TrackableCreator`.`id`,
    `TrackableCreator`.`handlename`,
    `TrackableUpdater`.`id`,
    `TrackableUpdater`.`handlename`,
    `Plugin`.`id`,
    `Plugin`.`language_id`,
    `Plugin`.`is_origin`,
    `Plugin`.`is_translation`,
    `Plugin`.`is_original_copy`,
    `Plugin`.`key`,
    `Plugin`.`is_m17n`,
    `Plugin`.`name`,
    `Plugin`.`namespace`,
    `Plugin`.`weight`,
    `Plugin`.`type`,
    `Plugin`.`version`,
    `Plugin`.`commit_version`,
    `Plugin`.`commited`,
    `Plugin`.`default_action`,
    `Plugin`.`default_setting_action`,
    `Plugin`.`frame_add_action`,
    `Plugin`.`display_topics`,
    `Plugin`.`display_search`,
    `Plugin`.`serialize_data`,
    `Plugin`.`created_user`,
    `Plugin`.`created`,
    `Plugin`.`modified_user`,
    `Plugin`.`modified`,
    `FramePublicLanguage`.`id`,
    `FramePublicLanguage`.`language_id`,
    `FramePublicLanguage`.`frame_id`,
    `FramePublicLanguage`.`is_public`,
    `FramesLanguage`.`id`,
    `FramesLanguage`.`language_id`,
    `FramesLanguage`.`frame_id`,
    `FramesLanguage`.`name`,
    `FramesLanguage`.`is_origin`,
    `FramesLanguage`.`is_translation`,
    `FramesLanguage`.`is_original_copy`,
    `BlocksLanguage`.`language_id`,
    `BlocksLanguage`.`block_id`,
    `BlocksLanguage`.`name`,
    `BlocksLanguage`.`is_origin`,
    `BlocksLanguage`.`is_translation`,
    `BlocksLanguage`.`is_original_copy`
FROM
    `nc3`.`frames` AS `Frame`
        LEFT JOIN
    `nc3`.`boxes` AS `Box` ON (`Frame`.`box_id` = `Box`.`id`)
        LEFT JOIN
    `nc3`.`blocks` AS `Block` ON (`Frame`.`block_id` = `Block`.`id`)
        LEFT JOIN
    `nc3`.`rooms` AS `Room` ON (`Frame`.`room_id` = `Room`.`id`)
        LEFT JOIN
    `nc3`.`users` AS `TrackableCreator` ON (`Frame`.`created_user` = `TrackableCreator`.`id`)
        LEFT JOIN
    `nc3`.`users` AS `TrackableUpdater` ON (`Frame`.`modified_user` = `TrackableUpdater`.`id`)
        LEFT JOIN
    `nc3`.`plugins` AS `Plugin` ON (`Plugin`.`key` = `Frame`.`plugin_key`
        AND `Plugin`.`language_id` = 2)
        LEFT JOIN
    `nc3`.`frame_public_languages` AS `FramePublicLanguage` ON (`FramePublicLanguage`.`frame_id` = `Frame`.`id`
        AND `FramePublicLanguage`.`language_id` IN (0 , 2)
        AND `FramePublicLanguage`.`is_public` = '1')
        LEFT JOIN
    `nc3`.`frames_languages` AS `FramesLanguage` ON (`FramesLanguage`.`frame_id` = `Frame`.`id`
        AND `FramesLanguage`.`language_id` = 2)
        LEFT JOIN
    `nc3`.`blocks_languages` AS `BlocksLanguage` ON (`BlocksLanguage`.`block_id` = `Block`.`id`
        AND `BlocksLanguage`.`language_id` = 2)
WHERE
    `Frame`.`is_deleted` = '0'
        AND `Frame`.`box_id` = 74
ORDER BY `Frame`.`weight` ASC
```

### 検索結果
12 | 1 | 74 | announcements | 7 | ee1eaaf158620b8ba6bb8c77ae5f03f2 | default | 1 | 0 |   |   | 1 | 2018-07-28 22:06:52 | 1 | 2018-07-28 22:07:57 | 74 |   | 4 | 2 | 1 | 7 | 3 |   |   |   |   |   | 7 | 1 | announcements | abd5196ab46675fd807b484756015e34 | 1 |   |   | 0 | 1 | 2018-07-28 22:07:01 | 1 | 2018-07-28 22:07:01 | 1 | 2 | 4 | 4 | 1 | 2 | 1 | 0 | visitor | 1 | 1 | 1 | Default |   | 2018-07-28 21:41:58 |   | 2018-07-28 21:41:58 | 1 | システム管理者 | 1 | システム管理者 | 9 | 2 | 1 | 1 | 0 | announcements | 1 | お知らせ | netcommons/announcements |   | 1 | dev-master | 0c4a1b5fa07db90ed7c2a47334f4a6bde794d042 | 2018-01-26 07:39:07 | announcements/view | announcement_blocks/index | announcements/edit | 1 | 1 | a:14:{s:3:"key";s:13:"announcements";s:9:"namespace";s:24:"netcommons/announcements";s:11:"description";s:35:"Announcements for NetCommons Plugin";s:8:"homepage";s:26:"http://www.netcommons.org/";s:7:"version";s:10:"dev-master";s:14:"commit_version";s:40... |   | 2018-07-28 21:42:01 |   | 2018-07-28 21:42:01 | 10 | 0 | 12 | 1 | 12 | 2 | 12 | お知らせ1 | 1 | 0 | 0 | 2 | 7 | １ | 1 | 0 | 0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
12 | 1 | 74 | announcements | 7 | ee1eaaf158620b8ba6bb8c77ae5f03f2 | default | 1 | 0 |   |   | 1 | 2018-07-28 22:06:52 | 1 | 2018-07-28 22:07:57 | 74 |   | 4 | 2 | 1 | 7 | 3 |   |   |   |   |   | 7 | 1 | announcements | abd5196ab46675fd807b484756015e34 | 1 |   |   | 0 | 1 | 2018-07-28 22:07:01 | 1 | 2018-07-28 22:07:01 | 1 | 2 | 4 | 4 | 1 | 2 | 1 | 0 | visitor | 1 | 1 | 1 | Default |   | 2018-07-28 21:41:58 |   | 2018-07-28 21:41:58 | 1 | システム管理者 | 1 | システム管理者 | 9 | 2 | 1 | 1 | 0 | announcements | 1 | お知らせ | netcommons/announcements |   | 1 | dev-master | 0c4a1b5fa07db90ed7c2a47334f4a6bde794d042 | 2018-01-26 07:39:07 | announcements/view | announcement_blocks/index | announcements/edit | 1 | 1 | a:14:{s:3:"key";s:13:"announcements";s:9:"namespace";s:24:"netcommons/announcements";s:11:"description";s:35:"Announcements for NetCommons Plugin";s:8:"homepage";s:26:"http://www.netcommons.org/";s:7:"version";s:10:"dev-master";s:14:"commit_version";s:40... |   | 2018-07-28 21:42:01 |   | 2018-07-28 21:42:01 | 10 | 0 | 12 | 1 | 13 | 2 | 12 | お知らせ変更 | 1 | 0 | 0 | 2 | 7 | １ | 1 | 0 | 0

**Comment by akagane99** [comment]
修正するのは、ここら辺かな
https://github.com/NetCommons3/Frames/blame/master/Model/Frame.php#L120

**Comment by nagasheep** [comment]
永原です。
保存するときに、フレームのタイトルを持つレコードが2件、できてしまっているんじゃないかと、見えるんだけどね。


2018/07/29 7:28 "Mitsuru Mutaguchi" <notifications@github.com>:

修正するのは、ここら辺かな
https://github.com/NetCommons3/Frames/blame/master/Model/Frame.php#L120

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NetCommons3/NetCommons3/issues/1302#issuecomment-408638871>,
or mute the thread

**Comment by akagane99** [comment]
FrameモデルのbindModelFrameLang()だけ、1個前にもどしてみた（※）けどバグ改善されませんでした。
念のため報告まで。

※1個前にもどしてみた
速度改善のための修正　https://github.com/NetCommons3/Frames/commit/2a423dcfeef1a20775e40d79def208c1831bc18f#diff-355b352d3b3d41242c127314e65562b1
↓
Change BlocksLanguage::useDbConfig https://github.com/NetCommons3/Frames/commit/b931a4c055a0b4f722f738b4b82b9d62d7898f0e#diff-355b352d3b3d41242c127314e65562b1

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons/pull/491
@s-nakajima 修正感謝！直りました。
