### ISSUE TITLE
【3.1.10】一般権限ユーザーはセッティングモードに変更できない

### ISSUE THREAD

**Issue by SatohDaisuke** [NetCommons3/NetCommons3#1309]
3.1.9から3.1.10にアップデートした後に以下のことが発生しています。
一般権限（ルーム管理者）については、セッティングモードONへの変更が不可能な状態です。クリックすると、トップ画面に戻されます（ログイン状態は維持されています）。この際、一般（ルーム管理者）の場合、セッティングモードON がトップ画面では権限がないので、OFF になってしまうということです。
そのため、トップ画面の権限があるシステム管理者権限（ルーム管理者）であれば、どのページであってもセッティングモードONにすると、トップ画面のセッティングモードが表示されます。

**Comment by akagane99** [comment]
下記のセッティングモードをセッションで維持する修正の中で、
https://github.com/NetCommons3/NetCommons3/issues/443

> セッティングモードを切り替えたときにページトップに戻るように修正
> https://github.com/NetCommons3/Pages/pull/148

が含まれていたので、その影響っぽいですね。
なにか修正した理由があると思うのですが、そこまではわからずです。

**Comment by osws-makino** [comment]
同現象確認しました。
再現方法です。
【ユーザー】：特定のルーム管理者ではあるが、パブリックには権限がない
・セッティングモード権限があるルームにて「セッティングモードON」リンクをクリック
・トップページへ強制遷移する
・トップページ（パブリックエリア）にはセッティング権限がない為、強制的にセッティングモードOFFになる
・セッティングモード権限があるルームへ遷移する
・強制的にセッティングモードがOFFになっている
・「セッティングモードON」のリンクをクリック　　……以下無限ループ

その為、ユーザーがサイト全体に編集権限を保持していると発生しない現象のようです。
以上、報告でした。

**Comment by akagane99** [comment]
> クリックすると、トップ画面に戻されます

もし、セッティングモード＝ON時に、トップ画面にもどされてたくない場合、手動でPagesController.phpを、下記ファイルで上書きすれば直ります。（NC3.1.10の最新から1つ前（セッティングモード切替アクション追加）のPagesController.phpです）

~~※一般権限ユーザーはセッティングモードに変更できない不具合が、直るかどうかまでは未確認です。~~

https://github.com/NetCommons3/Pages/blob/15eeb7176ce1ca28c0dd2d843d91670952bcf206/Controller/PagesController.php

【参考】PagesController.phpの更新履歴はこちら
https://github.com/NetCommons3/Pages/commits/master/Controller/PagesController.php

**Comment by akagane99** [comment]
> ※一般権限ユーザーはセッティングモードに変更できない不具合が、直るかどうかまでは未確認です。

https://github.com/NetCommons3/NetCommons3/issues/1309#issuecomment-409522143

上記を基に、動作確認してみました。
動きました。
お試しください。

### 動作確認

* 一般ユーザで
* パブリックルームはゲスト権限
* プライベートルームはルーム管理者
* 「操作」プライベートルームでセッティングモード＝ON

これでプライベートルームで、セッティングモード＝ONに切り替わること確認しました。

（蛇足）
また、この状態からパブリックルームを開くと、セッティングモードがOFFになり、
プライベートルームに戻っても、セッティングモードはOFFのままでした。

### 補足

* パブリックルームのルーム管理者のユーザであれば、この現象は発生しません。
（トップページに飛ばされても、ルーム管理者権限があり、セッティングモード=ONにできるため）

**Comment by akagane99** [comment]
本対応の内容です。
@s-nakajima さんに修正してもらいました。

https://github.com/NetCommons3/Pages/pull/149/files
https://github.com/NetCommons3/NetCommons/pull/492/files

この不具合は下記の症状がでるため、影響が多いと思い、上記を近日中にパッチとして公開する方向で進めています。
パッチ公開の際は、公式サイトに情報をのせて、使っているユーザの皆さまに連絡しようと思っています。

症状
・一般ユーザでパブリックルームのルーム管理者もっていないユーザは、セッティングモードがONにできない不具合です。
・一般ユーザのほとんどは、パブリックルームのルーム管理者をもっていないと思いますので、かなり痛いと思います。
・・例１）プライベートルームのセッティングが不可能になる
・・例２）コミュニティルームのルーム管理者は、セッティングが不可能になる。

ご連絡まで。

**Comment by SatohDaisuke** [comment]
早速にご対応くださり、ありがとうございました。
パッチ公開をお待ちしております。

**Comment by akagane99** [comment]
お待たせしました。パッチ公開しました。
https://www.netcommons.org/blogs/blog_entries/view/6/fe93a33648a37366b593ad6e8105d494?frame_id=13

ご連絡まで。
