### ISSUE TITLE
新しく追加したブロック設定タブのラベル名、多言語セットできず

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#132]
settingで__d()使うとsyntax errorになった。
解決策わからなかった。
@s-nakajima なにか対応方法ある？（優先度：低）
### ブロックタブ設定（VideoBlocksController.php）

https://github.com/NetCommons3/Videos/blob/c142f0945524a57de744e2afa7638dc1dda4634c/Controller/VideoBlocksController.php#L58

```
    public $components = array(
        'Blocks.BlockTabs' => array(
            'mainTabs' => array('block_index', 'frame_settings'),
            'blockTabs' => array(
                'block_settings',
                'role_permissions',
                'mail_settings' => array(
                    'url' => array(
                        'plugin' => 'videos',
                        'controller' => 'video_mail_settings',
                        'action' => 'edit',
                    ),
                    // 暫定対応
                    //'label' => __d('mails', 'メール設定'),    ←これエラー
                    'label' => 'メール設定',
                ),
            ),
        ),
        'NetCommons.Permission' => array(
            //アクセスの権限
            'allow' => array(
                'index,add,edit,delete' => 'block_editable',
            ),
        ),
        'Paginator',
    );

```
### ブロックプラグインでブロックタブの表示してるところ（block_tabs.ctp）

https://github.com/NetCommons3/Blocks/blob/51190eb5385ca32cca960409f5f5c136abb421cd/View/Elements/block_tabs.ctp#L47

``` php
                    <?php echo (isset($tab['label']) ? $tab['label'] : $tabKey); ?>
```

**Comment by akagane99** [comment]
レビュー指摘済み。
修正前でした。
下記対応が終わったら、解消する見込み。

https://github.com/NetCommons3/Blocks/blob/1037ad5cbb34dfb6fb269816c220f618636be807/README.md#blocktabscomponent

> ### BlockTabsComponent
> 
> なくなる予定
> BlockFormHelperに統合

**Comment by s-nakajima** [comment]
BlockTabsComponentはなくす予定だけれども、BlockFormHelperに統合するつもりはない。BlockTabsHelperのみにする。

**Comment by akagane99** [comment]
そうなんですね。
readme.mdを見て書いたのですが、どうも現状とはあっていないようです。

readme.mdを修正した方が良いと思います。

また、私の指摘した箇所については、helperで解消される、という認識でよかったでしょうか。
ご回答待ってます。

**Comment by s-nakajima** [comment]
https://netcommons3.github.io/NetCommons3Docs/phpdoc/Blocks/classes/BlockTabsHelper.html#method_beforeRender
サンプル3を参照
