### ISSUE TITLE
汎用DBのコンテンツ通知メールの中に記載されているURLリンクが正しくないようです

### ISSUE THREAD

**Issue by mikikosatou** [NetCommons3/NetCommons3#1332]
汎用DBのコンテンツ通知メールの中に記載されているURLリンクが正しくないようです。

誤：
https://www.xxxxxxxx.jp/multidatabases/multidatabase_contents/view/・・・・・

正しくは、以下とおもわれます。
https://www.xxxxxxxx.jp/multidatabases/multidatabase_contents/detail/・・・・・
(Ver.3.1.9)

（汎用DBのメールビヘイビアの組み込みで、action名の指定忘れのようです）

**Comment by akagane99** [comment]
これと同じかな？
NC3.1.10で解消していますね。
https://github.com/NetCommons3/NetCommons3/issues/1264
