### ISSUE TITLE
回覧板、記述式で回答しても回答済みにならない

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1339]
NC3.2.0で確認しました。

記述式で回答しても、回答が反映されませんでした。
とりあえず報告まで。

![image](https://user-images.githubusercontent.com/2756509/45271555-cd9c9600-b4e2-11e8-9207-b3d183c5c273.png)

**Comment by ohga21** [comment]
情報をいただきありがとうございます。
記述式の他、選択式も同様でした。
本件は、修正しマージを行いました。

**Comment by ghost** [comment]
「回答が反映されない」の具体的な意味を確認させてください。

私は、NC3.2.0で以下のような回覧板を設置し「辺 周長」なるユーザで回答してみました。
その結果、赤枠内の各項目である、
・「回答状況」
・「選択肢：」行の「回答数：」
・「回答」フレーム内でどの回答がなされたか
・「回答日時」
が、反映されていないという意味でしょうか。
また、これらを修正いただけたので、次回NCリリース時に改善されているという理解でよろしいでしょうか。

![default](https://user-images.githubusercontent.com/7931689/47262161-04bb8980-d51c-11e8-9dd3-15acea1b0a49.png)

**Comment by ghost** [comment]
3.2.1がリリースされましたので、早速試してみましたところ、回覧板プラグインも3.2.1にアップデートされておりました。でも、リリース内容の一覧（GitHubアナウンス）には、本スレッドの内容は含まれておりませんでした。

それはともかくとして、動作を確認しましたところ、上記の添付画像の赤枠内はすべて表示されておりました。
ありがとうございました！

**Comment by akagane99** [comment]
ご指摘及び、動作確認感謝です。
label「00Inbox」のままだったので、見落としてました。（汗）

リリースラベル付けましたので、クローズさせて頂きます。
