### ISSUE TITLE
単数、複数の国際化

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#134]
表示件数のHelper
https://github.com/NetCommons3/NetCommons/blob/ec01dd9b13e2e20133fa473aaf50d394dc213390/View/Helper/DisplayNumberHelper.php#L49-L57

で単数、複数の単位を使い分けていますが、_dnを使用するようにしといた方が良いと思います。
http://book.cakephp.org/2.0/ja/core-libraries/global-constants-and-functions.html#__dn

gettextの仕様っぽいです。

**Comment by s-nakajima** [comment]
了解です。
