### ISSUE TITLE
3.2.0 で施設予約のカテゴリーのバグ

### ISSUE THREAD

**Issue by nagasheep** [NetCommons3/NetCommons3#1343]
永原です。

3.2.0 で施設予約のカテゴリーのバグを見つけたので報告です。

カテゴリーを登録しても、画面に表示されません。
データベースを見ると、最後の1件だけ入っているので、画面表示時のバグなのかなと思います。

以上、報告です。

**Comment by akagane99** [comment]
3.1.9では大丈夫だったらしいです。

**Comment by akagane99** [comment]
#### 原因

カテゴリのデグレでした。
速度改善修正時に、なんでか下記箇所の小文字→大文字修正がまぎれで動かなくなってます。
このソースの変更を戻せば、動きます。

https://github.com/NetCommons3/Categories/commit/1fc39733ad384cb22d54e0de2841a183ab83aa03#diff-65e35663cca84aeb69aa5c18b7bf8215R35

#### バグ症状詳細

このバグ、具体的にはカテゴリ登録編集画面で、登録した内容が表示されない症状でした。
DBにはカテゴリを複数件登録した場合、ちゃんと登録されていました。
ただ、登録してもカテゴリ登録画面には表示されない症状でした。

#### （修正前）カテゴリ複数件登録後でもこんな画面になる
![image](https://user-images.githubusercontent.com/2756509/47155322-6b278880-d31f-11e8-896c-78e700047d2f.png)

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Categories/pull/53/files
対応しました。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Categories/pull/53/files

(1) 上記ファイルをNC3.2.0に適用しても、動かなかった。
(2) github最新のNC3では、動いた

おおよそ次バージョンでは解消されると思っています。
現時点での現象と暫定対応を記載します。

### (1)の現象

Chromeで確認。
登録はできるけど、登録後のカテゴリ登録画面に登録内容は表示されない。
更新でCategoriesLanguage.language_idがないvalidateエラーが出て、更新できない。

登録時に、CategoriesLanguage.language_idはpostには含まれていなかった。（NC3.2.0、github最新ともに）
どこかで自動セットされているはずだか、どこでセットされているのか追い切れなかった。

### (1)暫定対応

下記1行追記します。

NetCommons3\app\Plugin\Categories\Controller\Component\CategoryEditComponent.php
```
	public function startup(Controller $controller) {
		$controller->Category = ClassRegistry::init('Categories.Category');
		$controller->CategoryOrder = ClassRegistry::init('Categories.CategoryOrder');
		$controller->CategoriesLanguage = ClassRegistry::init('Categories.CategoriesLanguage');

		if ($controller->request->is(array('post', 'put'))) {
			$categories = array();
			if (! isset($controller->request->data['Categories'])) {
				$controller->request->data['Categories'] = array();
			}

			foreach ($controller->request->data['Categories'] as $post) {
				if (! isset($post['CategoriesLanguage']['name'])) {
					continue;
				}
				$category = null;
				if (! $post['Category']['id']) {
					$category = $controller->Category->createAll(array(
						'Category' => array(
							'id' => null,
						),
						'CategoriesLanguage' => array(
							'id' => null,
							'name' => $post['CategoriesLanguage']['name'],
							// =====================================================
							// 下記追記 
							// =====================================================
							'language_id' => Current::read('Language.id', '0'),
						),
						'CategoryOrder' => array(
							'id' => null,
							'weight' => $post['CategoryOrder']['weight'],
						),
					));
				}
```

**Comment by akagane99** [comment]
この修正をした後だと、ブログや、リンクリストなど他のプラグインが、同様の不具合が出ていました。
再修正します。
