### ISSUE TITLE
IEでミカエルテーマを見るとpowered by NetCommonsが上にくる

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1345]
NC3.2.0で確認しました。
ブラウザIE11, windows10です。
他のミカエルシリーズも同様かもしれませんが、確認してないです。
報告まで。

検証サイト
https://mutaguchi.netcommons3.jp/

画像
![image](https://user-images.githubusercontent.com/2756509/45759064-09152e00-bc62-11e8-8ea6-ac5fb2763a62.png)

(追記)テーマディレクトリ
https://github.com/NetCommons3/NetCommons3/tree/master/app/View/Themed

**Comment by ghost** [comment]
ミカエルシリーズはIEには非対応です。先日の3.2.0へのバージョンアップ時に、他のモダンブラウザでの動作を重視した結果、IEとは折り合いがつきませんでした・・・ IE用に別のCSSファイルを指定できるようにしていただけるようなら、対応可能なのですが・・・

**Comment by osws-makino** [comment]
OSWSの牧野です。
色々調べてみたところ、IE10～11のバグのようです。IE10～11さんは「flex」に省略形式で記載された時に間違った判定をしてしまうらしいです。
なので、省略形式を使わず「flex: 1 0 auto;」等と記載すれば直るようです。

*********************************************

app/webroot/theme/Michael4th/css/style.css
```
main.container, main.container-fluid {
    margin-top: 10px;
    flex:1 0 auto;
}
```
上記に変更したら、意図通りに表示された事を、IE11、Edge、Chrome、FireFoxで確認しました。

**Comment by akagane99** [comment]
上記対応で

* コンテンツが少ない時
  * 解消せず
* コンテンツが多い時
  * 解消しました。

コンテンツが多いとか少ないとか
https://github.com/NetCommons3/NetCommons3/commit/52d180295f3ccba6906cc97909bb5784f2e61b5d
