### ISSUE TITLE
サブルームを作成すると、Permalinkが親ルームのPermalinkが含まれないSpace直下のものとして作成される

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1352]
サブルーム作成時にはPermalinkには親ルームのPermalinkが含まれる階層化されたものが登録されるべきです

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Rooms/commit/545dadffbe58e29c2b599e4cd3f4ca4dd16c1770

@RikaFujiwara 
上記NC3.2.2で取り込まれて、リリース済みでした。
ということで、これは完了って事でOKでしょうか。

OKであれば、ラベルの更新とissueのCloseしちゃってくださいな。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Rooms/commit/545dadffbe58e29c2b599e4cd3f4ca4dd16c1770

github最新版で確認しました。
上記でサブルーム作成時、親ルームのパーマリンクが含まれ、メニューで遷移できる事を確認しました。

しかし、ページ設定の固定リンクは表示ミスで「/」に。

パブリックルーム「在校生」> サブルーム「sub1」のページ設定
![image](https://user-images.githubusercontent.com/2756509/59573876-f98f1c80-90ef-11e9-94b3-c52a7b5735ed.png)

例） パブリックルーム「在校生」> サブルーム「sub1」＞ページ「page_sub1」のページ設定
こちらは、ちゃんと表示されてる。
![image](https://user-images.githubusercontent.com/2756509/59573972-538fe200-90f0-11e9-9609-49db85d963a2.png)

報告まで。

**Comment by akagane99** [comment]
github最新版で確認しました。その２

下記でページ設定を決定すると、せっかく設定していた親ルームのパーマリンクがなくなりました。
報告まで。

ページ設定決定前のURL：/student/sub1
ページ設定決定後のURL：/sub1

> パブリックルーム「在校生」> サブルーム「sub1」のページ設定
> ![image](https://user-images.githubusercontent.com/2756509/59573876-f98f1c80-90ef-11e9-94b3-c52a7b5735ed.png)

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Rooms/commit/545dadffbe58e29c2b599e4cd3f4ca4dd16c1770
上記の修正は、ルーム管理でサブルーム作成時のみの、パーマリンク修正でした。

ページ設定でパーマリンク修正は下記で対応しました。
https://github.com/NetCommons3/Pages/pull/167/files
