### ISSUE TITLE
3.2.0 メニューの表示設定画面で「クリック時の動作」プルダウンが子ページがいない項目で表示されて、子ページがいることろで表示されない

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1353]
https://github.com/NetCommons3/Menus/blame/master/View/Helper/MenuFormHelper.php#L146
この行で、「クリック時の動作」プルダウンを表示するしないを判断する変数を設定しているが
「子ページの数」をbool値にするために（！）を付けていると思われるが、これは不要、もしくは（！！）とするべきなのではないか？

**Comment by akagane99** [comment]
修正内容
https://github.com/NetCommons3/Menus/commit/e64a39f9feb89f68af1af57438278ae5d75911af
