### ISSUE TITLE
フォルダタイプのメニューのプルダウン表示時にページの先頭に強制移動させられる

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1354]
ヘッダカラムに置くようなメニュー（タブ形式）でフォルダタイプのメニューを作成する。
メニューの上に高さが結構あるようなキービジュアル画像などを配置し、メニュー自体はページの下部ぎりぎりに来るようなデザインにする。

この場合、メニューの項目をフォルダタイプにしてプルダウンを表示させるようにすると、
プルダウンを表示するときにhref="#"が効いてしまって、プルダウン表示とともにページ先頭へ強制移動となり、プルダウンが見られない現象が発生。

href="javascript:void(0);"にするべきではないだろうか

**Comment by RikaFujiwara** [comment]
> href="javascript:void(0);"にするべきではないだろうか

これは誤り。最近の手法ではない。また、普通のBootstrapのPULL-DOWNメニューを使っていたら、ちゃんとHrefの先に移動しないようにガードが入っていた。
調べてみたら、メニュープラグインが独自に組み込んでいる機能で　liのng-clickで　Hrefの設定先に移動するような関数が実装されていた。
単にPULL-DOWNを開きたいだけのメニュー項目にも「linkClick」のAngular関数を設定していたのが誤りではないかな

**Comment by akagane99** [comment]
修正内容
https://github.com/NetCommons3/Menus/commit/e64a39f9feb89f68af1af57438278ae5d75911af
