### ISSUE TITLE
表示順の共通定義

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#136]
表示順の新着順、登録順、タイトルを共通定義しときました。
https://github.com/NetCommons3/NetCommons/commit/c328af34e1ac69541b283d7327b318475cb190e3

**Comment by akagane99** [comment]
指摘遅くなりました。
タイトルはタイトル順の方が適当のように思いますが、いかがでしょうか。

https://github.com/NetCommons3/Videos/blob/master/Locale/jpn/LC_MESSAGES/videos.po#L57

**Comment by kteraguchi** [comment]
新着順、登録順のながれできてるので、順いらないかと思いました。
順を付けるなら、msgidもSort a title とかにしといた方が良いと思います。

現状、msgid:Title、日本語:タイトルなので、使いまわしがきくかなと思ったていたのですが、
順を付けたほうが良いとかになると、融通効かなくなりますね。

タイトル「順」付けときましょう。Pushしといてください。

**Comment by akagane99** [comment]
了解

**Comment by kteraguchi** [comment]
回覧板とアンケートで少しニュアンスが違うようです。
回覧板：新着順（昇順）→modified ASC
アンケート：登録順→created ASC

結局言葉の共通は無理？
どっちかが間違ってる？

**Comment by RikaFujiwara** [comment]
ソート選択肢で最低限提供すべきは以下の認識でおります。

新着順　modified desc
登録順　created asc
タイトル順 title asc

この認識が間違っていたら訂正いたします。
いかがでしょうか

その他、それぞれのプラグインの性質によってソート条件を追加するようなイメージです
アンケートは、回答期間の締め切り日時順　「期限順」＝（end asc ) を用意します

**Comment by kteraguchi** [comment]
はい。アンケートはそれで良いと思います。
回覧板の新着順（昇順）→modified ASCをどうすかですね。
もくもく会で確認しましょう。

**Comment by go-to** [comment]
回覧板のソート選択肢も、他のプラグインに合わせることにします。
選択肢は全部で、新着順、登録順、タイトル順、回答期限順の４つになります。

**Comment by to-hashimoto-3** [comment]
アンケートの方は、改修完了・確認完了しています。
回覧板の方がおわりましたら、closeでお願いします。

**Comment by go-to** [comment]
回覧板も修正完了しました。
クローズします。
