### ISSUE TITLE
PHP5.4.16だとNC3.2.1がインストールができない。

### ISSUE THREAD

**Issue by prado1996** [NetCommons3/NetCommons3#1362]
NetCommonsHtmlHelper.phpのucwordsの引数が5.4.16だと1つしかとれないため、内部サーバーエラーが発生する。

NetCommonsHtmlHelper.php
$plugin = preg_replace('/_/', '', ucwords($match[1], '_'));

**Comment by prado1996** [comment]
原因はこれと同じですね。
https://github.com/NetCommons3/NetCommons/commit/187560fbe1872b2785f5b5188f75270e48b3ce20

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1363

ご連絡感謝です。
この修正のパッチ公開しました。
https://www.netcommons.org/blogs/blog_entries/view/6/6f1a4cb2122e1a16430d28da15343945?frame_id=13
