### ISSUE TITLE
MathJaxのファイル数減らしたい

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1367]
レンタルサーバーで、サーバ上でzipを解凍できない場合、nc3.zipを解凍後、ファイルをアップロードします。
ファイル数が多いと、その分時間がかかります。
nc3.zipは大体4万ファイル位ありますが、約2万ファイルはMathJaxです。

これを減らす事ができれば、全体ファイル数を削減でき、レンタルサーバーのアップロード時間も
軽減できるかなと思いました。

下記情報がありましたので、共有します。

http://docs.mathjax.org/en/latest/installation.html#obtaining-mathjax-via-bower

通常
```
bower install MathJax
```

For a slim copy without PNG fonts use
```
bower install components/MathJax
```
→ これでPNGフォントなしができそう。

1度試してみたいなぁ。
MathJaxが問題なく使えるなら対応したいなぁ。
とりあえずここまで。

**Comment by akagane99** [comment]
> bower install components/MathJax
> → これでPNGフォントなしができそう。

やってみました。PNGフォントもインストールされて、変化なかったです。うーん。

**Comment by ghost** [comment]
うーん💦

**Comment by akagane99** [comment]
バタバタすみません、できました！
bower.jsonを修正。NetCommons3,とウィジウィグリポジトリの修正する予定。
```
    "MathJax": "components/MathJax#>=2.6",
```
プルリクエストや、情報の整理などは、また後日。

**Comment by akagane99** [comment]
対応しました。
また、対応理由まとめました。

### 対応理由

* イメージフォント(pngのフォント画像)は、一部の古いブラウザーでTexを表示するために使われます。
* イメージフォントは約3万ファイルで、MathJaxは全体で38273ファイルあり、イメージフォントがファイル数の大半を占めています。
* このイメージフォントのファイル数が多すぎるため、NetCommons3のzip解凍時に時間がかかったり、解凍したレンタルサーバにアップロードする時間が掛かっています。
* MathJaxはWebフォントに対応していて、ブラウザのCSSで`@font-face`が使えるとWebフォントが使えます。
* `@font-face`が使えるブラウザは、IE6+、Chrome、Safari 3.1以上、Firefox 3.5以上、Opera 10以上です。
* NetCommons3はAnglarJSの利用で、既にIE9以上が必須のため、クライアント環境にも影響ないです。
  * https://github.com/NetCommons3/NetCommons3/wiki/システム要件#対応ブラウザ

このため、MathJaxのイメージフォントを含まないライブラリに変更します。

#### 情報源

http://docs.mathjax.org/en/latest/misc/faq.html#the-mathjax-font-folder-is-too-big-is-there-any-way-to-compress-it
> but in order to render math on some older browsers, you need image fonts, which take up most of the space.
> (Google翻訳) 一部の古いブラウザーで数式をレンダリングするには、ほとんどのスペースを占めるイメージフォントが必要です。
> (中略)
> users must either have the MathJax or STIX fonts on their computer or their browser must support the `@font-face` CSS directive. 
> This means IE6+, Chrome, Safari 3.1+, Firefox 3.5+, and Opera 10+, or other browsers based on their rendering engines. 
> (Google翻訳) ユーザは自分のコンピュータにMathJaxまたはSTIXフォントを持っているか、ブラウザが`@font-face` CSSディレクティブをサポートしている必要があります。
> これは、IE6+、Chrome、Safari 3.1以上、Firefox 3.5以上、Opera 10以上、またはその他のレンダリングエンジンに基づくブラウザを意味します。

http://docs.mathjax.org/en/latest/misc/faq.html#why-is-mathjax-using-image-fonts-instead-of-web-fonts
> Why is MathJax using image fonts instead of web fonts?
> Web fonts are supported by all popular browsers (IE, Firefox, Chrome, Safari, Opera…) and they are scalable, which means much better display and print quality. Clearly, you want to make sure this is working on your install of MathJax. 
> (Google翻訳)なぜMathJaxはWebフォントの代わりにイメージフォントを使用していますか？
> Webフォントは一般的なブラウザ（IE、Firefox、Chrome、Safari、Operaなど）でサポートされており、スケーラビリティがあり、表示品質や印刷品質が大幅に向上します。明らかに、MathJaxのインストール時にこれが動作していることを確認する必要があります。

### ファイル数：対応前

```
$ pwd
/var/www/app/app/webroot/components/MathJax

$ ls -1UR | wc -l
38273
```

### ファイル数：対応後

```
$ ls -1UR | wc -l
8307
```

### 動作確認

PC:windos10, 最新のFirefox, Chrome, IE, EageでTexが表示されることを確認しました。
スマートフォン: IPhone8(iOS12.1) SafariでTexが表示されることを確認しました。

### 備考

本家MathJaxでもファイル数議論されてました
https://github.com/mathjax/MathJax/issues/1214

bower.jsonの指定例
https://github.com/jupyter/notebook/pull/267/files

**Comment by akagane99** [comment]
この対応によりNetCommons3パッケージのファイル数は-3万ファイル程軽量化されます。

現在-ファイル数: 39,968
今後-ファイル数: 約9,968

### 現在

![image](https://user-images.githubusercontent.com/2756509/49336814-7e32b580-f64c-11e8-8608-92cb4f06b21d.png)
