### ISSUE TITLE
ルームの設定で承認不要になっているにも関わらず、カレンダーの予定で承認待ちになってしまう。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#1368]
１．ルームの設定は、下記のように、コンテンツの承認は不要となっています。

![image.png](https://zube.io/files/netcommons3/fb36711a8564e90fbbc925df158969f8-image.png)

２．会員権限が一般権限のユーザで、プライベートルームから、プライベートの予定として追加します。

![image.png](https://zube.io/files/netcommons3/d0e3f4155561f47a668238d1d3b5252c-image.png)

３．２で追加した予定を、公開範囲からルームの予定に変更します。そうすると、「承認待ち」の予定なってしまいます。
上の例では、「チームNetCommons」のルームに変更します。また、このルームのルーム内の役割は、「一般」です。

![image.png](https://zube.io/files/netcommons3/70c7b879d122f264e3f55848423daba8-image.png)

**Comment by s-nakajima** [comment]
追加情報です。

ルーム内の役割は、「一般」のルームの予定を編集しても、承認待ちとなりました。
その時の状況としては、パブリック(編集権限のない場所)で予定を編集しました。
その際に、公開範囲は、変更できない旨のメッセージが表示されていました。

**Comment by RikaFujiwara** [comment]
すみません　1つ確認させてください。
このときのカレンダーの設定画面で管理している権限設定画面では、これらのルームの承認設定はどうなっているでしょうか？
ルームとしては不要としてるが、カレンダーの権限設定で「必要」となっていませんでしたか？

**Comment by RikaFujiwara** [comment]
追加情報です。
もしもカレンダーの権限設定が「承認が必要」になっていたら、カレンダの動作としては正しいのですが、
確認したところ権限設定画面を初期表示するとき、ルームの設定がどうであれ、デフォルト「承認が必要」チェックボックスがONになっておりました。
どっちかっていうと、設定画面の問題の気がしてます。

ルームの設定を見ずにデフォルト「承認が必要」チェックボックスをON表示してるのが原因なのではと。
