### ISSUE TITLE
グループ選択後の対象ユーザー取得処理はGETでは？

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#137]
ユーザーの個別選択機能で、既存グループを選択後対象のユーザーを取得する処理がPOSTになっています。
指定したグループのユーザーリストを取得という意味で、GETの方が良いと思います。

tokenもいらなくなります。
グループコントローラーのselectアクションでグループ選択画面表示とユーザー取得を行っていますが、
ユーザー取得はGroupsAppController::usersアクションと分けるイメージです。

**Comment by go-to** [comment]
ユーザーを取得する処理をアクション化して、GETで処理するように修正しました。
https://github.com/NetCommons3/Groups/commit/d46deee44ea3a8ccc160ae7fa5e61c4bb2a5ab4f
