### ISSUE TITLE
個別ユーザーデータモデルについて

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#138]
回覧板等で、ユーザーを個別に選択して登録する機能があります。
その際に渡されるユーザーデータは以下の様になっています。

Ex.) 回覧板の場合

```
data[CircularNoticeTargetUser][user_id][ユーザーID値] = ユーザーID値
data[CircularNoticeTargetUser][user_id][ユーザーID値] = ユーザーID値
data[CircularNoticeTargetUser][user_id][ユーザーID値] = ユーザーID値
```

cakeのモデルで考えると以下のような気がします。
(CircularNoticeContent hasMany CircularNoticeTargetUserです)

```
data[CircularNoticeTargetUser][0][user_id] = ユーザーID値
data[CircularNoticeTargetUser][1][user_id] = ユーザーID値
data[CircularNoticeTargetUser][2][user_id] = ユーザーID値
```

ユーザーID値をkeyで保持しないと不都合でもあるのでしょうか？

**Comment by go-to** [comment]
特に不都合はないので、Cakeのモデル的な形に沿うように修正しました。
https://github.com/NetCommons3/Groups/commit/4d04a0667f9bd6718ed40f46ce85f3d0b8266dfa
