### ISSUE TITLE
登録フォームで登録通知メールが送信されない

### ISSUE THREAD

**Issue by ka2mz** [NetCommons3/NetCommons3#1380]
環境
OS: macOS Mojava 10.14.1
Apache:  2.4.37
PHP: 7.1.24
NetCommons 3.2.1.1
※ApacheとPHPは Homebrew でインストールしたもの

ユーザ管理でユーザを登録した時はメールが正しく送信されるが，登録フォームで登録通知メールが送信されない。エラーもなく，どこを調べれば良いか分からない状態です。

テストでCentOS7で試したところ，こちらは正常に動作して登録通知メールが送信されました。
macOSの環境固有かもしれませんが，よろしくお願いします。

**Comment by ghost** [comment]
管理画面で「システム管理」→「メール設定」で、
「メール送信方法」の項はどのような設定になっていらっしゃいますでしょうか。

p.s. 私、Homebrewは今は使っておりませんが、macOS High Sierraユーザです。

**Comment by ka2mz** [comment]
メール送信方法は「SMTP」にしています。

**Comment by ghost** [comment]
パラメータも教えてください。
また、「メールを送れるかテスト送信する」にチェックを入れ、送信テストをされた結果はいかがでしたでしょうか。

**Comment by ka2mz** [comment]
パラメータは以下のようになっています。送信テストは問題なく送信できますし，ユーザを追加した際のメールも送信されます。登録フォームの登録通知だけが送信されない状況です。
![2018-11-26 095227](https://user-images.githubusercontent.com/4596648/48987293-0c94cc00-f161-11e8-9c0b-3458b1091af0.jpg)

**Comment by ghost** [comment]
なるほど、SMTP設定には問題がないようですね。
そうすると、登録フォームプラグインの設定を確認する必要がありそうです。

下のスクリーンショット2点は、実際に私のところで使っている登録フォームです。赤枠内あたりを確認してみてもらえますか。（もちろん、ルーム管理者などにe-mailアドレスが設定されている必要はあります）

![registration1](https://user-images.githubusercontent.com/7931689/49004420-910a3d80-f1a7-11e8-99dc-9d57403ebb9f.png)

![registration2](https://user-images.githubusercontent.com/7931689/49004428-96678800-f1a7-11e8-85c8-6f38e2071794.png)

**Comment by ghost** [comment]
ひとつ思い出しましたが、OP25B (Outbound Port 25 Blocking) の影響はありませんでしょうか。
OP25Bで検索するか、お使いのメールサーバの提供社のサポートサイトなどを参考にされるとよろしいかと思います。
（ユーザ登録時にメールが送信されているということは OP25Bは関係ないのかもしれませんが）

あと、「テストでCentOS 7では、登録通知メールが送信された」とのことですが、このCentOS 7のサーバは自宅／自社等の内部にあるものなのか、レンタルサーバ等の外部にあるものなのかどちらなのでしょう?

**Comment by ghost** [comment]
［便乗質問］（ka2mzさんへではなく、閲覧されている皆さんへ）

登録フォームプラグインで、「セッティングモードON」→「メール設定」にある、「投稿メール」って何でしょうか? 「登録メール」と何が違うのでしょう。（オンラインマニュアルには記載が見当たりませんでした）

「投稿メール」の本文欄のようなメールが届いたという記憶はありません・・・

**Comment by ka2mz** [comment]
登録フォームの設定を確認しましたが，提示して頂いたものと同じ設定になっています。
OP25Bの影響はないです。
macOS, CentOS7 の両方とも組織内に設置しています。
登録フォームからの通知ですが，SMTPサーバのログを見ても CentOS7 からは正常に送信されてきていますが，macOSの方は SMTP のログがないので，そもそもmacOSから送信されていないようなのです。
テストメールはmacOSからも正常なので，何が悪いのか手掛かりが無くて困っています。

**Comment by ghost** [comment]
確認ですが、ルーム管理者等のメールを受け取るべき人には、会員の設定でメールアドレスを登録されてますよね?　（だんだん弱気モード...）

**Comment by ka2mz** [comment]
はい，会員設定でメールアドレスの設定をしています。

**Comment by ghost** [comment]
う〜ん、そうするとmacOS回りのような気がしてきました。
「システム環境設定」→「セキュリティとプライバシー」→「ファイアウォール」あたりはいかがでしょうか（Mojaveだとちょっと違うのかも）。
あと、Homebrewでファイアウォール系のものが入っちゃってたりしないでしょうか。

![firewall](https://user-images.githubusercontent.com/7931689/49008303-d2531b00-f1b0-11e8-95e7-576bb7d94d4c.png)

**Comment by ghost** [comment]
ウイルス対策ソフトはどうでしょうか。１度、停止させて試されては?
かつて、NetCommons3開発環境を構築時に、Kasperskyに何かを止められてて時間を浪費したことを思い出しました。

**Comment by ka2mz** [comment]
Firewallやウイルス対策ソフトは無関係のようです。
メールの設定を「SMTP」から「PHP mail()」に変更してテストをしてみましたが，
メール設定の中からの送信テストは正常に動作しますが，登録フォームの通知メールは送信されません。
macOSのターミナルで smtpd, smtp のログを表示させながらテストしましたが，送信テストではログが出力され送信されるのですが，登録フォームの通知メールの場合ログが一切出ません。PHP mail() のメール送信（/usr/sbin/sendmail -i -t）が呼び出されていないようです。
登録フォームで「登録通知メール」を有効にしていても，メールを送信する処理が呼び出されていないように思います。 

HomebrewでインストールしたPHP7.1の問題かもしれません。何かチェックできる方法を教えて頂けると助かります。
よろしくお願い致します。

**Comment by ghost** [comment]
すみませんが私にはもうお手上げです。MTAサーバの構築・運用から離れて4年もたち、記憶の彼方です・・・
Homebrewでpostfix入れてるわけでなく、macOS標準のを使われてるということだと、その構成でいいのかなという疑問はあります。

**Comment by akagane99** [comment]
デバッグ出力レベルを2にして、デバッグログを確認したら、メール送信できないものの何かヒントが出てるかもしれません。
参考まで。

* （画面上部）管理＞システム管理＞開発者向け（タブ）
  * デバッグ出力レベル： 2: 1だけでなく、完全なデバッグメッセージやSQLも出力します。
* 登録フォームに投稿します
* デバッグログを確認。
  * ドキュメントルート/app/tmp/logs/debug.log

**Comment by RyujiAMANO** [comment]
ひとつおもいあたる点が。

> ※ApacheとPHPは Homebrew でインストールしたもの

macOSだと標準でphpがはいっていて、コマンドラインでの実行だとapacheのphpでなく標準のPHPがよばれることがあります。

さっきこのことを思いだしてちょっとだけコードみたんですが、ユーザ登録のメール送信だとApache→PHPでメール送信されるのに対して、通知系はいったんMySQLのメール送信キューテーブルに保存され、その後でバッチで送信されるようになってます。(cron等でリマインドメール送信を送れるようにこういう構造になってます）

なので登録フォームからだとapache->php-> execでコマンドラインphp実行->コマンドラインphpでメール送信
ってなります。

このコマンドラインで実行してるときにうまく動いてないのだと思います。たぶんapacheとは違うphpがうごいてて、バージョンの問題かなんからの拡張不足なのか何かあるんだろうと思います。

**Comment by ka2mz** [comment]
> なので登録フォームからだとapache->php-> execでコマンドラインphp実行->コマンドラインphpでメール送信

この execでコマンドラインphp実行->コマンドラインphpでメール送信という部分は何処のソースファイルを見ると分かりますか？

**Comment by RyujiAMANO** [comment]
https://github.com/NetCommons3/Mails/blob/master/Utility/MailSend.php#L25
MailSend::send()
でバッチたたいてます。
これを呼び出してるのはMailsプラグインの
https://github.com/NetCommons3/Mails/blob/master/Model/Behavior/MailQueueBehavior.php
です。
登録フォームはこのビヘイビア経由でメール送信する仕組みになってます。

**Comment by ryu818** [comment]
コマンドラインで

$ (適宜パスを指定)/app/Console/cake Mails.mailSend send

をnc3が動いているユーザ(apache等）で実行してみればなにかわかるかもしれません。

そもそもapp/tmp/logs/下にerror.log,あるいはdebug.log等があり、それに何かしらの
エラーが記載されている可能性もあります。

**Comment by ka2mz** [comment]
httpd が ユーザ _www で動作しているので，ターミナル内で以下を実行しました。
$ sudo -u _www app/Console/cake Mails.mailSend send
結果，溜まっていた通知メールが一度に送信されてきました。
app/Console/cake Mails.mailSend send の実行がうまくできていないところまでは，分かりました。

**Comment by ka2mz** [comment]
debug.log に以下の出力がありました。
--
2018-11-27 12:29:05 Debug: [IsMailSendBehavior::isMailSend] /Library/WebServer/Documents/nc3/app/Plugin/Mails/Model/Behavior/IsMailSendBehavior.php (line 80)
2018-11-27 12:29:49 Notice: Notice (8): Undefined index: RegistrationAnswerSummary in [/Library/WebServer/Documents/nc3/app/Plugin/Registrations/Model/RegistrationAnswerSummary.php, line 122]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
RegistrationAnswerSummary::_getNewSerialNumber() - APP/Plugin/Registrations/Model/RegistrationAnswerSummary.php, line 122
RegistrationAnswerSummary::saveAnswerStatus() - APP/Plugin/Registrations/Model/RegistrationAnswerSummary.php, line 142
RegistrationAnswersController::confirm() - APP/Plugin/Registrations/Controller/RegistrationAnswersController.php, line 415
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 120

**Comment by RyujiAMANO** [comment]
かなり前のIssueですが、
https://qiita.com/RyujiAMANO/items/7842c1ead69d2002bcb6#202007271453-追記
と同じ状況かも。

**Comment by ka2mz** [comment]
情報ありがとうございます。

> これでOKかと思ったらこれでも不足で app/Plugin/Mails/Utility/MailSend.php の書換も必要でした。
> 
> 44行目 \MailSend::execInBackground() 内でコマンドを実行しているのですが、どいうわけか nohup を使うとcakeコマンドの呼び出しに失敗します。
> 
> そこで nohup 使わないように変更。

こちらの変更で，メールが飛ぶようになりました。
しかし，問合せした人のメールアドレスに「登録内容確認画面URL」という管理用のURLがメール末尾に付いたものと，付いていないもの２通届いてしまうようになりました。

![コメント 2020-07-30 162124](https://user-images.githubusercontent.com/4596648/88893080-c6223980-d280-11ea-8d5e-3f80f1f3c801.png)
![コメント 2020-07-30 162354](https://user-images.githubusercontent.com/4596648/88893366-30d37500-d281-11ea-9ed6-c309e4bafc73.png)
![コメント 2020-07-30 162428](https://user-images.githubusercontent.com/4596648/88893369-33ce6580-d281-11ea-8fa3-718432193a5a.png)

**Comment by RyujiAMANO** [comment]
> しかし，問合せした人のメールアドレスに「登録内容確認画面URL」という管理用のURLがメール末尾に付いたものと，付いていないもの２通届いてしまうようになりました。

URLのはいってるのはルーム管理者や編集長など、登録の通知をうけるユーザさんのメールアドレスあてに送られています。
URLなしのは、本人にも送る設定にしていたときに、フォームに入力されたメールアドレスあてに送られます。
管理者さんのメールアドレスとは違うメールアドレスでフォーム送信してみると違いがわかりやすいかと思います。

**Comment by ka2mz** [comment]
確認したところ，「ルーム管理者」「編集長」に設定されているアカウントのメールアドレスに URL 付きのものが届いていました。
別のメールアドレスでフォームを登録したところ，問題なく動作しました。
ありがとうございました。
無事解決したので Clonse します。
