### ISSUE TITLE
pdfを開く時はブラウザ内で開いて欲しい

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1384]
NC2の時はPDFをダウンロードすると、ブラウザ内で表示されました。
NC3ではダウンロードされます。

NC2と同じように、NC3でもブラウザ内で表示する方法がいいかと思います。

とりあえず要望まで。

**Comment by ghost** [comment]
うーん、個人的にはブラウザでの閲覧は使い勝手が悪いので、ダウンロードのままであって欲しいですけども・・・

**Comment by hmlyn523** [comment]
いちいちダウンロードするのは如何なものかと。ダウンロードしたければ、右クリックでダウンロードすればよいかと。複数のPDFを確認のためにtempやworkなどのフォルダにダウンロードして、確認したら、消すという作業が面倒です。

**Comment by ghost** [comment]
好みやPDFをどういう風に使っているかで、個人差があるということですね。

**Comment by akagane99** [comment]
@tatsuya-sagara @ToshiAkaz ご意見感謝です。ご意見ふまえて、モクモク会で相談してみます。

**Comment by akagane99** [comment]
参考に、修正前後の動作確認しました。

### 動作確認結果
* PC
  * 修正前：PDFダウンロードになる
  * 修正後：ブラウザ内表示になる。
* スマートフォン
  * iphone(7, safari)
    * 修正前、後：変化なし。別タブでPDF表示
  * android(8.1.0, chrome)
    * 修正前、後：変化なし。ダウンロード＆PDF表示（ドライブPDFビューワーで表示された）

とりあえずここまで。

**Comment by akagane99** [comment]
もくもく会でも検討しましたが、意見が半々でしたので、残念ながら対応見送ります。
ご意見いただき、ありがとうございました。
クローズします。

**Comment by hmlyn523** [comment]
ブラウザ内で開けるようにしても、ダウンロードするすべはあるけど、今のままだとダウンロードするしか選択肢がない。NetCommonsは基本的に職場で使うことが主な使い方になると思う。コンプライアンスやセキュリティが厳しくなっていく世の中で、今の仕様はいただけない。選択肢は増やすべき。
もう一度いいますが、ブラウザ内で開けるように変更しても、ただCtrlキーを押しながらクリックするだけでダウンロードできると思う。選択肢は広げましょう。痒いとこに手かが届かないシステムからの脱却を切に望みます。

**Comment by hmlyn523** [comment]
無理なのは承知ですが、どうしてもダメであれば修正箇所だけでも提示してくれたら自分で運営しているシステムに変更加えたいです。
サイボウズは、ブラウザで直接開けて便利すぎる。もちろんダウンロードもできる。ダウンロードもね。

**Comment by akagane99** [comment]
@tatsuya-sagara 
ブラウザで直接開ける修正はこちらになります。
ご参考まで。
https://github.com/NetCommons3/Files/pull/113/files

（このissueに表示されてる「fix: pdfはブラウザ内でひらく #113」ってリンクを開いて「Files changed (タブ)」から見れるんです。）

**Comment by hmlyn523** [comment]
@akagane99 
大変助かりました！ありがとうございます！！！
