### ISSUE TITLE
グループ選択画面における参加ユーザーモデルの階層は変えない方が良いのでは？

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#139]
グループ一覧取得処理で参加ユーザーを取得しています。
表示する処理で、アバター情報を取得するため、階層を変更しています。
GroupUserListHelper ：：convertGroupUserListForDisplay

モデルの階層が変わっているので混乱します。
見直しましょう。

**Comment by go-to** [comment]
グループ一覧取得処理及び影響箇所を修正しました。
https://github.com/NetCommons3/Groups/commit/18daaa3c4aeadfba6dc954f902c80bc65c578568
