### ISSUE TITLE
ページ設定、追加したパブリックルームをトップページとして一番上に移動しても、トップページとして表示されない

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1394]
NC3.2.1.1で確認しました。
追加したパブリックルームは、ページ設定でトップページまで移動できます。

ページを一番上まで移動させると、そのページがslugがないトップページとして表示されます。
しかし追加したパブリックルームを、トップページとして一番上まで移動しても、トップページと表示されず、元々のパブリックルームの一番上のページが表示されます。

### 例

https://mutaguchi.netcommons3.jp/
→ トップページとして「汎用DBページ」が表示されてる。「追加したパブリックルーム」ページが表示されない。
![image](https://user-images.githubusercontent.com/2756509/49726012-5d074000-fcb0-11e8-889a-6eefca58d7ca.png)

汎用DBページ
https://mutaguchi.netcommons3.jp/page_20180723101050
![image](https://user-images.githubusercontent.com/2756509/49726037-6ee8e300-fcb0-11e8-9cc8-88b5df7fb349.png)

追加したパブリックルーム
https://mutaguchi.netcommons3.jp/0e5fb07309ac3483291d8cae7dbfcd7d
![image](https://user-images.githubusercontent.com/2756509/49726073-80ca8600-fcb0-11e8-8e2c-6d76179c2860.png)

NC2では、追加したパブリックルームは、トップページまで移動して、トップページと表示されていました。

NC2
https://nc2default.opensource-workshop.jp/
![image](https://user-images.githubusercontent.com/2756509/49726120-9b046400-fcb0-11e8-9e3b-57c50de8c5b8.png)

とりあえず報告まで。

**Comment by horitada** [comment]
以下の処理をの条件をPage.room_id→Page.root_idにしたら正しそうですが、
意図してパブリックルームのみにしてるんですかね

https://github.com/NetCommons3/NetCommons/blob/4ab09327c8316970fbd7b1ff772dc0b763054027/Utility/CurrentPage.php#L271

**Comment by akagane99** [comment]
@horitada 多分考慮もれかと。
パブリックルームのみにしたかったけど、パブリックルームの他ルームが漏れちゃっただけの気がします。
明日のもくもく会で確認とっときます。

**Comment by akagane99** [comment]
> 以下の処理をの条件をPage.room_id→Page.root_idにしたら正しそうですが、

あってそう。

(A)
https://github.com/NetCommons3/NetCommons/blob/4ab09327c8316970fbd7b1ff772dc0b763054027/Utility/CurrentPage.php#L271
```php
				'Page.room_id' => Space::getRoomIdRoot(Space::PUBLIC_SPACE_ID),
```
の`Space::getRoomIdRoot(Space::PUBLIC_SPACE_ID)`は何をしてるのか調べました。

(B)
https://github.com/NetCommons3/Rooms/blob/master/Model/Space.php#L204
```php
/**
 * SpaceのルームIDを取得
 *
 * @param int $spaceId スペースID
 * @param string $spaceModel モデル名(Migrationで使用)
 * @param array $options ClassRegistryオプション
 * @return int
 */
	public static function getRoomIdRoot($spaceId, $spaceModel = 'Space', $options = []) {
		$Space = self::getInstance($spaceModel, $options);
		if ($spaceModel === 'Space') {
			if (! isset(self::$spaceIds['Space'])) {
				$spaces = $Space->find('list', array(
					'recursive' => -1,
					'fields' => array('id', 'room_id_root'),
				));
				if ($spaces) {
					self::$spaceIds['Space'] = $spaces;
				}
			}
			$spaceIds = [];
			if (isset(self::$spaceIds['Space'])) {
				$spaceIds = self::$spaceIds['Space'];
			}
		} else {
```

phpdocでは、ルームID取得って書いてるけど、Spaceテーブルの`room_id_root`取ってました。
Page.root_idは、そのルームの祖先にあたるルームIDっぽい。
なので、Page.room_id→Page.root_idの修正であってそう。

(A)' = 修正後
```php
				'Page.root_id' => Space::getRoomIdRoot(Space::PUBLIC_SPACE_ID),
```

とりあえずここまで。

**Comment by akagane99** [comment]
(A)
```php
				'Page.room_id' => Space::getRoomIdRoot(Space::PUBLIC_SPACE_ID),
```
上記比較は、他プラグインでも使ってたため、他プラグインの調査も必要そう。
メニューとか。

とりあえずここまで。

**Comment by akagane99** [comment]
カレンダーでも `Space::getRoomIdRoot(Space::PUBLIC_SPACE_ID)`の比較を行っていますが、大丈夫でした。

NC2 - パブリック別ルームあり
![image](https://user-images.githubusercontent.com/2756509/49914338-2e69af00-fed4-11e8-9c82-810183d85b6c.png)

NC3 - パブリック別ルームあり
![image](https://user-images.githubusercontent.com/2756509/49914485-c8c9f280-fed4-11e8-843b-725dc11daf14.png)

NC3 ソース
https://github.com/NetCommons3/Calendars/blob/master/View/Helper/CalendarLegendHelper.php#L232
```php
		} elseif ($id == Space::getRoomIdRoot(Space::PUBLIC_SPACE_ID)) {
```

とりあえずここまで。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1394#issuecomment-446825720

もくもく会で確認して内容違ったので、訂正します。
どうやら`Page.root_id`は、今後項目削除予定みたい。
なので、別の方法で修正します。

別の修正方法（roomとpageを結合して、スペースIDで判別）
https://github.com/NetCommons3/NetCommons/pull/509/files

また、他プラグインで`Space::getRoomIdRoot(Space::PUBLIC_SPACE_ID`の比較は、不具合発見次第、随時修正する方向にしようと思ってます。
