### ISSUE TITLE
施設予約、カテゴリー別で日表示のとき、表示が崩れる

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1400]
NC 3.1.10で確認。（NC 3.2.0以降は未確認）
ブラウザ Firefox (for macOS)で発生。（Chrome for macOSでは発生しない）

症状は以下のスクリーンショットのとおりです。
![2018-12-26 12 54 33](https://user-images.githubusercontent.com/7931689/50431380-d12b2000-090d-11e9-9107-28044bed2d54.png)

**Comment by akagane99** [comment]
nc3.2.1で修正されたようですよ。
https://github.com/NetCommons3/NetCommons3/issues/1292

**Comment by ghost** [comment]
おぉ既出でしたか。修正ありがとうございました。
