### ISSUE TITLE
移行ツール　キャビネットのフォルダサイズが移行されていない

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#1408]
ファイル１つ１つのサイズは移行していますが、その上のフォルダの合計Sizeが移行されていません。
下のファイルの合計値をセットするべきです。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/987

**Comment by RikaFujiwara** [comment]
2021/06　時点での移行プログラム実行したところ、この問題は解決しているようです
移行後のキャビネットでフォルダサイズが表示されました

**Comment by RikaFujiwara** [comment]
#987 Closeに伴い、こちらもCloseします
