### ISSUE TITLE
左右カラムに配置したプラグインから中央カラムへの表示出力をする場合に、表示プラグインが全画面を乗っ取ってしまう場合がある

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1420]
どうも左右カラムに配置するBoxの所属ページが、現在表示中ページと違う場合にこの現象が発生する模様です

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1394
上記修正の影響疑いあり。

**Comment by RikaFujiwara** [comment]
> どうも左右カラムに配置するBoxの所属ページが、現在表示中ページと違う場合にこの現象が発生する模様です

Ver. 3.3.1 では「現在表示中ページ」と違うBoxの左右カラムは現れなくなっています。セッティングモードでも。
再現できないのでCloseにします
