### ISSUE TITLE
ファイル、ダウンロード時ファイル名が日本語の場合、ファイル名がURLエンコードされたままのファイル名になる

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1433]
NC3.2.1.1で確認しました。

### 現象
新しいテキスト ドキュメント.txtをウィジウィグで添付して、ダウンロードすると、ファイル名が下記になりました。
%E6%96%B0%E3%81%97%E3%81%84%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%20%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%.txt

### 対応案
ソースを下記に直せば、日本語ファイル名でダウンロードできました。

https://github.com/NetCommons3/Files/blob/3b2c161537289a6f86897db0b431b643998a03bd/Controller/Component/DownloadComponent.php#L186
```php
			$content .= 'filename*=UTF-8\'\'' . rawurlencode($downloadFileName);
↓
			$content .= 'filename*=UTF-8\'\'' . $downloadFileName;
```

### 修正後の動作確認PCは以下です。
・windows10+Chrome最新 o
・windows10+Firefox最新 o
・windows10+IE11 o
・windows10+Eage o
・windows7+Chrome最新 o
・windows7+Firefox最新 o
・windows7+IE11 o

### 原因は不明
ネットを探しても、日本語ファイル名の文字化け対応は`'filename*=UTF-8\'\'' . rawurlencode($downloadFileName);` とrawurlencodeを使って対応する事が書かれていて、
今までは大丈夫だったと記憶してます。
そのため、原因はわかってないです。

### 関連issue
https://github.com/NetCommons3/NetCommons3/issues/1232

**Comment by akagane99** [comment]
### 修正後の動作確認
・iphone7+iOS12.1.2最新+safari o
・ipad+iOS11.4.1最新+safari o
・Xperia+android8.0.0+chrome o 

動作テストファイル名のファイル名が文字化けない＋中身が見えることを確認。

### 動作テストファイル名

H30研究発表会申込みファイル(団体名).xlsx
平成28年度出席停止意見及び登校許可書.docx
新しいテキスト ドキュメント.txt

**Comment by s-nakajima** [comment]
デグレしましたので、https://github.com/NetCommons3/Files/pull/114 の修正は取り消しました。
そもそも、本ISSUEの発生をもう少し調査すべきです。
そのため、rawurlencodeを付けるようにします。

**Comment by s-nakajima** [comment]
本件、そもそも発生したことが疑わしいく、デグレを元の戻したことで、今のところ発生していないため、いったんクローズします。
