### ISSUE TITLE
会員管理-エクスポート：[space_id]基本条件が会員情報一覧表示の時と違う

### ISSUE THREAD

**Issue by osws-makino** [NetCommons3/NetCommons3#1437]
会員情報-エクスポート処理にて、基本条件「space_id」が会員情報一覧表示のものと異なっている。

【会員情報一覧取得】
array('space_id !=' => Space::PRIVATE_SPACE_ID),

【会員情報エクスポート】
'space_id' => Space::PRIVATE_SPACE_ID,

なので、エクスポート処理の方の条件を、一覧表示の方に寄せた方が良いのではないかと思われる。

**Comment by akagane99** [comment]
【会員情報一覧取得】
~~https://github.com/NetCommons3/Users/blob/b4c35d69ab8a4ae711eea09641764b3f220e8300/Model/UserSearch.php#L145-L147~~
https://github.com/NetCommons3/UserManager/blob/c5bae1b8f36f81d4b25ed93cb75b3c373d29da4e/Controller/UserManagerController.php#L90

【会員情報エクスポート】
https://github.com/NetCommons3/UserManager/blob/c5bae1b8f36f81d4b25ed93cb75b3c373d29da4e/Controller/UserManagerController.php#L329

UserManager検索結果。検索条件「Space::PRIVATE_SPACE_ID」
https://github.com/NetCommons3/UserManager/search?q=Space%3A%3APRIVATE_SPACE_ID&unscoped_q=Space%3A%3APRIVATE_SPACE_ID
