### ISSUE TITLE
プラグイン管理、NC3.2.2にファイル上書きアップデートすると画面右上NetCommons3: 3.2.1    (3.2.1 → 3.2.2)残る？

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1443]
ファイル上書きでNC3.2.2にアップデートすると、プラグイン管理の画面右上に
NetCommons3: 3.2.1    (3.2.1 → 3.2.2)残る場合があるようです。

![image](https://user-images.githubusercontent.com/2756509/51822984-48930b80-2321-11e9-83ef-db97834c31f4.png)

とりあえず報告まで。

#### 関連してそうなプルリクエスト
https://github.com/NetCommons3/NetCommons/pull/530

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1551
こちらと同じなためクローズ
