### ISSUE TITLE
ミカエルシリーズで、画面の小さいスマホで見ると、レスポンシブがうまく動作しない

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1445]
#nc-system-footer を「コンテンツ量が少ないときはブラウザ下端に張り付ける」ようにした時から、問題が発生していました。
近日中に、（色以外は）Defaultテーマに戻す形で、新たなpull requestを送る予定です。

その前に、自分とこにforkしたNetCommonsをどうしたら最新にできるかが不明でして、スケジュール詰め詰め状態もあり、少し日数をください。

**Comment by akagane99** [comment]
> その前に、自分とこにforkしたNetCommonsをどうしたら最新にできるかが不明でして

こんな記事がネットにありました。参考まで。

GitHubでFork/cloneしたリポジトリを本家リポジトリに追従する - Qiita
https://qiita.com/xtetsuji/items/555a1ef19ed21ee42873

**Comment by ghost** [comment]
ありがとうございます。試してみます！

**Comment by ghost** [comment]
修正し pull requestしておきました。
ついでに、新着プラグインと動画プラグインでボタンの文字が見えづらかったのを修正しました（Michael the 4th と 5th）。

**Comment by akagane99** [comment]
ありがとうございます😊
マージしました。
