### ISSUE TITLE
ToDoとブログでカテゴリが追加できない。

### ISSUE THREAD

**Issue by hmlyn523** [NetCommons3/NetCommons3#1449]
最新バージョン(3.2.2)にて、タイトルにあるとおり、カテゴリが追加できません。

3.2.0 で施設予約のカテゴリーのバグ #1343
と同じような現象となっています。

**Comment by attikottidetti** [comment]
私も3.2.2で確認しましたので、3.2.1をインストールし直して作ってみましたが、同じようにカテゴリが空白になってしまいます。3.2.2だけで生じるわけではないのかもしれません。

**Comment by attikottidetti** [comment]
nc2にして運用することを考えた方が良いでしょうか。

**Comment by akagane99** [comment]
NC3.2.2でカテゴリのバグ修正されたはずなんですが、なんだろう？
以下の環境でカテゴリ登録できました。

### 環境
* NC3.2.2新規インストール
* xampp
* windows10
* chrome

### 画面
![image](https://user-images.githubusercontent.com/2756509/52389178-83d9cb00-2ad5-11e9-8ab3-702945c5e191.png)
![image](https://user-images.githubusercontent.com/2756509/52389190-92c07d80-2ad5-11e9-86f7-e5e31fbdd007.png)
![image](https://user-images.githubusercontent.com/2756509/52389195-9ce27c00-2ad5-11e9-991e-3eb337ad630f.png)

**Comment by attikottidetti** [comment]
私のところの環境です。
* NC3.2.2新規インストール
* NC3.2.1.1新規インストール
* xserver
* windows7 home edition
* firefoxとchromで再確認
MySQL5.7
PHP7.2.6
winscp

最新バージョンの３．２．２でグループウェアを作ったところ、ＴｏＤｏのカテゴリー登録し、決定を押すとあたかも登録されたようになりますが、再度、編集で開くと空白のままになります。こちらの画面は登録している状況のようですが、決定後、再度編集で開いても登録されたままでしょうか？登録された数だけ、空白のカテゴリーが表示されないでしょうか？
私は、その後、３．２．１．１のバージョンを新規インストールし直し、チャチャッと同じものを作りましたが、同じ状況です。

**Comment by hmlyn523** [comment]
下記環境で動作させていますが、カテゴリが追加できておりません。（追加したカテゴリが空白）

・NC3.2.2（NC3.2.1からのバージョンアップ）
・さくらインターネット
・DB：MySQL 5.7
・PHP：7.2.14

**Comment by RikaFujiwara** [comment]
私も確認しました。
DBをチェックしてみたら、カテゴリとして登録したデータは存在していたのですが、
（つまり「登録」はできてる）
categories_languagesテーブルに入っている言語情報にlanguage_idが設定されず「０」の値になっていました。
このlanguage_idが０のために、画面表示したときに正しいデータが引っ張ってこれず、空白のカテゴリが表示されることになっているみたいです。
カテゴリのlanguage_idってどこに設定されているんだろう

**Comment by RikaFujiwara** [comment]
たぶん、原因判明しました。
これが発生するのは、システム管理で「１言語でサイト構築」にしていて、コミュニティ空間やプライベート空間にカテゴリを利用するプラグインを配置した時です。
M17Behaviorが、多言語利用空間ならばlanguage_idを自動的に設定してくれるのですが、
そうでない空間だったらlanguage_idの設定を行わないようになっていました。

ただ、正しい修正方法がわからないです。
空間が多言語設定かどうかなんてチェックをやめちゃえばいいのかしら？
それともCurrentの情報設定時に、「多言語利用空間なのか」の判定フラグの設定を変えたほうがいいのかしら？

**Comment by attikottidetti** [comment]
現在、手入力でタイトルにカテゴリーを書いてしのいでいます。よろしくお願いします。

**Comment by RikaFujiwara** [comment]
「空間が多言語設定か」という判定はm17nには不要と判断して、ロジックを変更してみました
空間が多言語なのかどうか、という観点で見ちゃうとプラグインの機能自体がlanguage_idを必要としているものは多言語空間じゃない空間では配置できなくなってしまうのでは？という考え方です
Pull-Req投げます。

**Comment by attikottidetti** [comment]
お世話になります。ラベルに「２０作業中」と表示されています。今は誤りを直す作業をしている最中ですという意味で良いのですよね?作業が終わられたら、ダウンロードのところから、修正されたものを得ることができるという理解で良いのでしょうか?

**Comment by RikaFujiwara** [comment]
ああ、失礼しました。
タグ付けをミスっていました。
こちらで対応済み
https://github.com/NetCommons3/M17n/commit/e072de4ae24ab5fec0f4ad31d6820ab657b7c537
M17nリポジトリは修正されていますけど、NC3の新バージョンにはまだまとめられていないと思います。
お急ぎでしたら、M17nを取り込まれるとよいと思います。

**Comment by SatohDaisuke** [comment]
同じ現象が、リンクリストでも発生しておりましたので、情報共有させていただきます。

**Comment by akagane99** [comment]
リンクリストも当修正で直りました。
https://github.com/NetCommons3/M17n/pull/62/files
