### ISSUE TITLE
リダイレクト先がログイン画面になる（URLのpathとして存在しない物を指定した時）

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1450]
情報セキュリティの向上のため「ログイン」を非表示としています。具体的には、#nc-system-headerをわざと非表示にしています。

ところが、ブラウザのURL欄に（ホスト名に続けて）、存在しないpathを指定するだけで、ログイン画面にリダイレクトされてしまいます。これはセキュリティ上、問題ではないでしょうか。

NC2では存在しないpathを指定した場合、トップページにリダイレクトされるようになっておりました。

#699 の最後の段落の見解は理解できないのですが。
ログイン画面に遷移させず、トップページに遷移する仕様に戻していただけますでしょうか。

**Comment by ryu818** [comment]
ログインを非表示にするのは自由ですが、その多くを学生にも、保護者にもログインを許可する多くのサイトではログイン画面に遷移したほうが親切設計です。
デフォルト、ログインリンクを表示しているのですから、なんらセキュリティ的に問題ありません。
実際、確認したわけではないですがAmazon、楽天、facebook等をみてください。すべてログイン画面に遷移してるのではないでしょうか。

**Comment by ghost** [comment]
見解が異なるようですが、もう少々、実務を考えていただけないでしょうか（NetCommonsが学校専用CMS/グループウェアという公式見解はなかったかと思います）。
サービスやシステムにごとに状況も異なります。大手企業のサービスにおける防御レベルと、NetCommons導入サイトで同じ防御レベルを取れるとは考えにくいです。Wordpressでは、デフォルトの /wp-admin は変更して使うことが推奨されております。

**Comment by ryu818** [comment]
「Wordpressでは、デフォルトの /wp-admin は変更して使うことが推奨」といっしょにしないでください。
WordpressではCMSとしての利用しか想定していないこととともに、ログインへのURLがNC3では固定なので、根本的に意味が異なります。

１．ログインを隠すというのは、まず、機械によるフォースアタックによる防御を想定していますか？
もし、そうであるならば「#nc-system-header」を非表示にすることは、何のセキュリティ対策にもなりえません。
※　機械からは、ログインへのリンクは当然見えてますので。それをするなら、完全に削除しないと効果は期待できません。完全に削除したところで、たいした防御は期待できませんが。。

２．人による攻撃を防御することを想定した場合
これも無意味です。NC3を使っているということはすぐに判明しますので、ログインへのリンクは当然ながら、すぐみつかります。

もう少し、どうしてこれがWebセキュリティ対策になるのかお考えになって発言していただければと思います。
本格的にCMSとして利用したいのであれば、ログインへのリンクを非表示にする機能を追加するとともに、ログイン画面をIP制限できる等する必要があります。小手先の無意味なセキュリティ対策は行いません。

**Comment by ghost** [comment]
冒頭の私の言い方が悪かったようでしたら申し訳ありません。#699の筆者を避難する意図はありません。

> フォースアタック

　ブルートフォースアックのことでしょうか。もしそうだとして、必ずしも機械によるものだけではなく、人による攻撃も心配しております。

> 機械からは、ログインへのリンクは当然見えてますので

　「ログイン」とかいてありますから、それは見えてしまいますね。

> ログインへのリンクは当然ながら、すぐみつかります。

　すぐに見つからないような作りが必要というようにも聞こえます。

> もう少し、どうしてこれがWebセキュリティ対策になるのかお考えになって発言していただければと思います。

　「少しでもセキュリティ向上させる」という発想を持っていただきたいと思います。現場をみていればそういう感性が理解いただけるのではないでしょうか。「100%完璧な対策でなければ、やる意味がなし」というような厳密な技術論ではいかがなものでしょう。物事は完璧でなくても、一程度の効果があると期待できる時はやるものではないでしょうか。よほどコストがかかるとか何か事情があれば別ですが。

　Amazon等を例示いただきましたが、それらは何かあっても利用者個人の自己責任の範囲です。しかし、グループウェアでは一人の参加者のパスワードが脆弱な為に、組織全体の不利益につながる恐れがあります。組織の存亡に関わることすらあり得ます。この意味では、当初からのNetCommonsの仕様で「ログイン」が明示されていることは、NetCommonsに出会った当時から疑問を感じていました。

> 小手先の無意味なセキュリティ対策は行いません。

　そうですね。完全なセキュリティ対策をお願いいたします。

　ところでこのページは関係者にもみていただいておりますので、念のため申し添えます。

**Comment by dreamer9999** [comment]
もうcloseしていますが、私、こと、素人ユーザーが、横から失礼します、

ryu818さん
「実際、確認したわけではないですがAmazon、楽天、facebook等をみてください。すべてログイン画面に遷移してるのではないでしょうか。」
➡確認すると、facebook以外はトップページに遷移するようです。

「完璧なセキュリティ」のセキュリティレベルを100とすると、
「トップページに遷移させる」はレベル60
「ログイン画面に遷移させる」はレベル50
とザックリたとえてみます。

「完璧なセキュリティ」は現状難しい。
ならば、現状可能な範囲で選択するなら、次善策として
「トップページに遷移させる」のレベル60　を選択することが妥当であると思われます。

この議論は、上記のようないきさつになるようになるように思われます。

※　プロ同士の白熱した議論は、netcommonsの発展に欠かせないものかと思います。
ただ、そこには、議論の暗黙の基本ルールがあってしかるべきかと思います。
つまり、議論の相手に対する礼儀があってしかるべきかと思います。
それなしでは、本来外（netcommons）に向けるべきエネルギーが、メンバー間の軋轢に消費され、自家中毒を起こし、集団としてのモラルが下がり、良い結果につながらないと思います。

プロの技術も、土台となる良いチームワークに支えられてこそ、大きく進展すると思います。

素人ユーザーの目から、今回の議論のコトバ使いをみて、土台となるべきチームワークに
一抹の不安を感じ、僭越ながら、投稿させていただきました。

**Comment by ryu818** [comment]
ご心配をおかけして申し訳ございません。
なるべくには、そのように心掛けたいところではありますが、多忙な中、仕事の合間に無償で回答していることから、間違った内容の指摘を、簡潔に説明するに留まっております。
同じ技術者として厳しい意見となったこともあります。

さて、本件ですが、まず、セキュリティ上の問題ではないのに質問だけに留まらず、セキュリティホールでもあるかのように修正要請しています。
ただ、ログイン画面を隠し、一般にはログインできることをお知らせしたくないだけであるのにです。
ですので、それは誤りであることをお伝えしました（私の知らない別の攻撃手法があれば別ですが、それなら、その攻撃手法を示すべきです）。

上記、セキュリティにはいっさい関係なく、一般にはログインできることをお知らせしたくない理由であるならば、意味はわかります。NetCommonsを利用しているユーザが、すべてログインを隠しているのであれば、トップページに遷移するべきです。しかし、多くのNetCommonsユーザから見れば、ログイン画面へ遷移することが、最も合理的です。ログインのリンクを隠す機能をNetCommonsに導入されるとすれば、その際は、トップページに遷移するようにするべきともいえます。但し、操作性の問題であり、セキュリティの問題ではありません。
もし、セキュリティ上にそのようにしたいのであれば、NetCommonsというアプリで制御するよりも、もっと上位でわりと安易に施すことが可能です。
apacheですと、特定のIPアドレス以外をリダイレクトする機能です。これが私が考えうる最も簡単な方法です。
https://gray-code.com/blog/web-create/redirect-to-maintenance


> 「完璧なセキュリティ」のセキュリティレベルを100とすると、
> 「トップページに遷移させる」はレベル60
> 「ログイン画面に遷移させる」はレベル50
については、１００、０、０くらいです。まったくセキュリティ対策にはなっておりませんので。
同じ０なので操作性を損なわない「ログイン画面に遷移させる」を選択したにすぎません。

amazon, facebook,楽天、ついでにtwitterもつけました。
https://www.amazon.co.jp/gp/css/order-history?ref_=nav_orders_first
https://www.facebook.com/settings
https://my.bookmark.rakuten.co.jp/?l-id=myr_main_bookmark_pc
https://twitter.com/settings/account

リンク先にもよりますが、セキュリティの考慮ではなく、操作性の観点からログイン画面へ遷移しているといえます。

**Comment by dreamer9999** [comment]
■セキュリティに関連して

Ａ：トップページに遷移（ログインボタンを非表示）
Ｂ：ログイン画面に遷移　

とします。

ユーザー１００人いるとします。

①１０人は、悪意ある技術者ハッカー
　彼らにはＡ・Ｂいずれもセキュリティ上効果なし

②３０人は、技術はほとんど無いが、機会があれば、イタズラ心が生まれるチョイ悪の方々
　彼らには下記ＡＢそれぞれ遷移すると
　　Ａ：通常の閲覧して終了
　　Ｂ：何かできるんだな、と、イタズラ心が生まれ素人なりに、ログインしようとする危険発生。

③６０人は、良心的な一般日本人
　彼らにはＡ・Ｂいずれもセキュリティ上問題なし

＜結論＞
　②の理由で、Ａのほうが、セキュィテイの危険度が低いと思われます。

■利便性
　
netcommonsが使用される組織として、学校関連・一般企業・個人サイトなどがあると思われます。
その大多数のユーザーの主な権限は、ゲスト・一般であると思います。
（編集者・管理者権限などは一部の方々なので、対象として除きます）

①学校関連・一般企業では、ユーザーをゲスト権限として、閲覧だけを求めるサイトが多いかもしれません。
　　　https://opensource-workshop.jp/works/fcs/
　　　https://kawaguchicity-hs.ed.jp/tokusyoku/

　　　このようなサイトでは、閲覧だけする大多数のユーザーが、ログイン画面に遷移されると、
　　　不便を感じるかもしれません。

②個人サイトでは、ユーザーを一般権限として掲示板などへの投稿を求めるサイトもあるでしょう。

　　　このようなサイトでは、大多数のユーザーが、ログイン画面に遷移されると、
　　　利便性を感じるでしょう。


以上のことを考えると、

・最善策は、サイトを利用するユーザーの性質から、上記Ａ／Ｂを選択できるようにする。
・最善策が無理なら、総合的に考えると、Ａを選択する。

ことが妥当であるように思われます。

■その他

amazonなどの遷移画面

初回の投稿に「ブラウザのURL欄に（ホスト名に続けて）、存在しないpathを指定する」場合とあるので

   https://www.amazon.co.jp/+++999   と入力すると、トップページに遷移、
　以下同様に、
　楽天は、トップページに遷移、
　facebookはログイン画面に遷移
　twitterはログイン画面に遷移

 みたいです。

**Comment by ryu818** [comment]
ちょい悪の人はログインで何度かログインを試みるかもしれませんが、すぐあきらめます。むしろ、その程度の攻撃に脆弱なセキュリティなのかといことになります。そして、存在しないページをそもそも悪意がないので叩かないので、基本的にはログイン画面にたどり着きません。
さらに、そもそもログインへのリンクが表示されてますからね。
どんなユーザの定義をもってしてもセキュリティ対策ではないので意味をなさないのは、変わらないです。

１つあるとすれば、存在しないページだったら、トップページ、そうでなければログイン画面とすることですが、これも存在するページを伝えることになるのでやめたほうがよいです。

その下の利便性も大きな誤りがあります。
①の人は不正なページに基本的には遷移しないのでログイン画面に遷移することはありません。
さらに、トップページに遷移することで、たまたまトップページをみたかった人以外は、利便性は向上すらしてません。もちろん、サイトの作りにもよりますが。

そして、保護者、学生等がより多く参加して、ホームページに活気をもたせるためのネットコモンズと思ってますので、より多くの人はログイン前提での利用を１番に想定しております。
ログイン前提にしないのであればwordpress等で十分です。

簡単にapacheの設定で意図したいようにすることができるのですから、利便性重視で正しいと思います。

**Comment by dreamer9999** [comment]
Ａ：トップページに遷移（ログインボタンを非表示）
Ｂ：ログイン画面に遷移　

とします。

■「存在しないページを叩く」ことの条件

　ここで議論する場合、

　「存在しないページを叩く」条件として、間違ってしまって、ミスで行ってしまうことに限定。
　「存在しないページを叩く」条件として、悪意で行うことは除外。
　　※　理由　悪意の場合、セキュリティ上では、前記、ＡＢ共に同じレベルだから議論の余地なし。
　　　　　　　また、利便性上では、悪意あるものに対し議論するのは無意味。

■セキュリテイ

＜引用文：ちょい悪の人はログインで何度かログインを試みるかもしれませんが、すぐあきらめます。むしろ、その程度の攻撃に脆弱なセキュリティなのかといことになります。そして、存在しないページをそもそも悪意がないので叩かないので、基本的にはログイン画面にたどり着きません。＞

➡
間違って「存在しないページを叩く」人がチョイ悪であった場合、

たとえば、危険性が最高100点として、
上記Ａの場合危険性50点、
上記Ｂの場合危険性51点
（チョイ悪（タチの悪いチョイ悪がまじってるかも）にログイン画面を気づかせる分、危険度点+1）

気づかせる必要がなければ、気づかせないほうがベター、として、Ａに軍配かな？

■利便性

＜引用文：その下の利便性も大きな誤りがあります。
①の人は不正なページに基本的には遷移しないのでログイン画面に遷移することはありません。
さらに、トップページに遷移することで、たまたまトップページをみたかった人以外は、利便性は向上すらしてません。もちろん、サイトの作りにもよりますが。
そして、保護者、学生等がより多く参加して、ホームページに活気をもたせるためのネットコモンズと思ってますので、より多くの人はログイン前提での利用を１番に想定しております。
ログイン前提にしないのであればwordpress等で十分です。
簡単にapacheの設定で意図したいようにすることができるのですから、利便性重視で正しいと思います。＞

➡具体的な事例としてたとえば、下記、川口市立高等学校を取り上げてみます。
　https://kawaguchicity-hs.ed.jp/tokusyoku/

この学校のＨＰを見る全体人数は概算で、４５００名

　　全校生徒　　　　１４４０名＝１学年４８０名Ｘ３学年
　　先生・事務員　　　１００名（こんなくらい？かな）
　　ＰＴＡ　　　　　２８８０名＝ご両親Ｘ生徒数
　　その他学外の方　　　８０名（こんなくらい？かな）
　　合計　　　　　　４５００名

この中で、ＨＰの管理業務に携わり、ログインが必要な方、多くて１００名位？でしょうかね、
このＨＰには掲示板がなく、管理者以外は閲覧だけをするものとされてます。

間違って、「存在しないページを叩」いてしまった４４００名（４５００名ー１００名）が
全員、必要のないログイン画面に遷移されるのは、不便だと思われます。
１００名の管理関連の方は利便かもしれません。
サイト全体像を見た場合、不便４４００名、利便１００名、

４４００名の不便を防ぐべく、間違って「存在しないページを叩」いてしまった場合、
トップページに遷移したほうが良いと思われます。

※amazon 楽天が「トップページに遷移」は閲覧での使用を中心に考え、閲覧する多数の不便を防ぐ理由では？
　facebook twitter が「ログイン画面に遷移」は、書き込みでの使用を中心に考え、書き込みする多数の不便を防ぐ理由では？

以上、私見としましては、

・amazon 楽天風に、大多数の使用者がＨＰを閲覧で使用するサイトは、セキュリティ・利便性ともに、「トップページに遷移」が望ましくおもわれます。
（学校・一般企業がそれに値すると思われます）

・facebook twitter 風に大多数が書き込みでの使用を中心に考えられたサイトでは、
「ログイン画面に遷移」ということになるのではないでしょうか、
　（個人サイト・ブログなどがそれに値すると思われます）

**Comment by ryu818** [comment]
コアに利用する100名のためにそのようにするのは妥当です。その人たちに少しでも日々の業務を円滑に行っていただきたいです。
それ以外の人が誤ったページに遷移する確率が１パーセントないくらいなのに、そのあまりコアでない人の、しかも、誤ったURLを入力したときの利便性を重視したいなんて、考えにくいです。

そして、セキュリティについては、なんら効果がないのは何度も説明した通りです。ログインのリンクを非表示を前提にして考えるのならば、まず、ログインのリンクを非表示にすることを要望するのが先ではないでしょうか。

**Comment by ryu818** [comment]
川口市立高等学校のサイト拝見しました。まさにcmsとしての利用ですし、規模が大きいためか存在しないリンクが残されたままのようです。
そのように利用することが一定数いることは承知しております。

そして、ふとよい仕様を思い付いたのですが、技術的に可能かどうかはわかりませんが、パブリックのページへの遷移でありえないページならば、トップページ、それ以外ならば、ログイン画面へ遷移するのがよいのではと思いました。

とはいえ、ログインへのリンクを非表示にする機能を搭載してほしいという要望のほうが多いとは思いますが、簡単に直るのならばの選択肢の１つとして。

**Comment by dreamer9999** [comment]
現在の議論は、現状はそのままで、相対的に、下記どちらを選択すべきか、どちらに優位性があるか、ということかと思います。
新規の他のセキュリティ強化案は、別の議論になると思います。

Ａ：トップページに遷移（ログインボタンを非表示）
Ｂ：ログイン画面に遷移　

■セキュリティー

チョイ悪の「寝た子を起こす」要素をはらまない「トップページに遷移」の方が、
チョイ悪の「寝た子を起こす」要素をはらむ「ログイン画面に遷移」より
相対的に優位かと、

■利便性

一般閲覧者４４００名のうち「存在しないページを叩」く率1％＝４４名
　彼らは、「ログイン画面に遷移」させられると、不便をかんじる

コアメンバー（管理者）１００名のうち「存在しないページを叩」く率1％＝１名
　彼は、「ログイン画面に遷移」させられると、利便をかんじる

コアメンバー（管理者）の真意は、自分達は２の次にして、一般閲覧者がいかに気持ちよくＨＰを利用していただけるか、と、思われます。
コアメンバー（管理者）の真意は、自分達１名より、一般閲覧者４４名がいかに気持ちよくＨＰを利用していただけるか、と、思われます。

ＨＰは、管理者のためにあるのではなく、一般閲覧者・利用者のためにある、ＨＰの主人公は一般閲覧者・利用者、かと、
ＨＰ・netcommonsすべて、一般閲覧者・利用者目線で、考えることが、鉄則かと、

コアメンバー（管理者）に対する思いやり・利便性の概念をいま少し、広げ、深めるならば、そして、真に、一般閲覧者のことを気遣うコアメンバー（管理者）の気持ちに寄り添うなら、「トップページに遷移」の選択が、妥当かと、

**Comment by ryu818** [comment]
おっしゃることはわかります。しかしながら、ログインが表示されていること。それを非表示に変更できない点からもわかるようにNetCommonsはグループウェア＋会員制サイト＋eラーニング等のコミュニティツールとしての利用を最も促進しようとしているものです。
そういうことで、一概にトップページに戻すことが、良いとは言えません。
ご要望は受け止め前向きに検討します。
しかし、ご要望に添えない場合もありますが、ご容赦ください。

**Comment by dreamer9999** [comment]
＜引用文：ご要望は受け止め前向きに検討します。
しかし、ご要望に添えない場合もありますが、ご容赦ください。＞

➡

ありがとうございます。
ご検討、宜しくお願い致します。

以下、蛇足ですが、、、

＜引用文：おっしゃることはわかります。しかしながら、ログインが表示されていること。それを非表示に変更できない点からもわかるようにNetCommonsはグループウェア＋会員制サイト＋eラーニング等のコミュニティツールとしての利用を最も促進しようとしているものです。＞

➡「ログインが表示されていること。それを非表示に変更できない点からもわかるように」
　と、
「NetCommonsはグループウェア＋会員制サイト＋eラーニング等のコミュニティツールとしての利用を最も促進しようとしているものです」
の文章のつながりが不明です。（私の理解力が不足しているのかもです、、、）

＜引用文：そういうことで、一概にトップページに戻すことが、良いとは言えません。＞

➡「そういうことで」の理由が不明です。（私の理解力が不足しているのかもです、、、）


Netcommonsは、利用者が主人公、 より一層 、利用者目線で、その利用者の要望に真摯に、むきあっていただければ、と思う次第です。（ 当方 勝手なことを言う ばかりで 何もできずに恥ずかしい  限り です 
開発者の方のご苦労には頭がさがります・・・）

いづれにしても、Netcommonsの発展を願わずにはおりません。
ryu818さんのますますのご活躍を祈念しております。


（当方、逃げるようで誠に申し訳ないのですが、技術的にも、さほど、Netcommonsに寄与できる状況ではありません、せめて、Netcommonsの応援団の一員として、Netcommonsをウオッチし 発展 していく 姿を見ること を楽しみにして いきたいと思う 次第です）

**Comment by ryu818** [comment]
あまり時間をとられないため、簡潔にご回答いたしますこと、ご容赦ください。

１．一般的なCMSが前提として、コミュニティツールとして利用もできる仕様とするならば、ログインを非表示にするのをデフォルトにするため。
２．ログイン前提のグループウェアのようなものですので、使用者の全体はログイン前提の人たちです。なので、「そういうことで」と続きます。

こちらこそ、様々なご意見ありがとうございました。

**Comment by dreamer9999** [comment]
ちょっと、気になったことを書かせていただきます。

＜ryu818さんからの引用文：おっしゃることはわかります。しかしながら、ログインが表示されていること。それを非表示に変更できない点からもわかるようにNetCommonsはグループウェア＋会員制サイト＋eラーニング等のコミュニティツールとしての利用を最も促進しようとしているものです。＞

➡
「NetCommonsはグループウェア＋会員制サイト＋eラーニング等のコミュニティツールとしての利用を最も促進」ではないと思います。

　　ＨＰにあるように　( https://www.netcommons.org/NetCommons3 )

　「NetCommonsはホームページ＋グループウェア＋会員制サイト＋eラーニング＋ポータルサイト」
　　としての利用を目指していると思います。




＜ryu818さんからの引用文：ログイン前提のグループウェアのようなものですので、使用者の全体はログイン前提の人たちです。＞
（主に、学校でのグループウェアを想定していらっしゃるのか？）
（フト考えると、ホームページに遷移したとして、ホームページのログインを 再度 クリックするのに、０．１秒ほど？

　利便・不便の観点から、ログイン画面に遷移させる、云々すること自体、
　そんなには意味が 薄いの では、との想いにふけったり、、、）
　
  　
➡
さきほど述べたように、
「NetCommonsはホームページ＋グループウェア＋会員制サイト＋eラーニング＋ポータルサイト」
　　としての利用を目指している

　ので、ホームページ・ポータルサイトの事例の場合は、利用者は閲覧だけの方も多くなると
　思います。
　必ずしも「使用者の全体はログイン前提の人たち」とは言えないと思います。

＜結論＞

　Netcommonsの意義を、もっと広い観点から表現されているのは、
　　下記にあります。
　　　   ( https://www.nii.ac.jp/faculty/society/arai_noriko/ )

------具体的には、NetCommons（ネットコモンズ）という次世代の情報共有基盤システムを開発、無償で公開して実証研究をしています。できるだけ簡便に使えるツールに仕上げることで、技術や予算が十分ではない組織であっても、情報を共有したり、ウェブ上の情報発信力が高められるようになる社会を目指しています。------

　つまり、意義は「NetCommons（ネットコモンズ）という次世代の情報共有基盤システムを開発」
　し、
　「技術や予算が十分ではない組織であっても、情報を共有したり、ウェブ上の情報発信力が高める」
　ことです。

　射程を、教育関連のみに、置くのではなく、一般企業・個人サイトなどあらゆる組織が
　射程にはいっています。
　　　(参考：https://nc2.netcommons.org/bbr8lhuof-4093/#_4093)
 
 つまり、NetCommons（ネットコモンズ）は、「次世代の情報共有基盤システムを開発」するため、
とば口は、現在、主に、教育関連にしているが、ゆくゆくは、より一層、「あらゆる組織を射程」に
入れ、それをもって、「次世代の情報共有基盤システム」が完成となる、ということだと思います。

そのような、大きな枠組みで（教育関連だけではない）、Netcommonsの意義を捉えていないと、行く先々、まちがった仕組みづくりをしてしまうかもしれません。

このような大きな枠組みの元、開発していただき、
またまた、蛇足になりますが、
開発者が殿様ではなく、現場の利用者・現場に近いデベロパーが殿様であり、彼らの要望を真摯に受け止め、対応していくことにより、Netcommonsの発展は約束されたものになると思われます。
（万が一、彼らの要望に真摯な対応をし損ねると、沈黙のうちに、愛想をつかし、一人離れ、２人離れ、、、になるのがコワイと思います）

以上の件、いずれも、ご承知おきかと思いますが、老婆（爺）心の悪い癖が抜けず、いわずもがな、のことばかりで、失礼の段、Netcommonsへの愛着に免じ、どうぞお許しください。
