### ISSUE TITLE
速度改善 第四弾

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#1468]
主にCurrentライブラリに関する見直し。

**Comment by A11creATor-** [comment]
同じページに同じプラグインを２個配置しようとすると下記現象（Noticeとエラー（不正なリクエスト）になりました。
（パブリック、コミュニティ、プライベートのどこでも同じでした）
プラグインはアクセスカウンタ、ブログで発生を確認。

例）
１．同じページでブログを追加（２個）

↓Notice発生
![20190508_community_1](https://user-images.githubusercontent.com/5326831/57346810-f1f06580-718a-11e9-995e-27465853487a.png)

２．表示対象として２つの内の１つを選ぶ（ラジオボタンをクリック）と、
不正なリクエストの可能性があります。↓

![20190508_community_2](https://user-images.githubusercontent.com/5326831/57346829-092f5300-718b-11e9-8e9b-9094cd1f35de.png)
