### ISSUE TITLE
リリースしたプラグインにTestSuiteが残ってる

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1475]
nc3.2.2で確認しました。
とりあえず報告まで。

### 対象プラグイン
./Boxes/TestSuite
./Blocks/TestSuite
./Registrations/TestSuite
./Iframes/TestSuite
./Users/TestSuite
./UserRoles/TestSuite
./Workflow/TestSuite
./NetCommons/TestSuite
./Rooms/TestSuite
./PluginManager/TestSuite
./SiteManager/TestSuite
./Pages/TestSuite
./Frames/TestSuite
./M17n/TestSuite
./Topics/TestSuite
./Categories/TestSuite
./PrivateSpace/TestSuite
./AuthGeneral/TestSuite
./UserManager/TestSuite
./Reservations/TestSuite
./Quizzes/TestSuite
./Questionnaires/TestSuite
./Wysiwyg/TestSuite

### 対応方法

phpunit.xml.distに１行加える
```xml
<directory suffix=".php">app/Plugin/CleanUp/TestSuite</directory>
```
https://github.com/NetCommons3/CleanUp/blob/master/phpunit.xml.dist#L12

**Comment by s-nakajima** [comment]
リリースパッケージにTestディレクトリはありますか？
Testディレクトリがないのでしたら、不要ですね。
phpunit.xml.distって、phpunitの設定ファイルなので、リリースパッケージから除外するのは、ここじゃない気がするのですが。

**Comment by akagane99** [comment]
> リリースパッケージにTestディレクトリはありますか？
> Testディレクトリがないのでしたら、不要ですね。

はい、Testディレクトリ無かったです。

> phpunit.xml.distって、phpunitの設定ファイルなので、リリースパッケージから除外するのは、ここじゃない気がするのですが。

あれ？そうか。
phpunit.xml.distにTestSuiteの記載がないのは、TestSuiteをカバレッジに含めてる別件問題かな。

　Wysiwygの例：
　https://coveralls.io/github/NetCommons3/Wysiwyg

除外するなら多分こっちかなぁ。

　ファイルクリーンアップの例：
　https://github.com/NetCommons3/CleanUp/blob/master/.gitattributes

ファイルクリーンアップは記載なしでいけてるのは、謎だなぁ。

**Comment by s-nakajima** [comment]
ダウンロードしたプラグインで独自開発すると、UnitTestができなくなってしまうため、TestSuiteを含めます。
