### ISSUE TITLE
会員情報の追加会員項目（セレクト）の選択肢が正しく表示できない

### ISSUE THREAD

**Issue by hoangvnjp** [NetCommons3/NetCommons3#1477]
v3.2.2 会員情報の追加会員項目（セレクト）の選択肢が正しく表示できなかったのでご報告致します。修正をお願いします
![会員情報の設定](https://user-images.githubusercontent.com/39456776/55467320-fe3d4c00-563b-11e9-9886-27704b3a96d5.PNG)
![会員情報の表示](https://user-images.githubusercontent.com/39456776/55467321-fed5e280-563b-11e9-8231-a4cb818facb2.PNG)

**Comment by akagane99** [comment]
対応しました。

修正ソース
https://github.com/NetCommons3/Users/pull/172/files#diff-9ac9716e5bd971941be6cfa3db61d008
