### ISSUE TITLE
Edgeで、日付入力項目に対して日付以外の文字を入力するとエラーになる

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#1493]
日付入力項目で日付以外の文字を入力すると下記のエラーになる。ChromeとFirefoxでは、日付以外を入力すると、勝手に日付に元に戻してくれるが、Edgeの場合、文字がそのまま入力でき、下記のエラーになる。

![image.png](https://zube.io/files/netcommons3/281965d3f2b26fd41b28f0a8632992e2-image.png)

**Comment by A11creATor-** [comment]
不正な文字が入らないようになったこと、確認OKでした。

通常の日付を入力してみたところ、
例えば、2019-04-01　から、2019-05-08　まででエクスポートしようとしたところ、
invalid errorになりました（Chrome）↓

![20190508_1](https://user-images.githubusercontent.com/5326831/57341552-d29b0d80-7175-11e9-8166-8d8466bf34b4.png)
![20190508_2](https://user-images.githubusercontent.com/5326831/57341594-f2cacc80-7175-11e9-98c1-813428a10735.png)
