### ISSUE TITLE
ダウンロードパスワードの有無が設定できない

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#1496]
全体的にダウンロードパスワードの処理は入っているが、メタデータの設定で、ダウンロードパスワードを設定するか否かを設定できなかった。

**Comment by akagane99** [comment]
github最新版で動作確認しましたが、設定後、ダウンロードできなくなりました。
パスワードダイアログは表示されますが、パスワードがあってても、待ち違っても白画面になります。
エラーログは出力されてませんでした。

まだ作業途中かなぁ。
特に困ってないです。
