### ISSUE TITLE
汎用DBメール設定画面の埋め込みキーワードについて

### ISSUE THREAD

**Issue by SatohDaisuke** [NetCommons3/NetCommons3#1498]
「汎用DBのメール設定で埋め込みキーワードの説明が未設定 #971」ですでに解決となっていますが、NC3.2.2で同じ現象が起こっています。当サイトだけでしょうか。

**Comment by RyujiAMANO** [comment]
もしかして修正前からご利用ですか？
もし以前からご利用でしたら以前のcacheファイルが残っているのかもです。
app/tmp/cache/persistent/にあるキャッシュファイルを削除してみて症状がカイゼンするかためしてみてもらえますか

**Comment by SatohDaisuke** [comment]
早速にお返事ありがとうございます。
以前から使用していますが、使用しているNCは3.2以降が最初だと思います。
キャッシュファイルの削除をしましたが、症状に改善は見られませんでした。

**Comment by akagane99** [comment]
なんでしょうね？
・私のNC3.2.2でも同様の状態でした。
・app/tmp/cache/persistent/　キャッシュクリアしても改善せず
・app/tmp/cache/　の他のキャッシュもクリアしても改善せず
・プラグインの汎用DBをアップデート：改善せず

![image](https://user-images.githubusercontent.com/2756509/57894801-3f538d80-7883-11e9-996f-5ada221c13bd.png)

**Comment by akagane99** [comment]
typoあって、修正しました。
NC3.2.2で動作確認済み

修正箇所
https://github.com/NetCommons3/Multidatabases/commit/dcdd67a98e4cc43645c18fcc3d2a14d4cf445159

修正後画面
![image](https://user-images.githubusercontent.com/2756509/57895266-b1c56d00-7885-11e9-84da-f71cca997174.png)
