### ISSUE TITLE
汎用DBメール通知の埋め込みに「投稿内容」の追加希望

### ISSUE THREAD

**Issue by SatohDaisuke** [NetCommons3/NetCommons3#1499]
汎用DBメール設定画面の埋め込みキーワードに「投稿内容」を表示する機能がないようです。
例えば、メール通知機能でユーザーには内容を周知し、DB管理ユーザーとしてはデータをNC3上に蓄積していく、といった利用例もあると思います。NC2では同様の使用方法をしておりました。
もし可能でしたら、「投稿内容」もメール通知できるとありがたいです。

**Comment by akagane99** [comment]
参考にNC2とNC3のメール設定画面はります。

NC2
![image](https://user-images.githubusercontent.com/2756509/57910918-616c0080-78c1-11e9-8693-ce73a4d9539d.png)

NC3
![image](https://user-images.githubusercontent.com/2756509/57911029-a2641500-78c1-11e9-834d-4da539c71a4c.png)

**Comment by akagane99** [comment]
対応しました。

DBマイグレーションを追加したため、下記ソースを上書き後、プラグイン管理から、汎用DBをアップデートが必要です。
（汎用DBのメール定型文の初期値データのみ更新されます）

ソース
https://github.com/NetCommons3/Multidatabases/pull/37/files

**Comment by akagane99** [comment]
添付ファイル項目、画像項目だと、添付してても、メールの投稿内容の該当項目が空になるため、修正する予定。

NC2でも、同様でした。

**Comment by akagane99** [comment]
> 添付ファイル項目、画像項目だと、添付してても、メールの投稿内容の該当項目が空になるため、修正する予定。

対応しました。
https://github.com/NetCommons3/Multidatabases/pull/38/files
