### ISSUE TITLE
アソシエーションのdeleteAll

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#150]
グループの更新処理で、参加メンバーを全削除後、Insert処理しています。
https://github.com/NetCommons3/Groups/blob/9c7dc19974358e10d6f7c96b484df21066fc53ae/Model/Group.php#L176-L192

この処理だと、GroupsUserモデルではmasterデータソース見に行かないような気がしてます。

気になって、deleteAllでgrepしたところ、各プラグインの削除処理でアソシエーションのdeleteAllが使用されていました。
例えば、FAQ
https://github.com/NetCommons3/Faqs/blob/a9489e691153bf43883901536067522ce1ca18ba/Model/Faq.php#L298-L308

これも、masterデータソース見に行かないような気がしてます。

勘違いでしょうか？

**Comment by RyujiAMANO** [comment]
beginしたら全部masterに切り替わるようにする処理あったはずですが、今は想定通り動いてるかな？（以前はアソシエーション先だけで、アソシエーション先のアソシエーション先とかダメだったような…ちょっと記憶あいまい）

masterに切り替わらないモデルが残ると確かにダメかも

**Comment by kteraguchi** [comment]
> beginしたら全部masterに切り替わるようにする処理あったはずですが

ちょっと見てみました。
私の勘違いもありましたが、結果ダメっぽいです。

私の勘違いは、DboSource::beginでmasterに切り替えてるのかと思っていました。
Model::saveでDboSource::begin呼ばれるので、
https://github.com/cakephp/cakephp/blob/2.7.11/lib/Cake/Model/Model.php#L1749
saveは全部masterになるはずと。
んで、Model::deleteはDboSource::begin呼んでいないので、ダメじゃない？
ということで、上記をあげました。

実際は、NetCommonsAppModel::getDataSourceで切り替えていました。
https://github.com/NetCommons3/NetCommons/blob/47e79f762fe54962c67ca60ea5cde239046a5812/Model/NetCommonsAppModel.php#L159

NetCommonsAppModel::__changeDataSource見てみると、定義されているassociationモデルに対して
masterに切り替えています。
https://github.com/NetCommons3/NetCommons/blob/47e79f762fe54962c67ca60ea5cde239046a5812/Model/NetCommonsAppModel.php#L184

結果、
グループの更新処理はGroupsUserモデルをhasManyで定義しているのでOK。
FAQはFaqQuestionモデルはOKだけど、FaqSettingモデル,FaqQuestionOrderモデルは定義されていないので、masterとは限らないです。

要検討です。
間違ってたら突っ込んでください。

**Comment by kteraguchi** [comment]
間違ってました。

https://github.com/NetCommons3/NetCommons/blob/47e79f762fe54962c67ca60ea5cde239046a5812/Model/NetCommonsAppModel.php#L173
で全部のモデルがmasterに切り替わります。

https://github.com/NetCommons3/NetCommons/blob/47e79f762fe54962c67ca60ea5cde239046a5812/Model/NetCommonsAppModel.php#L184
はトランザクション後のSELECT処理用にassociationもmasterに切り替えている処理でした。

ということで問題なし。closeします。
