### ISSUE TITLE
iPhoneを利用して、検索プラグインの詳細検索で開始日（From）を指定すると画面が固まる

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#1504]
iPhone（iOS11.4,safari11）で検索プラグインを配置したNC3サイトに接続し、詳細検索で日付指定（開始日）をしたところ、画面が固まってしまい（チェックボックスにチェックが付けられなかったり、ボタンを押しても反応しないなど、画面をタップしても反応しなくなる）、終了するためにはブラウザをクローズするしかない。日付指定（終了日）の場合、画面は固まらない。

＜再現方法＞
①検索プラグインを配置したNC3サイトを準備する
②サイトにアクセス
③検索ボックスにて詳細検索ボタンを押す
④日付指定（From/開始）を行う

**Comment by akagane99** [comment]
公式サイトで確認してみました。
画面固まりませんでした。
なんだろう？

環境
iphone7, iOS12.3, safari 

公式サイトの検索
https://www.netcommons.org/

画面
![86ECA31F-1719-4836-8895-893FE908F83C](https://user-images.githubusercontent.com/2756509/58176489-55c37400-7cdd-11e9-9031-80c2a6328465.png)

**Comment by ghost** [comment]
お忙しい中、ご確認ありがとうございます。
こちらで公式サイトにアクセスして確認したところ、やはり画面が固まってしまいました。

今朝偶然、ご確認されているのとほぼ同じiPhone7がありましたので、
同じく確認したところ、ご指摘どおり画面は固まりませんでした。

iOSのバージョンによるものではないかと推測します。
（NC3は最新版3.2.2利用）

＜フリーズしない環境＞
iPhone7
iOS12.3
safari12

＜フリーズする環境＞
iPhone6
iOS11.4
safari11
※上記環境がございましたら、ご確認していただけると幸いです。

もし、上記環境でフリーズすることを確認していただけた場合、NetCommons3側で対応していただけるのでしょうか？

**Comment by ghost** [comment]
フリーズする環境ですが、一部誤りがございました。
iPhone7 -> iPhone6 
お詫びして、訂正いたします。

**Comment by akagane99** [comment]
残念ながらiphone6の実機がないため、私の方で調査出来ない感じです。

**Comment by osws-makino** [comment]
iphone6の実機で確認しました。
動作は一部遅いかな？　と思われる箇所はありましたが、動きました。
・iphone6
・iOS：12.3.1
・safari（※バージョンの確認方法が分からず）
・chrome（73.0.3683.68）

過去、同じ状況にPCでなった事があります。
その時はキャッシュ等を削除すれば正常に動作するようになりました。

以上、ご報告でした。

**Comment by ghost** [comment]
osws-makino 様、情報提供ありがとうございます。
こちらでも、キャッシュ等削除して試してみました。結果は変わりませんでした。

投稿後にこちらでわかったことは、iOSのバージョンにより発生するのでは？です。
iPhone7,10でも、iOS11.4だと現象が発生することを確認取れているためです。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1558 こちらで対応済み
