### ISSUE TITLE
PHP7.3.4下で、フォトアルバムへの画像投稿の際、「内部エラー」となり失敗します。

### ISSUE THREAD

**Issue by dreamer9999** [NetCommons3/NetCommons3#1505]
以下、M.NishimuraさんのNetCommons公式サイトからです。

[https://www.netcommons.org/bbses/bbs_articles/view/778/ab8d957b28c11d4727704834c732f62f?frame_id=199#!#%2Fbbs-article-348](https://www.netcommons.org/bbses/bbs_articles/view/778/ab8d957b28c11d4727704834c732f62f?frame_id=199#!#%2Fbbs-article-348
)

NC3.2.2の新規インストール後、フォトアルバム設置時の初回画像投稿で「決定」押下後、「内部エラー」となり失敗します。

調べたところ、以下のようなことが分かりました。

/www/app/Uploads/files/upload_file/real_file_name/x/x　内に入った画像ファイルのパーミッションが600．
キャビネットで同一画像をアップロードすると、同ディレクトリ内の画像ファイルのパーミッションが644．
フォトアルバムの仕様（？）かよくわからないのですが、何か参考になる情報をお持ちの方がいれば、教えていただけないでしょうか。

以下は補足事項です。

さくらのレンタルサーバ
PHP 7.3.4（php.iniに「extension = imagick.so」を設定）
MySQL 5.7

※PHP5.6下では正常に画像が投稿できます。
　　急遽の策で、PHP5.6で開始➡画像をアップ➡PHP 7.3.4に変更、で正常に動いていますが、何か問題が生じる可能性ありますか？

**Comment by akagane99** [comment]
掲示板から転記です。

https://www.netcommons.org/bbses/bbs_articles/view/778/ab8d957b28c11d4727704834c732f62f?frame_id=199#bbs-article-401
> こんにちは。
さくらのVPS環境でPHP 7.3.6を試したところ、フォトアルバムに投稿できました。
PHPバージョンの問題じゃなさそうな感じです。
> 
> ###
> 
> 私の方でも、さくらのレンタルサーバーのphp7.3で動かしたら、フォトアルバムの投稿で内部エラーになりました。
> 
> 利用しているPHPモジュールに違いがあるのかなぁ。
> とりあえずご報告まで。

**Comment by Tom-Hirabayashi** [comment]
失礼します。
掲示板にも投稿しましたが、
https://demo-nc3.eddy-k.jp/check/photoalbum
で関連情報がありましたので、参考までに上げさせてください。解決をユーザーとして、心待ちにしています。

> NC3の公式サイトのトラブルにて掲載されていた「フォトアルバム投稿時のパーミッションがおかしい（？）」でこちらのデモサイトにて確認したら確かに内部エラーとなりました。
> 
> っで、ちょっと調べてみたらrenameのところで落ちているようです。
> 
> そこでググってみたらいろいろとあり見てみたらこれかなあといった解決策があったので試してみました。
> 
> 良い方法とは思えないのですがこの方法で以下のフォトアルバムが設置できました。
> 
> 【解決策】
> 
> /app/Plugin/Upload/Model/Behavior/UploadBehavior.php
> 
> の360行目
> 
> return rename($filename, $destination);　のrenameの前に@をつけるのでした。
> 
> return @rename($filename, $destination);
> 
> とすれば、エラーを返さなくするようで現在の問題は回避できます。
> 
> もうひとつcopyし正常に複写できれば移動元を削除（unlink）するといった方法もあるようですが、コードを書く必要もあり@をつける方法を試しました。
> 
>  
> 
> この方法が本当に良いかは開発者さまの確認・検討が必要ですが・・・

**Comment by hmlyn523** [comment]
私も同様の現象に悩まされています。
