### ISSUE TITLE
500M以上の動画ファイル

### ISSUE THREAD

**Issue by Junkomata** [NetCommons3/NetCommons3#1516]
導入を前提に動画配信システムとして使用可能かテストしています。
ffmpegを使用せず500M以上のMP4はアップロードできないようで
この要領制限を変更するには、何を調整したら良いのでしょうか？

環境は以下です。
CentOS 7.6.1810
php 5.4.16
MariaDB 5.5.60
NetCommons 3.2.2 

ffmpegを入れると、260M程度でも、何がしかエラー表示が出始めたので、サムネール制作を諦めようと考えています。

**Comment by RyujiAMANO** [comment]
関連しそうなPHPの設定だと
- memory_limit
- upload_max_filesize
- post_max_size
- max_execution_time
あたりですかね。

**Comment by Junkomata** [comment]
php.ini を調整しましたが、無理でした。
ルーム内にpluginを設置したことから、システム管理－各コミュニティの容量　の制限が500Mでしたのでこれを無制限にしましたが、内部エラーとなりました。

今日は、ここまでで、作業を終了します。
270Mのファイルは登録できます。
670Mのファイルは、127M程度アップロードして内部エラーです。?_?

**Comment by Junkomata** [comment]
解決しました。
物理的にストレージの容量が足りていませんでした。
ストレージを付け足し、テストしたところ問題無くアップロードできました。
ffmpegを使用してのサムネール作りも、時間は掛かりましたが、動作しました。
お騒がせしました。m_m.

**Comment by RyujiAMANO** [comment]
解決して良かったです！
