### ISSUE TITLE
チェックボックス、ラジオボタンが巨大化

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#152]
フォトアルバムのレビューで、後で対応予定となっていた、チェックボックス、ラジオボタンが巨大化する件です。
レビュー時内容がぼやけたので、あげときます。

form-controlクラスで定義されているheight: 34pxが影響しています。

http://getbootstrap.com/css/#forms-example
を見ると、form-controlは&lt;input&gt;,&lt;textarea&gt;,&lt;select&gt;で使用するようです。

https://github.com/NetCommons3/NetCommons/blob/cb0e2fe6e35f5a995396299a5baa1855408ade1f/View/Helper/NetCommonsFormHelper.php#L168-L176

の処理に&lt;input&gt;, &lt;textarea&gt;,&lt;select&gt;のケースを追加するか、現状のまま呼び出す側で上書きするかですね。

**Comment by RyujiAMANO** [comment]
input, textarea, select に限定してform-control追加に＋1かなぁ

**Comment by kteraguchi** [comment]
FormHelperの出力結果をbootsrapに対応させるため、
before,after,separatorオプションの指定が必要になります。

参考
http://stackoverflow.com/questions/15649619/get-my-inputs-inside-my-labels-with-cakephps-formhelperradio-method

対応するなら、checkbox, radioのケースも考慮して実装する。
