### ISSUE TITLE
検索とカレンダー：検索結果からカレンダーを開いて、予定の編集や月一覧に戻って予定を開くと、見れる権限があっても「アクセスができません」

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1528]
nc3.2.2最新です。

* 検索からカレンダーに飛ぶとframe_idが消えます。
* カレンダーはframe_idがないと、「編集」や月一覧から予定を開く時に、見れる権限があっても「アクセスができません」メッセージが表示されます。

```
アクセスができません。指定したURLに移動するには、ログインが必要です。
ページが自動的に更新されない場合はこちらをクリックしてください。
```

frame_idあり（通常）
```
https://localhost/calendars/calendars/index/?frame_id=380&style=largemonthly&year=2019&month=09
```

frame_id空
```
https://localhost/calendars/calendars/index/?frame_id=&style=largemonthly&year=2019&month=09&page_id=4
```

##  frame_idなしで「アクセスができません」パターン

  * 月一覧から予定をクリック
  * ログイン済み。予定詳細をURLで開いて、編集をクリック

## 運用回避

メニューからカレンダーを配置しているページを開きなおせば、予定を開いたり、編集できます。

報告まで。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Calendars/tree/dd701d1c3697efaa0d9bedb5b22d56dccc863772 で修正済み
