### ISSUE TITLE
施設予約で施設数とルーム数が多い場合、予約の追加のページ表示に時間がかかる

### ISSUE THREAD

**Issue by prado1996** [NetCommons3/NetCommons3#1537]
施設数が17件、ルーム数が126件くらいあると「予約の追加」を開くまでに23分以上かかる。

app/Plugin/Reservations/Model/ReservationLocation.phpの「プライベートルームを除外したルームIDで予約可能かチェック」の二重のforeachで時間がかかっているようです。

**Comment by akagane99** [comment]
> app/Plugin/Reservations/Model/ReservationLocation.phpの「プライベートルームを除外したルームIDで予約可能かチェック」の二重のforeachで時間がかかっているようです。

上記の内容通りでした。

修正内容
https://github.com/NetCommons3/Reservations/pull/36/files

バグ修正しました。
どなたかマージできる方、ご確認の上、マージお願いします。
