### ISSUE TITLE
ファイルクリーンアップで汎用DBウィジウィグの添付ファイルが削除される

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#1539]
https://github.com/NetCommons3/NetCommons3/issues/1538

上記バグ修正後、NC3.2.2で確認しました。

・汎用DBのウィジウィグの添付ファイルは、正常登録でもupload_filesテーブル.content_keyが空のまま登録されていました。
・ファイルクリーンアップは、upload_filesテーブル.content_keyが空のものは使われていないと判断して消します。

この動作のため、汎用DBのウィジウィグ画像、添付ファイルは、ファイルクリーンアップをすると削除されます。

（また、汎用DBの項目で「添付ファイル」「画像」であれば、upload_filesテーブル.content_keyが登録されるため、ファイルクリーンアップで消える事はなかったです。）

報告まで。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/CleanUp/commit/873be5ea1c0196ed443ba202b86517ae794fae8f
こちらの対応で、content_key=nullのものは削除されないようになりました

**Comment by RikaFujiwara** [comment]
また汎用DBのウィジウィグへの貼り付けにおいてcontent_key=nullになる問題も、以下の修正によってカバーされています。
https://github.com/NetCommons3/Multidatabases/commit/8eb14862c27a69bdade7faebd22896c4c9e69a30
