### ISSUE TITLE
IEから施設予約の追加ができない。

### ISSUE THREAD

**Issue by schit55555** [NetCommons3/NetCommons3#1550]
バージョン3.2.2、3.3.0で確認しております。
IEで施設予約に予約を追加しようとすると添付画像の状態になり、決定ボタンをクリックすると「予期しないトークンにより、登録が正常にできませんでした。」とのエラー表示が掲載され再び画像の画面にもどります
![施設予約不具合03](https://user-images.githubusercontent.com/41180747/73046817-da8f0f00-3eb6-11ea-9981-eb5920bd48c6.jpg)

開発者ツールのコンソールタブを確認したところ、下記のエラーが検出されました。
Error: [$controller:ctrlreg] http://errors.angularjs.org/1.7.8/$controller/ctrlreg?p0=ReservationsDetailEdit
at Anonymous function (サイトURL/components/angular/angular.min.js?1552304448:97:338)
at ea (サイトURL/components/angular/angular.min.js?1552304448:79:332)
at p (サイトURL/components/angular/angular.min.js?1552304448:71:140)
at g (サイトURL/components/angular/angular.min.js?1552304448:64:477)
at g (サイトURL/components/angular/angular.min.js?1552304448:64:494)
at p (サイトURL/components/angular/angular.min.js?1552304448:73:75)

知識不足で大変恐縮ではございますが、IEでも追加できるように改善対応いただけますでしょうか。

**Comment by prado1996** [comment]
「施設予約プラグインにて施設を登録しようとすると、施設管理者の入力ができない。IE11で確認。 #1113」のAngularJS＋IE11問題と同じようですね。
 'largemonthly'の意味は分かりませんが、676行目を修正すれば入力ができるようになりました。

app/Plugin/Reservations/webroot/js/reservations.js
676行目
        //$scope.changeLocation = function(displayStyle = 'largemonthly') {
        $scope.changeLocation = function(displayStyle ) {

**Comment by prado1996** [comment]
IEとjavascriptのバグみたいですね。関数の引数にデフォルト値を設定してはだめみたいです。
https://to-memo.com/web/ie11_js_error01/
https://cpoint-lab.co.jp/article/201806/3590/

**Comment by schit55555** [comment]
ご投稿いただいた内容を自分の環境で試したところ、現象解消を確認できました。(win10、IE11)
もし他の機能に影響ないようでしたら、次バージョンにマージしていただけると大変ありがたいです。

**Comment by prado1996** [comment]
説明不足で申し訳ありません。
上記の修正で表題の不具合は解消しますが、修正箇所がどこに影響があるのかまでは検証できておりません。
修正はあくまでも暫定対処ですので、ご自身の判断によりご対応お願いします。
初期値も設定した修正です。

        //$scope.changeLocation = function(displayStyle = 'largemonthly') {
        $scope.changeLocation = function(displayStyle ) {
          if(typeof displayStyle === 'undefined') displayStyle = 'largemonthly';

**Comment by s-nakajima** [comment]
IEはサポート外となりましたので、Closeします。
