### ISSUE TITLE
Wysiwygエディタのolのメニューで、リストの見出し文字に「アルファベット」などを選んでも、デフォルトの数字に戻ってしまう

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1553]
Wysiwygエディタで、リストのスタイルが選べます。
![image](https://user-images.githubusercontent.com/3078370/74584153-6c032400-5012-11ea-86d2-d6b21139acf4.png)

上の図のように、「大文字のアルファベット」などを選んで、
決定すると、下図のようにデフォルトの数字見出しのリストになってしまっています

![image](https://user-images.githubusercontent.com/3078370/74584173-acfb3880-5012-11ea-8604-e341b3fe9c05.png)

POST時には間違いなく　
```
<ol list-style-type="upper-alpha"
```
でいっているのですが、書き込まれたデータでは　list-style-typeが落ちていました。
どこかでカットされているようです。

カットされるのが正しい仕様ならば、Wysiswygエディタのメニューには出さないようにするべきではないかと思います。
もしもWysiswygエディタのメニューのほうが正しいならば、カットしないようにしたいです。

**Comment by RyujiAMANO** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1189 と同じくHtmlPurifierが属性削除してると思われる。
list-style-type属性が許可されるように設定してやればよさそうな気はするけど試す時間がない^^;

**Comment by ryu818** [comment]
http://www.htmq.com/style/list-style-type.shtml
にあるようなlist-style-typeはすべて許可するように修正しました。
