### ISSUE TITLE
今は使われていないmenu_frames_roomsテーブルを見ている個所

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1559]
https://github.com/NetCommons3/Menus/blob/master/Controller/MenusController.php#L58-L64

すでに更新されなくなっているテーブルのデータを表示判定に加えているため、3.1のデータが残っているサイトでは、表示形式設定で設定変更を行っても、過去データに引きずられて思い通りの表示にならないです。

**Comment by s-nakajima** [comment]
当テーブルは、使用しなくなったのではなく、デグレで使用されなくなってしまっていました。
そのため、使用するように修正しました。
ex) パブリックを全OFFにして、ページを追加すると、追加したページが表示されてしまう。
