### ISSUE TITLE
TravisからPHP5.4, PHP5.5を削除し、PHP7.3, PHP7.4を追加する

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#1560]

**Comment by s-nakajima** [comment]
PHP7.4からスカラー型変数に配列アクセスするとE_NOTICEが出るようなった。
https://qiita.com/rana_kualu/items/eef7c214b8bf692a5eeb

**Comment by s-nakajima** [comment]
PHP7.3からDateTime仕様が若干変わって、1987年以前に対して世界標準時→日本時間に変換すると18:59が付与されるようになった。
(参考) https://www.m3tech.blog/entry/timezone-091859

PHP7.2までは、1987年以前も18:59が無視されていたが、PHP7.3からタイムゾーンが正確になったと思われる。

```
$zero = new DateTime('1887-01-01', new DateTimeZone('utc'));
$zero->setTimezone(new DateTimeZone('Asia/Tokyo'));
var_dump($zero->format('Y-m-d H:i:s'));

(結果)
string(19) "1887-01-01 09:18:59"
```

```
$zero = new DateTime('1888-01-01', new DateTimeZone('utc'));
$zero->setTimezone(new DateTimeZone('Asia/Tokyo'));
var_dump($zero->format('Y-m-d H:i:s'));

(結果)
string(19) "1888-01-01 09:00:00"
```

**Comment by A11creATor-** [comment]
（参考になれば）
1888年1月1日以前の日付が-1日になる問題の原因
http://piyocast.com/as/archives/9144
＞1888/1/1以前は子午線という概念が存在しなかったようです。

**Comment by s-nakajima** [comment]
TravisCIがphp74でZipArchiveとimagecreatefromgifを対応していないためphp73までとする。
対象プラグイン）Files、Questionnaires、PhotoAlbums
