### ISSUE TITLE
キャビネットに【拡張子がxlsm】のファイルをUpload後、Downloadするとファイル名が文字化けする

### ISSUE THREAD

**Issue by hmlyn523** [NetCommons3/NetCommons3#1583]
例えば、「aaa.xlsm」という名前のファイルをキャビネットにULしてからDLするとファイル名が「aaa.xlsm」ではなく、「1d4c73071103440720369cc02ca09f64.xlsm」のようなファイル名になってしまう。
拡張子が、.xls、.xlsxの場合は問題ありません。

**Comment by hmlyn523** [comment]
Netcommons3のバージョンは、v3.3.0
レンタルサーバは、さくらインターネット

**Comment by s-nakajima** [comment]
v.3.3.0では発生しませんが、v3.3.1でデグレしました。
そのため、当現象が発生しました。v3.3.2で修正しました。

関連ISSUE：https://github.com/NetCommons3/NetCommons3/issues/1433

**Comment by hmlyn523** [comment]
そもそも、
%E6%96%B0%E3%81%97%E3%81%84%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%20%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%.txt
というような文字化けではなく、
1d4c73071103440720369cc02ca09f64.xlsm
のような文字化けです。

v3.3.2でも発生しています。（現在は暫定的な対応をしています）

**Comment by hmlyn523** [comment]
ちなみに'download'のunsetを削除して203行目あたりを、
$this->_controller->response->file(
　$filePath,
　$options
);
ではなく、
$this->_controller->response->file(
　$filePath,
　[
　'download'=>false,
　]
);
としてます。

PHPのバージョンは、7.4.10(モジュール版)です。
