### ISSUE TITLE
アンケート、小テストでテンプレートから取り込んだ場合のウィジウィグエディタ中に設定している画像、ファイルにupload_filesテーブルのcontent_keyがNULL

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1593]
それぞれのウィジウィグを有するModelのafterSaveでupdateUploadFileの実行が必要ではないかと思われます。

**Comment by mikikosatou** [comment]
小テストについては、サブディレクトリにNetCommons3をインストールしたときに発生します。
原因と思われる箇所↓
https://github.com/NetCommons3/Wysiwyg/blob/master/Utility/WysiwygZip.php#L127
