### ISSUE TITLE
各プラグインで持っているuse_workflowやuse_comment_approvalなどを共通テーブル化

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#160]
ルームの設定で、承認ありとなし設定でき、その設定に基づき、use_workflowとuse_comment_approvalのデフォルト値が異なる。

現状、use_workflowやuse_comment_approvalなどを各プラグインで保持しているがBlockSettingテーブルという共通テーブルにすることで臨機応変に対応が可能となる。また、各プラグインで用意しているXxxxBlockPermissionControllerも不要になる？

その他、いいねの利用可否も同様にuse_likeとかもBlockSettingにまとめておくと良いのかも。

テーブル構成
| block_key | field_name | value |

データ例として
| block_key | field_name | value |
| -------------|----------------|-------- |
| block_1   | use_workflow | 1     |
| block_1   | use_comment_approval | 1 |
| block_1   | use_like        | 1        |
　　　・
　　　・
　　　・

**Comment by RyujiAMANO** [comment]
＋1

**Comment by s-nakajima** [comment]
牟田くんの方で対応したため、Close
