### ISSUE TITLE
ファイルクリーンアップ処理の途中で停止してしまう

### ISSUE THREAD

**Issue by kyoshida083** [NetCommons3/NetCommons3#1614]
php7.2、NetCommonsバージョン3.3.2patch1で確認

NetCommons3.2.2の複数のサイトを3.3.2までアップデートし、管理画面からファイルクリーンアップを実行しました。
処理の途中でログ出力がされなくなり、そのまま数時間放置してみましたが変化はありませんでした。
正常に完了したサイトもありましたが現象は複数のサイトで発生しており、停止したタイミングの削除件数、削除対象のファイルの種類等も違っており一貫性は見受けられませんでした。
再度削除を実行しようとしてもファイルクリーンアップ実行中のままで削除は行えず、ロックファイルの強制削除ををしてから再度削除処理を行ったところ、以降は”クリーンアップ処理が異常終了しました。”と出力され削除処理は行えなくなってしまいました。

同様の現象をご存じの方、お分かりになる方がいらっしゃいましたらお力添え頂けると幸いです。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/CleanUp/commit/36835fcfd8ed473f008c6c826667ab1f2b0c455a

以前のバージョンでは一部のプラグインのクリーンアップ処理で異常が発生していました。
上記のコミットや　Commits on Dec 16, 2020　の一連のコミットでこの件は対応されているのではないかと思います。
最新版で確認いただけますか？
