### ISSUE TITLE
メール通知機能・承認メール通知機能でメールが送信されない → 解決方法

### ISSUE THREAD

**Issue by harasei16** [NetCommons3/NetCommons3#1628]
登録フォームでどう設定しても登録者にも管理者等にもメールが送られませんでした．
エラーログには下記のような出力があります．

> 2021-03-07` 04:29:54 Error: syntax error, unexpected ':', expecting ';' or '{' in [/home/*******************/public_html/NC3/app/Plugin/Mails/Utility/NetCommonsMail.php, line 430]

ログの示しているNetCommonsMail.phpの該当部分ソースは下記のとおりです．

`private` function __getReceivableEmailsFromUser($user) : array {

下記のように修正して戻り値のタイプヒンティングである : array を削除するとメールが送られるようになりました．

`private` function __getReceivableEmailsFromUser($user) {

メール送信するアドレスが無く，戻り値がnullの場合にarrayと型が合わずエラーが発生するのではないかと思いました．
（エラーの種類がSystax errorである理由とは合致しないのですが．．．）

#1596，#1580 の問題もこれが関係しているのではないかと思います．

**Comment by RyujiAMANO** [comment]
もしかしてexec関数でphpをコマンドライン実行するとphp5系が動く環境でしょうか？
PHP5だと返り値のスカラ型は有効じゃないので `:array` の宣言あるとSyntax errorになりそうです。

以前XserverでCLIだけPHP5が動くってことがありました。参考 https://qiita.com/RyujiAMANO/items/f6923ed49145591c90ef

**Comment by harasei16** [comment]
> 以前XserverでCLIだけPHP5が動くってことがありました。参考 https://qiita.com/RyujiAMANO/items/f6923ed49145591c90ef

まさにXServerです！

参考リンクのとおりapp/Console/cakeを修正したら，
 先ほど私が書いたNetCommonsMail.phpの`: array`をもとに戻してもメールが送られるようになりました．

以前にNetCommons3をインストールしたときにapp/Console/cakeを修正した覚えがあるのですが，
3.3.3にアップデートしたときに修正前の状態に戻ったかもしれません．
