### ISSUE TITLE
メール送信Shellが排他処理となっていないため、同じメールが何度も配信処理される可能性がある

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1651]
ブログ・掲示板の記事投稿や、アンケート・登録フォームの回答などの処理において、「メール通知する」設定がなされている場合、当該データ保存時にメールキューテーブルに送信するためのメールデータが同時に保存される仕組みになっている。

同時にメール送信Shellが起動され、Shellはメールキューテーブルに保存されているメール送信データを読み取って、メール送信する。
このとき、Shellはメールキューテーブルにテーブルロックをかけることで排他制御をしようとしているようだが、トランザクションで挟んでいないため、ロックがかかっていない。
[https://github.com/NetCommons3/Mails/blob/master/Console/Command/MailSendShell.php#L109-L122](https://github.com/NetCommons3/Mails/blob/3.3.4.0/Console/Command/MailSendShell.php#L109-L122)

大量の同時アクセスなどでサーバーの処理が重くなり、かつ、登録フォームの回答が同時に大量発生した場合、
この状態では送信Shellが同時に複数起動され、ロックがないため同時に同じレコードの処理をしてしまう。
結果、同じメールが大量に配信される事象につながる。

メール送信Shellが複数起動されたとしても、同じレコードデータを処理しないようにする工夫が必要です。

**Comment by s-nakajima** [comment]
本件、調査して、修正しました。

調査したところ、現行のメール送信の作りが、
1. メールキューテーブルに存在するレコードが全てメール送信する対象になっている。
2. メールキューテーブルのレコードの削除タイミングが、対象の記事に対して全てのユーザへのメール送信が終了した後にレコードを削除する。

> このとき、Shellはメールキューテーブルにテーブルロックをかけることで排他制御をしようとしているようだが、トランザクションで挟んでいないため、ロックがかかっていない。
https://github.com/NetCommons3/Mails/blob/3.3.4.0/Console/Command/MailSendShell.php#L109-L122

`SELECT ~ FOR UPDATE`を実行している間は、ロックはかかっています。また、他の処理でメールキューテーブルに対してトランザクションを発行している最中も`SELECT ~ FOR UPDATE`ではトランザクションが終了するまで待機しています。
ただし、`SELECT ~ FOR UPDATE`の実行中のみ排他制御になっているだけで、メール送信実行中は排他制御されておらず、大量のメールを送信中に割り込みがあると、対象レコードがメールキューテーブルに残っているため、メール送信の対象になってしまい、結果、同じメールが複数送信されてしまっていました。

再現方法は、下記に`sleep(30);`を追加した後、
https://github.com/NetCommons3/Mails/blob/3.3.4.0/Console/Command/MailSendShell.php#L130
1. ブログの記事を投稿する。
2. 30秒以内に登録フォームに投稿する。

そうすることで、再現可能です。

メールキューテーブルの有無でメール送信する対象か否かを判断しているため、今回のような重複してメール送信されてしまう現象が発生しています。
ですので、別途カラムを設け、メール送信処理中のキューは対象から外すように改修しました。

今回、カラムを追加したため下記のMigrationを実行してください。
````
cake Migrations.migration run all -c master -i master -p Mails
````
