### ISSUE TITLE
登録フォームのフォーム投稿の通知をルーム管理には通知せずに本人のみに設定できるようにしてほしい。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#1669]
最近、個人情報の扱いがうるさくなってきたので、あまりメールで数百数千の情報を受け取りたくないという要望があるそうです。そのため、ルーム管理者にも投稿メールは送らず、CSVだけでフォームの投稿を管理し、本人には登録時の注意事項等を必ず送信する運用ができるようにしてほしいとのことです。

**Comment by s-nakajima** [comment]
修正方法としては、下図の「通知を受け取る権限」から「ルーム管理者」が外せるようにする。
![2021-10-15](https://user-images.githubusercontent.com/4422735/137619365-ec68655b-a2c3-49c0-ad11-a6fbb31427e9.png)

3.3.4をご利用の方は、下記のSQLを実行すると、ソースを最新にせずに設定できるようになります。
※チェックボックスが若干おかしくなりますが、支障はありません。
````
UPDATE `(テーブルPrefix)default_role_permissions` SET `fixed` = '0'
 WHERE `role_key` = 'room_administrator' AND `permission` = 'mail_answer_receivable'; 
````

2021/10/18以降にgithubからソースを最新にした方は、下記のMigrationを実行してください。
````
cake Migrations.migration run all -c master -i master -p Roles
````

また、アンケートも同様にルーム管理者への通知有無の設定ができるようになります。

**Comment by suga45** [comment]
ありがとうございます。上記のクエリを実行して、「ルーム管理者」の☑を外すことができました。

1点気になったことですが、「ルーム管理者」だけに☑を入れることはできないが、「編集長」にだけなら☑を入れることは可能という挙動で合っていますでしょうか。
![image](https://user-images.githubusercontent.com/13383157/137948926-6ecb395d-2f3c-46de-95c2-d1c94cdbd634.png)

**Comment by s-nakajima** [comment]
その現象は、githubの最新ソースで既に修正済みです。
https://github.com/NetCommons3/Blocks/commit/f427d0235b3960206e5ed01e9443e7a110a78e38

最新のソースに入れ替えるか、チェックを外した後、下記のクエリを実行して、元に戻してください。
````
UPDATE `(テーブルPrefix)default_role_permissions` SET `fixed` = '1'
 WHERE `role_key` = 'room_administrator' AND `permission` = 'mail_answer_receivable'; 
````
元に戻しても、先に変更した設定は維持されます。
よろしくお願いします。

**Comment by suga45** [comment]
ご回答いただき、ありがとうございました。
