### ISSUE TITLE
saltが同じサイトで無条件ログイン

### ISSUE THREAD

**Issue by kayokof** [NetCommons3/NetCommons3#1682]
全く同じレイアウトで複数のサイトを構築したかったので、「サイトA」にインストールしたNetCommons3を雛形としてバックアップを取り、「サイトB」「サイトC」にリストアして運用していました。
問題なく使えていたのですが、「サイトA」にログインした状態で「サイトB」を別タブで開くと、同じ権限のユーザでログインした状態で「サイトB」が開くことがわかりました。
複製を作る際に、「app/Config/application.yml」の「salt」を雛形の文字列で書き換えているので、「salt」はA、B、C、全て同じ文字列が書かれていますが、これが原因でしょうか。
「サイトA」にログインした状態で「サイトB」を別タブで開いてもログインしていない状態で「サイトB」に接続させたいのですが、対処方法はありませんでしょうか。
これでは無条件に他サイトにログインできることになってしまいますので、大変困っております。

Ubuntu 20.04.2 LTS
NetCommmons 3.3.3
PHP 7.4.3
mysql 8.0.28

IE 11、chrome 97、で発生します。

何か方法がありましたら、ぜひともご教示いただきたいです。
よろしくお願いします。

**Comment by yuichiro53** [comment]
NetCommonsサーバのドメイン変更目的で、以下のページを参考にバックアップし、バックアップファイル内のドメインを書き換え、新ドメインのサーバでリストアしたら、旧ドメインのIDとPWでログインは出来るのですが、各種リンクが切れてしまいました。そこで、app/Configのみバックアップ対象外として同様の作業を行ったところ、旧ドメインのIDとPWでログインできなくなりましたが、パスワード再発行手続きを行うことで、旧ドメインと同様に利用できています。
以上をふまえ、「app/Configをバックアップしない」ことで解決できそうですが、いかがでしょうか。
https://github.com/NetCommons3/NetCommons3/wiki/%E3%83%90%E3%83%83%E3%82%AF%E3%82%A2%E3%83%83%E3%83%97%E3%83%BB%E3%83%AA%E3%82%B9%E3%83%88%E3%82%A2%E6%96%B9%E6%B3%95%E6%96%B9%E6%B3%95

**Comment by kayokof** [comment]
yuichiro53様

アドバイスをありがとうございます。
こんなに時間が経過してしまい、大変失礼いたしました。

ご教示いただきました方法ですが、サイトの運用がすでに始まっていましたので
NetCommon3内に会員が登録されており、各会員に再登録をお願いできない状況でしたので実施できませんでした。
テスト用に環境を構築した際には、試してみたいと思います。
本当にありがとうございました。

結果的に、以下の方法で解決しました。
-(引用)------------------------------------------
app/Config/core.php 219行目あたりの下記の記述の

    Configure::write('Session', array(
        'defaults' => 'php'
    ));

ここにcookieの記述を追加して下記のようにします

    Configure::write('Session', array(
        'cookie' => 'site2',
        'defaults' => 'php'
    ));

これでcookie名変更してログインも可能な状態になると思います
-(ここまで)-------------------------------------------
Qiitaで@RyujiAMANO様に助けていただきました。
https://qiita.com/RyujiAMANO/items/68a883c503115772c5b1

ユーザディレクトリ毎にNetCommonsをインストールして、そのレイアウトを統一したサイトを構築したかったので、ひな形をどんどんコピーして増やしていったのですが、そのせいでsaltが同値「A]と「B」のサイトをブラウザで開いた状態で「A]にログインすると「B」にも自動的にログインした状態になる、という困ったことになっていました。

おかげ様で現在は順調に利用できております。
本当に助かりました。
ありがとうございました。
