### ISSUE TITLE
表示設定画面の「特定のルームの特定のブロックを表示する」が　何を選択していてもリストの一番上のブロックが選択された状態で表示される

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#1689]
このため、本来ならリストの2番目、3番目を選択していても、
再設定で開いて、何も考えずに決定すると意図せず対象ブロックが変わってしまいます。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1671
