### ISSUE TITLE
編集するとアンケート方式の「繰り返しの回答をさせる」のチェックが外れてしまう。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#169]

**Comment by RikaFujiwara** [comment]
新規作成で３手順目の「アンケートの設定」画面へいって、決定せずに前の画面へ戻ったらときに発生。
画面データ設定中にPOSTではなくリンク遷移なので画面編集データが失われた。
この問題に対処するには、この作成フロー処理を見直す必要がある
どうしようか悩み中です

以下のいずれかの方法を取らなくてはならないはず。
１．前の画面にもどるときもとりあえずPOSTさせて情報を失わないようにする
　メリット：編集中データは失われない
　デメリット：POSTということは必ずValidate走ってしまうので、ちょっと戻りたい、だけなのにいちいち正確な設定を求められて面倒くさい（もしかしたら取りやめたいのかもしれないのに

２．リンククリック時には「今戻ると、この編集中データが失われますがよいですか？保存をしておきたい場合は「一時保存してください」」の確認を求めてから戻るようにする
　メリット：とりあえず戻りたい、は満足される。失うかもしれないことについて認識させることもできる
　デメリット：それでも編集中データを失うこと二変わりはない

３．画面の３段階に分けてのステップをやめて、POSTは一回にする。３画面はJavascriptで画面切り替えをするイメージに大改造する
　メリット：データを失うことはない
　デメリット：画面処理が複雑化する。。。。POSTでエラーがあったとき、どこの画面を表示させてやるのか。。。。

４．１の亜種。POSTはするが、「戻る」系のPOSTのときはValidate,書き込みを通さないようにする
メリット：１の良いところ＋１の問題は解決する
デメリット：いま、POSTのときにはセッションにアンケートデータを保持している。そのセッションデータはValidateがすんだ保証された値だと信じて処理が行われるようになっているが、これを導入するとセッションデータは汚れたデータの可能性がでてくる。。。。

**Comment by RikaFujiwara** [comment]
「繰り返し回答」のチェックボックスはなくなったので自動的にこの問題はCloseとなります。
