### ISSUE TITLE
承認OFFにして、一般で投稿すると、未承認になる

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#170]
承認OFFでも一般なので、`Current::permission('content_publishable')`がなく、未承認で投稿していました。
https://github.com/NetCommons3/Workflow/blob/cdd05e50120bb486fbc08b308e4fc147be3ba0d8/View/Helper/WorkflowHelper.php#L146

承認OFFなら、一般にも`Current::permission('content_publishable')`がつくのか、
それとも、上記で承認ON,OFFを判定して処理のわければいいのかは、わからずでした。

とりあえずタグは`zz Workflow`で投げて、ご報告まで。

**Comment by akagane99** [comment]
解消していることを確認しました。クローズします。

**Comment by RyujiAMANO** [comment]
権限設定画面を一度も保存してないと発生するので再オープンします。
