### ISSUE TITLE
Submit時のdisabled制御

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#176]
PhotoAlbumプラグインで、写真の承認ボタンを実装した際に気づきました。

ContentCommentプラグインの承認ボタンを参考に実装したのですが、
ボタンのdisabled処理が入ってなかったです。

他にもあるかもなので、wikiに書いときました。
https://github.com/NetCommons3/NetCommons3/wiki/連続Submitの制御

**Comment by akagane99** [comment]
おっ！？知らなかった& 気づいてませんでした。
ありがとうです。コンテンツコメント、対応します。

**Comment by akagane99** [comment]
コンテンツコメント対応しました。

**Comment by akagane99** [comment]
NetCommonsFormHelperのbutton function、独自のなかったので
いっそ`NetCommonsForm->button`使ったら`'ng-class' => '{disabled: sending}'`つけてもいいかも。

https://github.com/NetCommons3/NetCommons/blob/master/View/Helper/NetCommonsFormHelper.php

**Comment by s-nakajima** [comment]
ButtonHelperで対応したため、Close
