### ISSUE TITLE
UIの統一

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#177]
どこかのタイミングで、UIを統一する作業を行う。

・キャンセルの×アイコン
・「○○」ボタンに、「○○する」という動詞があったりなかったり
・登録後の戻り先
・glyphicon の統一

などなど

**Comment by s-nakajima** [comment]
既に統一できてるはずなので、いったんCloseする。統一されていないのは、別途Issueに挙げるようにする。
