### ISSUE TITLE
タイトルアイコン？でJavascriptエラー

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#178]
発生個所は、ブログの記事登録画面で発生。おそらくタイトルアイコンのエラーだと思います。
下記、コンソールログの内容

"NetworkError: 403 Forbidden - http://127.0.0.1:9090/blogs/blog_entries_edit/add/%7B%7Bicon.path%7D%7D"

**Comment by RyujiAMANO** [comment]
同様のURL（　http://127.0.0.1:9090/questionnaires/questionnaire_edit/edit/11/cb3ca31655e2658c59ab25da35dd6cf2/%7B%7Bicon.path%7D%7D ）にアンケートでもアクセスしてるようなのですが、アンケートだとこのURLが普通にレスポンス返すのでエラーにならないで問題が表面化しないでいるようです。

BLOGだとパラメータがおかしいってことで403になっちゃってエラーに出てるのだと思われます。

たぶん意図してないimgタグTitleIconヘルパで出力されてるんじゃないかなとおもいます。
