### ISSUE TITLE
コンテンツコメントの承認機能

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#184]
コンテンツコメントの承認機能で、
コメント一覧を表示中に、書き換えられた場合、承認すると書き換えられた内容が公開されてしまいます。

具体的には、
１．一般が「AAA」とコメント投稿
２．管理者がコメント一覧を表示（「AAA」が表示されている）
３．一般が「AAA」→「BBB」に変更
４．管理者が表示されている「AAA」を承認する
５．「BBB」が公開される。

承認する処理に表示している内容もPOSTすれば良い気がしています。
テストケースも追加しときたいです。

**Comment by akagane99** [comment]
ご指摘感謝！
週末テストで対応＆テスト追加したいと思います。
