### ISSUE TITLE
gjslintの文字数制限について意見ください

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#185]
みなさん、意見聞かせてください。
昨晩、馬嶋さんのほうからgjslintの文字数を120文字にしてほしいという要望が出ました。
特にアンケートは、プラグイン名が長いのでさすがに80文字はきついという話だったので、
文字数を増やそうと思います。
その際、どのくらいが妥当なのか、皆さんの意見を聞かせてください。
もしくは、指針みたいのあったら、教えてほしいです。

ちなみに、最近私は、プログラムを書くとき、80～100文字を意識して書くようにしています。
超えたとしても、110文字ぐらいにするように心がけています。
このぐらいに収めておくと、どのパソコン、エディタでも大半が横スクロールなしでコードが読めます。

なので、gjslintを文字数を増やすなら、100文字ぐらいが妥当かなって思います。

みなさんは、どうでしょうか。

※文字数制限を変更するオプション --max_line_length
例） gjslint --max_line_length 120

**Comment by RyujiAMANO** [comment]
私は普段だと意識しないでダラダラ長く書きがちな人です。
で、あらためてどのぐらいがいいか考えてみると

・PHPStormでコーディングしてるときは1行120ぐらいは収まるのでOK
・diffったりGithubのプルリクでdiffみるときに80超えると折り返し発生するんでちと見づらくなる（けど100ぐらいまでは目GREPしてても許容できそうな感じ）

で経験的には何か問題が起きてバグの根本原因さがしたりするときって過去のバージョンとDiffったりすることが多いので並べてみるときの見やすさ考えると80はいいかなって思います。
（ならPHPコードもそうしろって話ですが…）

現状JSはテストコード無しってのもあるんで、制約きつめでもいいのかなとも思います。

**Comment by RyujiAMANO** [comment]
あと、80から100とかにしたら、次は120、その次は140って、徐々に大きくなりそうな気もして、拡大するのに積極的な理由を見いだせないってもあるかも(^^;

**Comment by s-nakajima** [comment]
なるほど。JSはテストコード無しってことで、制約きつめって考え方ありますね。
ほかの人はどうでしょう？

補足、制約を外すってのは無しで。。。プログラマーは、制約なかったら、とことん一行で書くから、制約は付ける方向で。。

**Comment by RikaFujiwara** [comment]
１００文字に１票

厳しい制限の中で、自分が書いていてもっとも嫌だったのはデータ配列属性にアクセスするときに「ドット」で折り返さなきゃいけない場合でした。

```
クラス名.属性名 = クラス名.属性名　　　
```

こんな風に書きたいところを

```
クラス名.
属性名 =
クラス名.
属性名
```

って書かないと制限に引っかかっていたのです。
アンケートは変数名長いうえに、ページ、質問、選択肢の階層構造作っていますから,,,,
アンケート基準にすると話がややこしくなるのでひとまず置いて。

できるだけ、「ドット」折り返しを避けたい。

```
クラス名.属性名 = クラス名.属性名　
```

と書きたい。
せめて

```
クラス名.属性名 =
  クラス名.属性名
```

PHPで変数名は20文字以内って制限があります
AngularコードではPHPのデータ配列変数を内部に取り込んで処理することが多いです。

```
20文字.20文字 = 20文字.20文字
```

これで８５文字
前にインデント付くこと考えて100文字はいかがでしょうか。

なお、本音を言えば120文字派です.....

**Comment by s-nakajima** [comment]
藤原さん、意見、ありがとうございます。

他の人はどうですかね？？？

**Comment by akagane99** [comment]
~~120に1票。~~
最近はワイドモニターなどで画面の横幅ながくなって、見ずらくないと思うので。

php側はどうなってるのか気になって調べました。
cakephpのphpcsは1行の最大文字は無制限でした。
https://github.com/cakephp/cakephp-codesniffer/blob/master/CakePHP/ruleset.xml#L40-L42
おおらかですね。参考まで。

**Comment by akagane99** [comment]
gjslintの1行80文字制限。angular.js本体が守ってないデフォルト設定値ってどうなのよ？というのも気になりました。
デフォルト設定値の正当性が薄い気がしてます。

```
/var/www/app/app/webroot/components/angular/angular.js
　313行：122文字
　28800行：169文字
```

・・・しかし、JS書かないから、あんまりこだわりないです。
参考程度に。

**Comment by kteraguchi** [comment]
80かなぁ。

> あと、80から100とかにしたら、次は120、その次は140って、徐々に大きくなりそうな気もして

おっしゃる通りかと。

> アンケート基準にすると話がややこしくなる

のですが、現状アンケートを例に考えるのが良いかなと思います。

https://github.com/NetCommons3/Questionnaires/blob/e72ace85c02e33182f203e2e67449902f8892c08/webroot/js/questionnaires_edit_question.js#L226-L250
を例として、改行で文字数制御するのではなく、ローカル変数に置き換えてやる方が良いと思っています。
現状の

``` javascript
      /**
       * change DateTimePickerType
       *
       * @return {void}
       */
      $scope.changeDatetimepickerType = function(pIdx, qIdx) {
        var type = $scope.questionnaire.questionnairePage[pIdx].
            questionnaireQuestion[qIdx].questionTypeOption;
        var format;
        if (type == variables.TYPE_OPTION_DATE) {
          format = 'YYYY-MM-DD';
        } else if (type == variables.TYPE_OPTION_TIME) {
          format = 'HH:mm';
        } else if (type == variables.TYPE_OPTION_DATE_TIME) {
          format = 'YYYY-MM-DD HH:mm';
        }
        $scope.questionnaire.questionnairePage[pIdx].
            questionnaireQuestion[qIdx].min =
            $scope.getDateStr($scope.questionnaire.questionnairePage[pIdx].
                questionnaireQuestion[qIdx].min, format);
        $scope.questionnaire.questionnairePage[pIdx].
            questionnaireQuestion[qIdx].max =
            $scope.getDateStr($scope.questionnaire.questionnairePage[pIdx].
                questionnaireQuestion[qIdx].max, format);
      };
```

は、

``` javascript
      /**
       * change DateTimePickerType
       *
       * @return {void}
       */
      $scope.changeDatetimepickerType = function(pIdx, qIdx) {
        var pageKey = questionnairePage[pIdx];
        var questionKey = questionnaireQuestion[qIdx];
        var questionnairePage = $scope.questionnaire.pageKey;
        var type = questionnairePage.questionKey.questionTypeOption;
        var format;

        if (type == variables.TYPE_OPTION_DATE) {
          format = 'YYYY-MM-DD';
        } else if (type == variables.TYPE_OPTION_TIME) {
          format = 'HH:mm';
        } else if (type == variables.TYPE_OPTION_DATE_TIME) {
          format = 'YYYY-MM-DD HH:mm';
        }

        var minValue = questionnairePage.questionKey.min;
        var maxValue = questionnairePage.questionKey.max;
        minValue = $scope.getDateStr(minValue, format);
        maxValue = $scope.getDateStr(maxValue, format);
      };
```

な感じです。
だとすると、後者の方が分かりやすいと思って、80っす。

**Comment by s-nakajima** [comment]
> 現状JSはテストコード無しってのもあるんで、制約きつめでもいいのかなとも思います。

このこともあるので、個人的には、寺口さんに＋１です。
８０のままでも良いのかなって！！

**Comment by RikaFujiwara** [comment]
できる限りローカル変数への置き換えはやっておこうとは思っているのですが、そうはできない場面もあるのですよよよ。

```
            // テキスト、１行テキスト、日付け型は集計結果を出さない設定
            if (question.questionType == variables.TYPE_TEXT ||
                question.questionType == variables.TYPE_TEXT_AREA ||
                question.questionType == variables.TYPE_DATE_AND_TIME) {
              $scope.questionnaire.questionnairePage[pIdx].
                  questionnaireQuestion[qIdx].isResultDisplay =
                  variables.EXPRESSION_NOT_SHOW;
            }
            // この質問の中にエラーがあるか
            if (question.errorMessages) {
              $scope.questionnaire.questionnairePage[pIdx].
                  questionnaireQuestion[qIdx].hasError = true;
              $scope.questionnaire.questionnairePage[pIdx].
                  hasError = true;
            }
```

せめてこれらをこう書かせてほしいところです

```
            // テキスト、１行テキスト、日付け型は集計結果を出さない設定
            if (question.questionType == variables.TYPE_TEXT ||
                question.questionType == variables.TYPE_TEXT_AREA ||
                question.questionType == variables.TYPE_DATE_AND_TIME) {
              $scope.questionnaire.questionnairePage[pIdx].questionnaireQuestion[qIdx].isResultDisplay =
                  variables.EXPRESSION_NOT_SHOW;
            }
            // この質問の中にエラーがあるか
            if (question.errorMessages) {
              $scope.questionnaire.questionnairePage[pIdx].questionnaireQuestion[qIdx].hasError = true;
              $scope.questionnaire.questionnairePage[pIdx].hasError = true;
            }
```

あ、いかん。これでは105文字だ

**Comment by RikaFujiwara** [comment]
上記かいてみて、GitHubの閲覧が１００文字で横スクロールが出たのを見ました
１００文字未満にしておかないと。こういうやり取りもしづらいのかなぁ

**Comment by RyujiAMANO** [comment]
https://google.github.io/styleguide/javascriptguide.xml?showone=Code_formatting#Code_formatting
これみると80文字とはいってるけどナゼ80文字かはかいてないねぇ

**Comment by kteraguchi** [comment]
JavaScriptのオブジェクトは参照渡しなので、

``` javascript
            // テキスト、１行テキスト、日付け型は集計結果を出さない設定
            if (question.questionType == variables.TYPE_TEXT ||
                question.questionType == variables.TYPE_TEXT_AREA ||
                question.questionType == variables.TYPE_DATE_AND_TIME) {
              question.isResultDisplay = variables.EXPRESSION_NOT_SHOW;
            }
            // この質問の中にエラーがあるか
            if (question.errorMessages) {
              question.hasError = true;
            }
```

で行けると思います。

<br>

> ナゼ80文字かはかいてないねぇ

そうなんですよ。。。。
昔からの伝統ですかね。
http://programmers.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width#answer-148678

**Comment by RikaFujiwara** [comment]
> JavaScriptのオブジェクトは参照渡しなので、

およよ失礼いたしました......お恥ずかしい

**Comment by RyujiAMANO** [comment]
http://book.cakephp.org/3.0/en/contributing/cakephp-coding-conventions.html#line-length
PHPも制限しなきゃダメ？(^^;
こっちの規約は120はゼッタイダメで100推奨みたい

**Comment by Saway** [comment]
120に１票
80の制限って、まだ画面に緑色しか映せないテレビの時代の制限ですよね。
（COBOLディスるとあれなので・・）
今はワイドだし、変数名だってわかりやすければ長い変数名でもかまわない風潮なのだから
８０縛りで縦書きにするほうが可読性が下がるのではないかと思います。

**Comment by s-nakajima** [comment]
こんな統計とってる記事があった。
http://q.hatena.ne.jp/1206356740

昔は80みたいだけど、今は100？

**Comment by Saway** [comment]
その統計からも、まさに
100 characters is the soft limit.
120 characters is the hard limit.
がちょうどいいくらいですね。

**Comment by akagane99** [comment]
> ナゼ80文字かはかいてないねぇ

C++ formatting rules のリンク先の下に「Line Length」ありました。こっちも80文字でした。
https://google.github.io/styleguide/cppguide.html#Formatting

なんか、そのまま持ってきた感が。。。

100に1票に訂正

cakephp3的にはphpcsでは制限かけないけど、100「推奨」。
規約でうたってみたものの、cakephp3のコアで160文字でオーバーしちゃった。という感じなのだろうか。
https://github.com/cakephp/cakephp/blob/master/src/Controller/Controller.php#L232

なんだそのノリ、よくわからん。

**Comment by s-nakajima** [comment]
皆さん、多数意見ありがとうございます。
どの記事みても、決定的な回答ないみたいですね。

NetCommonsとしてのJSコードの規約として、何文字にするか、最終的な決取りましょう。

１．80文字
２．90文字
３．100文字
４．110文字
５．120文字

ちなみにPHPは、CakePHPは100文字推奨となっているので、100文字にします。
時間見て、100文字制約入れます。

**Comment by s-nakajima** [comment]
１に一票

**Comment by RyujiAMANO** [comment]
phpもJSも100文字に＋1

**Comment by akagane99** [comment]
phpもJSも100文字に＋1

**Comment by kteraguchi** [comment]
色々聞いて変えます。
phpもJSも100文字に＋1

**Comment by Saway** [comment]
Cakeに倣い phpcsの制限は5　推奨は３

**Comment by otokomae** [comment]
php, js ともに 100文字に１票でおねがいします。

**Comment by s-nakajima** [comment]
橋本さん、藤原さんの回答待とうかと思っていたけど、多数決でphp, js ともに 100文字ですね。

では、php, js ともに 100文字とします。
JSの方だけは、今日中に100に上げておきます。
PHPの方は、後日対応します。100にしたら、お知らせしますね。

みなさん、ありがとうございました。
