### ISSUE TITLE
メール送信が有効になっているかどうかの判定メソッドがほしい。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#191]
会員登録後の通知処理でキューに登録せずに呼ぶことになる。そのため、メールが送れない場合、画面制御が必要になる。

**Comment by akagane99** [comment]
`IsMailSendBehavior::isMailSend()`があるけど、これは使えないだろうか？
https://github.com/NetCommons3/Mails/blob/77dbd0d9a75f4813fb28be67476bb5556cb758fc/Model/Behavior/IsMailSendBehavior.php#L54

`MailQueueBehavior`を使っていれば、`IsMailSendBehavior`を動的loadしてます。
テストがまだなので、バグってたらごめんなさい。

**Comment by s-nakajima** [comment]
詳しくは見てないけど、この部分だけがやりたい。
会員からの通知は、投稿には関係ないから、他のところを通す必要もないし。

https://github.com/NetCommons3/Mails/blob/77dbd0d9a75f4813fb28be67476bb5556cb758fc/Model/Behavior/IsMailSendBehavior.php#L59-L61

**Comment by akagane99** [comment]
isMailSendCommon() publicにしました。
