### ISSUE TITLE
認証キーが空だったら認証キーレコードを追加しないで欲しい

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#197]
現状だと認証キーが空でもレコードが作成される

そのためCabinetsでは認証キー使わないデータでも全てダウンロードパスワード入力を求められてしまいます。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/AuthorizationKeys/commit/81af61212cdf0ff63289fbb374ab4e372fccbf59
