### ISSUE TITLE
動画一覧でサムネイルの横・縦サイズが固定されている。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#204]
動画一覧でサムネイルの横・縦サイズが固定されている。
https://github.com/NetCommons3/Videos/blob/master/View/Videos/index.ctp#L120
そのため、縦長の画像をアップすると、つぶれた感じで表示されてしまう。あと、style属性で直接書いているけど、class属性で定義してください。

（元の画像）
![KN011.png](https://zube.io/files/NetCommons3/e3cc417ddc9f5af540f5fea133802ad0.png)

（サムネイル表示）
![image](https://zube.io/files/NetCommons3/1183ebab906cb015f8de15e3cc2286d8.png)

Bootstrapのimagesを使って表示すると、良い感じでつぶれないで表示されます。
http://getbootstrap.com/css/#images

**Comment by akagane99** [comment]
画像つぶれ対応済み。

>  あと、style属性で直接書いているけど、class属性で定義してください。

対応しようと思うんだけど、
この決めって、どの規約か資料に書いてあるんだっけ？

**Comment by akagane99** [comment]
規約とかはなさそう。
外部ファイル化した方がcssのオーバーライトなど、扱いやすい。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Videos/commit/c823923367f3c4fea4b51182337159da741c8428
対応済みクローズ
