### ISSUE TITLE
WorkflowHelper::buttonsのキャンセル処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#212]
PhotoAlbumの写真追加画面はモーダルです。
WorkflowHelper::buttonsで、キャンセルのリンク先を指定しているのですが、
アドレスバーのURLと同じため、リンクされません。

とりあえず、ランダムのパラメータつけて、無理やりリンクさせてます。
たぶん、キャビネットも同様かと思います。

https://github.com/NetCommons3/PhotoAlbums/blob/d5811147cb6186ec9f30868ca2b65566f349c582/View/PhotoAlbumPhotos/edit.ctp#L63-L64

**Comment by s-nakajima** [comment]
試そうと思ったら、エラーになってアルバムが登録できません。

![image](https://cloud.githubusercontent.com/assets/4422735/15418055/15ffbe7a-1e97-11e6-829c-228a28cc4ab8.png)

たぶんですが、第二引数を””もしくは"#"。第三引数にarray('ng-click' => 'cancel()')で閉じないでしょうか。

**Comment by RyujiAMANO** [comment]
第2引数はcancelUrlでcancelボタンのoptionsを渡す方法はありませんでした

**Comment by RyujiAMANO** [comment]
キャンセルで閉じられるようなのでCabinets外します

**Comment by s-nakajima** [comment]
Buttonヘルパーで対応しました。Buttonヘルパーを使っていれば、閉じられるようになりました。フォトアルバムも確認お願いします。

**Comment by s-nakajima** [comment]
フォトアルバム確認したのでClose
