### ISSUE TITLE
無駄なHelperの定義がある

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#221]
'NetCommons.Token'の定義がありますが、Ajaxを使う画面以外は不要です。
使っていなければ削除してください。

不要例）
https://github.com/NetCommons3/CircularNotices/blob/master/Controller/CircularNoticeFrameSettingsController.php#L63

**Comment by RyujiAMANO** [comment]
Cabinets対応済み

**Comment by RyujiAMANO** [comment]
Blogsも対応済み

**Comment by go-to** [comment]
CircularNotices対応済み

**Comment by RikaFujiwara** [comment]
AuthorizationKeysはNetCommons.Tokenのヘルパーは組み込んでいませんでした

**Comment by RikaFujiwara** [comment]
画像認証も対応しました。
Closeします。

**Comment by RikaFujiwara** [comment]
すみません　完了ラベルだけでCloseはしてはいけませんでしたね。失礼しました。
