### ISSUE TITLE
メール設定で、ヘルプブロックで説明書きがあるが、未来送信関係ないものにも未来の説明が表示される

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#223]
メール設定で、ヘルプブロックで説明書きがあるが、未来送信関係ないものにも未来の説明が表示されてしまいます。消すことはできませんか？

![image](https://zube.io/files/NetCommons3/aeea66adce507e6e0d6b1d3478398ea2.png)

**Comment by akagane99** [comment]
対応してみます

**Comment by akagane99** [comment]
デフォルト非表示にしました。

表示する場合は、サンプル参照です
http://netcommons3.github.io/NetCommons3Docs/phpdoc/Mails/classes/MailFormHelper.html#method_editFrom
