### ISSUE TITLE
メールのキュー登録処理のチェックがおかしい？？？

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#224]
https://github.com/NetCommons3/Mails/blob/master/Model/Behavior/MailQueueBehavior.php#L620

isSendMailQueueNotice()で投稿したユーザのチェックを行っているようなので、
作成者（created_user）としていますが、これは、更新者（modified_user）で処理させなければダメじゃないでしょうか。

例えば、最初にルーム管理者（公開権限あり）が投稿⇒その後、編集者（公開権限なし）の人が記事を修正したら、メール飛ばない気がします。

仕様の確認お願いします。

**Comment by akagane99** [comment]
> 作成者（created_user）としていますが、これは、更新者（modified_user）で処理させなければダメじゃないでしょうか。

作成者に飛ばさないと、
１．一般が投稿。未承認の記事
２．管理者が承認、承認完了メール、飛ばせない

これかできないな。
うーん。

> 例えば、最初にルーム管理者（公開権限あり）が投稿⇒その後、編集者（公開権限なし）の人が記事を修正したら、メール飛ばない気がします。

おおう。メール飛ばないな。（汗）
対応考えてみるは。

(1). 最初にルーム管理者（公開権限あり）が投稿
(2). その後、編集者（公開権限なし）の人が記事を修正

公開された他人の記事(1)を、公開権限ない編集者が修正(2)
