### ISSUE TITLE
メール形式をテキストプレーンにした場合、strip_tagsした方が良いのでは？

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#229]
メール形式をテキストプレーンにした場合、htmlspecialcharsしているが、strip_tagsの方が良いと思います。たしか、NC2では、strip_tagsしていたような気がします。

NC2を確認したうえで、検討お願いします。

**Comment by akagane99** [comment]
NC2でstrip_tagsしてた。
失礼、対応します。
