### ISSUE TITLE
いくつか、不要なタグや間違った使い方しているものがあります。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#233]
いくつか、不要なタグや間違った使い方してて、気になったので挙げておきます。
- Gridにする必要ない気がします。
  https://github.com/NetCommons3/Videos/blob/master/View/Videos/index.ctp#L24
- Gridのrowを付ける必要ないと思います。
  https://github.com/NetCommons3/Videos/blob/master/View/Videos/index.ctp#L103
- 不要と思われる&amp;nbsp;があります。
  https://github.com/NetCommons3/Videos/blob/master/View/Videos/view.ctp#L139
- 不要と思われる、clearfixのdivがあります。
  https://github.com/NetCommons3/Videos/blob/master/View/Videos/view.ctp#L143
- h関数を付ける必要あります。
  https://github.com/NetCommons3/Videos/blob/master/View/Videos/view.ctp#L162
- Gridの使い方間違ってます。class="row"のすぐ下に、class="col-xs-○○"のタグがくる必要あります。
  https://github.com/NetCommons3/Videos/blob/master/View/Videos/view.ctp#L185-L189

**Comment by akagane99** [comment]
なんだか、コードレビューしてもらってるみたいで、ありがたい。
掲示板やブログを参考にした箇所もあるので、もくもくで確認させてください。

**Comment by akagane99** [comment]
> - Gridにする必要ない気がします。
>   https://github.com/NetCommons3/Videos/blob/master/View/Videos/index.ctp#L24

ここ、BBS,blogを参考にしたけど、
BBS,blogも間違っている。という事なんだろうか？
これで正解のようにも思えるので、話聞かせてください。

https://github.com/NetCommons3/Bbses/blob/8de200a61b6936450dbdea9b508a7645f1bdc2e1/View/BbsArticles/index.ctp#L19
https://github.com/NetCommons3/Blogs/blob/6f05858c466a3ed07f823415a8991f15d7bb75e5/View/BlogEntries/index.ctp#L44

> - Gridのrowを付ける必要ないと思います。
>   https://github.com/NetCommons3/Videos/blob/master/View/Videos/index.ctp#L103

91行目の事かな？
修正しました。

https://github.com/NetCommons3/Videos/blob/d0bb59f89e35bc21f869176ac627af56169c02cc/View/Videos/index.ctp#L91

> - 不要と思われる&amp;nbsp;があります。
>   https://github.com/NetCommons3/Videos/blob/master/View/Videos/view.ctp#L139
> - 不要と思われる、clearfixのdivがあります。
>   https://github.com/NetCommons3/Videos/blob/master/View/Videos/view.ctp#L143
> - h関数を付ける必要あります。
>   https://github.com/NetCommons3/Videos/blob/master/View/Videos/view.ctp#L162
> - Gridの使い方間違ってます。class="row"のすぐ下に、class="col-xs-○○"のタグがくる必要あります。
>   https://github.com/NetCommons3/Videos/blob/master/View/Videos/view.ctp#L185-L189

ほんとだ！修正しました。

**Comment by akagane99** [comment]
> - Gridにする必要ない気がします。
>   https://github.com/NetCommons3/Videos/blob/master/View/Videos/index.ctp#L24

すでに修正済みだった。
