### ISSUE TITLE
Currentクラスで不要プロパティ

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#234]
https://github.com/NetCommons3/NetCommons/blob/63bbac419957dc2188d28f3c19e8cd4b51b85da7/Utility/Current.php#L396-L398

$_instanceプロパティは使われてないと思われます。

あと、
https://github.com/s-nakajima/NetCommons/commit/c01e9c6cbee03d39d5cca0f1c3da020b9ebb76ef

で、CurrentBaseクラスが追加されてますが、何かあったのでしょうか？
Currentクラスのままでよかったように思います。

**Comment by s-nakajima** [comment]
phpmdで怒られました。そのため、分割しました。

**Comment by kteraguchi** [comment]
> phpmd

おぉー。public method 12個ですなぁ。
了解です。
