### ISSUE TITLE
予定の追加のUIが他と異なる。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#244]
全体的にほかのプラグインと登録UIが異なります。とりあえず、気になるところを挙げておきます。
- form-horizontalが使われていますが、使わないでください。
  https://github.com/NetCommons3/Calendars/blob/master/View/Elements/CalendarPlans/edit_form_create.ctp#L14
- Bootstrapのgridを使うなら、rowとcolが対となるように使用してください。ただ、いくつか見ると、Gridを使わなくでも良いものが多々あります。見直しお願いします。
  https://github.com/NetCommons3/Calendars/blob/master/View/CalendarPlans/detail_edit.ctp#L52
- form-groupでmarginが取られているので、brは不要です。
  https://github.com/NetCommons3/Calendars/blob/master/View/CalendarPlans/detail_edit.ctp#L60

**Comment by to-hashimoto-3** [comment]
こちらは、５月のご指摘のあと、全般見直し修正をおこなったので、すでに対応済したと認識しております。
