### ISSUE TITLE
MailsプラグインでNoticeが出る。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#248]
詳しくは、追ってないのですが、RSSリーダの表示時、Mailsプラグイン関係でNoticeが出る。

Notice (8): Undefined index: key [APP/Plugin/Mails/Model/Behavior/MailQueueBehavior.php, line 382]

**Comment by akagane99** [comment]
- 多分、表示時でなくて、save時じゃないかな。（その箇所、afterSaveで使ってる箇所なので）
- RSSのテーブルにkeyフィールドないなら、keyFieldで設定できるよ。 https://github.com/NetCommons3/Questionnaires/blob/786d2cb3a5d534c6c7ce55dd162fe812d7514da4/Model/QuestionnaireAnswerSummary.php#L35

**Comment by akagane99** [comment]
聞いてた通り、軽井沢環境のRSSリーダー、何か定期的に動いてるみたい。
RSSを人間がさわってない時に、メール飛んできてました。
参考まで。

### メール - `[NetCommons3-RSSリーダー](パブリック)` 6/3 11:26 受信

```
RSSリーダーにリンクが追加されたのでお知らせします。
ルーム名: パブリック
RDF/RSSのURL:
RDF/RSSのサイト名:
RDF/RSSのサイトURL:
RDF/RSSのサイト説明:
登録者: ログインしていないユーザ
登録日時: 2016/06/03 11:26:33

この内容について確認するには、下記アドレスへ
http://xxxx/rss_readers/rss_readers/view/163?frame_id=21
```

### RSS - 更新日 6/1

![image](https://cloud.githubusercontent.com/assets/2756509/15767767/01af8dac-2986-11e6-9337-56b574644c4e.png)

**Comment by s-nakajima** [comment]
りょうかいです。そのあたりから、デバッグします。
とりあえず、皆さんに迷惑かけるので、OFFにしました。

**Comment by s-nakajima** [comment]
RSSリーダ側で対応したが、saveFieldで一部のフィールドを更新しただけで、メールが飛ぶのも良くないと思う。

**Comment by akagane99** [comment]
afterSaveでsaveFieldとsaveを区別する方法って、何かあるんだっけ？

**Comment by akagane99** [comment]
> afterSaveでsaveFieldとsaveを区別する方法って、何かあるんだっけ？

区別するにはdataの中身みればできるけど、ヤな感じのコードなるみたい。

なので、呼出元で'callback => false'で対処してもらう。
http://book.cakephp.org/2.0/ja/models/saving-your-data.html#model-savefield-string-fieldname-string-fieldvalue-validate-false
