### ISSUE TITLE
日表示による表示で真っ白になる。

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#252]
月拡大表示から、週をクリックし、週表示へ遷移し、そこから日をクリックすると
以下のようなURLとなり、画面が真っ白になってしまう。

calendars/calendars/index/style:weekly/year:2016/month:05/undefined

**Comment by to-hashimoto-3** [comment]
本件、対処済。
現在は、同様の操作を実施しても、問題なく日が表示されます。
