### ISSUE TITLE
予定の追加で公開対象プライベート時の不具合

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#253]
公開対象でプライベートを選択した場合、デフォルトで自分自身は参加した状態で
削除できないようにするべき。

現状、そのまま「決定」すると、何事もなかったかのようにおわるようだ。

**Comment by to-hashimoto-3** [comment]
プライベート予定は、仲間の共有に自分自身は入れないのが、仕様だと認識しております。
仲間の共有は、「仲間（他者）」と情報を共有したいときだけ、入れるのが普通モードだとおもう。
（ぷらベート予定は個人予定を入れることがもともと主眼で、仲間に自分をいれる、と明示する必要はないため。
ちなみに、現在は、自分を仲間にいれても・いれなくても、共有予定ＴＢＬには、自分は外す（strip)した状態で
登録するようになっており、それで全体をとおして辻褄あうように実装しております。

上記の内容で、ご理解いただければ、幸いです。
宜しくお願いします。
