### ISSUE TITLE
画像認証、認証キーのリダイレクト方式について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#26]
認証対象のアクションが呼ばれた際に、リファラーが認証用コントローラーでない場合、
認証後にリダイレクトされるURLをセッションに保持して、認証用コントローラーにリダイレクトしています。

んで、認証画面から認証用コントローラーにPOSTされ、OKの場合、セッションのURLにリダイレクトしています。

結果、コンポーネントの$returnUrlプロパティが使用されていない状態です。
削除しましょう。と思ったのですが、もうちょっとシンプルにいけないか考えてみました。

リクエストパラメーターに['AuthorizationKey']['authorization_key']がセットされていなければ認証用コントローラーにリダイレクト。
['AuthorizationKey']['authorization_key']がセットされていれば、OKか判断する（checkメソッド）。
OKの場合認証対象のアクションの処理に流す。
NGの場合認証用コントローラーにリダイレクト。

以上の処理でうまくいく気がしています。
ダメそうだったら、現処理で$returnUrlプロパティだけ削除しときましょう。

**Comment by kteraguchi** [comment]
CakePHPのAuthComponentがセッション使ってて同じやり方をしているっポイですね。
やり方は合わせといた方が良いと思うので、$returnUrlプロパティだけ削除しときましょう。

**Comment by RikaFujiwara** [comment]
AuthComponentも見ていただいてありがとうございます。そう、お察しのとおり、このプラグイン作る前にAuthComponent思い切り参考にしてます。
$returnUrlは削除の方向で了解です
