### ISSUE TITLE
一般画面に総件数不要

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#266]

**Comment by akagane99** [comment]
補足

ブロック一覧に総件数表示するなら、一般画面にはいらないね

だったかと思いました。
https://github.com/NetCommons3/NetCommons3/issues/262

**Comment by s-nakajima** [comment]
その後、全面的にブロック一覧に総件数を表示する方向になって、一般画面から総件数を消そうって方向になったかと思います。

**Comment by akagane99** [comment]
サンキュー、理解しました

**Comment by s-nakajima** [comment]
統一されたはずなので、Closeする。発見した際は新たにIssueに挙げる
