### ISSUE TITLE
上下の区切り線不要

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#270]

**Comment by s-nakajima** [comment]
コンテンツ間の区切り線はあった方が良いのですが、不要な理由を教えてください。
デザイナーの意見も聞きたいです。

**Comment by RyujiAMANO** [comment]
ブログでSNSボタン等を一切使わないで区切り線なしにすると下記のようになるんでわかりにくくないですかね？

![ブログ区切り線無し](https://dl.dropboxusercontent.com/u/102968/blog_no_line.png)

マージンしっかりあければOKってことかな？一覧でコンテンツ間のマージンってテーマとかで決まるようになんかのclass使うように統一したほうがいいかな

**Comment by s-nakajima** [comment]
統一した共通のclassを使う

**Comment by s-nakajima** [comment]
統一されたはずなので、Closeする。発見した際は新たにIssueに挙げる
