### ISSUE TITLE
checkboxBlockRolePermission関数呼び出し時のモデル名変数化

### ISSUE THREAD

**Issue by go-to** [NetCommons3/NetCommons3#279]
権限設定のチェックボックス表示のエレメントで、BlockRolePermissionFormヘルパーのcheckboxBlockRolePermission関数を呼び出す際に、モデル名がBlockRolePermissionで固定になっている（下記URL参照）が、変数化して汎用的にしてほしい。
※プラグインによっては、権限設定の設定項目を独自に追加したい場合があるため

https://github.com/NetCommons3/Blocks/blob/master/View/Elements/block_permission_setting.ctp#L54-L55

**Comment by s-nakajima** [comment]
用途を教えてください。

**Comment by go-to** [comment]
ToDoプラグインの初回提案時は、権限設定画面で「カテゴリの作成・編集権限」というのを設定できるようにする想定でした。
上記を実現するために、任意のモデル名を渡せるようにしてほしいと思ってIssueに挙げたのですが、その仕様は無くなったので、対応不要です。

**Comment by s-nakajima** [comment]
了解です。では、Closeします。
