### ISSUE TITLE
phpunitのカバレッジレポートについて（phpunit.xml.distファイルについて）

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#28]
phpunitのカバレッジを&lt;filter&gt;&lt;blacklist&gt;で除外しているのですが、
https://github.com/NetCommons3/Blogs/blob/master/phpunit.xml.dist
&lt;whitelist&gt;で除外しようと考えています。

それで、&lt;whitelist addUncoveredFilesFromWhitelist="true"&gt;
とすることで、一度もテストされていないファイルもカバレッジレポートのリストに上がるようになるみたいです。
https://phpunit.de/manual/current/ja/code-coverage-analysis.html#code-coverage-analysis.whitelisting-files
これで、テスト漏れも事前に発見できると思います。

実際のphpunit.xml.distファイルとしては、こんな感じになるのでシンプルになります。
https://github.com/NetCommons3/Announcements/blob/master/phpunit.xml.dist

これをNetCommonsのルールとして定めた方が良いと思ったのですが、どうでしょうか

**Comment by RyujiAMANO** [comment]
+1

**Comment by kteraguchi** [comment]
👍
そうしましょう。

**Comment by s-nakajima** [comment]
返信ありがとうございます。
りょうかいです。その方向で直します。
