### ISSUE TITLE
記事編集画面にてEnterでSubmitされてしまう。

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#290]
ブログに限った話ではないのかもしれないが、
テキスト中にカーソルがある状態でEnterを行うとSubmitされてしまう。

タグ追加では、Enter時にタグが追加されてほしい。

**Comment by s-nakajima** [comment]
タグは、ちょっと微妙。それ以外は、javascriptで制御した。
タグは、そもそもキーボードで選択できないところから見直した方が良いかも。

**Comment by RyujiAMANO** [comment]
Enterキーでタグ追加できるようにしたので、ここまでで一旦完了扱いにします。
根本見直しはまた別途に。
