### ISSUE TITLE
回覧板の各テーブルに不要なフィールドがある。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#291]
回覧板の各テーブルに'is_auto_translated'、'translation_engine'など、不要なフィールドがあります。
https://github.com/NetCommons3/CircularNotices/blob/master/Config/Migration/1432105496_initialize.php#L64-L65

この辺とかも不要かと・・・
https://github.com/NetCommons3/CircularNotices/blob/master/Config/Migration/1432105496_initialize.php#L96-L98

あと、全体的にxxxx_flagなどのフィールドは使わず、is_xxxxやuse_xxxxなどとすることになっていますので、修正お願いします。

**Comment by go-to** [comment]
修正完了。
