### ISSUE TITLE
RoomBehavior::getRoomsCondtionsのlimit制限

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#294]
削除予定？

https://github.com/NetCommons3/Rooms/blob/e0275bb743f1af837244cfe63cc006810e94c196/Model/Behavior/RoomBehavior.php#L66-L67

**Comment by s-nakajima** [comment]
ページネーションで使うことを想定して作ったが、ページネーション側に移動するように修正する
https://github.com/NetCommons3/Rooms/blob/e0275bb743f1af837244cfe63cc006810e94c196/Controller/Component/RoomsComponent.php#L94
