### ISSUE TITLE
UsersController::selectアクションの更新処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#295]
グループ作成時に呼ばれるユーザー選択アクションですが、
選択された回数を保持しています。（UsersControllerモデル）

グループに参加している数ではなく、選択された数で良い？

**Comment by s-nakajima** [comment]
はい。そうです。
グループ選択時に、会員を新たに選択する画面で良く選択している人順に表示するために使用しています。

**Comment by s-nakajima** [comment]
返信ないのでCloseします。
