### ISSUE TITLE
angularJSの依存性注入は配列アノテーション式に統一

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#299]
以前のIssueに挙がった件ですが、まだ、修正されていないプラグインがいくつかあります。
https://github.com/NetCommons3/NetCommons3/issues/118

**Comment by RyujiAMANO** [comment]
Registrations対応済みなのでラベル外しました

**Comment by go-to** [comment]
Groups, CircularNotices対応済み

**Comment by to-hashimoto-3** [comment]
Calendar対応済です。

**Comment by to-hashimoto-3** [comment]
Holidayすでに対応済です。

**Comment by to-hashimoto-3** [comment]
AuthorizationKeys, Questionnaires, Quizzesすでに対応済です。

**Comment by to-hashimoto-3** [comment]
すべてのpluginのラベルが外れたので、closeさせていただきます。
