### ISSUE TITLE
このIssueのラベル

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#3]
コア系機能実装等のチケットをあげたいのでIssueのラベル増やしたいです。

Inbox とりあえず書いただけ。まだ検討されてない。
検討中 どうするか結論はまだ。検討は開始されてる状態
実施予定 やることは決まってるけど、まだ未着手
作業中
完了

あたりが欲しいかなと。

**Comment by RyujiAMANO** [comment]
他に必用そうなの
・やらない　やらないと決めたこと
・一時保留　何かしらの理由で後で再検討が必用なコト。（3ヶ月に1回ぐらい見直し？）

**Comment by kteraguchi** [comment]
ドキュメントに追加しました。
https://github.com/NetCommons3/NetCommons3/wiki/301.Issuesの利用
Closeします。
