### ISSUE TITLE
UsersController::deleteアクションのBadRequest判断

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#306]
https://github.com/NetCommons3/Users/blob/2e5e08844e3923f6131e697d8837ad999e14dffd/Controller/UsersController.php#L199-L200

自分以外のユーザーを削除できない？？

あと、GETメソッドでも受け付ける？

**Comment by s-nakajima** [comment]
このアクションは、退会処理です。
あと、deleteのみです。
https://github.com/NetCommons3/Users/blob/master/Controller/UsersController.php#L206-L209

処理の順番変えた方が良いですか？

**Comment by s-nakajima** [comment]
返答ないので、このままとします。
