### ISSUE TITLE
回覧板のコードが古い仕様のプログラムで、CakePHPの流儀に沿っていない

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#310]
下記のように、camelizeKeyRecursiveを使っていて、CakePHPの流儀に沿っていない

https://github.com/NetCommons3/CircularNotices/blob/master/Controller/CircularNoticesController.php#L113
https://github.com/NetCommons3/CircularNotices/blob/master/Controller/CircularNoticesController.php#L212

**Comment by go-to** [comment]
camelizeKeyRecursiveを使用しないように修正しました。

https://github.com/NetCommons3/CircularNotices/commit/c730b8f287eaead4569b20c101e2bad8193f774c
