### ISSUE TITLE
メールデータ作成migrationのクラス名

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#313]
002_mail_setting_records.phpファイルのクラス名が、BbsMailSettingRecordsと、Bbsがついています。

お知らせだと、
https://github.com/NetCommons3/Announcements/blob/8a47173ca802f062d00a66b2a32ff45e1d6f9dda/Config/Migration/002_mail_setting_records.php#L18

ほかのプラグインもBbsMailSettingRecordsになっていると思われます。

**Comment by akagane99** [comment]
対応済みでしたので、クローズします。
