### ISSUE TITLE
TreeBehavior::recoverの呼び出し。

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#315]
Cabinetsプラグインで、TreeBehavior::recoverを呼び出し、ツリーデータ構造の再構築を行っています。
https://github.com/NetCommons3/Cabinets/blob/44d8702d4e187b751734e036622c26a92bab1e81/Controller/CabinetFilesController.php#L119

初期画面を表示するたびに、再構築処理が走るので、ファイルの保存処理で呼び出す方がよいかなと思っています。

また、Bbses、PagesプラグインはTreeBehavior::recoverを使用していないので、同様に記事の保存時に呼び出すのが良いと思っています。

そもそも、トランザクション処理があるので、ツリーデータ構造が異常になるケースってある？っつー感じですが、一応TreeBehavior::recoverの処理は、どこかに入れといた方が良いのかなぁと。

**Comment by RyujiAMANO** [comment]
別件で何かあって入れてたと思ったんですが、どうも私の思い違いだったようで別件のソースちゃんと確認したら使ってませんでした。
ってことで削除しときますー

**Comment by s-nakajima** [comment]
掲示板のみ登録時にrecover処理追加。ページはrecoverを入れると、moveUp、moveDownしたものが元に戻ってしまうため、対応しない。
