### ISSUE TITLE
回答メールを通知する権限を設定しても、一般にメールが飛んだ？

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#327]
~~メール対応時の考慮不足のバグでした。~~
### 現象

例えばアンケートのblock_role_permissions

　投稿メール：通知する権限（mail_content_receivable）
　~~回答メール：通知する権限（mail_content_receivable）~~
　回答メール：回答を通知する権限（mail_answer_receivable）

で登録すると、登録メールも回答メールも同じ mail_content_receivable なので、
登録メールと回答メールの mail_content_receivable が~~混ざりました。~~まざってなかった。
### 画面

![image](https://cloud.githubusercontent.com/assets/2756509/17234916/e3e5dc68-5577-11e6-9b35-77a42c7eb6a2.png)
### DB

| # id | roles_room_id | block_key | permission | value | created_user | created | modified_user | modified |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| '39' | '3' | 'db23cdd891be51178a1a94e700afa186' | 'mail_content_receivable' | '1' | '1' | '2016-07-29 01:03:31' | '1' | '2016-07-29 01:11:16' |
| '40' | '4' | 'db23cdd891be51178a1a94e700afa186' | 'mail_content_receivable' | '1' | '1' | '2016-07-29 01:03:31' | '1' | '2016-07-29 01:11:16' |
| '41' | '5' | 'db23cdd891be51178a1a94e700afa186' | 'mail_content_receivable' | '1' | '1' | '2016-07-29 01:03:31' | '1' | '2016-07-29 01:11:16' |
| '42' | '2' | 'db23cdd891be51178a1a94e700afa186' | 'mail_answer_receivable' | '1' | '1' | '2016-07-29 01:03:31' | '1' | '2016-07-29 01:11:16' |
### 対応案

~~影響を少なく対応するとしたら、新しく権限作る方向かなと思っています。~~
~~例）回答メールの通知する権限を mail_content_receivable_answer にする。~~
~~こんな感じ。~~

~~　投稿メール：通知する権限（mail_content_receivable）~~
~~　回答メール：回答を通知する権限（mail_content_receivable_answer）~~

**Comment by akagane99** [comment]
あれ！？mail_answer_receivableがあるのか？
もうちょっと調べます。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Mails/pull/90/commits/25194948daccd6a0350db576ffba415885240607

**Comment by akagane99** [comment]
メールのバグで、プルリク頂きました。
マージしたので、クローズします。
