### ISSUE TITLE
回覧板の回答方式内の回答選択肢に同じ内容を入力すると回答選択欄で1つの選択肢として表示されてしまう。

### ISSUE THREAD

**Issue by kitatsuw** [NetCommons3/NetCommons3#328]
例）
登録編集画面
回答方式 
単一又は複数選択を選ぶ。
選択肢1　あああ
選択肢2　あああ

詳細画面
回答：
◯あああ

という感じで選択肢が1つへ統合される。

**Comment by go-to** [comment]
修正完了、クローズします。
