### ISSUE TITLE
デザインガイドに沿っていない

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#339]
![image](https://zube.io/files/NetCommons3/4ccfdb828968d97806a43f125d84aa4a.png)

・罫線要らない
・絞り込みと追加ボタンは同行。

**Comment by s-nakajima** [comment]
この画面以外に入力画面等もデザインガイドに沿っていません。全画面、見直してください。

**Comment by go-to** [comment]
見直しを行いました。
