### ISSUE TITLE
アンケートで編集時、集計結果表示の設定から戻ると、入力内容が消えました。

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#343]
「集計結果表示の設定」から「戻る」と入力内容、ページも消えました。
![image](https://cloud.githubusercontent.com/assets/2756509/17460520/42e85dce-5ca5-11e6-9f40-55dcc73353a0.png)
### 【参考】

「集計結果表示の設定」の「質問の作成」リンクをクリックで戻ると、入力内容をは正しく表示されました。
![image](https://cloud.githubusercontent.com/assets/2756509/17460525/9e7f585e-5ca5-11e6-9394-6a51c86c89d5.png)

「質問の作成」リンクと同じURLパラメータにすれば解決するような気がします。
#### 「質問の作成」リンク

http://127.0.0.1:9090/questionnaires/questionnaire_edit/edit_question/13/s_id:d009e8106275ef5cb0ac27a3fedeeafe?frame_id=17
#### 「戻る」ボタン

http://127.0.0.1:9090/questionnaires/questionnaire_edit/edit_question/s_id:d009e8106275ef5cb0ac27a3fedeeafe

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Questionnaires/commit/136882162ae0d6db2ddb4341b8780afcbaa7f99e

**Comment by akagane99** [comment]
解消しました！ご対応ありがとうございました。
