### ISSUE TITLE
viewファイルをeditにするなら$this->view = 'edit';でやってください。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#363]
これなんですか？
https://github.com/NetCommons3/Tasks/blob/master/Controller/TaskContentsController.php#L172

viewファイルをeditにするなら$this->view = 'edit';でやってください。

$this->render()を使うと、Controller.beforeRenderなどのイベントを強制的に呼び出していることになるので、
$this->view = 'edit';としてください。

**Comment by kitatsuw** [comment]
$this->view = 'edit'に修正しました。
