### ISSUE TITLE
postとputの両方許可していますが、editなので、putだけで良いのではないですか。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#364]
https://github.com/NetCommons3/Tasks/blob/master/Controller/TaskContentsController.php#L204

postとputの両方許可していますが、editなので、putだけで良いのではないですか。
もし、putだけにならないなら、リクエストパラメータがおかしいです。

**Comment by kitatsuw** [comment]
下記条件下でputではなくpostが飛んできたのでCloseからOpenに変更。

編集画面で入力値を不正にしてから決定ボタンを押下しバリデーションエラーを発生させる。
登録画面が再描画されその後に入力値をを変更せず再度決定を押下。
2度目のバリデーションエラーは起きず、渡されてきたパラメーターがpostであることを確認。
その後は正常な値を入れて決定ボタンを押下してもパラメーターがpostから変わらない。

**Comment by kitatsuw** [comment]
不具合対応が完了したのでCloseします。
