### ISSUE TITLE
予定の詳細画面が他のデザインと異なる

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#368]

**Comment by to-hashimoto-3** [comment]
すいません。修正内容がずれるといけなので、確認させてください。
他のデザインと異なる、とは具体的には、「インデントがついているのでそれをはずしてください」という意味でしょうか？

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Calendars/commit/031ac8271992b9aa1cccb5e2bdaa6725dc78db7c
