### ISSUE TITLE
日付のみに範囲指定ができない。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#369]
日付のみに範囲指定ができない。期間指定を選ぶと必ず時間もせっているすることになってしまう。

**Comment by to-hashimoto-3** [comment]
当初は、日付について簡易入力（単一日、単一日の時間）、詳細入力（日のfrpmto範囲、日時間のfromto範囲）の４段階だったが、画面の見直しを指示いただいたとき、現在の入力画面で（単一日、日時間のfromto範囲）の２段階で仕様提案（仕様検討会の場にて）し、ご了解いただいた上実装したものです。なので、現在はこれで仕様通り実装されていると認識しております。よろしくお願いします。

**Comment by to-hashimoto-3** [comment]
前出のとおりなので、ご指摘の内容は、仕様検討会の場で決まった通りの実装なので不具合(issue)としてはいったんcloseさせていただき、あたためて仕様のさらなる改良依頼(request)、という認識とさせていただければと存じます。
