### ISSUE TITLE
Framesテーブルのdefault_action

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#37]
https://github.com/NetCommons3/Frames/blob/797bb5d9f25024c5909e8059453f13b0519c7c9b/Config/Migration/1434983278_init.php#L46
は何でしょうか？
Pluginsテーブルにもあるので、冗長になってます。

https://github.com/NetCommons3/Frames/commit/2ec9d1eb4bcc09e60d2d22c8d4537483509f1153#diff-c66ece1283a1361747ef36b50db89502
で使用しているっポイです。
コミット前の処理でも問題ないと思っているのですが、何かあったのでしょうか？

**Comment by kteraguchi** [comment]
https://github.com/NetCommons3/Questionnaires/issues/75#issuecomment-159207049

ですね。
自己解決です。

**Comment by s-nakajima** [comment]
はい。そうです。
