### ISSUE TITLE
回覧板の絞り込みのボックスが長い

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#376]
![image](https://zube.io/files/NetCommons3/774c3ef77bd94715afa56ded4685487d.png)

「全て表示」で良い

**Comment by go-to** [comment]
UIガイドライン対応で、ステータスと回答状況を別プルダウンにしました。

![circularnotices](https://cloud.githubusercontent.com/assets/2410870/17724337/3b8585f0-647c-11e6-8c76-3b51f5387c24.png)
