### ISSUE TITLE
選択肢を追加したら、そこにカーソルを移してほしい。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#379]

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Questionnaires/commit/b33f66848ba843e7b725ca2b3e8c287c5e206e83

**Comment by RikaFujiwara** [comment]
1f04544795eb1cce2037e0d8a888af04b1c314eb

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Quizzes/commit/1f04544795eb1cce2037e0d8a888af04b1c314eb

**Comment by RikaFujiwara** [comment]
アンケート対応済
小テスト対応済
