### ISSUE TITLE
変なところに罫線がある

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#381]
![image](https://zube.io/files/NetCommons3/af12ef3e64a1212e64f4027924734536.png)

アンケート、小テストだけ、変なところに罫線がある。統一されていない。他のプラグインは罫線はない。

**Comment by RikaFujiwara** [comment]
上記　２Commitで対処完了。確認できたらCloseお願いします。

**Comment by RikaFujiwara** [comment]
対処済みなのでCloseします
