### ISSUE TITLE
「他の会員の情報も閲覧できる」としている一般会員の閲覧権限

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#399]
氏名（会員項目設定で表示）で権限設定「他の会員の情報も閲覧できる」としている一般会員が、他の会員情報をみた場合、氏名が閲覧できなかった。

**Comment by s-nakajima** [comment]
別セッションで一般会員がログインしている際に、その会員の権限を切り替えても反映されない。
※ログインしなおせば反映されるが。

最終更新日を見て、取り直すように修正する
