### ISSUE TITLE
ウィジウィグのファイルアップロード

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#40]
無理にウィジウィグにボタンを追加するのではなく、
redmineのように別項目としてファイルをアップロードする方式でも良いんじゃなかろうか？
![default](https://cloud.githubusercontent.com/assets/2756509/11457427/2e3c95fe-96ec-11e5-8cac-5874e4dffc23.PNG)

**Comment by akagane99** [comment]
風呂に入ってて、思い付いたのでつい書いちゃった。

**Comment by akagane99** [comment]
画像の貼り付けは、既にあるんですね。（仮かもしんないけど）
これがあるなら、同じイメージにしたいだろうなぁ。
（もし実装楽になるなら、変えちゃうのもありかなぁと思うけれども、案どまりです。）
![default](https://cloud.githubusercontent.com/assets/2756509/11457569/bff6f48c-96ef-11e5-8cfd-7f5c8ab3da19.PNG)

**Comment by s-nakajima** [comment]
馬嶋さんの方で実装していただいたのでCloseする
