### ISSUE TITLE
ウィジウィグのTexボタン追加

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#41]
世界中の誰かが、既にタイニーMCEの特定バージョンで、Tex対応してるではなかろうか？
ソースが使える。使いまわせる。組み込むだけでいける可能性がありそうな気がする。
要テストコード、ライセンスチェック。

下記はなんか検索にでてきたものを、参考に適当にピックアップ。
https://www.google.co.jp/search?q=%E3%82%BF%E3%82%A4%E3%83%8B%E3%83%BCmce+tex&ie=utf-8&oe=utf-8&hl=ja

▼ Equations in Tiny MCE v4 | CodeCogs Equation Editor
https://www.codecogs.com/latex/integration/tinymce_v4/install.php

▼ Text editors - Moodle - Library Guides at Monash University
http://guides.lib.monash.edu/moodle/text-editors

**Comment by akagane99** [comment]
> ▼ Equations in Tiny MCE v4 | CodeCogs Equation Editor
> https://www.codecogs.com/latex/integration/tinymce_v4/install.php

パワードバイcodecogs だった。サービスで、Api通してtexを表現してた。これじゃない。

**Comment by akagane99** [comment]
あ、息抜きがてら調べてます。

**Comment by akagane99** [comment]
http://moonwave99.github.io/TinyMCELatexPlugin/
は Google Infographics API で実現していたが、同Apiは2012年に既にサービス提供終了？してるので、使えない。
https://developers.google.com/chart/infographics/docs/overview

**Comment by akagane99** [comment]
むむ、なんだtexむずい。
タイニーmceの追加プラグインで、オープンソースかつApiサービスに繋がないでスタンドアロンでlatex表現できるの、ざっと見、見つからなかった。

nc2で実現出来ているのであれば、移植開発が妥当なのだろうか？
そこらへんは開発する人が検討する事かな。

**Comment by akagane99** [comment]
nc2のウィジウィグのTeXボタンは、そもそもどうやって実現していたか、確認必要。
多分それが仕様として正解に近い答えを含んでいそう。

**Comment by akagane99** [comment]
nc2　公式サイト-プライベートルーム-お知らせで確認
入力後、プレビュー、画像生成してる。外部に通信している感じがしないっぽい。
1. 決定かプレビューでAjaxで画像を生成＆ダウンロードかな？
   `http://localhost/index.php?action=common_tex_main&c=11xxxx11`

![default](https://cloud.githubusercontent.com/assets/2756509/11459182/fc5dda5c-9713-11e5-84ff-17e79e23ed05.PNG)

**Comment by akagane99** [comment]
NC2で使ってるCのライブラリはこれ。
▼ mimetex.html
http://www.forkosh.com/mimetex.html
- MimeTeXは，"マイムテフ"と読みます。
- パーミッションつけないとNC2でも動ないけど、インストールドキュメントにはその記述なかったので、かなり実行権限のパーミッション付け忘れられているんでないかな。
  http://www.suguru.jp/mimetex/

#### NC2Texライブラリ

https://github.com/netcommons/NetCommons2/tree/develop/html/webapp/modules/common/tex/mimetex

#### TeXライブラリ呼び出し。システムコール。

https://github.com/netcommons/NetCommons2/blob/develop/html/webapp/modules/common/tex/main/Main.class.php

これNC3に移植すれば良さそう。
ライブラリもこれで良さそう。
返る理由は特に無さそう。
なんでないかな？

**Comment by RikaFujiwara** [comment]
茶々を入れます
こんなのもあるよー　
https://github.com/Sommerregen/grav-plugin-mathjax
確かMathMLってW3CがHTML5での文法サポートを昨年末に決定したんじゃなかったっけか

**Comment by akagane99** [comment]
なんと〜。
こんなのもあるんすね。

HTML5でサポートしてくれたら、一番てっとり早いですね。
各社ブラウザが素直に迅速に対応してくれるかは別話として。

**Comment by s-nakajima** [comment]
馬嶋さんの方で、MathJaxで実装したためCloseとする。
