### ISSUE TITLE
ルーム管理 参加者選択の「ルーム内の役割を変更する」、「ルーム内の役割」の動作の差異

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#414]
１．チェックボックスでチェックし、「ルーム内の役割を変更する」のセレクトボックスで不参加を選択する。
２．個別で「ルーム内の役割」を不参加に変更する。

１．は、行が消えるが、２．だと「未登録 ( 変更前: 一般 )」とラベルがつく。

１．と２．で動作が異なる意味はなぜか？
２．の動作のほうが正しいと思えるが、それでよいか？
（１．の動作にしてしまうと、誤って不参加にした場合に元に戻せなくなってしまうため等が考えられる）

仮に２．の動作に統一したとして、「未登録 ( 変更前: 一般 )」のラベルの必要性がわからない。
決定を押さないと、登録されないように統一しているはず。
・未登録　なのはあたりまえではないか？
・変更前の状態を知りたい場合はどんな場合か？

**Comment by s-nakajima** [comment]
以前、舛川さんに仕様の相談した時、１のチェックボックスを選択した場合、直接登録で良いとのこと。

仕様の検討する時間がなかったのと、Gmailとかチェックして、「既読する」を実行すると、すぐに反映されることもあり、そっちの方が使い勝手が良いのかなと思い、以前の仕様から変更していない。

「未登録 ( 変更前: 一般 )」のラベルは、実際に切り替えしているときに、どのユーザを切り替えたのか、パッと見、わからないため、付けました。

**Comment by ryu818** [comment]
直接登録で、どうして納得したのかが記載がないため、「言ったからやった」では判断できません。
下に「決定」ボタンを配置した段階で、ＮＣ３全体を通して「決定」ボタンをおすと登録される
インターフェイスではないでしょうか。

そもそも、Gmailでは、そうだからという理由はおかしいです。
Gmailでは、一覧表示の全体を通して即時更新のインターフェイスに揃えているため
違和感はないです。
例えるならば、選択して削除するパターンと、削除ボタンと２つの同じ機能を有するものがあった場合に
その２つで異なる動きをするとユーザーが不安がります。

「「未登録 ( 変更前: 一般 )」のラベルは、実際に切り替えしているときに、どのユーザを切り替えたのか、
パッと見、わからないため、付けました。」＝＞それなら一瞬ハイライトにしてください。jqueryを
使用しているのだから、わりと簡単にできるはずです。いきなり、行が伸びてしまう今の仕様は違和感があります。

**Comment by s-nakajima** [comment]
りょうかいです。修正します。
