### ISSUE TITLE
現情報提供クラス（Current○○Class）のスタティックメソッドとインスタンスメソッド

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#42]
スタティックメソッドになっているのとインスタンスメソッドになっている意図は何でしょうか？
例
https://github.com/NetCommons3/NetCommons/blob/master/Utility/CurrentFrame.php#L115
https://github.com/NetCommons3/NetCommons/blob/master/Utility/CurrentFrame.php#L147

**Comment by kteraguchi** [comment]
各Current○○Classに$__instanceプロパティがありますが、
インスタンスメソッドを呼び出すためにインスタンス化しているのでしょうか？
上記の意図にもよりますが、プロパティじゃなくて、ローカル変数で良い気がします。

**Comment by s-nakajima** [comment]
了解です。
