### ISSUE TITLE
キャビネットの左ツリーは狭すぎて操作できない

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#434]
左側、狭くて無理だと思います。ぱんくずが出るなら、左側いらなくないですか？とのこと。

**Comment by RyujiAMANO** [comment]
メインカラムの幅を取得して幅にあわせて表示・非表示切り替えがいいのかな。
たしかに右カラムあると厳しい。けどフルに使えるときはあったほうが階層移動しやすいので。
http://eiua-memo.tumblr.com/post/114825906638/angularjs%E3%82%A6%E3%82%A3%E3%83%B3%E3%83%89%E3%82%A6%E3%82%92%E3%83%AA%E3%82%B5%E3%82%A4%E3%82%BA%E3%81%97%E3%81%9F%E3%81%A8%E3%81%8D%E3%81%AB%E5%87%A6%E7%90%86%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%95%E3%81%9B%E3%82%8B%E6%96%B9%E6%B3%95

このあたり参考にして左ツリーON/OFFかなぁ

**Comment by RyujiAMANO** [comment]
3カラム表示だったらフォルダツリー非表示にする
