### ISSUE TITLE
ＢＢＳ：記事詳細画面で編集ボタン、コメントのインターフェイス

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#435]
ＢＢＳ：記事詳細画面で編集ボタン、コメントのインターフェイスがブログと異なる。

**Comment by s-nakajima** [comment]
掲示板のコメントは、NC2の子記事であり、コメントに対してコメントを書ける仕様であるため、ブログのコメントとは異なる。そのため、このようなUIにしている。また、NC2同様にWISIWYGで書けるようにしている。

**Comment by ryu818** [comment]
コメントはそのままにしても、一時保存等のラベルの位置と、親記事編集ボタンは、ブログと揃えたらよいのでは？

**Comment by ryu818** [comment]
コメントの位置ともそろえたかったんだとうと思ったので、これはこのままでClose．
