### ISSUE TITLE
WYSIWYG機能項目

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#44]
- 画像アイコン機能
  - ローカル画像ファイルのアップロード機能（複数OK？）
  - URL入力機能（複数OK？）
- ファイルアイコン機能
  - ローカルファイルのアップロード機能（複数OK？）
- カラーピッカーアイコン機能
- 絵文字アイコン機能
- WYSIWYG内容ダウンロードアイコン機能
  - zipダウンロード機能
  - 暗号化zipダウンロード機能（いる？）
  - 使用ファイル取得機能
  - 使用ファイル参照URL変換機能
- Texアイコン機能
  - Texライブラリ呼び出し機能
- セキュリティ機能

とりあえず、ざっとあげときます。
不足、変更、追加等はレスしてください。

**Comment by s-nakajima** [comment]
Amazonリンクがないです。
ただ、Amazonリンクはキーとかが必要になるため、Amazonリンクの代わりに、GoogleBooksリンクが必要です

**Comment by kteraguchi** [comment]
NC2のTexは以下を利用してます。
http://www.forkosh.com/mimetex.html

同じもの使うか、今だと他にもあるのかは要検討です。

**Comment by akagane99** [comment]
#41　Tex話題。参考程度に。

**Comment by akagane99** [comment]
#40 ウィジウィグのファイルアップロード話題。参考程度に。

**Comment by akagane99** [comment]
#63 WYSIWYGってどこに配置されている？。参考まで。

> bower updateすると、NC3にインストールされるTinyMCEは、現最新の4.3.1っぽいですね。

**Comment by akagane99** [comment]
#### 開発ベース

TinyMCE4.x＋AngularJS1.x＋Cakephp2.x＋NC3

**Comment by akagane99** [comment]
youtubeの埋込コードが無かった。

### ＮＣ２ウィジウィグ

![default](https://cloud.githubusercontent.com/assets/2756509/11805471/2dff7862-a34f-11e5-89e7-b72b57bf56f9.PNG)

**Comment by akagane99** [comment]
zipダウンロード、いらない

**Comment by akagane99** [comment]
#63 から転記

#### Overwrite FormHelper::input($fieldName, array('type' => 'textarea'))

https://github.com/NetCommons3/NetCommons/blob/master/View/Helper/NetCommonsFormHelper.php#L347-L370

#### ＮＣプラグイン（例：お知らせ）から呼び出し

https://github.com/NetCommons3/Announcements/blob/master/View/Announcements/edit.ctp

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Wysiwyg
実装済みのため、クローズします。
