### ISSUE TITLE
システム管理者なのにブログ記事のハンドルから表示される会員情報に編集ボタンが表示されない。

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#449]
システム管理者なのにブログ記事のハンドル（一般会員）から表示される会員情報に編集ボタンが表示されない。

**Comment by s-nakajima** [comment]
他人の会員情報を変更するのは、一般画面の方ではやらせないほうが良いと思っているため、会員情報に編集ボタンを出していません。出した方が良いですか？
編集ボタンをクリックした後、会員管理に飛ばす感じにするなら、出しても良いのかな？

**Comment by ryu818** [comment]
こちらもいったんClose。
