### ISSUE TITLE
アンケート回答処理でセッションIDの使用

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#45]
アンケート回答時にセッションIDを登録しています。
非会員の回答済判断で、同じセッションIDがあれば回答済みと判断していますが、
同じセッションIDが発行される可能性は0ではないです。
とは言っても、とんでもない確率ですが。。。

非会員の回答済判断はCookieの利用が良いかと思いますが、
丁度サブクエリー処理部分と絡むので、もうちょっと考えてみます。
とりあえずあげときました。

https://github.com/NetCommons3/Questionnaires/issues/23

**Comment by RikaFujiwara** [comment]
c3af742e89e879ce05273d4ebef5910a102138e9
