### ISSUE TITLE
会員情報のポップアップでの表示

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#450]
会員項目設定の以下のすべてにチェックしてある項目をシステム管理者が閲覧しても表示されない。

・会員管理プラグインを使えるユーザのみ閲覧できる
・会員管理プラグインを使えるユーザのみ編集できる
・各自で公開・非公開を設定可能にする （管理者に対しては個人情報管理に基づきます）

**Comment by s-nakajima** [comment]
会員管理からは、すべての項目が閲覧できるように修正。
会員情報は、会員項目の設定＋個人情報設定の状態に基づいて表示する。

**Comment by ryu818** [comment]
同じ会員情報の画面で、いる場所によって表示されるものが、ここまで変わると、不具合っぽく感じるが、これでしばらく様子みましょう。
いったんＣｌｏｓｅ。
