### ISSUE TITLE
新規登録の受付を行うとトークンエラー

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#457]
新規登録の受付画面で決定をおすと、「予期しないトークンにより、登録が正常にできませんでした。」となる。

**Comment by s-nakajima** [comment]
ログインしていない場合、SessionからToken情報がなくなってしまう。そのため、CSRFのチェックで失敗してしまう。

**Comment by ryu818** [comment]
新規登録画面で、普通に入力して「次へ」をおすと、Bad Request2と表示されて、登録できない。
エラーもひどいが、エラーメッセージもひどすぎる。

会員項目をいくつか追加したのも影響あるかも？

**Comment by s-nakajima** [comment]
管理者のみ編集できる項目で、必須項目の場合、発生

**Comment by T-Yoshinori** [comment]
3.3.3 でも、新規登録で「次へ」を押すとトークンエラーになります。
