### ISSUE TITLE
会員項目設定の権限のデフォルト値

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#459]
会員項目設定の権限のデフォルト値は、以下にチェックがついている。

・会員管理プラグインを使えるユーザのみ閲覧できる
・会員管理プラグインを使えるユーザのみ編集できる

nc2では一般であっても自分自身ならば閲覧可能なのがデフォルトである。
なぜ、チェックをつけたのが不明であるが、デフォルトでは一般でも自分の会員権限が
なにか知りたい。その他の項目のデフォルト値もおかしいかもしれないが、みていない。
nc2のデフォルト値との差異を調べなおす必要がある。

**Comment by s-nakajima** [comment]
NC2では、一般に権限が閲覧出来るのは確認した。
＞＞＞2015/7頃の管理系の打合せで権限は外す感じになった。音声ファイルはあるが、未確認。

その時に言われた内容を反映したキャプチャ。

全体がグレーになっている項目が会員管理プラグインが使えないユーザが閲覧できない設定のもの。
※それ以外の選択肢は、適当。
ただ、この時は、閲覧と編集が二つに分かれてなかったから、この時は、この仕様が妥当だったのかも。再度確認した方が良いかも。

![権限管理-個人情報設定（会員管理の使用不可）.png](https://zube.io/files/NetCommons3/d9825fc9306314309bb23276aa66ffd8.png)

**Comment by s-nakajima** [comment]
その後、もくもく会か軽井沢のどちらかで、パスワード変更日時、最終ログイン日時、前回ログイン日時は本人に閲覧させようってことで現状の仕様になっている。

**Comment by ryu818** [comment]
この仕様のままで、運用してみましょう。こちらもいったんClose。
