### ISSUE TITLE
アンケート一覧でtryブロック

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#46]
https://github.com/NetCommons3/Questionnaires/blob/64f7ea46ce575029091071cc5b18aee84ba984e3/Controller/QuestionnairesController.php#L90

でtryブロック使用していますが、

https://github.com/NetCommons3/Questionnaires/blob/64f7ea46ce575029091071cc5b18aee84ba984e3/Controller/QuestionnaireBlocksController.php#L91

では使用していないです。

サブクエリー処理のExceptionログを取りたい感じでしたら、tryブロック使用しなくても、error.logに出力されますので、tryブロック不要かと思います。

なにか理由等あるのでしょうか？
他のプラグインでもtryブロック付けたほうが良いということになりますのであるようでしたら、言ってください。

**Comment by RikaFujiwara** [comment]
Try外します。
かなり以前、参考にしたソースがもとで残ってしまったものだと思います（記憶が薄いですが）
