### ISSUE TITLE
サイト管理　入会設定の文言

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#463]
会員登録承認メール　会員管理からの登録通知メールも、意味がわからないと思ったけど、
会員登録承認メールの件名って「管理者による承認」となっても必要なんだっけ？
実際、新規登録してみればいいのだけど、できないので文言を考えるのは保留。

**Comment by s-nakajima** [comment]
> 会員登録承認メールの件名って「管理者による承認」となっても必要なんだっけ？

はい。必要です。

管理者による承認のフロー
１．新規登録
２．管理者にメール（会員登録受付メール）
３．管理者が承認する
４．会員に登録承認した旨のメール送信（会員登録承認メール） 
５．会員がそのメールのリンクを踏んで始めてアカウントが有効になる

ちなみに、ユーザ自身の確認は、
上記の４、５です。

**Comment by s-nakajima** [comment]
返信がないので、Closeします。
