### ISSUE TITLE
ドキュメントの見栄え

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#47]
https://github.com/NetCommons3/NetCommons3Docs/blob/master/phpdocMd/NetCommons/NetCommonsHtmlHelper.md

メソッドと、引数等が同じフォントサイズで表示されてて見づらいっす。
メソッド配下は、フォントサイズ小さくなって欲しいけど、それは可能なんだろうか？

**Comment by akagane99** [comment]
後から入ってくる人の為にも、ここら辺がどーにかなってると、対応しやすいのでは、なかろうかと考えます。

**Comment by akagane99** [comment]
### 別案1) いっそGithubのソースにリンク貼った方がわかりやすいのかもです。（ソース見てね方針）

下記リンクを、いっそwikiに書いてしまう。

例）
https://github.com/NetCommons3/NetCommons/blob/master/View/Helper/NetCommonsHtmlHelper.php#L39-L192

### 別案2) nc3devとかに、phpdocサーバーたてる？

サーバー構築必要？
デメリット：手間がかかる

### 別案3) vagrant 環境でphpdoc見れるので、その方法をwikiに書く？

メリット：すでに環境があるので、手間が少なさそう。
デメリット：vagrant環境作らなきゃ見れないじゃん！

vagrant 環境のphpdoc　確か見た事ある。
やり方は、見聞きすれば手順わかりそう。

**Comment by akagane99** [comment]
### 別案4) phpdocをそのままnetcommonsdocリポジトリにアップする。

てか、あるので、これ更新するだけでいいんじゃね？
https://github.com/NetCommons3/NetCommons3Docs/tree/master/phpdoc
更新頻度を週1か、月１とか決めれば、手間はかからなそう。

メリット：手間が少ない
デメリット：とくにない

別案1) との組合せで、wikiからはソース参照させて、
phpdoc見たかったら、ダウンロードしてみ見てね。でもいい気がする。

**Comment by akagane99** [comment]
@kteraguchi さんへ
12/17もくもく会でとりあげました。

https://github.com/NetCommons3/NetCommons3/wiki/Wikiメモ
の通り、phpdoc→MD形式に変換しているとの事。
変換プログラムは（evert/phpdoc-md）を使っています。
https://github.com/evert/phpdoc-md

変換したMD形式の再度確認しました。
https://github.com/NetCommons3/NetCommons3Docs/blob/master/phpdocMd/NetCommons/NetCommonsHtmlHelper.md

一番気になったのは、`Methods`内の各メソッドと、その引数(`Arguments`)が判りずらいです。
MD形式では以下で出力されていました。

```
### __call　（各メソッドの一例）
#### Arguments
```

ArgumentsはH4相当で出力されているけど、黒一色なので、見分けが微妙と感じました。
H5相当で出力すれば、改善されると思います。（ブラウザから修正で、編集前プレビューで確認可能）

```
##### Arguments
```

下記いじればいけそう。

evert/phpdoc-md
https://github.com/evert/phpdoc-md/blob/master/templates/class.twig#L100

次回もくもく会でドキュメントの検収時に、参加者の皆様のOKがでて、
かつ、これから参画するであろう他の事業者様が見ても、わかるよね。となるのであれば、
別段、上記変更しなくても良いかと思います。

以上、参考まで。

**Comment by kteraguchi** [comment]
了解です。

ちょっと保留します。

**Comment by akagane99** [comment]
phpdocで表示できるようにして頂いたため、クローズします。
