### ISSUE TITLE
サイト管理の基本設定でデフォルトの言語を英語に変更すると、ログインしても、すぐログインしていない状態に戻る

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#471]
サイト管理の基本設定でデフォルトの言語を英語に変更すると、ログインしても、すぐログインしていない状態に戻る
デフォルトの表示スペースをコミュニティの変更したせいかもしれない。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Auth/commit/bb920e4d5e5123cb2aef889d25ed773ecd6b07b6
もしくは、
https://github.com/NetCommons3/SiteManager/commit/8b2e15b4c55910562aaeba13f4c062b318875f11

で修正されたはず。
