### ISSUE TITLE
パスワード再発行画面のリダイレクト

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#476]
「パスワード再発行の機能を使う」を無効にし、「auth/forgot_pass/request」に遷移するとBad requestとなっているが、その後のリダイレクト先が「nc3(サブディレクトリ名)/nc3(サブディレクトリ名)/XXX」となり、永遠にリダイレクトされる（※　サブディレクトリにインストールした場合のみ起こる現象かも）。

**Comment by s-nakajima** [comment]
現象発生しない。もしかしたら、Not Foundのリダイレクト先の修正で直ったかも。
https://github.com/NetCommons3/NetCommons3/issues/460
