### ISSUE TITLE
「サイトを一時停止にする」にした場合のログイン

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#477]
「サイトを一時停止にする」にした場合、一般で正しくログインしても、「ログイン情報が間違っています」と表示される。ログイン情報は間違っていません。

**Comment by s-nakajima** [comment]
「メンテナンス中のため、管理者しかログインできません」
「Under maintenance. Nobody is allowed to login except for administrators.」

とする。
