### ISSUE TITLE
認証キー成功後のredirectでサブディレクトリ名が二重になる

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#478]
キャビネットで発生。
http://nc3dev2.nakazii-co.jp/nc3/page_20160817034050

認証キーでの認証成功後に

http://nc3dev2.nakazii-co.jp/nc3/cabinets/cabinet_files/download/21/3b6c966557b4fa7a6a8c91401a4dfd12?frame_id=50

に移動すべきところが、
http://nc3dev2.nakazii-co.jp/nc3/nc3/cabinets/cabinet_files/download/21/3b6c966557b4fa7a6a8c91401a4dfd12?frame_id=50
に移動してしまう

**Comment by RikaFujiwara** [comment]
認証キープラグインがわで、「もといたURLに戻る」ために $controller->here　でURL文字列を取り込んで処理してるため、上記現象。
サブディレクトリのことを考慮するとcontroller->hereでURLを見てredirectするのはNGか。

現状、リダイレクトモードで認証キーを使っているのはキャビネットだけであることを考えると、いささか固定的だがプラグイン、コントローラー名、アクション名、ブロックID、キーを取り出して配列情報として保持し、リダイレクト処理に用いるのが現状、最短の（一時的）解決法か。

**Comment by RyujiAMANO** [comment]
```
            $returnUrl = $controller->here;
```

を
                $returnUrl = $controller->request->here(false);
にしたらOKでした。

**Comment by RikaFujiwara** [comment]
おぅ！なんと！
ありがとうございます！　その修正いれておきます！

**Comment by RikaFujiwara** [comment]
->request->here(false);
って、オンラインマニュアルには載ってないのですね。。。。
よくお見つけになられました。奥が深い。。

**Comment by RikaFujiwara** [comment]
対処しました。確認できたらCloseお願いします
