### ISSUE TITLE
件名に特殊文字がある場合、メール内でエンコードされてしまう。

### ISSUE THREAD

**Issue by ohga21** [NetCommons3/NetCommons3#488]

**Comment by akagane99** [comment]
どういうふうになるのでしょうか？

**Comment by ohga21** [comment]
メールの件名とメール本文のToDoタイトルが

```
<⇒&lt;
&⇒&amp;
>⇒&gt;
```

のようになりました。

以下にメールの内容を載せます。
---件名-------------------
(承認依頼)[NC3-ToDo]ZZZ&lt;&amp;&gt;(パブリック)

---本文-------------------
※このメールに返信しても相手には届きませんのでご注意ください。

WithOne@編集者さんからToDoの承認依頼があったことをお知らせします。

担当者への連絡:

ToDoにToDoが作成されたのでお知らせします。
ルーム名:パブリック
ToDoタイトル:ZZZ&lt;&amp;&gt;
投稿者:WithOne@編集者
投稿日時:2016/08/18 13:52:46

EEE&lt;&amp;&gt;

このToDoの内容を確認するには下記のリンクをクリックしてください。

## http://ｘｘｘｘ/nc3/tasks/task_contents/view/65/845bc53a52dad528b94f058d67b8510d?frame_id=53

NetCommons Project
連絡先：　03-XXXX-XXXX FAX:03-XXXXX-XXXXX

## 住所：東京都千代田区ＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸＸ

**Comment by akagane99** [comment]
内容把握できました。詳細感謝です。

```
<⇒&lt;
&⇒&amp;
>⇒&gt;
```

メールでテキスト形式設定なら、セキュリティ対応として一律、件名と本文にh()つかって特殊記号排除
してるんです。
半角記号の変換は打倒な対応かと思うのだけれども、どうでしょう？

**Comment by ohga21** [comment]
h関数はHTML的なセキュリティ対応で、メールは別の話ではありませんかね？
NC2系もちゃんと表示されてますし、一般の人から見るとバグに見えてしまうような気がしています。

でもNC3でのHTMLメールの扱いとかが僕はわかってないので、その辺との兼ね合いで仕方がないならいいのかもしれません。

**Comment by akagane99** [comment]
> h関数はHTML的なセキュリティ対応で、メールは別の話ではありませんかね？

うーん、言われてみると確かにメールのセキュリティ話じゃないですね（＾＾；
という事で、今は対応する方向に思えてきました。

phpでメール処理のセキュリティを調べなおしてみました。
- メールヘッダインジェクション対策（`\n`排除で対策）位でした。

なのでh関数が必須ではなさそうです。
あと、h関数は内部で htmlspecialchars() 使って変換してるんだけど、どうゆう訳かNC2でもバリバリ使ってるんだよねぇ。

https://github.com/netcommons/NetCommons2/blob/63c3ebed814475f87bc4fe4e3f0aeeb463c81c47/html/webapp/modules/bbs/action/main/mail/Mail.class.php#L50
https://github.com/netcommons/NetCommons2/blob/63c3ebed814475f87bc4fe4e3f0aeeb463c81c47/html/webapp/components/mail/Main.class.php#L268

使ってるけど全部じゃないから、件名と本文はうまい事すり抜けるようになっているのかなぁ。
はたまた再変換で元に戻しているのか、なんかやってそうです。

ここら辺はNC2の動きはデバックしないと何ともな感じです。
とりあえず、時間的にきっついけど対応やってみますね。
