### ISSUE TITLE
リダイレクト画面のヘッダーメニュー

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#491]
リダイレクト画面なのだから、ヘッダーメニューは必要ない。

**Comment by s-nakajima** [comment]
どこのサイトのエラーかわからなくなるため、ヘッダーメニューは削除せずにサイト名だけにする。

**Comment by ryu818** [comment]
よくわからないのですが、リダイレクトするサイトがどこなのかわかる必要はあるのでしょうか。
これは、そもそもどこのサイトかわかりたいならば、リダイレクトは使わずエラー画面出します。
もし、リダイレクトをしている画面でヘッダーメニューを表示するものが、複数存在するのでしたら
お知らせください。

リダイレクトするのは、それなりに意味がある先へリダイレクトするでしょうし、
NetCommons内の別ページにリダイレクトしているのに、どこのサイトかわからないというのも
よくわかりません。

**Comment by s-nakajima** [comment]
りょうかいです。消します。
