### ISSUE TITLE
動画のサムネイル

### ISSUE THREAD

**Issue by noricoco** [NetCommons3/NetCommons3#493]
動画のサムネイルは指定しなかったときには、自動で切り出すのだと思っていました。
現在は自動での切り出しはしていないようです。
ふつうのユーザは動画からサムネイルを切り出すアプリを持っていない可能性があるので、自動切り出しをお願いします。

**Comment by akagane99** [comment]
> 動画のサムネイルは指定しなかったときには、自動で切り出すのだと思っていました。

はい、その通りです。
自動で切り出すにはFFmpegが必要で、インストールされている環境なら、その通りに動くように対応済みです。

> 現在は自動での切り出しはしていないようです。

検証環境はレンタルサーバですので、FFmpegがインストールされていないんです。
そのため、サムネイルも合せてアップロードするようになっています。
（FFmpegがない環境でも動画プラグインが動くようにしましたので、こんな形になりました）

本日のモクモク会で説明後、当issueをクローズしたいと思います。

**Comment by noricoco** [comment]
了解です。

**Comment by ClumsySmile** [comment]
仮想環境（CentOS）とレンタルサーバーにFFMPEGを入れて試しましたが、今の画像切り出しパラメーターでは切り出しができませんでした。
私の環境では、

-i MP4ファイル名 -f image2 -frames:v 1 出力画像名

で行けました。FFMPEG のバージョンによると思います。
現段階で、画像切り出しコマンドは VideoBehavior.php にべた書きになってしまっているので、環境に合わせて書き換えられるようにしておいた方が無難かと思います。

なお、php-gd がないとエラーで落ちますね。

**Comment by akagane99** [comment]
@noricoco 説明し忘れました。すみませんでした。

@ClumsySmile 情報感謝！

> -i MP4ファイル名 -f image2 -frames:v 1 出力画像名

手元の開発環境だと動かずでした。
上記ffmpegのバージョン教えてほしいです。

Ubuntsu12.04LTSのapt-getで取得できるffmpegのバージョンは以下の通りです。

```
ffmpeg version 0.8.17-4:0.8.17-0ubuntu0.12.04.2, Copyright (c) 2000-2014 the Libav developers
  built on Apr  1 2016 14:24:20 with gcc 4.6.3
```

> 画像切り出しコマンドは VideoBehavior.php にべた書きになってしまっている

提案感謝です。定数化で対応しようと思います。

> なお、php-gd がないとエラーで落ちますね。

あれ？ffmpegコマンドって、php-gd使ってるんでしたっけ？
バージョンによるのかなぁ。

**Comment by ClumsySmile** [comment]
CentOS 環境だと yum で入らないので、git でソース取得してビルドしてます。
バージョンは、

```
ffmpeg version N-81346-g0ea03db Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-17)
```

と出てますが、3.1.2（最新）です。

> あれ？ffmpegコマンドって、php-gd使ってるんでしたっけ？

失礼しました。
php-gd が入っていないと落ちるのは、/app/Plugin/Upload/Model/Behavior\UploadBehavior.php のメソッド _imagecreatefromjpegexif() でした。

**Comment by akagane99** [comment]
@ClumsySmile 

> -i MP4ファイル名 -f image2 -frames:v 1 出力画像名

ffmpegの最新ドキュメントで、コマンド確認しました。
- `-frames:v 1`は実体で`-vframes 1`はaliasとして定義されているので、`-vframes 1`で大丈夫でした。
- `-ss`のオプションを消されていたのですが、ドキュメントにはあり、最新ffmpegで使える事を確認しました。
  - `-ss`のオプションは、サムネイルを取得する秒数を指定しているので、必要でした。

そのためコマンドを下記に見直しました。
これでCentOSにいれたｆｆmpegでも動くかと思います。

```
-i MP4ファイル名 -ss 1 -vframes 1 -f image2  出力画像名
```

#### 参考リンク

https://ffmpeg.org/ffmpeg.html#Video-Options

> -vframes number (output)
> Set the number of video frames to output. This is an alias for -frames:v.

https://ffmpeg.org/ffmpeg.html#Main-options

> -ss position (input/output)

### 対応

https://github.com/NetCommons3/Videos/blob/75599f5c930b4c260d0b6c593260d5cdf7835d2a/Model/Video.php#L72

サムネイル画像については、これで対応完了です。

**Comment by akagane99** [comment]
@ClumsySmile 
タッチの差でコメント書いてしまった。

### バージョン感謝です

1つ前のコメント（ https://github.com/NetCommons3/NetCommons3/issues/493#issuecomment-240695539 ）のようにオプション見直しました。
最新ffmpegでも、これでいけるはずです。

### php-gdについて

了解、間違いだったようで安心しました。

**Comment by akagane99** [comment]
@ClumsySmile 

### php-gdについて2

imagemagickが入ってないとgd使うみたいです。
参考まで。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/493#issuecomment-240626035
上記説明通り、問題ないためクローズします。
