### ISSUE TITLE
タグの区切り

### ISSUE THREAD

**Issue by noricoco** [NetCommons3/NetCommons3#495]
タグの区切り文字として、半角の,のほかに全角の、，も対応しているか確認してください。多くの方は、タグを日本語で書き、そのまま日本語で区切り文字を書くと想定されます。その際、機種や設定により、　、　，　　の両方がありうると思います。

**Comment by RyujiAMANO** [comment]
タグは区切り文字ありません。ひとつひとつテキストボックスに入力して「タグ追加」でタグが追加される仕様になっています。

**Comment by noricoco** [comment]
タグを入力するテキストボックスが微妙に長いこともあって、ここに複数入れてしまいそうです。どうしたらアフォーダンス的によいでしょうね。
あ、わかりました。最初に２つ（今より少し短い）タグボックスを起きます。そして、右側にタグ追加ボタンをつければ、タグはひとつずつ区切ってボックスに入れることが容易にわかるのではないでしょうか。

**Comment by RyujiAMANO** [comment]
カンマ区切り方式に変更しました。全角でも区切れるようにしました。
