### ISSUE TITLE
システム管理　セキュリティ設定　IP変動を禁止する会員権限の表示における不具合

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#497]
IP変動を禁止する会員権限は、権限管理で追加した権限を含めて表示されるはずだが、
「システム管理者」、「サイト管理者」「一般」しか表示されない。

**Comment by s-nakajima** [comment]
現状でも表示されている。別のサイトと勘違いしたのではないでしょうか？

**Comment by ryu818** [comment]
勘違いということでClose
