### ISSUE TITLE
期限付き公開のブロックのコンテンツを期限切れ後に登録すると画面が白くなり操作不能になる

### ISSUE THREAD

**Issue by ohga21** [NetCommons3/NetCommons3#498]
ブロックを期限付き公開に設定（ブラウザA）
⇒期限内に一般ユーザで登録画面を表示（ブラウザB）
⇒ブロックを期限切れに変更（ブラウザA）
⇒登録画面で決定ボタンを押下（ブラウザB）
⇒画面が白くなる（ブラウザB）

非公開に変更した際も同様

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3/issues/460
