### ISSUE TITLE
NetCommons3 issueとNetCommons issueの使い分け

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#5]
https://github.com/NetCommons3/NetCommons/issues
にコア機能系のアイディアや課題が結構登録されてます。

提案ですが、課題・アイディア系はNetCommons3 Issueに集約しませんか？（あるいは専用で別リポジトリ切るとか別のシステムでもいいです。できればツール増やしたくはないですが）

なぜなら、
課題、アイディア系がNetCommons3 IssueとNetCommons Issueとに分散すると
状況把握が大変になりそうだからです。

各プラグインのIssueはそのプラグインで「やることが決まったコト」「不具合報告」のように何をするのか明確なモノだけにして、全体に影響しやすいことは1箇所で集約できればなと思います。

Issue #3 と合わせてもくもく会で話しできればと思います

**Comment by kteraguchi** [comment]
最初の入り口としてNetCommons3 Issueがあるイメージですね。なるほどです。

１．まずNetCommons3 Issueにあげる
２．検討、放置等をIssue上で議論する
３．対応方法が決まり、各Pluginの対応が必要な場合は、別途対象のPlugin Issueにあげる
４．Issue #3 のチケット管理は、NetCommons3 Issueと対象のPlugin Issueで別々に行う
　　　（担当が違うため）

チケットの種類はssue #3 で良いと思います。
これで進めましょう！

**Comment by RyujiAMANO** [comment]
+1
あとは今開発してくれてる開発者さんたちへ周知ですね（それと今後参加する人の為に開発者向けドキュメントへの追加か）

**Comment by kteraguchi** [comment]
ドキュメントに追加しました。
https://github.com/NetCommons3/NetCommons3/wiki/301.Issuesの利用
Closeします。
