### ISSUE TITLE
IP変動を禁止する会員権限の下部文言

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#500]
「IP変動を禁止しない場合、セッションハイジャックされる可能性があります。」は

「セッション中に異なるIPアドレスからのアクセスを禁止する会員権限を指定できます（DHCPではない環境では、管理者についてONにすることをお勧めします）。IP変動を禁止しておくことで、セッションハイジャックされるリスクが軽減されます。」

DHCPではなく・・・の箇所は誤りだったら修正して。修正前だと、禁止しておかないとセッションハイジャックされちゃう感がする。

**Comment by s-nakajima** [comment]
文章おかしかい気がしたので、修正してみた。

> セッション中に異なるIPアドレスからのアクセスを禁止する会員権限の指定ができます。
> 管理者については、ONにすることをお勧めします。IP変動を禁止することで、セッションハイジャックのリスクが軽減されます。
> ただし、DHCPを利用している環境では、IPアドレスが変わってしまうため、OFFにしないとログインできなくなります。
