### ISSUE TITLE
Twitter, facebook連携機能の見直し

### ISSUE THREAD

**Issue by noricoco** [NetCommons3/NetCommons3#506]
twitterに連携させるときに、単に
ブログ　－NC3　URL　（プラグイン名、サイト名、　URL)
と出ます。タイトルも詳細情報もなし。これではだめなのではないでしょうか。
ふつうは、
詳細- タイトル-サイト名　URLか
詳細 -サイト名　URLか
タイトル-サイト名　URL
のいずれかではないですか？

**Comment by RyujiAMANO** [comment]
WordPressサイトを見てみると 「タイトル 記事URL」という形が多そうなので
「タイトル - サイト名 記事URL」にしようと思います。
