### ISSUE TITLE
カレンダー時間が枠からはみ出る

### ISSUE THREAD

**Issue by noricoco** [NetCommons3/NetCommons3#513]
![nc_3](https://cloud.githubusercontent.com/assets/15189276/17769841/a1de58dc-6575-11e6-84e9-b203a10c6db0.png)

**Comment by RikaFujiwara** [comment]
対応済みです
CSSのキャッシュが残っていると、折り返さないので、すみませんが強制リロードお願いします

**Comment by RikaFujiwara** [comment]
すみませんです。完了取消しです。
ChromeではOKでしたがFireFoxでは時間部分が折り返してなかったので、再検討します。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Calendars/commit/11db7dd13bf945dda37c9fccf65b514535009fe5

"-"の両側にブランクを入れて、折り返しが可能なポイントを作り、かつ、CSSで半角が続いても折り返しあり、の設定を行った。
その他、NetCommonsのstyle.cssが追加されたこと二よりレイアウト崩れが発生していたところも、もともと考えていた表示になるようにCSS調整

**Comment by to-hashimoto-3** [comment]
すいません、本件対象おわりましたので、ＣＬＯＳＥさせてきただきます。
