### ISSUE TITLE
Berksfileのうごき

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#52]
備忘録
- vagrant up default時、vagrant ｐｌｕｇｉｎの`vagrant-berkshelf` berkshelf（chefの依存関係解決ツール。yumとかapt-getのchef版） が動く。
- https://github.com/NetCommons3/NetCommons3/blob/master/Berksfile が設定ファイル

```
source 'https://api.berkshelf.com'
```

によってapi.berkshelfの公式サイトよりデータひっぱてきてきてる。
- https://supermarket.chef.io/cookbooks/boilerplate#readme でここみてる（西川さんリポジトリじゃん！）
- https://github.com/topaz2/chef_boilerplate/blob/master/Berksfile 参照される
- https://github.com/topaz2/chef_boilerplate/blob/master/attributes/default.rb#L42 なんでかこのファイルも参照される（おおよそchefのお約束だろう）
- ここを書き換えればＯＫ、てか書き換わってないじゃん！  @kteraguchi 
- berkshelfすると、ユーザディレクトリ配下にキャッシュされる

`C:\Users\akaga\.berkshelf\`
`C:\Users\akaga\.berkshelf\cookbooks\boilerplate-0.5.10\attributes\default.rb (41,38):`
こんな感じ。

**Comment by akagane99** [comment]
#2

**Comment by akagane99** [comment]
### 暫定対応

forkして自分リポジトリ作成。それを修正して、参照させる。
可能であればプルリクなげる。けど、このリポジトリ、NetCommons3アカウントでリポジトリ管理したほうがよさそうだと思うけど、どうなんだろう？
https://github.com/akagane99/chef_boilerplate

↓
失敗。なんでかboilerplateのローカルにキャッシュされたものは、`apache2-mpm-prefork`入りだった。
公式リポジトリが勝っている？？まさかまさか。

**Comment by akagane99** [comment]
▼ Berkshelfを試してみる - Qiita（2013年の古い記事けど、コメントでフォローされてる）
http://qiita.com/uchiunyo/items/5aa243f7a39ae443e10d

**Comment by akagane99** [comment]
寺口さんと検討した。

> 可能であればプルリクなげる。けど、このリポジトリ、NetCommons3アカウントでリポジトリ管理したほうがよさそうだと思うけど、どうなんだろう？
> https://github.com/akagane99/chef_boilerplate

netcommons3アカウントで管理するようにする。
異論ある方は早めに突っ込んでー。

**Comment by akagane99** [comment]
### 参考情報

▼ Cookbookの管理を楽にするBerkshelfの使い方( ｰ`дｰ´)ｷﾘｯ とか。 - 256bitの殺人メニュー
http://d.hatena.ne.jp/akuwano/20140806/1407291260

▼ Chef-Solo + Berkshelf による自動環境構築 - Qiita
http://qiita.com/Salinger/items/3e9e4614f2187c1d7c01

**Comment by akagane99** [comment]
- NetCommons3にフォークさせた。
-  delete apache2-mpm-preforkした

https://github.com/NetCommons3/chef_boilerplate

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/blob/master/Berksfile#L3-L16

```
[西川]  cookbook 'apt', git: 'https://github.com/topaz2/apt', branch: 'firewall_workaround'　→西川さん製　
[西川]  cookbook 'boilerplate'　　　　　　→西川さん製　https://supermarket.chef.io/cookbooks/boilerplate
[西川]  cookbook 'boilerplate_jenkins', git: 'https://github.com/topaz2/chef_boilerplate_jenkins.git'　→西川さん製
[西川]  cookbook 'boilerplate_php'　　　→西川さん製　https://supermarket.chef.io/cookbooks/boilerplate_php
[誰か]  cookbook 'chef-dk'　　　　　　　　　→誰か製　https://supermarket.chef.io/cookbooks/chef-dk
[公式]  cookbook 'chef-server'　　　　　　　→chef公式　https://supermarket.chef.io/cookbooks/chef-server
[誰か]  cookbook 'composer', git: 'https://github.com/Morphodo/chef-composer.git'　→誰か製
[誰か]  cookbook 'docker'　　　　　　　　　　→誰か制　https://supermarket.chef.io/cookbooks/docker
[公式]  cookbook 'jenkins'　　　　　　　　　　→chef公式　https://supermarket.chef.io/cookbooks/jenkins
[西川]  cookbook 'mroonga'　　　　　　　　　→西川さん製　https://supermarket.chef.io/cookbooks/mroonga
[西川]  cookbook 'netcommons', git: 'https://github.com/NetCommons3/chef_netcommons.git'
[誰か]  cookbook 'php', git: 'https://github.com/trinitronx/php.git', branch: 'COOK-4439-add-php-5.5.9-support-on-ubuntu-12.04'   　　→誰か制
[誰か]  cookbook 'vagrant'  　　　　　　　　→誰か制　https://supermarket.chef.io/cookbooks/vagrant
[誰か]  cookbook 'virtualbox'　　　　　　　→誰か制　https://supermarket.chef.io/cookbooks/virtualbox
```

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/blob/master/Berksfile

と

https://github.com/NetCommons3/chef_netcommons/blob/master/Berksfile

に重複しているcookbookがある。

https://github.com/NetCommons3/NetCommons3/blob/master/Berksfile
のほうに書いてある重複した記述、もしかしていらないのでは？

↓

vagrant up こけた。とりあえず、ここはそっとしておく。

**Comment by akagane99** [comment]
> 寺口さんと検討した。
> 
> >  可能であればプルリクなげる。けど、このリポジトリ、NetCommons3アカウントでリポジトリ管理したほうがよさそうだと思うけど、どうなんだろう？
> > https://github.com/akagane99/chef_boilerplate
> 
> netcommons3アカウントで管理するようにする。

プルリク投げた。適用するよー。
https://github.com/NetCommons3/chef_netcommons/pull/1

**Comment by akagane99** [comment]
プルリク適用しました。topaz2 リポジトリ→NetCommons3リポジトリに置き換えただけなので。
NetCommons3/chef_netcommons#1

**Comment by akagane99** [comment]
不具合あり。vagrant up でこけた人、ごめんなさい。

https://github.com/NetCommons3/chef_netcommons/blob/master/Berksfile

```
cookbook 'boilerplate', git: 'https://github.com/NetCommons3/chef_boilerplate.git'   ←ここで不具合。tag指定なしなので、最新とっちゃう。
cookbook 'boilerplate_php', git: 'https://github.com/NetCommons3/chef_boilerplate_php.git'   ←不具合でてないけど、最新とっちゃう。
```

見直し必要。
その前に、windows10で成功したBerksfileファイル等を @kteraguchi に連絡する。
（来週中になりそう）

**Comment by s-nakajima** [comment]
全面見直しが必要。いったんClose
