### ISSUE TITLE
「`」登録画面で文字列を「`」で囲むとフォントが変わるさらに編集及び削除できないごみデータが作成できてしまう。

### ISSUE THREAD

**Issue by kitatsuw** [NetCommons3/NetCommons3#521]
「`」登録画面で文字列を「`」で囲むとフォントが変わる
font-familyがSTIXGeneral,"Cambria Math","Arial Unicode MS",serifに変化している。
強制的に数式モードで表示しているみたいです。

更にタイトルなどの入力欄に「`」を2つのみ入力し登録を行うと詳細画面及び一覧画面で必須項目のタイトルなどが見えなくなる（リンクもなくなる）

タイトルリンクを押せなくなりcontentの編集が詳細画面からしか行えないPluginでは軒並み編集及び削除できないごみデータが作成できてしまう。

上記に関しては環境依存文字を使用すると必須入力チェックを通りつつnullで登録できてしまうためごみデータが作成できてしまう。

![1](https://cloud.githubusercontent.com/assets/17841377/17808303/8685feb6-664a-11e6-8827-d638dd6d3e26.PNG)

![2](https://cloud.githubusercontent.com/assets/17841377/17808398/07283412-664b-11e6-83a8-c05bfe6d3e3e.PNG)

**Comment by go-to** [comment]
「$$」で囲むと事象が再現します。

**Comment by s-nakajima** [comment]
$$は仕様です。NC3全体として、TeXを表すものとするので！
やるなら、必須チェックで外す感じですかね！
