### ISSUE TITLE
カレンダーの日時不正アラートがおかしい

### ISSUE THREAD

**Issue by noricoco** [NetCommons3/NetCommons3#529]
症状：
一般によって入力されていたカレンダーの予定（8月23日ユーザカンファレンス）を承認しようとしたら、日時不正のアラートが表示された。
8月23日０時から０時の予定になっていたので、終了時間を23:59にしたが受け付けない。
終日予定にしたら入力された。
タイトルアイコンを編集したら、また日時不正アラートが表示された、

**Comment by to-hashimoto-3** [comment]
「8月23日０時から０時の予定になっていたので、終了時間を23:59にしたが受け付けない。」
これですが、datetimepickerの仕様により、５分刻みのみの受付となっております。なので、終日を時間レンジで表現するとき、２４：００はおなじく、datetimepickerには存在しない（＝datetimepickerが受け付けない）ので、8/23 00:00 - 8/24 00:00 （以上、未満）という形式になっております。なにとぞご了解ください。

「タイトルアイコンを編集したら、また日時不正アラートが表示された、」
＞こちらですが、内部チェックは複数のチェックをおこなっていますので、タイトルアイコンは正しく設定されたが、上記の件で日付入力形式の方でエラーがでたのでは、と拝察されます。

以上お願いいたします。

**Comment by to-hashimoto-3** [comment]
ちなみに、1分きざみの時間を登録できるよう制限（仕様）を変えた場合、画面に表示されるdatetimepickerのセレクタが、６０選択肢表示され、５分きざみにくらべ入力操作性が大きく低下すると考えます。

**Comment by noricoco** [comment]
了解です。現在のままということで理解しました。
ただ、入力の際の誤解を防ぐためには、23:59と入れたら、一番ちかい５分刻みにセットされるとよいかもしれません。この例の場合は、24日0:00か24日23:55分かのどちらかがよいかと思います。

**Comment by RikaFujiwara** [comment]
現在　調査したところ以下のようになりました。

ブラウザ画面側：
Pickerではなく、inputのテキストを直接編集して59分とか54分などの半端な分にしたところ、自動的に55とか00の近似値に丸められました。

この自動丸め機能は、カレンダーやNetCommonsHelperで対処されたものではなさそうです。
ちゃんと調べ尽くしていませんが、おそらくは「bootstrap-datetimepicker」側のバージョンアップで自動的に対応されたのではないかと考えます。


サーバー側：
特に５分刻みでないとエラーにするといったValidate処理は入っていません。
クライアントから送られた時分のままに投入ができるので、こちらのエラーチェック誤りはないと判断します。

以上の理由からこのISSUEはCloseにしたいと考えています。
