### ISSUE TITLE
ブログ、TODOのブロック設定画面「コメントを使用する」が文言統一されていない

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#533]
軽井沢で決まった文言統一話。ｘｘｘｘを使用する(ｘｘｘｘも使用する) で統一。
コメントは、これ使ってください。
https://github.com/NetCommons3/ContentComments/blob/11ffda68b947cf5392d1e4267d9ba813c3e1f8f7/Locale/jpn/LC_MESSAGES/content_comments.po#L68
### ブログ

![image](https://cloud.githubusercontent.com/assets/2756509/17838262/f8ea4fb0-6803-11e6-8228-954fb2d2a57e.png)
### TODO

![image](https://cloud.githubusercontent.com/assets/2756509/17838268/25688886-6804-11e6-9938-bfb380016d45.png)

**Comment by kitatsuw** [comment]
対応しましたのでタグ外します。

**Comment by RyujiAMANO** [comment]
ブログ対応しました。
