### ISSUE TITLE
一度公開したアンケートを一時保存にしてもアンケートに回答できる

### ISSUE THREAD

**Issue by netcommons** [NetCommons3/NetCommons3#537]
外部公開されているページで、一度公開したアンケートを「編集」で一時保存にしてもアンケートに回答できるのは仕様でしょうか？

**Comment by RikaFujiwara** [comment]
アンケートに限らずですが、
NetCommons３では一度公開したデータは、履歴が残ることで「公開データ」としてずっと公開され続けます（＝回答できる状態）

何らかの理由で、回答をさせたくない場合は、回答期間を制限して回答できなくするとか、表示形式設定で、一覧から外すとか、するしかないと思います。

**Comment by RikaFujiwara** [comment]
つまり仕様です。

**Comment by RikaFujiwara** [comment]
こちら仕様通りということでCloseさせていただきます。
