### ISSUE TITLE
小テスト複数選択の問題で複数正解がある場合の結果表示について（検討）

### ISSUE THREAD

**Issue by mikikosatou** [NetCommons3/NetCommons3#538]
複数選択問題で複数正解がある問題で、一部分のみ回答した場合、
回答結果の左に緑○がでるので、一瞬正解（または部分点がある）と間違えやすいと思いました。

![default](https://cloud.githubusercontent.com/assets/10765970/17845565/c891a79e-687d-11e6-9a4d-51f96116f759.png)

**Comment by RikaFujiwara** [comment]
選択肢個別に○×つけるのは、やはりやめにします。
部分点機能がないのに、選択肢個別に○×付けるのは意味がないですね。

**Comment by RikaFujiwara** [comment]
対応済み
https://github.com/NetCommons3/Quizzes/commit/edaf1eb0f374276686edceeeb8d0e31269828d8c
