### ISSUE TITLE
WYSIWYG非表示だとrowsオプション指定が効かない

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#541]
Blogsの続きを書くで、あとからWYSIWYGを表示させるケースだとrowsオプションがきかない。

すでに続きを書いてあり、編集するケースだとrowsオプション有効になる

**Comment by s-nakajima** [comment]
非表示（display:none）になっているTinyMCEのWysiwygに対してrowsのheightにならないため、optionsでheightを指定できるようにする。

詳しく追ってはないが、この TinyMCEのJS内にvisibleというコードがあるのtextareaがvisibleになっているもののみ対応している模様。
https://github.com/tinymce/tinymce-dist/blob/b1a185342e17e8bf331459c41c36b63e1d089117/tinymce.js
