### ISSUE TITLE
README.md で "cd NetCommons3" , "bundle" とは?

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#550]
すみません。教えていただいてよろしいでしょうか。

今、README.md を拝見しつつインストール作業中です。
「依存性ライブラリのインストール」の項でわからないところがあります。

(1) cd NetCommons3

ubuntu と OS Xの場合に、「cd NetCommons3」と操作することになっています。
しかし、そういうディレクトリがあるわけではないので、「No such file or directory」とエラーになります。NetCommons3というディレクトリが予めどこかに作っておくということでしょうか。
もし作る場合、任意のディレクトリ内でよろしいのでしょうか。

(2) bundle

ubuntuとOS Xの場合、(1)の操作の後に「bundle」を実行することになっています。
しかし、bundleは、whichコマンドで探しても見当たりません。
brew install bundle などとして、bundleなるものを予めインストールしておくべきということでしょうか。

なお、brewは予めHomebrewのサイトに行ってインストール済みです。
また、npmもデフォルトではインストールされていませんので、brewインストール後に brew install npmと操作してインストールしました。bundleもそうしたたぐいのものなのでしょうか。

以上、よろしくお願いいたします。

**Comment by ToshiAkaz** [comment]
(1)の質問で NetCommons3 というディレクトリを作成する場合、「ソースの配置」の項で「

**Comment by akagane99** [comment]
windows環境なもので、推測ですが回答してみます。
（macで検証したいけど、バタバタで時間作れそうにないです＞＜）

> (1) cd NetCommons3

ReadMeに書いてある順番は前後しちゃってますが、おそらく https://github.com/NetCommons3/NetCommons3　をダウンロードしたディレクトリなのかなと思います。
違ってたらごめんなさい。

> (2) bundle
> brew install bundle などとして、bundleなるものを予めインストールしておくべきということでしょうか。

多分その通りだと思います。

こんなんで参考になれば幸いです。

**Comment by ghost** [comment]
ありがとうございます。長らく見落としてました。
もう手でインストールすることもないと思うのでcloseしておきます。
