### ISSUE TITLE
カテゴリ名に長文を入れられた場合、カテゴリ絞り込みdropDownが枠をはみ出す。

### ISSUE THREAD

**Issue by kitatsuw** [NetCommons3/NetCommons3#555]
![isuues01](https://cloud.githubusercontent.com/assets/17841377/17955005/e1e03ad8-6ab9-11e6-8d6f-a7d4b7379b8d.png)

**Comment by akagane99** [comment]
外枠にcssでoverflow: hidden;で対応できそう。

``` css
overflow: hidden;
```

中央画面乗っ取り前は、.media, .media-bodyで上記効いてるけど、
乗っ取り後は.media, .media-bodyのclass消えてるので、効かなくなっていた。

**Comment by akagane99** [comment]
overflow: hidden;でいくなら、スマホで見た時隠れすぎて意味不明に
なっていない事を確認する。
意味不明なら、このままで行く選択肢もありと考えます。

**Comment by akagane99** [comment]
やってみたけど、件数0件のカテゴリで隠れすぎて選択できなくなった。
overflow: hidden;対応はダメっぽい。

対象プラグインの運用上、長すぎるカテゴリをつけて表示が崩れたなら、カテゴリ名を見直すべき。
（表示はみ出してもいいなら、長いカテゴリ名でもつける事ができる）
という事で対応なしクローズにします。

もし他の対応方法があるなら、またissue立ち上げましょう。

![image](https://cloud.githubusercontent.com/assets/2756509/17990287/3d183bb6-6b6f-11e6-8155-9d596472b8f5.png)

![image](https://cloud.githubusercontent.com/assets/2756509/17990293/510e7b8a-6b6f-11e6-8f0e-5781160e086a.png)

**Comment by kitatsuw** [comment]
![isuues05](https://cloud.githubusercontent.com/assets/17841377/17990396/51a7dae0-6b70-11e6-8768-f4f02ec41a16.png)

下記のようなCSSを当てて見てはどうでしょうか？
    min-width: ～px;
    max-width: ～px;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;

カテゴリ選択時に選択したカテゴリ名が画面上に表示されているのでdropDownで省略してみるのはどうでしょうか？
min-width: ～px;
max-width: ～px;は別のものにした方が良いとは思いますが。
これで行けそうであれば暫定対応という形でやってみるのもありかと。

**Comment by akagane99** [comment]
@kitalab PC、タブレット、スマートフォンに対応できそう？できそうなら、プルリクエストお願いだ

**Comment by kitatsuw** [comment]
@mediaでwidth指定してmax-width: ～px;の値を変えていけば対応可能だと思います。
検証して対応でき次第プルリク送ります。

**Comment by kitatsuw** [comment]
Linksはカテゴリを使用しているが画面崩れ箇所が起きないためタグを外します。

**Comment by kitatsuw** [comment]
FaqsはCategriesのHelperを直接読んでいるのでCategriesにCSSを差しこむことで解決できるのでタグを外します。

**Comment by akagane99** [comment]
プルリクサンキューでした。マージしましたので、動画ラベル外しました。

**Comment by RyujiAMANO** [comment]
プルリクマージしたのでBLOGラベル外しました。

**Comment by s-nakajima** [comment]
全て、外れたのでCloseします。
