### ISSUE TITLE
アンケートの回答完了データ登録処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#56]
https://github.com/NetCommons3/Questionnaires/blob/90ca24a09fc2a4bb3121248cabaabfd3f4ae766c/Controller/QuestionnaireAnswersController.php#L255

モデルでトランザクション開始（beginメソッド）しないと、masterに切り替わらないと思います。

**Comment by RikaFujiwara** [comment]
対応済み
