### ISSUE TITLE
登録編集画面で開発者モードを使用しselectタグ内選択肢のvalueに不正な値を入れ登録処理を行った際、リダイレクト画面のselectタグ内が空欄になる

### ISSUE THREAD

**Issue by kitatsuw** [NetCommons3/NetCommons3#560]
![isuues06](https://cloud.githubusercontent.com/assets/17841377/17991037/4a3ac622-6b76-11e6-9e04-9eacfcd673d0.png)

**Comment by go-to** [comment]
修正しました。
