### ISSUE TITLE
パブリックスペースで管理者たちに公開メールが送られない

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#562]

**Comment by akagane99** [comment]
- 私も忘れていましたが、承認完了を配信した人には、ほぼ同じ内容なので公開メールは送らないようにしていました。
- 承認完了受け取っていない人で、ルーム配信に該当する人には、ルーム配信メール送ってました。

修正する事も出来ますが、承認完了時には、登録者と承認者達に2通（承認完了、ルーム配信）くることになり、かなりうざったいので、このまま行きたいんですが、いいよね？

https://github.com/NetCommons3/Mails/blob/master/Model/Behavior/MailQueueBehavior.php#L638
https://github.com/NetCommons3/Mails/blob/master/Model/Behavior/MailQueueBehavior.php#L665

**Comment by RikaFujiwara** [comment]
これって、「グループルームでコンテンツ登録したとき、投稿者以外に公開通知メールが送られない」問題ですか？

**Comment by akagane99** [comment]
> これって、「グループルームでコンテンツ登録したとき、投稿者以外に公開通知メールが送られない」問題ですか？

承認完了を受取ってたら、同じ問題ですね。
それすら受け取ってなかったら、別問題になります。

**Comment by RikaFujiwara** [comment]
承認完了を配信した人には公開メール送らない、はありだとおもいますが。
問題は、承認権限を持っている人が、いきなり投稿したときかな。

その時は承認フローがすっ飛んで、いきなり公開なので、承認メールが送られてないし、
そして公開通知メールも来ないってことになっちゃいません？

**Comment by akagane99** [comment]
> その時は承認フローがすっ飛んで、いきなり公開なので、承認メールが送られてないし、
> そして公開通知メールも来ないってことになっちゃいません？

そこはちゃんと作りこんでいて、ルーム配信メールがルームに飛ぶのですよ。

**Comment by akagane99** [comment]
local開発環境で、パブリックスペースのルーム管理者たちにメール送られていない症状確認。
バグだぁ。
