### ISSUE TITLE
長いブロック名だとブロック一覧でテーブルの横スクロール発生

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#572]
![スクリーンショット 2016-08-26 18.08.14.png](https://zube.io/files/NetCommons3/ed1cffc0090ec0b827a8ab6ee9806c5b.png)

MacChromeだけかもだが、テーブル横スクロールが発生すると現状のデフォルトスタイルだと右にカラムが存在するのがわからない。

ブロック名部分は折り返しOKにした方がいいと思うけどどうかな？

**Comment by RyujiAMANO** [comment]
たぶん、全プラグインで発生してると思われる

**Comment by akagane99** [comment]
windows Chromeだとこう見えるので、右に何かありそうとわかるんですよね。
![image](https://cloud.githubusercontent.com/assets/2756509/18002908/b8883fde-6bc5-11e6-8461-06ae3cab14bb.png)

mac Chromeは横スクロールバー消えてる、横スクロールさせるとうっすら表示（デザインでそうなってる）なので、
わかりずらいんですよね。（・・・とお客さんにも別案件で説明した事があったなぁ）

**Comment by s-nakajima** [comment]
ある程度の文字で折り返すように修正
https://github.com/NetCommons3/NetCommons/commit/80c4900e827d87ae7de008ebb99617586a3a09d0
