### ISSUE TITLE
アバターの閲覧許可。

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#578]
「アバターが閲覧できない。」と権限設定で行い
ポップアップの会員情報では表示されていないのに
「users/users/download/19/avatar/medium」を直接みると、みえてしまう。
（ippan001/ippan001会員で別の一般会員の会員情報を表示(masukawa2/masukawa2)し現象確認）

これを修正することによって、今度は、会員管理で表示しているアバターが
個人情報的で非公開に設定されていると、表示されなくなるはずなので
こちらも併せて修正する必要ある。
（会員管理のアバターのＵＲＬも同じだったため）

一律で、会員管理が使えるならば、見せるような安易は修正はしないこと。
（ルームと管理系での個人情報をわけて管理している意味がなくなる）
管理系のほうから押すとＵＲＬをパラメーターを１つつけて
そのパラメーターがＯＮかつ、会員管理が使えるならば、表示する？
管理系のすべてのアバターを表示するところにつけるという労力はかかるけど、
ほかの情報を信用すると不具合につながるから仕方ないかな。

**Comment by s-nakajima** [comment]
アクションで分けるよう修正。
会員管理は、user_manager/user_manager/download/xxx
その他は、users/users/download/xxx。
