### ISSUE TITLE
ページ編集でのパーマリンク

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#584]
パーマリンクを以下のようにコンテンツをさすと、
ページクリック時にそのコンテンツが表示するだけになる。
blogs/blog_entries/view/99/f31a7a5472ea0292052b42a7d46663e2?frame_id=61

これはこれで、おもしろいし、裏技？として、この仕様にのこす？
これによって、動作不能になるとか、不具合につながらないならいいのかなとか思う

あと、一般でもルーム権限がルーム管理者なら、この編集できるだろうから
いたずらされないかと心配かな。ちょっとしたページをお気に入りみたいに使える機能だけならよいけどねぇ

**Comment by ryu818** [comment]
パーマリンクに「javascript:alert(1);」と入力すると、トップページに遷移した。

**Comment by s-nakajima** [comment]
「javascript:alert(1);」でエラーにすべき

**Comment by s-nakajima** [comment]
バリデーションを追加する。
