### ISSUE TITLE
migrationのupdateAndDeleteが意図通りでないと思われる

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#586]
BlockSettingMigrationとMailsMigrationにupdateAndDelete()があるが、動作が意図してない動きになってるように思える。

コードを眺めた感じだと、おそらくすでにあるレコードを更新する意図だと思われるが、実際にはマイグレーション実行すると新規にレコードが追加される。

理由は内部的に呼び出してるupdateRecords()でデータ削除に失敗しているため。

NetCommonsMigration::updateRecords()にも問題があり、
$clear= trueで呼び出したとき（デフォルト）はそのModelの全データを削除しようとしてる。（これが失敗してるので新規レコード追加になってる）
Modelの全データ削除だとMailsやBlockSettingのように他のプラグインに横断的に使われてるモデルだと、新規プラグインが追加されたときに別のプラグインのBlockSettingやMailSettingまで削除されてしまう。
なのでupdateRecords()は横断的に使われるプラグインのマイグレーションで使っちゃダメだと思われる。

BlockSettingMigration, MailsMigration（もし他に横断的に使われるモデルのレコードMigrationがあればそれも）では、NetCommonsMigration::updateRecords()を使わないで自前でデータ更新するとか、ちゃんとFindしたデータを更新してupdateRecords($model, $records, false)で呼び出すとか変更が必要そう。

将来のアップデート時に設定データ消失の原因になりそうなので、修正の重要度は高そう

**Comment by akagane99** [comment]
Mails,Blocks対応したのでLabel外します。

**Comment by akagane99** [comment]
ざっくり調べてみました。

### updateRecords 影響と使っているパターン

NetCommonsMigration::updateRecords を使ってるのは、全プラグインでざっと60か所。
$clearを指定して使っている箇所は無かった。

使っているパターンは、おおよそ２パターン

　(1). 各プラグインで定義している 001_plugin_records系の初期データ投入
　(2). プラグイン個別の初期データ投入

(1) は事故る

おそらく(2)のパターンを意識して全削除を入れたと推測。（お知らせの初期データにid入りのものがあった）
初期データを消すために、全削除をするべきではないと思える。（話がそれるので、これはちょっと置いておく。）

### 修正案

updateRecordsのデフォルト値（$clear = true)をいじって
(1)か(2)に修正プルリクが必要そう。
修正箇所が少ない方を選びたいな。

### NetCommonsMigration::updateRecords()のModel全削除

下記に修正すれば、全削除できた。

```
$Model->deleteAll(array('1 = 1'), false, false)
```

**Comment by akagane99** [comment]
現状 NetCommonsMigration::updateRecords のデフォルト値（$clear = true)は機能していなくて、全削除されてない。
全削除されていなくて、初期インストール時にこけていない事から、デフォルト値（$clear = false)にしても悪さしないと考えます。

そのうえで、全削除したいマイグレーションがあるならば、個別に$clear = trueを設定してもらうので、良い気がしてきました。
よし、上記でプルリクエスト投げます。

**Comment by akagane99** [comment]
NetCommonsMigration::updateRecords()を修正したのでクローズします。
