### ISSUE TITLE
キャビネット名に「ああああ<>」で登録すると、内部エラーになる

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#595]
![image](https://zube.io/files/NetCommons3/a68a5dac04c210ef9fb1d10c163aca48.png)

**Comment by RyujiAMANO** [comment]
ルートフォルダをつくるときのvalidationErrorか。
キャビネット名は実ファイルシステムに依存しないから、ルートフォルダ作成時はファイル名validation外すのがよさそう
