### ISSUE TITLE
Current:: で現在システム時刻を取得できるように

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#6]
タイムゾーンを考慮したシステム時刻を取得する共通関数が作成される方向になっているかと記憶しています。
この時間を取得するのをCurrentにメソッド追加で対応するというのはいかがでしょうか

**Comment by RyujiAMANO** [comment]
＋1

**Comment by RyujiAMANO** [comment]
CurrentでなくCakeTimeあたりでやるかも

**Comment by RyujiAMANO** [comment]
NetCommonsTime::getNowDatetime()で実装済み
