### ISSUE TITLE
コミュニティがルーム管理者で、パブリックが一般なのにヘッダーの編集ボタンが表示される。

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#609]
コミュニティがルーム管理者で、パブリックが一般なのにヘッダーの編集ボタンが表示される。
（コミュニティのページを表示している場合に表示される。）

上下左右のカラム、プラグインの追加も同様。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3/issues/726
