### ISSUE TITLE
ルーム管理のコミュニティ下のサブルームの参加者の選択

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#610]
ルーム管理のコミュニティ下のサブルームの参加者の選択で、親のコミュニティに参加していない会員も
参加することができる。

**Comment by s-nakajima** [comment]
会員選択時と、親から会員を除かれたときにサブも一緒に削除する必要ある。
すでに誤って入っているかもしれないので、Migrationの提供も必要。

**Comment by kteraguchi** [comment]
会員管理の「参加ルームの選択」も同様
