### ISSUE TITLE
「担当者への連絡」のメールについて

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#611]
問題点）コンテンツ編集時は、ワークフローが走らない限り、「担当者へ連絡（メール）」してくれない仕様のようですが、編集においても「コメント」が追加されたのだから通知してほしい

修正するとすれば、以下のパターンのいずれか。

(1). 編集時、「コメント」入力ありなら、「通知を受け取る権限（ルーム配信）」におくる。
(2). 編集時、「コメント」入力ありなら、承認者(ルーム管理者、編集長)であっても「ルーム管理者、編集長、編集者へ（＋投稿者）」におくる。
(3). 編集時、「通知を受け取る権限（ルーム配信）」に必ずおくる。
(4). 編集時、「ルーム管理者、編集長、編集者へ（＋投稿者）」に必ずおくる。

「コメント」は「ルーム管理者、編集長、編集者へ（＋投稿者）」しか見えない承認コメントなので、(2)を採用。

**Comment by akagane99** [comment]
承認フローの定型文は、承認依頼、差し戻し、承認完了の３つ。
(2)の時送るメールは、上記に該当しないので、「担当者への連絡」定型文を追加。

**Comment by akagane99** [comment]
対応済みクローズ
