### ISSUE TITLE
「メール通知機能を使う」の設定

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#612]
お知らせ(RSS)の場合、現在、
「メール通知機能を使う」の設定は使用されておらず、
追加時は必ず、「承認メール通知機能を使う」がルームの設定によって決まってしまう仕様となっています。
（新規登録時はメール設定画面へ遷移できないため）

後者の「承認メール通知機能を使う」がルームの設定によって決まるのは、
仕様としても、よいと思いますが、
「メール通知機能を使う」の設定が無意味なので、
「メール通知機能を使う」を設定できなくすること。

（メール設定画面は、「承認メール通知機能を使う」のチェックボックスだけになって、通知を受け取る権限、件名、本文（当然、「メール通知機能を使う」も）はなくなる。）

**Comment by akagane99** [comment]
メール対応済みでラベル外しました

**Comment by akagane99** [comment]
対応済みクローズ
