### ISSUE TITLE
app\Config\application.yml　これどこで作ってる？

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#62]
自動生成されてるけど、これってどこのプログラムで作ってるか、ご存じのかたいる？
C:\projects\NetCommons3\app\Config\application.yml

**Comment by akagane99** [comment]
```
PhpDocumentor:
  classHeader: |
```

の記述が足りてないので、追加したいのです。

**Comment by s-nakajima** [comment]
application.ymlを作っているところは下記。
https://github.com/NetCommons3/Install/blob/master/Controller/InstallController.php#L448-L455

実際にPhpDocumentorの設定値が書かれているところは、
https://github.com/NetCommons3/NetCommons/blob/master/Config/bootstrap.php#L14-L19

**Comment by akagane99** [comment]
thx!
修正してプルリクなげます。
