### ISSUE TITLE
権限管理の基本設定「グループを作成できる」がＯＦＦなのに回覧板の「個別に選択」が表示される。

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#625]
権限管理の基本設定「グループを作成できる」がＯＦＦなのに回覧板の「個別に選択」が表示される。

**Comment by go-to** [comment]
権限管理のUI変更に伴い修正が必要ということですね、対応します。
https://github.com/NetCommons3/UserRoles/commit/51e71389f0189531d1c2c2b4b19a809793e417e9
