### ISSUE TITLE
登録フォームでメールタイプにてメール書式ではない入力を行った場合のメッセージ

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#629]
ヘッダーメニューのエラーに「入力した内容に誤りがあります。内容を確認してください。」と表示されるのはよいが、メールテキストの下のメッセージも「入力した内容に誤りがあります。内容を確認してください。」となり、なにが間違ったのかわからない。

**Comment by RyujiAMANO** [comment]
Mailsプラグインのメールアドレス入力チェックエラーと同じメッセージを採用することにした。
