### ISSUE TITLE
WYSIWYGってどこに配置されている？

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#63]
誰か知ってたら、おしえてー

**Comment by s-nakajima** [comment]
お知らせプラグイン

**Comment by akagane99** [comment]
thx!

**Comment by akagane99** [comment]
利用しているプラグインがお知らせ、という事ね。

netcommonsリポジトリにあったこいつで呼び出してるっぽい。
https://github.com/NetCommons3/NetCommons/blob/master/webroot/js/wysiwyg.js

本体は、bowerとかで持ってきてそう。
バージョン固定してるかな、どうかな？

**Comment by s-nakajima** [comment]
angular-ui-tinymceのバージョンに合わせてる。
https://github.com/NetCommons3/NetCommons3/blob/master/bower.json#L16

**Comment by s-nakajima** [comment]
bower updateすると、NC3にインストールされるTinyMCEは、現最新の4.3.1っぽいですね。

**Comment by akagane99** [comment]
thx!

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons/blob/master/View/Helper/NetCommonsFormHelper.php#L347-L370

ＮＣプラグイン（例：お知らせ）から呼び出し
https://github.com/NetCommons3/Announcements/blob/master/View/Announcements/edit.ctp
