### ISSUE TITLE
いいねボタンを一覧からでも押したい

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#634]
押すスペースも変わらないし、記事がみえているのだから、押したい。
唯一、動画は、動画みてから押すという導線となりよいきもするが
これもほかが一覧からでも押せるようになるなら、押させてようとおもう。

（※　動画：ルーム管理者なのに、詳細画面から「いいね」できなかった）
（※　FAQ：一覧にはそもそもいいねアイコンがない。詳細へはリンクを右クリックして別タブに表示するしかなく、実質的にいいね　できないに等しい）

**Comment by s-nakajima** [comment]
FAQはあるので、ラベル外す

**Comment by akagane99** [comment]
> （※　動画：ルーム管理者なのに、詳細画面から「いいね」できなかった）

検証環境で動作確認しました。
いいねできたので、問題ないと思います。

いいねできるできないは、ロール（ルーム管理者）を見てないように思います。

**Comment by RyujiAMANO** [comment]
Blog対応。リリースまではLabel残しておきます。

**Comment by akagane99** [comment]
動画は詳細画面で再生してみるため、一覧からはいいねさせない。
ラベル外します。
