### ISSUE TITLE
インストール時、ＤＢユーザ名不正のとき、エラーメッセーが正しく表示されない

### ISSUE THREAD

**Issue by to-hashimoto-3** [NetCommons3/NetCommons3#637]
ＮＣ３インストール時、ＤＢユーザ名に、データベースに存在しない名前をいれたところ、validationエラーとなったがその時のメッセーが、 undefined/ だった。ここは、意味のわかるメッセージにしてほしい。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3/issues/655
これで対応したのでCloseする
