### ISSUE TITLE
カレンダー　月拡大表示の要望

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#646]
NetCommonsプロジェクト　事務担当者からの強い要望です。
頻繁に使ってて、よっぽど不便なのだと思いissueとしてあげます。

月大表示のカレンダーしたに月の移動、今月への移動の部分をつけてほしいそうです。
週表示・日表示も同様にあったほうがよいきがします。
イメージとしては、以下のようなかんじでお願いできればと思います。
ご検討のほどよろしくお願いいたします。

![- nc3](https://cloud.githubusercontent.com/assets/2410721/18114530/ad9002d2-6f72-11e6-81b0-8dd9a869433c.png)

**Comment by RikaFujiwara** [comment]
スマホ表示のときとかに下にも操作ボタンがないとつらいってことですかね？

**Comment by ryu818** [comment]
スマホ表示はどうでしょうねぇ。操作してみないとわからないです。でも、表示されてても困ることはないのではないでしょうか。

**Comment by RikaFujiwara** [comment]
おっと。私の勘違いであったようです。スマホのときにツライ、ということではなくPC表示のときにも下の表示が欲しいということだったのですね。
了解です。
表示していても困ることはないので、こちら対応するようにします。

**Comment by ryu818** [comment]
「本当にありがとうございます。」とのことでした。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Calendars/commit/b733786200a5092e3a586425f23eb8a042eb0c42
