### ISSUE TITLE
「すべての会員をデフォルトで参加させる」にチェックを入れて次へボタンを押すと内部エラーが発生

### ISSUE THREAD

**Issue by go-to** [NetCommons3/NetCommons3#652]
ルーム管理のコミュニティ / ルーム作成画面で、「すべての会員をデフォルトで参加させる」にチェックを入れた状態で次へボタンを押すと内部エラーが発生する（PHP7環境で事象確認）

![netcommons3](https://cloud.githubusercontent.com/assets/2410870/18119439/90c971c4-6f95-11e6-93c4-a911fe939453.png)
![500 internal error netcommons3](https://cloud.githubusercontent.com/assets/2410870/18119441/915f18fa-6f95-11e6-8bcb-1af24ebc8673.png)

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3/issues/654 の問題であるため、こっちのISSUEはCloseする。
