### ISSUE TITLE
MySQL5.6の環境で動作させるとDatabase Errorが起きる

### ISSUE THREAD

**Issue by kitatsuw** [NetCommons3/NetCommons3#654]
小テスト
小テスト追加で小テスト設定画面で決定を押下時
![db](https://cloud.githubusercontent.com/assets/17841377/18121526/ed9216f4-6f9f-11e6-9a00-677758cd42ef.png)
ToDo
ブロック追加で決定を押下時
![db 2](https://cloud.githubusercontent.com/assets/17841377/18121527/eec52cfa-6f9f-11e6-9513-908af879f6d3.png)
回覧板
フレームに配置時
![db 3](https://cloud.githubusercontent.com/assets/17841377/18121528/effdf05c-6f9f-11e6-92b6-520933a5e1d3.png)

原因はmy.cnf内のsql_modeにSTRICT_TRANS_TABLESが設定されているため。

**Comment by kitatsuw** [comment]
検索ボックス
表示方法変更画面のデフォルトで検索対象とするプラグインで決定を押下時
![db 4](https://cloud.githubusercontent.com/assets/17841377/18123709/0c7669e4-6faa-11e6-9087-c291e88d7e10.png)

**Comment by s-nakajima** [comment]
このISSUEも同様
https://github.com/NetCommons3/NetCommons3/issues/652

**Comment by kitalab** [comment]
カレンダー
フレームに配置時
![db 5](https://cloud.githubusercontent.com/assets/17841377/18153113/3a0a0cc6-7036-11e6-8a13-958cf711be52.png)

**Comment by kitatsuw** [comment]
カレンダーのエラーは勘違いですのでタグ外します。

**Comment by kudarisenmon** [comment]
MySQL 5.7でも同じ結果になりました。
5.7.15-0ubuntu0.16.04.1 (Ubuntu)

**Comment by kudarisenmon** [comment]
![2016-09-22 7 49 07](https://cloud.githubusercontent.com/assets/2560699/18731821/869cb3fe-8099-11e6-8158-e688d86140f0.png)
小テストのところのグラフ？のアイコンを押すと以下のエラーになります。

Database Error
Error: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'nc3.Statistics.user_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SQL Query: SELECT `QuizAnswerSummary`._, `User`._, `Statistics`._, `LastAnswer`._ FROM `nc3`.`quiz_answer_summaries` AS `QuizAnswerSummary` LEFT JOIN `nc3`.`users` AS `User` ON (`QuizAnswerSummary`.`user_id` = `User`.`id`) LEFT JOIN (SELECT user_id, MAX(id) AS id, MAX(passing_status) as passing_status, MAX(within_time_status) as within_time_status, AVG(elapsed_second) as avg_elapsed_second, MAX(summary_score) as max_score, MIN(summary_score) as min_score, MIN(passing_status) as not_scoring FROM `nc3`.`quiz_answer_summaries` AS `Statistics` WHERE `Statistics`.`quiz_key` = '5810ccf4f1d98fa2bd69efe0934bc7a7' AND `answer_status` = 2 GROUP BY CASE WHEN user_id IS NULL THEN id ELSE user_id END) AS `Statistics` ON (CASE WHEN `Statistics`.`user_id` IS NULL THEN `QuizAnswerSummary`.`id` = `Statistics`.`id` ELSE `QuizAnswerSummary`.`user_id` = `Statistics`.`user_id` END) LEFT JOIN (SELECT user_id, id, summary_score, is_grade_finished FROM `nc3`.`quiz_answer_summaries` AS `LastAnswer` WHERE `quiz_key` = '5810ccf4f1d98fa2bd69efe0934bc7a7' AND `answer_status` = 2) AS `LastAnswer` ON (`Statistics`.`id` = `LastAnswer`.`id`) WHERE `QuizAnswerSummary`.`quiz_key` = '5810ccf4f1d98fa2bd69efe0934bc7a7' AND ((`QuizAnswerSummary`.`id` IS NULL) OR (`QuizAnswerSummary`.`user_id` IS NULL)) ORDER BY `User`.`handlename` DESC LIMIT 10

**Comment by akagane99** [comment]
mysql の strict mode、3.1.10で対応したため、クローズします。
https://github.com/NetCommons3/NetCommons3/issues/1262
