### ISSUE TITLE
新着、「全てのステータス」条件、未ログインでも「承認待ち」等選べました

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#661]
未ログインなら「全てのステータス」は、非表示で問題ないと思います。

![image](https://cloud.githubusercontent.com/assets/2756509/18296834/6bce9ec4-74e7-11e6-8c6d-86dffb0a0d60.png)

**Comment by akagane99** [comment]
@s-nakajima プルリクエストなげました。トラビステストOKなら、マージしてほしいです。

**Comment by s-nakajima** [comment]
PullReqありがとう。ただ、まだマージしてないけど、私のローカルで修正済みで、競合すると面倒なので、このPullReqマージしません。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3/issues/635
このIssueと同じなので、Closeします。

**Comment by akagane99** [comment]
失敬！＆対応ありがとう。
