### ISSUE TITLE
回答期限の日付フォーマットがおかしい

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#673]
DateHelperを使っていると思うが、第二引数でフォーマットが指定できます。この部分は、Y/m/d H:i 形式固定で良い。

![image](https://zube.io/files/NetCommons3/4ada34a0386a4fe9023972dda143fdd4.png)

回覧板は、月日が出ているが、年も表示しても良いと思う。また、時間も指定できるわけだし、時分まで出さないと問題になると思う。

**Comment by RikaFujiwara** [comment]
Questionnaires　完了
https://github.com/NetCommons3/Questionnaires/commit/77241bb516783c6d19675010dfc2985e39cccb4e

**Comment by RikaFujiwara** [comment]
Quizzes 完了
https://github.com/NetCommons3/Quizzes/commit/8076fe6392a8f60e62fe219b2a09b35422699ad5

**Comment by kitatsuw** [comment]
CircularNotices対応済み

**Comment by RikaFujiwara** [comment]
アンケート、小テスト、回覧板、それぞれ対応終わっているってことなので、状態を「完了」に変えました。
既にリリースもされているのではないでしょうか？
