### ISSUE TITLE
afterFindでデータくっつけるビヘイビアの動作とrecursive設定を連動させる

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#68]

**Comment by RyujiAMANO** [comment]
TagやFilesの添付ファイル等をafterFindで元データにくっつけて返すとき

recursive -1だったらくっつけない
recursive 0以上でくっつける

とした方が、不要なときに余計な負荷を発生させなさそう。

NetCommons3として方針をまとめた方がよさそう

参考 http://www.cpa-lab.com/tech/public/image/spok/200802/CakePHP_recursive_attention.jpg

**Comment by kteraguchi** [comment]
👍
いいですね。賛成っす。

**Comment by s-nakajima** [comment]
該当するプラグインは、要調査。とりあえず、心当たりありそうなプラグインのラベルを付与。

**Comment by akagane99** [comment]
ContentCommentのビヘイビア、対応済みのためタグ外しますね。
https://github.com/NetCommons3/NetCommons3/issues/163

**Comment by akagane99** [comment]
tagsプラグインは対応済みでした。
https://github.com/NetCommons3/Tags/commit/dc9b6eb7591b9d8d0806d19e8b6a3418eb2f6386

**Comment by akagane99** [comment]
カテゴリプラグインのビヘイビアは１つのみでfindないため、対象外のように見えます。
https://github.com/NetCommons3/Categories/blob/master/Model/Behavior/CategoryBehavior.php

そのため、 ~Likesプラグインのプルリクエストがマージされたら、~ 当イシューは対応完了かと思います。
→（6/29追記）Likesプラグインはsetupでmodelをbindしてるだけだったから対応不要でした。
