### ISSUE TITLE
カレンダーの予定削除クリック時

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#680]
他のプラグインだと確認アラートがでて削除なのに、カレンダーはポップアップ画面が表示される。

**Comment by RikaFujiwara** [comment]
カレンダーは繰り返しの削除のときには「全部消す」「これ以降全て消す」「この予定だけ消す」の三択を聞かなくてはなりません。
そのためにカレンダーだけは例外的に削除時アラートを出そうということになりました。
