### ISSUE TITLE
バージョンアップの際にMigrationを実行する画面がない。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#683]

**Comment by akagane99** [comment]
多分画面からMigrationを実行するすべたないissueかと思いますが、念のため情報共有します。

コンソールからinstallコマンドを実行する事できました。
（nc3betaからNetCommons3.0.0.zipにアップデート際にお世話になった。installコマンドで代用できた）

なので方法が無いわけでなく、バージョンアップ時にこのコマンドを実行を実行してね。とアナウンスするのでも良さそうです。

```
$ Console\cake install.install install_migrations
```

参考まで。

**Comment by s-nakajima** [comment]
ごめん。画面がないということです。
