### ISSUE TITLE
メニューの編集画面のフォルダ形式

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#685]
メニューの編集画面のフォルダ形式のボタンがわかりずらい。
ＯＮなのか、ＯＦＦなのかもわからないし、ボタンの意味もわからない。

**Comment by s-nakajima** [comment]
EDLバグ・要望リストNo106

クリック時の表示として、「下層ページを表示」「当ページに遷移」を選ばせるUIにする
