### ISSUE TITLE
Modelのrecursiveのデフォルト？

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#69]
NetCommonsとして、Modelのrecursiveのデフォルトを何にした方が良いのだろうか。結論は出ないと思うけど、一度話しておいた方が良いと思うので、忘れないために挙げておく。

CakeのコアのModelのrecursiveは、public $recursive = 1　となっているが、マニュアルでは、-1を推奨している。
http://book.cakephp.org/2.0/ja/models/model-attributes.html#recursive

個人的な意見としては、勝手に余計なものを付けるなって気持ちもあるので、-1にすべきかなって思うのですが、、、

みなさん、どう思いますか？？

**Comment by RyujiAMANO** [comment]
recursive = -1 に1票

**Comment by akagane99** [comment]
recursive = -1 に1票

コアが 1 で、cakephp慣れない人がさわると、何でこんなにテーブル情報取ってくるかわからん現象を食らって戸惑うし。（それがrecursiveの機能なんだけど）
1 になってるのを意識してる人も居るだろうけど、何時もは定義してて、たまたま recursive の記述漏れがあって、なんじゃこの挙動。みたいな調査に半日かかって、このcakephpのrecursive機能とそのデフォ値が判明する。ような事はやりたくないので。
ドキュメントの推奨値が良いっす

**Comment by kteraguchi** [comment]
👍
そうしましょう。

**Comment by s-nakajima** [comment]
recursive = -1にすると、Cakeのコアが動かなくなる可能性あるため、現状のまま。
各自省略しないようにする。
