### ISSUE TITLE
存在しないページへの遷移。

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#699]
存在しないページへの遷移すると
「アクセスができません。指定したURLに移動するには、ログインが必要です。」と表示されてリダイレクトされる。

その際、「404 Missing Controller - （サイトタイトル）」とtitleがつくようだが、Missing Controllerなのをばらさないほうがよい。

また、ページが存在していれば、ログイン画面へリダイレクト、存在していなければ、トップページに遷移しているようだが、セキュリティ上、すべてログイン画面へ遷移させるべき。

**Comment by ghost** [comment]
#1450
ログイン画面に遷移させるのは、情報セキュティ的に弱くなると思います。全て、トップページか「見つからないページ」に遷移させるべかと思います。
