### ISSUE TITLE
NetCommonsAppModel::createの弊害

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#7]
createでschemaをみて全カラム分のデフォルト値がセットされるようになったけど弊害も起きるようになりました。

Model::_schemaの構造みたら文字列系のNot NULLカラムでdefaultがnullになっちゃてっます。

余計な情報が残ってる状態でModel::save()しないようにModel::save()前にModel::create()することが多いんですが、そうするとNot null カラムにnullの入った$dataがModel内に保持され、その状態でsave();するとnot nullカラムにnullを指定して保存しようとしてエラーになります。

not nullカラムだったら空文字列をデフォルトで入れたりとか別の方法がとれればいいんですが、Model::_schemaみてるとこまでの構造は保持してないので難しそうです

**Comment by RyujiAMANO** [comment]
```
    'blog_key' => array(
        'type' => 'string',
        'null' => false,
        'default' => null,
        'length' => (int) 255,
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8'
    ),
```

null => falseの時にdefaultがちゃんとセットされてれば問題無いはず

**Comment by kteraguchi** [comment]
別の問題がありました。
親クラスのcreateにnull,falseを渡すと空を返すようになっていたので、同じように直しました。
https://github.com/NetCommons3/NetCommons/commit/8b9599f9114dc63f57cc177e08de07f7847179e3

ということでCloseします。
