### ISSUE TITLE
vagrant関連

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#70]
いくつか、vagrant関連で発生したことまとめときます。
wikiに書いたんですが、検索がwikiの中だけしかできないっぽいので、ここにあげときます。

**Comment by kteraguchi** [comment]
[windows-updateでvagrant-upエラー](https://github.com/NetCommons3/NetCommons3/wiki/windows-updateでvagrant-upエラー)

**Comment by kteraguchi** [comment]
[VagrantとVBoxの関係が切れた](https://github.com/NetCommons3/NetCommons3/wiki/VagrantとVBoxの関係が切れた)

**Comment by kteraguchi** [comment]
[vagrant up でAuthentication failure. Retrying...](https://github.com/NetCommons3/NetCommons3/wiki/vagrant up でAuthentication failure. Retrying...)

**Comment by akagane99** [comment]
vagrant関連でハマったりしたときの解消法はwikiのTipsに書いた方が、よいのかしら？

**Comment by kteraguchi** [comment]
検索にヒットすると思ってwikiに書いたんですが、ヒットしないのことに気づき、今の状態です。
とりあえずissueにあげて、問題、解決方が明確になったら、wikiにまとめとく感じで良いかと思っています。

**Comment by akagane99** [comment]
> 検索にヒットすると思ってwikiに書いたんですが、ヒットしないのことに気づき、今の状態です。

おお、本当だ！wiki検索ないんだ。。
了解、その通りにしますね。

**Comment by kteraguchi** [comment]
wikiの検索はwikiの中にあります。

<img width="692" alt="wikisearch" src="https://cloud.githubusercontent.com/assets/3079266/11836738/fd89bbc6-a41f-11e5-8948-27db56f3e1a7.png">

リポジトリ内の検索にヒットしないので、たどりづらくなっちゃいます。

**Comment by akagane99** [comment]
うそん！？おれその検索入力欄ないのですが、これはいったい。。。
![default](https://cloud.githubusercontent.com/assets/2756509/11836858/aec24e62-a420-11e5-9137-ce092e560e07.PNG)

**Comment by kteraguchi** [comment]
ごめんなさい。
Chromeのアプリでした。

https://chrome.google.com/webstore/detail/github-wiki-search/gdifdhnjmjaidbajhapmbcbnoocoeooc?hl=ja
