### ISSUE TITLE
アンケート作成の権限チェック

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#71]
https://github.com/NetCommons3/Questionnaires/blob/812dd6851aeecd2a5c6165f1b0a2d990f097abd2/Controller/QuestionnaireAddController.php#L67-L70
で投稿権限をチェックしていますが、

https://github.com/NetCommons3/Questionnaires/blob/812dd6851aeecd2a5c6165f1b0a2d990f097abd2/Controller/QuestionnaireAddController.php#L39-L44
の設定でアクションまで来ないので、不要と思われます。

しかし、
https://github.com/NetCommons3/NetCommons3/issues/60
であげた件が不明瞭なので、アクションでもチェックしたほうが良いのかもです。

もくもくで確認しましょう。

**Comment by RikaFujiwara** [comment]
Component設定に任せて、Action内でのチェックは削除した
