### ISSUE TITLE
ボックスの変更機能の追加

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#726]

**Comment by kteraguchi** [comment]
名前に"s"がついていないテーブルが存在すると、MissingTableExceptionが発生します。

https://github.com/NetCommons3/Rooms/blob/a7357af60605cf1127ed01f58ea526b3ac8f2f07/Config/Migration/1477298144_switch_boxes.php#L146-L152
この処理で、テーブル一覧からModelClass名を作成し、以降の処理に利用しています。

https://github.com/NetCommons3/Rooms/blob/a7357af60605cf1127ed01f58ea526b3ac8f2f07/Config/Migration/1477298144_switch_boxes.php#L222-L223
ここで、他とえば、bar というテーブルがあった場合、
Barクラスが生成され、barsテーブルを参照するが、存在しないということでMissingTableException

生成されたModelClassに実テーブル名をセットする処理があると良いと思います。

ログ貼っときます。

```
Error: exception 'MissingTableException' with message 'Table index_tests for model IndexTest was not found in datasource master.' in /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Model/Model.php:1172
Stack trace:
#0 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Model/Model.php(3667): Model->setSource('index_tests')
#1 /var/www/html/nc3/app/Plugin/NetCommons/Model/NetCommonsAppModel.php(188): Model->getDataSource()
#2 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Model/Model.php(1394): NetCommonsAppModel->getDataSource()
#3 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Model/Model.php(1490): Model->schema()
#4 /var/www/html/nc3/app/Plugin/Rooms/Config/Migration/1477298144_switch_boxes.php(196): Model->hasField('room_id')
#5 /var/www/html/nc3/app/Plugin/Rooms/Config/Migration/1477298144_switch_boxes.php(143): SwitchBoxes->__updateAssociation('up', Array)
#6 /var/www/html/nc3/app/Plugin/Migrations/Lib/CakeMigration.php(560): SwitchBoxes->after('up')
#7 /var/www/html/nc3/app/Plugin/Migrations/Lib/CakeMigration.php(242): CakeMigration->_invokeCallbacks('afterMigration', 'up')
#8 /var/www/html/nc3/app/Plugin/Migrations/Lib/MigrationVersion.php(338): CakeMigration->run('up', Array)
#9 /var/www/html/nc3/app/Plugin/Migrations/Console/Command/MigrationShell.php(293): MigrationVersion->run(Array)
#10 /var/www/html/nc3/app/Plugin/Migrations/Console/Command/MigrationShell.php(273): MigrationShell->_execute(Array, false)
#11 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Console/Shell.php(458): MigrationShell->run()
#12 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(212): Shell->runCommand('run', Array)
#13 /var/www/html/nc3/vendors/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#14 /var/www/html/nc3/app/Console/cake.php(35): ShellDispatcher::run(Array)
#15 {main}
An error occurred when processing the migration:
  Migration: 1477298144_switch_boxes
  Error: Interrupted when running "after" callback.
---------------------------------------------------------------
Do you want to mark the migration as successful?. [y]es or [a]bort. (y/a)
```

**Comment by kteraguchi** [comment]
上記エラーが発生すると、
rooms_bk1477036926sテーブルが作成済みだが、Migrationは実行前の状態になり、
再度Migrationを実行しても、テーブルが既存なので、エラーになります。
＃ ログ消しちゃいまいした。

create table、alter tableのMigrationプログラムと、insert、updateのMigrationプログラムは分けた方が良いです。

**Comment by kteraguchi** [comment]
アップロードファイルのパスとかも変わるのでは？
upload_files.path

WYSIWYGの内容のパスもかわるので、ちょっと検討した方が良いと思います。

**Comment by kteraguchi** [comment]
本日再検討しました。

rooms.idを更新せずに、spaces.room_id_rootカラムを追加する方向になりました。

現状のコミットは戻さずに、
・Migrationを削除、修正する
・Room::WHOLE_SITE_PARENT_ID
    Room::PUBLIC_PARENT_ID
    Room::PRIVATE_PARENT_ID
    Room::ROOM_PARENT_ID
    の使用箇所を見直す

感じです。

**Comment by s-nakajima** [comment]
すでにリリースして使っていることもあり、サイト全体のルームのデータは作成するが、現状未使用とし、
サイト全体のSpace.room_id_root＝パブリックスペースのSpace.room_id_rootとする。

今後、もしサイト全体とパブリックスペースを分ける場合は、
Box.type=1のBox.room_idとSpace.room_id_rootをサイト全体のRoom.idに変更する。また、既にフレームを配置している場合は、Frameのroom_idも変更する必要あり。

とりあえず、メモっておく。

**Comment by kteraguchi** [comment]
> 今後、もしサイト全体とパブリックスペースを分ける場合は、
> Box.type=1のBox.room_idとSpace.room_id_rootをサイト全体のRoom.idに変更する。また、既にフレームを配置している場合は、Frameのroom_idも変更する必要あり。

現状すでに、「サイト全体で共通のエリア」と「パブリック共通のエリア」で分けないといけないのでは？
Box.room_idが"1"でも
Box.typeがBox::TYPE_WITH_SITEかBox::TYPE_WITH_SPACEで判断しながら処理する感じかな？

また後で教えてください。
