### ISSUE TITLE
メール送信機能のその他メールアドレス

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#73]
その他メールアドレスがやめようという話だったかと記憶しています。
"etc_to_address"で検索したところ、数か所ヒットしました。
後々混乱しそうなので消しましょう。

**Comment by akagane99** [comment]
これはメールプラグインのレビュー結果でしょうか？
だとしたら、こちらに記載お願いします。
https://github.com/NetCommons3/Mails/issues

**Comment by akagane99** [comment]
あ、こっちで書いちゃいました。

**Comment by kteraguchi** [comment]
すみません。issueのルール書いてあったのですが、目次ページにリンクがなかったです。
https://github.com/NetCommons3/NetCommons3/wiki/Issuesの利用

リンク追加しときました。

**Comment by akagane99** [comment]
ありがとうでです。

各プラグインのレビュー結果って、　https://github.com/NetCommons3/NetCommons3/issues　に
書くのが適当なのかな？
とちょっと疑問に思いました。
そこは、各プラグインのissueが適当なのかなと思うのですが、他の方はどう思いますか？

https://github.com/NetCommons3/NetCommons3/wiki/Issuesの利用#課題アイディアがあった場合の作業フローです

と題名にある通り、`課題アイディアがあった場合の作業フロー` であれば、その通りかと思いました。

**Comment by akagane99** [comment]
上記話題は別issueにあげました。
https://github.com/NetCommons3/NetCommons3/issues/77

**Comment by akagane99** [comment]
@kteraguchi @RyujiAMANO これ、12/24のどっかで相談させて。

何か @RyujiAMANO の要望があったような気がしました。
牟田口勘違いで、特に要望無ければ、消しちゃいましょう。

牟田口はどっちでもOK。

**Comment by akagane99** [comment]
@RyujiAMANO と相談済み。
消します。

**Comment by akagane99** [comment]
消しました
