### ISSUE TITLE
ルーム管理者で編集しても未承認のままになる場合がある

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#734]
検証環境のお知らせで確認しました
http://nc3dev2.nakazii-co.jp/nc3/68c0f8bd2435a190b3a633b57863b621

### 条件

* ルームの「コンテンツの承認機能」=不要に設定
* パブリックルーム
* お知らせの権限設定：承認が必要
* ユーザのルーム権限：ルーム管理者

上記にしてお知らせを編集すると、ルーム管理者でも承認待ちになり、誰も承認できないコンテンツになりました。

お知らせの不具合ではなく、共通部分のワークフローの不具合のような感じがします。
報告まで。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons3/issues/754 と同じなので、こっちをCloseにする
