### ISSUE TITLE
メール送信機能の利用イメージ

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#74]
機能がMailSettingBehaviorに集約されてる感じですが、
1.  メール設定機能
2. メール送信内容登録機能
3. メール送信機能

と分けたほうが良いと思います。
1.  メール設定機能
   各プラグインのメール設定画面で使用し、mail_settingsテーブルを操作します。
   - Mailsプラグインの機能
     - Mails/Model/MailSetting.php<br>
       mail_settingsテーブルのモデルです。<br>
       MailSetting::saveMailSetting()で<br>
           \* バリデーション処理<br>
           \* トランザクション処理<br>
           \* 登録処理<br>
       を実装します。
     - Mails/View/Elements/MailSetting/edit_form.ctp<br>
       メール設定画面のエレメントです。
   - 掲示板からの利用イメージ
     - メール設定コントローラー(Bbses/Controller/BbsMailSettingController.php)を作成します。
     - メール設定アクション(BbsMailSettingController::edit)を作成します。
     - メール設定アクションの処理<br>
       POSTの場合はMails.MailSetting->saveMailSetting()を呼び出します
     - メール設定ビュー(Bbses/View/BbsMailSetting/edit.ctp)を作成します。
     - メール設定ビューの処理<br>
       Mails/View/Elements/MailSetting/edit_form.ctpを呼び出します.
2.  メール送信内容登録機能
   各プラグインのコンテンツ登録機能でで使用し、mail_queueテーブルを操作します。
   （mail_queue_send_requests、mail_queue_deliversは一つで良い気がしています。別途issueにあげます。）
   - Mailsプラグインの機能
     - Mails/Model/MailQueue.php<br>
       mail_queueテーブルのモデルです。<br>
       MailQueue::saveMailQueue()で<br>
           \* バリデーション処理<br>
           \* トランザクション処理<br>
           \* 登録処理<br>
       を実装します。<br>
     - Mails/Model/Behavior/MailQueueBehavior.php<br>
       MailQueueBehavior::afterSave()でMailQueue::saveMailQueue()を呼び出します。<br>
       MailQueueBehavior:setSendTime()で送信時間を保持します。
   - 掲示板からの利用イメージ
     - Bbses/Model/BbsArticle.phpにMailQueueBehaviorを定義します。
     - 送信時間を変更する場合は、BbsArticle::saveBbsArticle()の前に、BbsArticle->setSendTime()を呼び出します。
3.  メール送信機能
   クーロンで呼び出される機能です。
   - Mailsプラグインの機能
     - Mails/Controller/MailSendController.php<br>
       送信処理コントローラーです。<br>
       MailSendController::send()で<br>
           \* MailQueueとMailSettingでbelogsToアソシエーション定義（belogsToプロパティで定義しとけばよいかもです。）<br>
           \* MailQueue->find('送信時間が過ぎているレコード')<br>
           \* 取得したレコードの送信対象ロールをから、ユーザーを取得<br>
           \* 取得したユーザーに対してメール送信<br>
           \* MailQueue->delete('送信済みレコード')<br>
       を実装します。<br>

こんなイメージです。

**Comment by akagane99** [comment]
レビュー及び、ご提案ありがとうです。
読み込んどきます。

**Comment by kteraguchi** [comment]
mail_queue_send_requests、mail_queue_deliversの件について、
mail_queue_deliversはカレンダー、パスワード忘れ等、ユーザー個人に送信する場合使用するテーブルですね。
これはいりますね。

mail_queue_send_requests→mail_queue
mail_queue_delivers→mail_queue_user
の方が分かりやすいと思います。

また、mail_queue_send_requestsのmail_subject、mail_bodyは不要な気がします。
mail_settingsのmail_fixed_phrase_subject、mail_fixed_phrase_bodyを使えば良いのかなと思っています。

**Comment by akagane99** [comment]
読込ました。

> 2．メール送信内容登録機能

この処理をした後、最後にメール送信するイメージです。
（でないとクローン使えない環境で、メール飛ばなくなるので。）
（キューにため込むけど、未来日でなければ即時送信のイメージです。）

> mail_queue_send_requests、mail_queue_deliversの件について、
> mail_queue_deliversはカレンダー、パスワード忘れ等、ユーザー個人に送信する場合使用するテーブルですね。
> これはいりますね。

了解です。

> mail_queue_send_requests→mail_queue
> mail_queue_delivers→mail_queue_user
> の方が分かりやすいと思います。

了解、修正します。

> また、mail_queue_send_requestsのmail_subject、mail_bodyは不要な気がします。
> mail_settingsのmail_fixed_phrase_subject、mail_fixed_phrase_bodyを使えば良いのかなと思っています。

あ、それメールのプレーンテキストを入っているイメージなので必要なんです。
mail_queue_send_requests　からコンテンツ逆引きできない（各プラグイン側が保持するコンテンツのテーブル構成は自由で、逆引き無理）のため。
なので、このままで行きたいです。

**Comment by kteraguchi** [comment]
> > 2．メール送信内容登録機能
> 
> この処理をした後、最後にメール送信するイメージです。
> （キューにため込むけど、未来日でなければ即時送信のイメージです。）

送信先が多い場合、処理が遅くなります。
ajax、もしくはthreadで登録処理とは別処理で動作するよう工夫が必要です。
NC2はajaxでメール送信処理のリクエスト投げてました。レスポンスは無視です。

> > また、mail_queue_send_requestsのmail_subject、mail_bodyは不要な気がします。
> > mail_settingsのmail_fixed_phrase_subject、mail_fixed_phrase_bodyを使えば良いのかなと思っています。
> 
> あ、それメールのプレーンテキストを入っているイメージなので必要なんです。
> mail_queue_send_requests　からコンテンツ逆引きできない（各プラグイン側が保持するコンテンツのテーブル構成は自由で、逆引き無理）のため。
> なので、このままで行きたいです。

こちらも、送信先が多い場合、処理が遅くなります。
mail_queueにmail_subject、mail_bodyを持たせれば行けそうです。

**Comment by akagane99** [comment]
> > > 2．メール送信内容登録機能
> > 
> > この処理をした後、最後にメール送信するイメージです。
> > （キューにため込むけど、未来日でなければ即時送信のイメージです。）
> 
> 送信先が多い場合、処理が遅くなります。
> ajax、もしくはthreadで登録処理とは別処理で動作するよう工夫が必要です。
> NC2はajaxでメール送信処理のリクエスト投げてました。レスポンスは無視です。

ご指摘ありがとうございます。
NC2のajaxをイメージしていました。

ここはやってみて、どうできるかと思っています。

> > > また、mail_queue_send_requestsのmail_subject、mail_bodyは不要な気がします。
> > > mail_settingsのmail_fixed_phrase_subject、mail_fixed_phrase_bodyを使えば良いのかなと思っています。
> > 
> > あ、それメールのプレーンテキストを入っているイメージなので必要なんです。
> > mail_queue_send_requests　からコンテンツ逆引きできない（各プラグイン側が保持するコンテンツのテーブル構成は自由で、逆引き無理）のため。
> > なので、このままで行きたいです。
> 
> こちらも、送信先が多い場合、処理が遅くなります。

何と比較して処理が遅くなるのでしょうか？
もし、nc2と同程度で遅い。というご指摘であれば、問題ないと思っています。

> mail_queueにmail_subject、mail_bodyを持たせれば行けそうです。

```
mail_queue_send_requests→mail_queue
mail_queue_delivers→mail_queue_user
```

今のままで、mail_queue_send_requestsには、mail_subject、mail_bodyはあるので、
今のままで良い。という事ですね？

**Comment by kteraguchi** [comment]
> 今のままで、mail_queue_send_requestsには、mail_subject、mail_bodyはあるので、

あぁ、見落としてました。
mail_queue_send_requestsの、mail_subject、mail_bodyを使用すれば行けそうです。

> 何と比較して処理が遅くなるのでしょうか？
> もし、nc2と同程度で遅い。というご指摘であれば、問題ないと思っています。

送信先ユーザー分のデータを登録するので、送信先が増えれば、mail_subject、mail_bodyの書き込み分が掛け算で遅くなるかなと思いました。
個人宛のメールに限るので、せいぜい50件くらいの想定で大丈夫でしょうか。。。
50件くらいなら、そんなにかからないかなぁ。

どちらにせよ、mail_queue_send_requestsにmail_subject、mail_bodyがあるので、mail_queue_deliversのmail_subject、mail_bodyは不要かと思います。

> NC2のajaxをイメージしていました。
> ここはやってみて、どうできるかと思っています。

ajaxで即時送信呼び出すなら、Mails/Model/Behavior/MailQueueBehavior.phpじゃなくて、Mails/Controller/Component/MailComponent.phpの方が良いかもです。
MailComponent::afterRenderでMailQueue::saveMailQueue()呼び出しと、メール送信リクエスト用ajax出力処理を実装するイメージです。

**Comment by akagane99** [comment]
すいません、返事遅くなりました。

> > 今のままで、mail_queue_send_requestsには、mail_subject、mail_bodyはあるので、
> 
> あぁ、見落としてました。
> mail_queue_send_requestsの、mail_subject、mail_bodyを使用すれば行けそうです。

了解しました。

> > 何と比較して処理が遅くなるのでしょうか？
> > もし、nc2と同程度で遅い。というご指摘であれば、問題ないと思っています。
> 
> 送信先ユーザー分のデータを登録するので、送信先が増えれば、mail_subject、mail_bodyの書き込み分が掛け算で遅くなるかなと思いました。
> 個人宛のメールに限るので、せいぜい50件くらいの想定で大丈夫でしょうか。。。
> 50件くらいなら、そんなにかからないかなぁ。

NC2仕様からいうと、個人宛てメールって通知系になると思うのですが、
通知系って、会員登録とか、パスワード再発行位なんです。

```
\Google ドライブ\NetCommons3\プラグイン仕様\メール\仕様定義\NC2メール仕様\NC2メール仕様調査.xlsx　「メール定型文の固定値」シート参照
```

なので、50件もいかないだろうと思っています。
（NC3で新しく実装する通知、例えばカレンダーの通知（実装されるかどうかは判りませんが）が考えられますが、それは先の話かなと思っています。）

> どちらにせよ、mail_queue_send_requestsにmail_subject、mail_bodyがあるので、mail_queue_deliversのmail_subject、mail_bodyは不要かと思います。

あれ！？
どっか　mail_queue_delivers　にmail_subject、mail_bodyってありました？どこかに有ったら教えて欲しいください。
訂正します。

先ほど確認して、schema.php、ERDには上記ありませんでした。

https://github.com/NetCommons3/Mails/blob/master/Config/Schema/schema.php#L53-L63
https://raw.githubusercontent.com/NetCommons3/NetCommons3Docs/master/sphinx/source/reference/nc3ERD.png

> > NC2のajaxをイメージしていました。
> > ここはやってみて、どうできるかと思っています。
> 
> ajaxで即時送信呼び出すなら、Mails/Model/Behavior/MailQueueBehavior.phpじゃなくて、Mails/Controller/Component/MailComponent.phpの方が良いかもです。
> MailComponent::afterRenderでMailQueue::saveMailQueue()呼び出しと、メール送信リクエスト用ajax出力処理を実装するイメージです。

おお！提案ありがとうございます。
cakephp不勉強ですいません、こんな方法もあるんですね。
試してみます。

**Comment by kteraguchi** [comment]
> どっか　mail_queue_delivers　にmail_subject、mail_bodyってありました？どこかに有ったら教えて欲しいください。

ごめんなさい。勘違いでした。レビューしてる間に頭の中で入れ替わっっちゃってました。
現状でOKだと思います。
お手数をかけてしまってすみません。

テーブル名だけ、変えましょう。
mail_queue_send_requests→mail_queue
mail_queue_delivers→mail_queue_user

**Comment by akagane99** [comment]
> > どっか　mail_queue_delivers　にmail_subject、mail_bodyってありました？どこかに有ったら教えて欲しいください。
> 
> ごめんなさい。勘違いでした。レビューしてる間に頭の中で入れ替わっっちゃってました。
> 現状でOKだと思います。
> お手数をかけてしまってすみません。

了解しました。

> テーブル名だけ、変えましょう。
> mail_queue_send_requests→mail_queue
> mail_queue_delivers→mail_queue_user

了解！対応します。

**Comment by akagane99** [comment]
対応済みクローズ
