### ISSUE TITLE
開発用Vagrant環境にzipコマンドインストールを追加して欲しい

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#75]
Filesプラグインでパスワード付きZipの作成と解凍でzipコマンド使ってるので、開発用Vagrant環境でもzipコマンド使えるようになってて欲しいです。

**Comment by s-nakajima** [comment]
リリースしたので、Vagrantは必要ある人だけ使って、各自で環境をそろえても良いので、Closeする。
