### ISSUE TITLE
キャビネットのダウンロードでエラー

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#752]
http://www.netcommons.org/bbr4cdsqr-18477/#_18477

ファイル編集の「ダウンロードパスワードを設定する。」を設定してアップロードを行い、ファイル一覧で対象ファイルの「詳細」を開いて画面下の「ダウンロード」を押下すると以下エラーが表示される。とくにダウンロード時に認証キーを入力するボックスが表示されるわけでもありません。
環境--------------------------------------------------------
PHP 5.6
Apache/2.2.15
MariaDB10.1.17

エラー内容--------------------------------------------------------
認証キーの入力が必要です。
エラー:  /cabinets/cabinet_files/download/26/9656bd2f199b901c8a3f3e5531809f54?frame_id=32 
ページが自動的に更新されない場合はこちらをクリックしてください。 
Stack Trace
APP/Plugin/AuthorizationKeys/Controller/Component/AuthorizationKeyComponent.php line 264 → AuthorizationKeyComponent->_popupStartup(CabinetFilesController) 
APP/Plugin/AuthorizationKeys/Controller/Component/AuthorizationKeyComponent.php line 221 → AuthorizationKeyComponent->_guard() 
•APP/Plugin/Cabinets/Controller/CabinetFilesController.php line 273 → AuthorizationKeyComponent->guard(string, string, array) 
•[internal function] → CabinetFilesController->download() 
•CORE/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(CabinetFilesController, array) 
•CORE/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest) 
•CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(CabinetFilesController, CakeRequest) 
•APP/webroot/index.php line 107 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by RyujiAMANO** [comment]
再現しました。修正します。
