### ISSUE TITLE
ルームで承認機能を無効にしたときで、ブロック設定で承認を有効にした場合、承認できなくなる

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#754]
http://www.netcommons.org/bbfh3g5bs-18477/#_18477

承認機能について複数のプラグインで以下のような事象を確認しております。
仕様として想定動作でしょうか。

[事象]
ルームで承認機能を無効、ブロック設定、もしくはブロックの一覧表示の登録で承認機能を有効にした環境において、承認待ちとなっているブロックの一覧表示の登録、もしくは投稿された記事などを承認済みにできない。承認者で承認待ち状態の登録、記事を編集表示すると「差し戻し」ボタンが表示されるはずですが表示されておりません。そのまま「決定」ボタンを押下しても承認待ちは解除されません。
[対象プラグイン]
お知らせ、掲示板、ブログ、リンクリスト、フォトアルバム、アンケート、小テスト、登録フォーム、ToDo、動画

[事象]
ルームで承認機能を無効、ブロック設定の「コメントのみ承認」を有効にした環境では、コメント登校時に承認待ちにならず承認済みとなる。
[対象プラグイン]
掲示板

[事象]
ルームで承認機能を無効、ブロック設定の「コメントのみ承認」を有効にした環境では、登録した承認待ちコメントがルーム管理者権限では表示されないため承認できない。承認者を編集長、編集者権限で有効にしている場合、編集長、編集者で承認待ちコメントが表示され承認を実行できる。
[対象プラグイン]
ToDo、動画

**Comment by akagane99** [comment]
### 動画

コンテンツの承認、コメントの承認、仕様じゃないです。
すまん、ロジック見れてないです。

（コンテンツの承認）もしプラグイン側に不具合があるとしたら、お知らせ、掲示板のロジックを真似たので、それと同じように動いちゃってると思います。

（コメントの承認）ルームで承認無効にすると、デフォルトのルーム管理者のコメント承認権限（コンテントコメントパブリッシャブル）がOFFになってるのかも。

とりあえず回答まで。

https://github.com/NetCommons3/NetCommons3/issues/734
上記と同じ不具合かと思ってます。

**Comment by s-nakajima** [comment]
EDLバグ・要望リストNo88、89、121

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/NetCommons/commit/552446b97e2a25f6cb9d9b243761776f243de42f

**Comment by s-nakajima** [comment]
キャビネットで、承認機能をありでルーム管理で「編集長」にも承認権限をチェックしたのに、キャビネットに承認待ちになっているものを承認できない。

「高島テスト（ルーム）」にあるキャビネットで、現在承認待ちになっているものを編集長権限のあるweb担当で入っても承認できません。

**Comment by s-nakajima** [comment]
EDLの報告だと、直っていないようです。Reopenします。

条件）
EDLバグ・要望リストNo88、89ですが、
パブリックのルームに対して、
大前提の部分で「ルーム管理の中で承認機能をOFF」にして
そのルームに設置したキャビネットで「承認が必要」にした場合に、「編集長」で発生するものらしいです。

**Comment by kteraguchi** [comment]
確認してみましたが、再現しませんでした。

確認した手順

１．パブリックルームで承認が必要なルームを作成（承認有無を変更するルーム）
２．一般ユーザー、編集長ユーザーを参加させる　
３．「承認有無を変更するルーム」にキャビネットを配置（承認有無を変更するキャビネット）
４．「承認有無を変更するキャビネット」は承認が必要
５．一般ユーザーでログインしなおす
６．「承認有無を変更するキャビネット」にファイルを追加→承認待ちになる
７．管理者ユーザーでログインしなおす
８．「承認有無を変更するルーム」を承認不要に変更
９．編集長ユーザーでログインしなおす

「承認有無を変更するキャビネット」の承認待ちファイルの詳細→編集で差し戻しボタン表示されました。
決定すると承認されました。

手順が違うのかな。

**Comment by kteraguchi** [comment]
再現しました。

１．「承認有無を変更するルーム」が承認不要の状態で、承認有のキャビネットを作成。
２．上記５～９を行う。

差し戻しボタンが表示されず、決定しても承認されませんでした。

**Comment by kteraguchi** [comment]
Commitコメントに  Fix NetCommons3/NetCommons3#754 と書いたので、Close してしまった。
完了ラベル付けてReopen

**Comment by kteraguchi** [comment]
既存データのMigrationが必要。

承認不要のRoomで、承認が必要なBlockの’content_publishable’ 権限レコードを削除する。

と書いて気付いた。

NetCommons3/Blocks@fda6bff の修正は間違っている。
ルーム管理から編集者に公開権限を付与したときに問題になる。

’content_publishable’ のvalueを更新するのではなく、
承認が必要なBlockの場合は、削除しないといけない。

ということで、再度修正。

**Comment by kteraguchi** [comment]
当件に関係するデータ、処理について、ちょっと整理します。

関係するデータ
・DefaultRolePermission の content_publishable,content_comment_publishable
・RoomRolePermission の content_publishable,content_comment_publishable
・BlockRolePermission の content_publishable,content_comment_publishable
・BlockSetting の use_workflow
・BlockSetting の use_comment_approval
・Room の need_approval

関係する処理
・公開権限初期処理
　　CurrentFrame::setBlockRolePermissions
・use_workflow の判断処理
　　CurrentFrame::setBlockRolePermissions
　　block_approval_setting.ctp
・use_comment_approval の判断処理
　　CurrentFrame::setBlockRolePermissions
　　block_approval_setting.ctp
・Room.need_approval の更新処理
　　Room::afterSave

こんな感じかと。

現状、公開権限初期処理では、
use_workflow 、use_comment_approval  の値によって公開権限を決めています。
https://github.com/NetCommons3/NetCommons/blob/3.1.2/Utility/CurrentFrame.php#L299-L312

~~ここの処理がややこしくしている気がします。~~
~~Room.need_approval の更新処理で、~~
~~承認必要の場合は、~~
~~BlockRolePermission の content_publishable,content_comment_publishable を削除すれば良いです。~~
~~https://github.com/NetCommons3/Rooms/blob/3.1.2/Model/Room.php#L398~~
~~に処理追加。~~
~~そうすると、~~
~~公開権限の取得処理は~~
~~DefaultRolePermission、RoomRolePermission、BlockRolePermission をマージするだけで良くなります。~~
~~また、~~
~~use_workflow,use_comment_approval  は、権限設定画面を表示する際に使用するだけになります。~~

~~ダメだったら、指摘してください。~~

https://github.com/NetCommons3/NetCommons3/issues/754#issuecomment-312551546
で修正。

**Comment by s-nakajima** [comment]
ルーム管理で承認ありに変更した際にBlockRolePermission を初期化してしまうと、変更前のときに「コメントを承認できる権限」を編集者にしたものまで初期化されてしまい、編集者が承認できなくなってしまいます。

**Comment by kteraguchi** [comment]
~~おぉ、content_comment_publishable は ブロックの権限設定で変更ですな。~~
~~削除はダメですね。~~

~~更新する方向で、修正します。~~

https://github.com/NetCommons3/NetCommons3/issues/754#issuecomment-312551546
で修正。

**Comment by kteraguchi** [comment]
既に削除処理がありました。
https://github.com/NetCommons3/Rooms/blob/3.1.2/Model/Room.php#L312
https://github.com/NetCommons3/Rooms/blob/3.1.2/Model/Behavior/SaveRoomAssociationsBehavior.php#L437

~~ここを更新処理に修正します。~~
https://github.com/NetCommons3/NetCommons3/issues/754#issuecomment-312551546
で修正。

**Comment by kteraguchi** [comment]
いろんな処理が絡んで、ややこしいので、データパターンをまとめた。
このデータパターンのテストケースを作成し、通れば万事OKな感じにする予定です。

|   |  | Room | BlockSett<br>ing | BlockSett<br>ing | DefaultRo<br>lePermiss<br>ion | RoomRoleP<br>ermission | BlockRole<br>Permissio<br>n | DefaultRo<br>lePermiss<br>ion | RoomRoleP<br>ermission | BlockRole<br>Permissio<br>n |  |
|  ------ | ------ | :------: | :------: | :------: | :------: | :------: | :------: | :------: | :------: | :------: | ------ |
|  № | RoleKey | need_appr<br>oval | use_workf<br>low | use_comme<br>nt_approv<br>al | content_p<br>ublishabl<br>e | content_p<br>ublishabl<br>e | content_p<br>ublishabl<br>e | content_c<br>omment_pu<br>blishable | content_c<br>omment_pu<br>blishable | content_c<br>omment_pu<br>blishable | 不<br>整<br>合 |
|  1 | room_administrator | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |  |
|  2 | room_administrator | 1 | 1 | 1 | 1 | 1 | null | 1 | 1 | null |  |
|  3 | room_administrator | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |  |
|  4 | room_administrator | 0 | 1 | 1 | 1 | 1 | null | 1 | 1 | null |  |
|  5 | room_administrator | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |  |
|  6 | room_administrator | 0 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 |  |
|  7 | room_administrator | 0 | 0 | 0 | 1 | 1 | null | 1 | 1 | null |  |
|  8 |  |  |  |  |  |  |  |  |  |  |  |
|  9 | chief_editor | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |  |
|  10 | chief_editor | 1 | 1 | 1 | 1 | 1 | ０ | 1 | 1 | 1 | ✓ |
|  11 | chief_editor | 1 | 1 | 1 | 1 | 1 | null | 1 | 1 | null |  |
|  12 | chief_editor | 1 | 1 | 1 | 1 | 0 | 1 | 1 | 1 | 1 | ✓ |
|  13 | chief_editor | 1 | 1 | 1 | 1 | 0 | ０ | 1 | 1 | 1 |  |
|  14 | chief_editor | 1 | 1 | 1 | 1 | 0 | null | 1 | 1 | null |  |
|  15 | chief_editor | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |  |
|  16 | chief_editor | 0 | 1 | 1 | 1 | 1 | ０ | 1 | 1 | 1 | ✓ |
|  17 | chief_editor | 0 | 1 | 1 | 1 | 1 | null | 1 | 1 | null |  |
|  18 | chief_editor | 0 | 1 | 1 | 1 | 0 | 1 | 1 | 1 | 1 | ✓ |
|  19 | chief_editor | 0 | 1 | 1 | 1 | 0 | 0 | 1 | 1 | 1 |  |
|  20 | chief_editor | 0 | 1 | 1 | 1 | 0 | null | 1 | 1 | null |  |
|  21 | chief_editor | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |  |
|  22 | chief_editor | 0 | 0 | 1 | 1 | 1 | 0 | 1 | 1 | 1 | ✓ |
|  23 | chief_editor | 0 | 0 | 1 | 1 | 0 | 1 | 1 | 1 | 1 | ✓ |
|  24 | chief_editor | 0 | 0 | 1 | 1 | 0 | 0 | 1 | 1 | 1 | ✓ |
|  25 | chief_editor | 0 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 |  |
|  26 | chief_editor | 0 | 0 | 0 | 1 | 1 | 0 | 1 | 1 | 1 | ✓ |
|  27 | chief_editor | 0 | 0 | 0 | 1 | 0 | null | 1 | 1 | null | ✓ |
|  28 | chief_editor | 0 | 0 | 0 | 1 | 0 | 1 | 1 | 1 | 1 | ✓ |
|  29 | chief_editor | 0 | 0 | 0 | 1 | 0 | 0 | 1 | 1 | 1 | ✓ |
|  30 | chief_editor | 0 | 0 | 0 | 1 | 0 | null | 1 | 1 | null | ✓ |
|  31 |  |  |  |  |  |  |  |  |  |  |  |
|  32 | editor | 1 | 1 | 1 | 0 | 0 | ０ | 0 | 0 | 0 |  |
|  33 | editor | 1 | 1 | 1 | 0 | 0 | ０ | 0 | 0 | 1 |  |
|  34 | editor | 1 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | ✓ |
|  35 | editor | 1 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 1 | ✓ |
|  36 | editor | 1 | 1 | 1 | 0 | 0 | null | 0 | 0 | null |  |
|  37 | editor | 1 | 1 | 1 | 0 | 1 | ０ | 0 | 0 | 0 | ✓ |
|  38 | editor | 1 | 1 | 1 | 0 | 1 | ０ | 0 | 0 | 1 | ✓ |
|  39 | editor | 1 | 1 | 1 | 0 | 1 | 1 | 0 | 0 | 0 |  |
|  40 | editor | 1 | 1 | 1 | 0 | 1 | 1 | 0 | 0 | 1 |  |
|  41 | editor | 1 | 1 | 1 | 0 | 1 | null | 0 | 0 | null |  |
|  42 | editor | 0 | 1 | 1 | 0 | 0 | ０ | 0 | 0 | 0 |  |
|  43 | editor | 0 | 1 | 1 | 0 | 0 | ０ | 0 | 0 | 1 |  |
|  44 | editor | 0 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | ✓ |
|  45 | editor | 0 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 1 | ✓ |
|  46 | editor | 0 | 1 | 1 | 0 | 0 | null | 0 | 0 | null |  |
|  47 | editor | 0 | 1 | 1 | 0 | 1 | ０ | 0 | 0 | 0 | ✓ |
|  48 | editor | 0 | 1 | 1 | 0 | 1 | ０ | 0 | 0 | 1 | ✓ |
|  49 | editor | 0 | 1 | 1 | 0 | 1 | 1 | 0 | 0 | 0 |  |
|  50 | editor | 0 | 1 | 1 | 0 | 1 | 1 | 0 | 0 | 1 |  |
|  51 | editor | 0 | 1 | 1 | 0 | 1 | null | 0 | 0 | null |  |
|  52 | editor | 0 | 0 | 1 | 0 | 0 | ０ | 0 | 0 | 0 | ✓ |
|  53 | editor | 0 | 0 | 1 | 0 | 0 | ０ | 0 | 0 | 1 | ✓ |
|  54 | editor | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 0 |  |
|  55 | editor | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 1 | ✓ |
|  56 | editor | 0 | 0 | 1 | 0 | 1 | ０ | 0 | 0 | 0 | ✓ |
|  57 | editor | 0 | 0 | 1 | 0 | 1 | ０ | 0 | 0 | 1 | ✓ |
|  58 | editor | 0 | 0 | 1 | 0 | 1 | 1 | 0 | 0 | 0 |  |
|  59 | editor | 0 | 0 | 1 | 0 | 1 | 1 | 0 | 0 | 1 |  |
|  60 | editor | 0 | 0 | 0 | 0 | 0 | ０ | 0 | 0 | 0 | ✓ |
|  61 | editor | 0 | 0 | 0 | 0 | 0 | ０ | 0 | 0 | 1 | ✓ |
|  62 | editor | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | ✓ |
|  63 | editor | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 1 |  |
|  64 | editor | 0 | 0 | 0 | 0 | 0 | null | 0 | 0 | null | ✓ |
|  65 | editor | 0 | 0 | 0 | 0 | 1 | ０ | 0 | 0 | 0 | ✓ |
|  66 | editor | 0 | 0 | 0 | 0 | 1 | ０ | 0 | 0 | 1 | ✓ |
|  67 | editor | 0 | 0 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | ✓ |
|  68 | editor | 0 | 0 | 0 | 0 | 1 | 1 | 0 | 0 | 1 |  |
|  69 | editor | 0 | 0 | 0 | 0 | 1 | null | 0 | 0 | null | ✓ |
|  70 |  |  |  |  |  |  |  |  |  |  |  |
|  71 | general_user | 1 | 1 | 1 | 0 | 0 | ０ | 0 | 0 | 0 |  |
|  72 | general_user | 1 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | ✓ |
|  73 | general_user | 1 | 1 | 1 | 0 | 0 | null | 0 | 0 | null |  |
|  74 | general_user | 0 | 1 | 1 | 0 | 0 | ０ | 0 | 0 | 0 |  |
|  75 | general_user | 0 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | ✓ |
|  76 | general_user | 0 | 1 | 1 | 0 | 0 | null | 0 | 0 | null |  |
|  77 | general_user | 0 | 0 | 1 | 0 | 0 | ０ | 0 | 0 | 0 | ✓ |
|  78 | general_user | 0 | 0 | 1 | 0 | 0 | ０ | 0 | 0 | 1 | ✓ |
|  79 | general_user | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | ✓ |
|  80 | general_user | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 1 | ✓ |
|  81 | general_user | 0 | 0 | 0 | 0 | 0 | ０ | 0 | 0 | 0 | ✓ |
|  82 | general_user | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | ✓ |
|  83 | general_user | 0 | 0 | 0 | 0 | 0 | null | 0 | 0 | null | ✓ |
|  84 |  |  |  |  |  |  |  |  |  |  |  |
|  85 | visitor | 1 | 1 | 1 | 0 | 0 | ０ | 0 | 0 | 0 |  |
|  86 | visitor | 1 | 1 | 1 | 0 | 0 | null | 0 | 0 | null |  |
|  87 | visitor | 0 | 1 | 1 | 0 | 0 | ０ | 0 | 0 | 0 |  |
|  88 | visitor | 0 | 1 | 1 | 0 | 0 | null | 0 | 0 | null |  |
|  89 | visitor | 0 | 0 | 1 | 0 | 0 | ０ | 0 | 0 | 0 | ✓ |
|  90 | visitor | 0 | 0 | 1 | 0 | 0 | ０ | 0 | 0 | 1 | ✓ |
|  91 | visitor | 0 | 0 | 0 | 0 | 0 | ０ | 0 | 0 | 0 | ✓ |
|  92 | visitor | 0 | 0 | 0 | 0 | 0 | null | 0 | 0 | null | ✓ |

**Comment by kteraguchi** [comment]
上記のデータパターンでテストケースをまとめてて気づきました。

まず、前述してた内容に間違いがありました。

承認不要のルームで、ブロックの権限データが存在しない(NULL)の場合、
DefaultRolePermission、RoomRolePermission、BlockRolePermission をマージすると、
general_user(一般)の content_publishable が false になってしまいます。
（前述したときは、マージすればOKだと思っていた。）

現状、
https://github.com/NetCommons3/NetCommons/blob/3.1.2/Utility/CurrentFrame.php#L287-L313
の処理で、content_publishable を上書きしています。
DefaultRolePermission、RoomRolePermission、BlockRolePermission をマージした後、
Room.need_approval,BlockSetting.use_workflow,BlockSetting.use_comment_approval の状態を判断し、この処理を通すのが正しい処理と思います。

以上を踏まえ、ちょっとリファクタリングします。

また、BlockRolePermission content_publishable は不要なので、持たないようにします。
（Migrationで削除。ルーム更新時に更新もしない。）
BlockRolePermission content_comment_publishable は必要。

**Comment by kteraguchi** [comment]
コンテンツの公開権限(content_publishable)周りは、収拾がついてきましたが、
コンテンツコメントの公開権限(content_comment_publishable) の更新処理で、
3点確認です。

https://github.com/NetCommons3/Blocks/blob/3.1.2/Model/Behavior/BlockRolePermissionBehavior.php#L144-L163

ここの処理。

まず、1点目。
各プラグインの権限設定画面があります。
![image](https://user-images.githubusercontent.com/3079266/27854016-1399e08c-61a0-11e7-817c-09bc95930763.png)

承認機能を不要 にした場合、コメントを投稿できる権限（content_comment_creatable）にチェックされているロールに公開権限も付与されます。
そうすると、承認機能を不要 にした後、コメントのみ承認が必要 に変更すると、
一般にcontent_comment_publishable がついたままの状態になります。
間違っているので、直します。
（content_comment_publishable と content_comment_creatableを連動させないようにする）


続いて、2点目。
同画面で、承認機能を記事・コメント両方に承認が必要 にした場合、編集者のコメントを承認できる権限が剥奪されます。
コメントを承認できる権限の編集者にチェックを付けても、付与されないです。
間違っている気がしてます。
コメントを承認できる権限 でチェックされている状態のまま更新するのが正しいと思っています。

最後、3点目。
前述にも軽く上がっていますが、ルーム管理で、承認が必要とした場合、
編集者のコメントを承認できる権限が剥奪されます。
2点目は、この処理と整合性を保とうとしたのかもです。
コメントを承認できる権限はルーム管理からは操作できず（表示もなし）、
各プラグインの権限設定画面で操作することになります。
ルーム管理では、コメントを承認できる権限に対して、何もしないのが良いのかと思います。


2点目、3点目が現状で正しいとすれば、
権限設定画面で、承認機能を記事・コメント両方に承認が必要 にチェックしたら、
コメントを承認できる権限の編集者チェックボックスをDisableにすると良いのかと思います。

**Comment by kteraguchi** [comment]
コンテンツコメントの公開権限について確認しました。

各プラグインの権限設定画面で、
承認機能を記事・コメント両方に承認が必要 にしても、編集者のコメントを承認できる権限を剥奪しない。チェックのON、OFFに基づいて更新する。

ルーム管理で承認が必要としても、編集者のコメントを承認できる権限を剥奪しない。

にします。
