### ISSUE TITLE
承認依頼メールが通知されない

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#755]
http://www.netcommons.org/bbfh3g5bs-18477/#_18477

ルームで承認機能が有効で、以下の条件では承認待ちにはなるが承認依頼メールが通知されない。
・編集長権限以上で登録済み（承認機能を有効、承認通知メール有効）を、編集者権限で編集した場合
（「担当者への連絡」に記述すると承認依頼メールが通知される。）
・編集長権限以上でブロックを追加し、一覧表示に未登録（記事記載しないでキャンセル）の状態で、編集者権限で初回編集した場合
（編集者権限で二回目以降の編集では承認依頼メールが通知される。）
[対象プラグイン]
お知らせ

**Comment by akagane99** [comment]
> ・編集長権限以上で登録済み（承認機能を有効、承認通知メール有効）を、編集者権限で編集した場合
> （「担当者への連絡」に記述すると承認依頼メールが通知される。）

（担当者への連絡）メールが通知されるので、想定通りです。
※承認依頼メールは飛ばない事を確認しました。

> ・編集長権限以上でブロックを追加し、一覧表示に未登録（記事記載しないでキャンセル）の状態で、編集者権限で初回編集した場合
> （編集者権限で二回目以降の編集では承認依頼メールが通知される。）

お知らせプラグインで、blocksettingをafterSaveで登録しているため、1度目はblocksettingが空で、メール飛ばなかったです。

https://github.com/NetCommons3/Announcements/blob/11e60bf657da2ba50dc5f951a1a05bbc833b1bcc/Model/Announcement.php#L133

beforeSaveにすれば解決しました。

**Comment by akagane99** [comment]
メールのバグではなかったので、ラベル外しました。
