### ISSUE TITLE
承認完了メールが通知されない

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#756]
http://www.netcommons.org/bbfh3g5bs-18477/#_18477

[事象]
ルームで承認機能が有効で、以下の条件では承認済みは可能だが承認完了メールが通知されない。
・編集長権限以上で作成済み（承認機能を有効、承認通知メール有効）を、編集者権限で編集した場合
（承認者が承認時に「担当者への連絡」に記述すると承認完了メールが通知される。）
[対象プラグイン]
お知らせ

**Comment by akagane99** [comment]
検証環境で上記条件の場合、メール飛ばない事を確認しました。
http://nc3dev2.nakazii-co.jp/nc3/video

https://github.com/NetCommons3/NetCommons3/issues/755
上記を修正後のローカル環境だと、メール飛びました。
そのため、完了ラベルを付けました。
