### ISSUE TITLE
各プラグインのレビュー結果は、　当issueに 書くのが適当？

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#77]
ちょっと疑問に思いました。
そこは、各プラグインのissueが適当なのかなと思うのですが、他の方はどう思いますか？

https://github.com/NetCommons3/NetCommons3/wiki/Issuesの利用#課題アイディアがあった場合の作業フローです

と題名にある通り、課題アイディアがあった場合の作業フロー であれば、その通りかと思いました。

**Comment by s-nakajima** [comment]
私も疑問に思ってます。
共通的なものだったらわかるのですが、各々のIssueであれば、わざわざNetCommons3プラグインのIssueに書く必要ないと思います。また、NetCommons3プラグラインのIssueに書かれてしまうと、どのプラグインが該当するIssueなのか分からなくなってしまいます。漏れにもつながります。

牟田くんに＋１です

**Comment by RyujiAMANO** [comment]
各プラグインの中で完結する話とか該当するプラグインがどれなのかハッキリとしてるなる、そのプラグインのIssueが適当かなと思います…

…が、各プラグインのIssueに分散しすぎて全体を追いにくくなるという問題もでてくるかなとも思ってます。

個人的にzube.io使いながら思ったのは、大まかな作業ステータスはzube.ioにまかせて、どのプラグイン（あるいは機能）についてはLabelで分類でもいいのかなぁとも思ったり(^^;

**Comment by s-nakajima** [comment]
私もZube.io使ってます。結構良いです。

**Comment by akagane99** [comment]
ご意見ありがとうです。
案まとめてみました。
本日の進捗資料の「（４）共有・特記事項・依頼事項」に記載しましたが、スルーされちゃったら、そのままで。
来年のもくもく会の時に、牟田口が再指摘しようと思います。

### 案１ 基本、レビュー結果は各プラグインのissueに書く
- レビュー結果は各プラグインのissueに書く。
- 共通的に使われるプラグインで、皆に周知必要なら、NetCommons3リポジトリのissueに、各プラグインのissueのURL貼り付けて、「皆、一読お願い」とか書きこめば、事たりそう
- デメリット：各プラグインのIssueに分散しすぎて全体を追いにくくなるという問題あり。

### 案２ レビュー結果はNetCommons3リポジトリのissueにラベルを付けて投稿する

現状、レビュー内容かどうか、内容を読まないとよくわからないので、ラベルを付ければ改善されると思う。
- メリット：各プラグインのissueに分散しない

**Comment by kteraguchi** [comment]
昨日のもくもく会で大枠決まりました。
頂いたの案を合わせた感じかと思います。

~~1. まず、各プラグインのissueに書く
    ラベルは[こちら](https://github.com/NetCommons3/NetCommons3/wiki/Issuesの利用#課題アイディアがあった場合の作業フローです)にある通り
2.  続けて、NetCommons3リポジトリにも同タイトルをかいて、リンクさせる。
     プラグイン名のラベルを付けることで全体の把握がしやすくなる<br>~~

あと、レビュー結果について、特に話題に上がらなかったのですが、レビュー結果と、レビュー以外での意見を分けることは、重要ではない気がしてます。
分けるなら、”レビュー結果”というラベルを付けようかと考えています。

**Comment by kteraguchi** [comment]
間違えました。訂正します。
1. まず、NetCommons3リポジトリに書く
2. 該当プラグイン名のラベル、[ステータスラベル](https://github.com/NetCommons3/NetCommons3/wiki/Issuesの利用#課題アイディアがあった場合の作業フローです)を付ける
3. 該当プラグイン担当者が、該当プラグインのissueに書いて、、NetCommons3リポジトリissueにリンクをはる

の流れです。

補足として、意見交換等のやり取りは基本プラグイン側のissueで行います
例外としては、「対応しないので、Closesします。」などの2,3回のやり取りで済むものは、NetCommons3リポジトリissuesでOKです。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/wiki/レビュールール
に記載済みのため、このissueクローズします。
