### ISSUE TITLE
アンケート、小テストで不要データかもです

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#772]
アンケート、小テストを削除しても、
questionnaire_questions
questionnaire_choices
quiz_questions
quiz_choices
quiz_corrects
にデータが残っています。

https://github.com/NetCommons3/Questionnaires/blob/3.0.1/Model/Questionnaire.php#L617
https://github.com/NetCommons3/Quizzes/blob/3.0.1/Model/Quiz.php#L672
に削除処理が必要かと思います。

**Comment by kteraguchi** [comment]
質問タイプが選択肢じゃないのに、
questionnaire_choices
quiz_choices
quiz_corrects
にデータがあります。

https://github.com/NetCommons3/Questionnaires/blob/3.0.1/Model/QuestionnaireQuestion.php#L307
https://github.com/NetCommons3/Quizzes/blob/3.0.1/Model/QuizQuestion.php#L275
に質問タイプが選択肢か判断する処理をいれるといけそうです。

**Comment by RikaFujiwara** [comment]
削除処理は対応します。
質問タイプが選択系のものではないのに、選択肢データや正解データがあるのはそのままにします。不要といえば不要ですが、あっても動作不具合になるものではないこと、あと処理の単純化のためにとりあえずレコードがある状態を保ちたいと考えています

**Comment by RikaFujiwara** [comment]
小テスト対応済み
https://github.com/NetCommons3/Quizzes/commit/d6fdceda14720697fd9a6b3221cd2068c232084d

**Comment by RikaFujiwara** [comment]
アンケート対応済み
https://github.com/NetCommons3/Questionnaires/commit/b69bcfcda40cb22dcb4e2b7183e06dcd89f9fdfc
