### ISSUE TITLE
登録フォームの不要データ、処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#774]
権限設定機能
registrations/registration_block_role_permissions/edit

は不要な気がしますが。。。

**Comment by kteraguchi** [comment]
BlockSettingの"use_workflow"データも不要と思います。

**Comment by kteraguchi** [comment]
すみません。修正します。
配置したフォームの編集できるケースがありますので、
BlockSettingの"use_workflow"データは必要でした。

権限設定機能では、承認が必要、不要の設定のみ表示し、
"登録フォームを作成できる権限"が不要になるのが正しいと思います。

**Comment by RyujiAMANO** [comment]
配置だけしてフォーム作成しない状態だと、フォームの新規作成もできるようになってるので、フォーム作成もいると思うんですがどうでしょう

**Comment by kteraguchi** [comment]
おおっ！配置だけするケースですか。
了解しました。
closeします。
