### ISSUE TITLE
アンケート,小テストの回答通知を送るチェックボックス

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#776]
アンケート,小テスト作成時に設定する
"回答通知メールを送る"
のチェックと

メール設定タブで設定する
"メール通知機能を使う"
のチェックの関係が少しわかりづらい気がします。

登録フォームは
"このフォームではメール通知は許可されていないため設定できません。 "
の内容が表示されるため、わかる気がします。

アンケート,小テストはルーム毎にメール設定されるので、検討が必要かと思います。

**Comment by RikaFujiwara** [comment]
回答通知メールの設定がメールプラグインに実装されたことにより、アンケート、小テストの編集画面から「回答通知メールを送る」のチェックボックスはなくなりました。

**Comment by RikaFujiwara** [comment]
アンケートにはありました。小テストを除外して、アンケートだけに絞って見なおします。

**Comment by RikaFujiwara** [comment]
アンケート、小テストでは、メール設定タブで設定する「メール通知機能を使う」がOFFのときは、このチェックボックスの表示もされません。
ONのときのみ表示されます。
登録フォームは、ON/OFFに関わらず表示はしておき、もしもOFFのときには「このフォームではメール通知は許可されていないため設定できません。」の注意を出すようにしています。

この部分の仕様に相違があるため、ユーザーを戸惑わせるかもしれませんね。
登録フォームに揃えますか？

**Comment by RikaFujiwara** [comment]
登録フォームに揃えます

**Comment by RikaFujiwara** [comment]
アンケート対応済み
https://github.com/NetCommons3/Questionnaires/commit/d96f405f2b5856525589d8ddcec12017b269a9da

**Comment by RikaFujiwara** [comment]
小テスト対応済み
https://github.com/NetCommons3/Quizzes/commit/e489eb44da8c90135531f50521352ee9f1623264
