### ISSUE TITLE
未利用ファイル、空フォルダ、emptyファイルをどこまで削除するか

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#78]
# 未利用ファイル

FilesプラグインにおけるFilesAppController 

FilesプラグインにはコントローラがないのでFilesAppControllerは使われてない。bake時に生成されたまま

同様にbake時に自動生成されるファイルとしてPluginnameAppModelもある

このファイルはコードカバレッジにも影響すると思われる。
# 空フォルダ

Model/BehaviorやController/Componentなど、実際に配置するファイルが無く、空フォルダのまま存在しつづけているフォルダがある。

カバレッジレポートには影響しないが、これらを残すのか最終的に削除するのか？
# emptyファイル

gitで空フォルダが登録できないために空フォルダにデフォルトでemptyという名のファイルができるが、フォルダが空でなくなったら削除すべきと考えられる。

正式リリースまでに不要PHPコード、不要ctp、空フォルダ、空フォルダ維持の用が済んだemptyファイルの削除をした方が良いと思うのですが、どうでしょうか？

**Comment by kteraguchi** [comment]
はい。削除しましょー。

**Comment by akagane99** [comment]
＋１

**Comment by s-nakajima** [comment]
一旦Closeする。見つけ次第、別途Issueとして挙げる
