### ISSUE TITLE
新着は既存のウィンドウにしたい

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#782]
http://www.netcommons.org/bbv1c16z4-15004/#_15004

NC2は既存ウィンドウだけど、NC3では新規ウィンドウになりました。
何か理由があるのかな。

### 修正案

https://github.com/NetCommons3/Topics/blob/6081a957367091b582027e4f1918b311a02e104c/View/Elements/Topics/item.ctp#L16
```html
<a href="<?php echo $item['topic']['url']; ?>" target="_blank">
↓
<a href="<?php echo $item['topic']['url']; ?>">
```

**Comment by s-nakajima** [comment]
単純に、tagent=_blankを外すだけだと、history backでもっと見るが解除されてしまい、使い勝手が悪いため、別な方法で修正します。
