### ISSUE TITLE
アンケートの集計結果のグラフのテキストが重なってしまい選択肢の文言が読めなくなってしまう。By EDL

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#799]
EDLバグ・要望リストNo44

**Comment by RikaFujiwara** [comment]
選択肢をグラフに表示するのはアンケートプラグインのみの機能なので小テストは対象外とします

**Comment by RikaFujiwara** [comment]
X軸のラベルは斜めに傾けて表示する。
ラベル表示域は選択肢の長さに応じて変更する。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Questionnaires/commit/66179af7ebcc88c36bb597df49170f333c280322

こちらにて対応済み
