### ISSUE TITLE
FilesプラグインのIssueで不要となったIssueのCloseお願いします

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons3#80]
Filesの実装が大幅に変わった結果不要になったIssueがあると思います。

Issueを書かれた方が一番状況わかると思うので、不要になったIssueあったらCloseお願いします。

https://github.com/NetCommons3/Files/issues

**Comment by s-nakajima** [comment]
私が、わかる範囲でCloseしました。

**Comment by s-nakajima** [comment]
@akagane99 
不要になったIssueのCloseお願いします。

**Comment by kteraguchi** [comment]
私の方もCloseしました。

https://github.com/NetCommons3/Files/issues/13
については、ERD反映後Closeします。

**Comment by akagane99** [comment]
遅くなり、すみません。Ｃｌｏｓｅしました。
