### ISSUE TITLE
PageLayoutComponentの処理でFrameごとに処理されるのは遅くなる

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#806]
https://github.com/NetCommons3/Pages/blame/master/Controller/Component/PageLayoutComponent.php#L53

で、Page::getPageWithFrameを呼ぶように修正されています。

https://github.com/NetCommons3/Pages/blame/master/Controller/Component/PageLayoutComponent.php#L70

で、requestActionで呼ばれた場合(Frameの内容取得処理)、抜けているのですが、
Page::getPageWithFrameを呼ぶ前にしないと、処理が重い気がします。

**Comment by s-nakajima** [comment]
キャビネットで、現在のContainerの状態でフォルダを表示するかなど制御しているため、処理をPage::getPageWithFrameをrequestActionの前に持って行った。（PageLayoutHelper::hasContainer使用）

https://github.com/NetCommons3/Cabinets/blob/3.1.0/View/CabinetFiles/index.ctp#L88

何度も呼ばれてしまうので、一度しか呼ばれないように対処する。

**Comment by kteraguchi** [comment]
変わらずPage::getPageWithFrameが毎回実行されています。

https://github.com/NetCommons3/Pages/commit/338544c45e6a8adf7c18d774c7195088d7630183

で、Current::$current に PageLayout.page 情報を書き込んでいるようですが、
requestActionごとに

https://github.com/NetCommons3/NetCommons/blob/3.1.2/Controller/NetCommonsAppController.php#L201
https://github.com/NetCommons3/NetCommons/blob/3.1.2/Utility/Current.php#L350

が呼び出され、 PageLayout.page 情報は毎回 NULL になっています。

https://github.com/NetCommons3/Pages/blob/3.1.2/Controller/Component/PageLayoutComponent.php#L57-L73
の処理は、
https://github.com/NetCommons3/NetCommons/blob/3.1.2/Controller/NetCommonsAppController.php#L174

前に行わないとな気がします。

PageLayoutComponent で、Current:$originalCurrent も書き換えるのでもいけそうです。
