### ISSUE TITLE
コントローラのpublicメソッドは、アクション扱いになるので内部処理で使用するときはprotectedかprivateを使う

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#813]
https://github.com/NetCommons3/Calendars/blob/master/Controller/CalendarsController.php#L145

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Calendars/commit/ecc1db02e0b07cd1ca3019913611828b15a16488
