### ISSUE TITLE
小テストの複数選択問題で、正解チェックボックスデータが正常に登録されない

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#814]
小テストの質問作成画面で、
１．問題の形式を複数選択
２．「新規選択肢1」を変更（「変更した選択肢」とします）
３．「変更した選択肢」の正解にするチェックボックスをON
４．次へをクリックすると、正解を設定してください。エラーで進めないです。

https://github.com/NetCommons3/Quizzes/blob/3.1.0/webroot/js/quizzes_edit_question.js#L570-L580

「新規選択肢1」を変更したときに、正解にするチェックボックスがOFFになるのですが、
quizzes_edit_question.js#L570-L580　に入ってこないので、
「新規選択肢1」がcorrectオブジェクトに残った状態になります。

**Comment by RikaFujiwara** [comment]
対応しました
https://github.com/NetCommons3/Quizzes/commit/2ff48bdc10faf7bb0b87aee6f3668c86d4bb6b52
