### ISSUE TITLE
アンケート、小テストのQuestionEditHelperクラス

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#815]
同名のクラスなので、キャッシュが利用されエラーになることがあります。

１．アンケートの問題編集で、最後の画面まで進み、決定はしない。
２．小テストのページに移動し、小テストの問題編集

で発生します。

Quizzes.QuestionEditHelper ではなく、
キャッシュにあるQuestionnaires.QuestionEditHelper　が利用されるためです。
（逆も同様です。）

キャッシュの処理は、
CakePHPのCore/App.php　でやってます。
App::uses() のやつです。

App::init、App::shutdown　でキャッシュの読み書きしてます。
キャッシュファイルは、app/tmp/cache/persistent/myapp_cake_core_file_map で、
クラス名と、ファイルパスを保存している用です。
１で記録されたパスから、クラスをロードして、２でエラーになる感じです。

クラス名を変えるか、キャッシュをクリアするかが必要です。

他にも同名のクラスがある場合は要注意です。

**Comment by RikaFujiwara** [comment]
小テスト側のクラス名を変更することで対応しようと思います。アンケートはそのまま。作業数減のため。ですが両クラス名は違えることになるので解決になりますよね？
