### ISSUE TITLE
新着の表示設定によってエラー発生

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#817]
表示方法：プラグイン毎に表示する
指定したプラグインのみ表示するチェック：ON
　適当なプラグインをチェック

で決定するとエラーになります。

https://github.com/NetCommons3/Topics/blob/3.1.0/Model/TopicFramesPlugin.php#L107-L127

でPluginモデルとbindしていますが、

https://github.com/NetCommons3/Topics/blob/3.1.0/Model/TopicFramesPlugin.php#L85-L89

で破棄されるため、発生するエラーです。

**Comment by kteraguchi** [comment]
https://github.com/NetCommons3/Topics/blob/3.1.0/Model/TopicFramesPlugin.php#L125

を TopicFramesPlugin::bindModel の前に行うようにしてみましたが、
条件に、'Topic.plugin_key'が指定され、TopicモデルはAssociationに定義されていないので、
結局エラーになりました。

参考まで。

**Comment by kteraguchi** [comment]
https://github.com/NetCommons3/Topics/blob/3.1.0/Controller/TopicsController.php#L178

のSQLが遅いです。
条件も変な気がします。
``` 
'Plugin.key' => 'announcements'
'Topic.plugin_key' => [
      0 => '0'
      1 => 'announcements'
      2 => 'bbses'
      3 => 'blogs'
]
・・・・
```

結果オーライな気もしますが、
``` 
'Topic.plugin_key' => 'announcements'
・・・・
```
で良いのかなと思います。

あと、BlocksLanguageのJOINでIndexが使われてないようなので、
BlocksLanguage.block_id,BlocksLanguage.language_id にIndexを作成するか、
JOINの条件を見直すかで、少し速くなります。

**Comment by s-nakajima** [comment]
下記Commitでインデックス見直し。ただ、一部SQLを見直した方が良さそうな箇所がある。

https://github.com/NetCommons3/Blocks/commit/d958ba146ee32ed5f47fdad7bf74097fb75b83b2
https://github.com/NetCommons3/Topics/commit/48ed6c45a7a9035d7ef0c1f3f8626655d3339305
