### ISSUE TITLE
新着の表示件数

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#818]
最大の表示件数が1,000件のようです。

https://github.com/NetCommons3/Topics/blob/3.1.0/Model/TopicFrameSetting.php#L372

1,000件取得すると、TopicsHelper::camelizeKeyRecursive が遅いです。（15秒ほど）
https://github.com/NetCommons3/Topics/blob/3.1.0/View/Topics/index.ctp#L12

件数を少なくするくらいしかないのかな。

**Comment by kteraguchi** [comment]
PHP7では、同じデータで2.6秒らしい。

**Comment by s-nakajima** [comment]
調査しました。ボトルネックになっているところは、一つ一つは微々たるものですが積み重ねで、遅くなっているようです。特に下記のところが重いようです。
・(new Topic())->statuses
　↑これ自体遅い
・call_user_func(['Inflector', 'variable'], 'display_' . $key);
　↑call_user_funcも遅いけど、Inflector::variable自体、多用すると遅くなる
・Hash::get
　↑単体ではそれほどでもないけど、多用すると遅くなる
・HtmlHelper->image
　↑DisplayUser->avatarが遅くなっている理由はこれ。

HtmlHelper->imageは仕方がないので、無理ですが、それ以外のところを対応し、半分弱は速く(11秒→5秒弱)なりました。ただ、これ以上は無理そうなので、この対応とlimit=100にして「もっと見る」で見れるようにする方向で対応しました。対応方法は、

・(new Topic())->statusesを使わず、constractでメンバ変数にセットする。（Modelと二重持ちになってしまうが）
・Camelizeをやめる
・Hash::getを使わなず、別メソッドを作って対応。

**Comment by s-nakajima** [comment]
上記修正後、同じ条件の約1000件測定でPHP7では、1.4秒ぐらいだった。もともと速かったが、若干速くなった。
