### ISSUE TITLE
お知らせの新規追加で、アップロードされたupload_files.block_key

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#841]
お知らせの新規追加で、アップロードされたupload_files.block_key が空で登録されます。
移行処理では、新規追加になるため、お知らせのupload_files.block_keyが全て空になります。

新規追加時は、まだblock_keyが決まっていないため、仮登録等で、決定時に再更新するなど、対応する場合は、改めて検討した方が良い気がしますが、とりあえずあげときます

**Comment by s-nakajima** [comment]
この https://github.com/NetCommons3/NetCommons3/issues/969 ISSUEと同じ
