### ISSUE TITLE
メニューを均等幅にしてほしい。（ヘッダーとフッターに配置した際）

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#860]
EDLバグ・要望リストNo135

**Comment by s-nakajima** [comment]
追加要望：EDLバグ・要望リストNo136
ページに下層ページがある時、ヘッダーで「タブ」表示をしている際、下層ページはプルダウンで表示されるようにしてほしい。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Menus/commit/c55be1555715ef63f8ea8380c3e5e19c7b46d3a6
https://github.com/NetCommons3/Menus/commit/d16b5d72154aa683a0df9e4184102eaab58e7f3a

**Comment by s-nakajima** [comment]
追加要望：EDLバグ・要望リストNo145
センター揃えにしてほしい。
丸枠（nav-pills）の場合、枠を付けてほしい

**Comment by s-nakajima** [comment]
ある程度、調整はしましたが、ブラウザの仕様（中身の文字やタブの数等）によるものなので、これ以上は無理。

**Comment by kteraguchi** [comment]
表示タイプを、丸み(nav-pills)表示 にして、幅を狭くすると文字がはみ出るようになってます。

https://github.com/NetCommons3/Menus/blob/3.1.2/webroot/css/style.css#L102-L104

の定義の影響です。
修正の履歴見て、何をしたかったのか探ります。

**Comment by kteraguchi** [comment]
~~履歴を見ても良く分からなかったので、~~
```
.menu-header-tabs.nav-justified > li,
.menu-footer-tabs.nav-justified > li {
	width: 7%;
}
```
~~を消します。~~

**Comment by kteraguchi** [comment]
Bootstrapのnav-justified（均等割りの定義）が均等でない問題の対応らしいです。

参考
http://dtp.jdash.info/archives/Bootstrap_nav-justified_CSS_Fixed

ちょっといろいろやってみますが、ダメそうだったら、Bootstrapにお任せにします。

**Comment by kteraguchi** [comment]
http://dtp.jdash.info/archives/Bootstrap_nav-justified_CSS_Fixed

を参考にやってみた。

![image](https://user-images.githubusercontent.com/3079266/28198090-63465b18-6896-11e7-9937-25ccf93fd89e.png)

おおっ！うまくいってるっぽい。
スマホは。。。

![image](https://user-images.githubusercontent.com/3079266/28198146-c1ff34c2-6896-11e7-94da-83d7836c01bf.png)

なんじゃこりゃ。
右に寄ってるし。

っつーことで、ギブアップ。
Bootstrapにお任せにします。
