### ISSUE TITLE
一旦「一時保存」した後、問題文修正・回答追加→「一時保存」しテスト回答しようとしたが、内容修正されていない。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#861]
EDLバグ・要望リストNo99

手順）
１．テストモードで回答を開始する。
２．１で開始中の途中で、別PCもしくは別ブラウザで問題文を修正。
３．１で問題文をリロードする。
４．本来、１でも内容が変わるはずが変わってない。

**Comment by s-nakajima** [comment]
小テストで発生。アンケート、登録フォームは未検証であるが、同じつくりなので、発生すると思うので、とりあえずラベルを付ける。

**Comment by RikaFujiwara** [comment]
小テストには「ページのランダム並び替え出力」「選択肢のランダム並び替え出力」があります。
これを実現するため、試験開始時に（ランダム指定ありなしに関わらず）試験データの任意並び替え処理を通します。
このときセッションに並び替え処理を行った試験データを書きこみ、試験中のリロードはDBからの読みだしではなくセッションからの読みだしを行うようにしているため発生しています。

対処をするとしたら.....
テストモードのときは毎回データベースから読みだす？
しかし、そうするとテストモードのときはランダム並び替えの「試し」にならなくなる

ページのシーケンス番号だけをセッションに取っておいて、
リロード時はとってあったシーケンス番号順にDBデータを並び替える？

しかしそれでもページの増減をされた場合は対応しきれなくなる。（セッションには２→３→１）と記録されていて、読みこみなおしたデータが２ページしかなかったら？もしくは５ページに増えていたら？？

テストモードでの解答を一度始めると最後までやりきらないと、新しい編集結果は反映されませんよ、という仕様で仕切りたいところなのですが、、、、

**Comment by RikaFujiwara** [comment]
編集画面の「一時保存」「決定」が押下され、Saveロジック通るときにセッションの内容をクリアする

**Comment by RikaFujiwara** [comment]
登録フォームは当事象は発生しない

**Comment by RikaFujiwara** [comment]
アンケートではこの事象は発生しない
