### ISSUE TITLE
メール送信内容の置換処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#875]
投稿内容に{X-○○}の置換対象文字列があった場合、画面上は{X-○○}と表示されるが、送信されるメールの内容は、置換された内容になっている。

タイトルは無問題。

https://github.com/NetCommons3/Mails/blob/3.1.0/Utility/NetCommonsMailAssignTag.php#L321-L336

おそらく、この辺りの順番。

**Comment by akagane99** [comment]
ウィジウィグで再現するかんじ。
動作確認する
