### ISSUE TITLE
ルームの並び替えができない

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#885]
サブルームは、ページ設定で並び替えができるが、ルーム自体の並び替えを行うところがない。

**Comment by ghost** [comment]
今、これが問題になりつつあります。是非、次回アップデートで対応をよろしくお願いいたします。

また、以前はルーム内のページが、「ページ設定」ペインの側で階層表示されていたかと思いますが、少なくとも 3.1.3 では階層表示されないため（添付画像）、わざわざ「むさしルーム」に移ってから、「セッティングモードON > ページ設定」という手間が発生しております。（別Issueとして挙がっているか調べ、挙がってなかったら挙げておきます）

![default](https://user-images.githubusercontent.com/7931689/29738061-d33bf5d8-8a54-11e7-9cd0-9726d8f632f1.png)

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/1014
にて修正済み
