### ISSUE TITLE
運用中のサイトで新規プラグインを追加してもプライベートルームでの使用ができない。

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#888]
ルーム管理のプライベート→プラグインの選択
の画面には、新規プラグインがチェックされていても、使用できない。

アップデート処理で、プライベートのルートデータに、新規プラグインを割り当てるが、
各ユーザーのプライベートルームデータには割り当てていいため、この現象が発生する。

プライベート→プラグインの選択　の表示で プライベートのルートデータを表示し、
決定時に各ユーザーのプライベートルームデータには割り当てている。

アップデート処理で、プライベートのルートデータに割り当てなければ、
プライベート→プラグインの選択 のチェックと、つじつまが合うが、
新規インストール後に、手動で設定することになってしまう。

まとめると、インストール時と、アップデート時で、処理を分けるのが良い。

インストールの場合：
　プライベートのルートデータ、および、全ルームのルートデータにプラグインを割り当てる。

アップデートの場合：
　全ルームのルートデータにのみプラグインを割り当てる。

Configure::read('NetCommons.installed') でインストールとアップデートの判断ができる。

**Comment by to-hashimoto-3** [comment]
すいません、これは、Plugin管理側で修正されるべきものなのか、label対象となっている各pluginそれぞれが対処すべきものなのか、いずれになりますでしょうか？

**Comment by akagane99** [comment]
> すいません、これは、Plugin管理側で修正されるべきものなのか、label対象となっている各pluginそれぞれが対処すべきものなのか、いずれになりますでしょうか？

同意。私も知りたいです。
モクモク会の時にでも聞いてみようっと。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues/797
あれ？
上記issueと同一内容なのかなぁ。
プラグインマネジャーに修正入ってるし、もしそうであれば作業いらないのかもです。

**Comment by kteraguchi** [comment]
対処方法から検討です。

#797 
と関係してる程度で、同一内容ではないです。

**Comment by akagane99** [comment]
いつのバージョンからか不明ですが、nc3.1.10では設定可能になっていました。
完了タグつけときます。

![image](https://user-images.githubusercontent.com/2756509/43202191-c969aa34-9055-11e8-9ddd-e03b6d1e4ba2.png)
