### ISSUE TITLE
汎用DBのブロック設定画面で項目移動できなくなる

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#894]
デフォルトのままの項目で一番下の「画像」を
「上に移動」を行うと「画像」のテキストが消え、その後
「１段目に移動」を「画像」の項目にて行っても反応しなくなる。

**Comment by rs-ohno-tomoyuki** [comment]
本件現象を確認しました。現在修正を進めています。

**Comment by rs-ohno-tomoyuki** [comment]
本件修正済みです。
