### ISSUE TITLE
ブロック設定の項目設定

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#896]
下記のように３段目を使用しない（２段目だけを使用しないこともありえる）登録もできるようにするべきでは？ちなみに段の中が空だとエラー（ブラックホール）となり登録できない。

![image](https://cloud.githubusercontent.com/assets/2410721/26716645/3e98dfcc-47b5-11e7-87d8-30f0a5f19914.png)

**Comment by rs-ohno-tomoyuki** [comment]
修正しました。次回Commit/Pushにて反映予定です。
