### ISSUE TITLE
カレンダー予定登録で、毎回Blockデータが追加される

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#898]
Frameデータを必須でなくすように修正 
https://github.com/NetCommons3/Blocks/commit/1a3ed8aa9dd721cdeb82335f7b86507ff8b73665

で、毎回Blockデータが追加されるようになっています。

BlockBehaviorを使用しているのは、CalendarRrule モデルで、
予定編集の場合は、CalendarRrule->save が2回呼ばれるため、以下でエラーが発生してます。
https://github.com/NetCommons3/Blocks/blob/3.1.2/Model/Behavior/BlockBehavior.php#L274
Notice (8): Undefined index: id

1回目のCalendarRrule->save で BlockデータがInsertされ、
2回目のCalendarRrule->save で Update になるため、id が取得できないようです。

編集自体はできているようです。

1回目と2回目のトレースを書いときます。

【1回目】
１．[CalendarActionPlan::saveCalendarPlan](https://github.com/NetCommons3/Calendars/blob/3.1.2/Model/CalendarActionPlan.php#L542)
２．[CalendarPlanGenerationBehavior::makeNewGenPlan](https://github.com/NetCommons3/Calendars/blob/3.1.2/Model/CalendarActionPlan.php#L592)
３．[CalendarPlanGenerationBehavior::__copyRruleData](https://github.com/NetCommons3/Calendars/blob/3.1.2/Model/Behavior/CalendarPlanGenerationBehavior.php#L83)
４．[CalendarRrule::save](https://github.com/NetCommons3/Calendars/blob/3.1.2/Model/Behavior/CalendarPlanGenerationBehavior.php#L159)

【2回目】
１．[CalendarActionPlan::saveCalendarPlan](https://github.com/NetCommons3/Calendars/blob/3.1.2/Model/CalendarActionPlan.php#L542)
２．[CalendarUpdatePlanBehavior::updatePlan](https://github.com/NetCommons3/Calendars/blob/3.1.2/Model/CalendarActionPlan.php#L597)
３．[CalendarCrudPlanCommonBehavior::saveRruleData](https://github.com/NetCommons3/Calendars/blob/3.1.2/Model/Behavior/CalendarUpdatePlanBehavior.php#L671)
４．[CalendarRrule::save](https://github.com/NetCommons3/Calendars/blob/3.1.2/Model/Behavior/CalendarCrudPlanCommonBehavior.php#L53)

BlockBehavior は、CalendarRrule モデルではなく、Calendar モデルで定義するのが良い気がしてますが修正の影響が大きそうです。

**Comment by kteraguchi** [comment]
Calendarテーブルに登録されているblock_keyに合わせた方が良い気がします。
あと、既に追加されたBlockデータは削除しなくて良いですかね？
Migrationで削除しといた方が、後々混乱しないかなと思います。

**Comment by kteraguchi** [comment]
~~あぁ、既に追加されたBlockデータは削除すれば、~~
~~今の修正(https://github.com/NetCommons3/Calendars/commit/188d8920e72f96664a01ea79c42dcc8f5bcc95bc)~~
~~で、Calendarテーブルに登録されているblock_keyと同じデータを取得するようになるのか。~~

**Comment by kteraguchi** [comment]
現状、Calendar.block_key からたどった、Block.room_id と、
Calendar.id からたどった、calendar_rrules.room_id は違うっぽい。
なので、
既に追加されたBlockデータを削除しても、Calendarテーブルに登録されているblock_keyと同じにならない。

Calendar.block_key は不要な気もしてきた。
今の修正(https://github.com/NetCommons3/Calendars/commit/188d8920e72f96664a01ea79c42dcc8f5bcc95bc)
は残しつつ、3.1.3リリースして、別途一回まとめた方が良いです。

**Comment by kteraguchi** [comment]
NetCommons3/NetCommons3#810
が絡む

**Comment by RikaFujiwara** [comment]
2017/07/20 もくもく会にて
カレンダーテーブルのblock_keyがそもそも不要ではないかとの話が出ました。
そうなると calendars テーブルの block_keyをDROPして、これまでのblocksテーブルのcalendarsのレコードをすべて削除するmigrationを書くような変更になります。

ソースコード変更箇所としては
（１）block_keyを参照しているところを変更
（２）BlockBehaiviorを外す

こちらで一度検討する

**Comment by RikaFujiwara** [comment]
過去に出来上がってる不要レコードの削除と、新たなロジックでのblocks, calendarsの整合性とれるレコードを作るマイグレーションが必要

**Comment by kteraguchi** [comment]
Calendar.block_key のField削除も、ありかと思います。
影響が大きそうでしたら、Calendar.block_key を更新するMigrationですね。

```
// calendar_id が同じなのに、room_id が違う、もしくは、
// room_id が同じなのに、calendar_id が違うデータがない前提
$quety = [
    'fields' => [
        'calendar_id',
        'room_id',
    ],
    'group' => [
        'calendar_id',
        'room_id',
    ],
];
$calendarRrules = $CalendarRrule->find('all', $quety);
foreach ($calendarRrules as $calendarRrule) {
    $block = $Block->findByRoomIdAndPluginKey(
        $calendarRrule['CalendarRrule']['room_id'],
        'calendars',
        'key',
        null,
        -1
    );

    // なければ予定追加時に正しいBlockデータが作成される
    if (!$block) {
        coninue;
    }

    $calendar = $Calendar->findById(
        $calendarRrule['CalendarRrule']['calendar_id'],
        [
            'id',
            'block_key',
        ],
        null,
        -1
    );

    // Calendar.block_key が正しくなければ正しい値に更新
    if ($calendar['Calendar']['block_key'] !== $block['Block']['key']) {
        $calendar['Calendar']['block_key'] = $block['Block']['key'];
        $Calendar->save($calendar);
    }

    $crrectBlockKeys[] = $block['Block']['key'];
}

// Block.block_key が正しくないデータを削除
$conditions = [
    'plugin_key' => 'calendars',
    'NOT' => [
        'key' => $crrectBlockKeys
    ]
];
$Block->deleteAll($conditions);
```

で整合がとれると思います。
漏れ、間違い等ありましたら指摘してください。

**Comment by kteraguchi** [comment]
>    // なければ予定追加時に正しいBlockデータが作成される
>    if (!$block) {
>       coninue;
>    }

予定追加するまで、Calendar.block_key が、Blockに存在しない状態が発生するので、良くない。
Block.room_idを更新するような処理の方が良いかも。

**Comment by kteraguchi** [comment]
```
// calendar_id が同じなのに、room_id が違う、もしくは、
// room_id が同じなのに、calendar_id が違うデータがない前提
$quety = [
    'fields' => [
        'calendar_id',
        'room_id',
    ],
    'group' => [
        'calendar_id',
        'room_id',
    ],
];
$calendarRrules = $CalendarRrule->find('all', $quety);
foreach ($calendarRrules as $calendarRrule) {
    $calendar = $Calendar->findById(
        $calendarRrule['CalendarRrule']['calendar_id'],
        [
            'id',
            'block_key',
        ],
        null,
        -1
    );

    $block = $Block->findByKey(
        $calendar['Calendar']['block_key'],
        [
            'room_id',
            'key',
        ],
        null,
        -1
    );

    // Block.room_idが正しくなければ正しい値に更新→使用箇所、影響範囲の調査
    if ($calendarRrule['CalendarRrule']['room_id'], !== $block['Block']['room_id']) {
        Block.room_id更新
    }

    $crrectBlockKeys[] = $block['Block']['key'];
}

// Block.block_key が正しくないデータを削除
$conditions = [
    'plugin_key' => 'calendars',
    'NOT' => [
        'key' => $crrectBlockKeys
    ]
];
$Block->deleteAll($conditions);
```
な感じですかね。
