### ISSUE TITLE
Frameモデルで、BlocksLanguageのbind

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#913]
ヘッダーに何か配置した状態で、アンケートの表示方法変更画面を表示するとエラーになります。

![image](https://user-images.githubusercontent.com/3079266/26969774-e1acb27e-4d41-11e7-8d3f-50356dc6fc45.png)

他のプラグインの表示方法変更画面では、発生しないのが謎で、もうちょい調査します。

**Comment by kteraguchi** [comment]
アンケートの初期処理で、Questionnaire::afterFrameSave がで呼び出され、
Frame::useDbConfig が master 、Frame::BlocksLanguage::useDbConfig が slave のままになっているため、発生するエラーです。


https://github.com/NetCommons3/Frames/blob/3.1.2/Model/Frame.php#L99-L100

で Model::bindModel を使用しているため、NetCommonsAppModel::begin の
Model::useDbConfig 切り替え処理で、Frame::BlocksLanguage::useDbConfig が master にならないです。

Frame::useDbConfig 、Frame::BlocksLanguage::useDbConfig が異なったまま、Model::find されると
JOINではなく、別DBを参照するため、上記のSQLが発行されます。

んで、Frameの結果が存在した場合に、BlocksLanguage::fetchAll でエラー。
Frameの結果が存在しない場合は、fetchせず、Frame::BlocksLanguage::useDbConfig を master に変更し
次の処理に行くため、ヘッダーにFrame を配置した場合のみ、発生します。

参考：
Frame::BlocksLanguage::useDbConfig が master に切り替わる個所
https://github.com/cakephp/cakephp/blob/2.9.9/lib/Cake/Model/Datasource/DboSource.php#L1206


という状況です。
修正法方法は、状況が複雑なので、
https://github.com/NetCommons3/Frames/blob/3.1.2/Model/Frame.php#L99-L100

の後に、

```
$this->BlocksLanguage->useDbConfig = $this->useDbConfig 
```
くらいしか思いつかないです。

**Comment by RikaFujiwara** [comment]
これ、アンケートに限らずafterFrameSaveを使用しているプラグイン全てで発生しませんでしょうか。

アンケート、小テスト、カレンダー

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Frames/blob/3.1.2/Model/Frame.php#L99-L100を下記のようにしてみたらどうでしょうか。

```
$belongsTo = $this->Block->bindModelBlockLang();
$this->bindModel($belongsTo, true);
$this->BlocksLanguage->useDbConfig = $this->useDbConfig;
```
「$this->BlocksLanguage->useDbConfig = $this->useDbConfig;」を追加した感じです。
