### ISSUE TITLE
カレンダーで帯の予定が短いと文字がはみ出ます

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#914]
![image](https://user-images.githubusercontent.com/3079266/27027480-9834f202-4f9c-11e7-91dd-4918b00d859c.png)

CSSの calendar-plan-line クラスセレクタ　に
overflow: hidden

で行けるかと思います。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Calendars/commit/995ca3c9201b2f198e0b77463d576da9c35292e1

こちらにて対応済み
