### ISSUE TITLE
カレンダーの予定を編集すると終了日がおかしい。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#915]
例）
11:00から14:30の予定を編集すると、終了日が11:00になる。

**Comment by s-nakajima** [comment]
11:15～の編集をすると11:00になるらしい。

**Comment by to-hashimoto-3** [comment]
再現確認したところ、こちらではtoの方で分がかわる現象を確認しました。datetimepickerのupdateあたりとの兼ね合いかもしれないので、再度確認見直します。
