### ISSUE TITLE
画像ダウンロードのブラウザキャッシュ

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#917]
画像のダウンロード（ユーザーの~~サムネイル~~アバターを含む）が多いと、リクエスト数が増えるため、
どんどん遅くなるようです。

ブラウザキャッシュを利用しようと思います。

NetCommons3/NetCommons3#880
から派生

**Comment by ryu818** [comment]
これをいれるってことは、ログインしないとみえないアバターが、ログアウトしても見れることになったり、逆にログイン前にみえないアバターが、ログイン後にもみえないまんまにならないっけ？

**Comment by kteraguchi** [comment]
一回キャッシュされると、そうなります。
ログイン前が、NoImage画像で、ログイン後はアップロードしたアバター だとまずいですな。

また、共有PCを同じアカウントで利用した場合も、考慮した方が良いのかな。

もろもろ、もうちょい検討が必要。

**Comment by kteraguchi** [comment]
ブラウザキャッシュは、ちょっと保留で、そもそも WysiwygImageController::download が遅いので確認中。

Current::initialize,PermissionComponent::checkSpaceAccess が遅い感じです。
んで、
WysiwygImageController は、Current::initialize,PermissionComponent::checkSpaceAccess を使わず、
WysiwygImageController の中で、参照できるかチェックする方法が良いのかなと思った。

ちょっとやってみて、別ブランチでPush予定なので、Pushしたら要相談です。

**Comment by kteraguchi** [comment]
Push しました。
問題ないと考えていますが確認したいです。

大丈夫そうだったら、ユーザーのアバターも似たような処理にします。

**Comment by kteraguchi** [comment]
エラーの場合、エラーメッセージが変です。。。
処理自体大丈夫そうだったら、エラーメッセージも直します。

**Comment by kteraguchi** [comment]
エラーメッセージの件、確認しました。

今回の修正で、PermissionComponent::checkSpaceAccess を飛ばしたため、'Not found file' のエラーメッセージが渡されます。（修正前は 'Permission denied' メッセージ）

https://github.com/NetCommons3/Files/blob/3.1.2/Controller/Component/DownloadComponent.php#L113

んで、
https://github.com/NetCommons3/NetCommons/blob/3.1.2/Error/NetCommonsExceptionRenderer.php#L70

で何も出力されないので、変になっていました。
メッセージで、判断するのは違う気もしますがこれは別途。。（Exception で判断した方が良い）

結果としては、正常な動作と思います。

**Comment by kteraguchi** [comment]
お知らせのWYSIWYGに画像14枚アップロードして、修正前と時間を比較してみた。

前回計測
(https://github.com/NetCommons3/NetCommons3/issues/880#issuecomment-308001747)
の環境で、ページを追加し、画像14枚アップロードしたお知らせのみ配置して計測。
Chrome のバージョン上がってた。(59.0.3071.104)

### 修正前(共通初期処理有り)
| 回数  | DebugKit.Timer | Chrome(TTFB) | Chrome(Load) |
| ----- | -------------: | -----------: | -----------: |
| 1回目 | 275ms          | 300.81ms     | 2.59s        |
| 2回目 | 247ms          | 271.24ms     | 2.76s        |
| 3回目 | 277ms          | 296.52ms     | 3,04s        |
| 4回目 | 210ms          | 230.80ms     | 2,73s        |
| 5回目 | 227ms          | 249.88ms     | 2.84s        |


### 修正前(共通初期処理無し)
| 回数  | DebugKit.Timer | Chrome(TTFB) | Chrome(Load) |
| ----- | -------------: | -----------: | -----------: |
| 1回目 | 248ms          | 268.47ms     | 1.67s        |
| 2回目 | 259ms          | 280.82ms     | 1.75s        |
| 3回目 | 237ms          | 269.67ms     | 1,63s        |
| 4回目 | 221ms          | 241.26ms     | 1,78s        |
| 5回目 | 236ms          | 255.48ms     | 1.60s        |

**Comment by kteraguchi** [comment]
アバターの処理もやってみた。

アクション(UsersController::download)の判断処理が必要でした。
（WysiwygImageController::download も同様）

Config/routes.php で Controllerを分けた方が、シンプルになるので、そうします。

**Comment by akagane99** [comment]
主に @kteraguchi さんかな。
画像表示の修正は、ウィジウィグ、アバターと個々に対応してたので、動画のサムネイルもなんかやった方がいいのだろうか？

ウィジウィグ、アバターはごりごり修正されていたので、動画もどうかな？と思いちょっと調べてみたのですが、サムネイル表示は大したことやってなかったです。
https://github.com/NetCommons3/Videos/blob/32628a6b7978d6b6324d1f71b2a8bbdc53287a6a/Controller/VideosController.php#L277

何か改善できるもんなのか、いまいちピンときてないので、モクモク会の時にでも相談のってください。

**Comment by kteraguchi** [comment]
> ウィジウィグ、アバターはごりごり修正されていた

共通処理をすっ飛ばして、必要最低限のチェックとデータ取得しかしないようにしました。

> 何か改善できるもんなのか、いまいちピンときてないので、
> モクモク会の時にでも相談のってください。

了解です。

**Comment by akagane99** [comment]
動画サムネイル、対応の仕方わかったので対応します。

**Comment by akagane99** [comment]
~~ファイル（サムネイル、動画等）のアクセス制御（ダウンロードできるルームに所属してるかどうか等）は共通処理にもっていった方がよさそう。~~
（8/17追記）WysiwygのWysiwygImageDownloadController::downloadで共通化しようと思ったけど、RoomRolePermissionsをSQLで絞ってCurrentにセットする感じだった。
動画で画像を表示する時で、共通化させようとしたら条件異なったため、共通化しない。

### 素案
* Filesプラグインの共通処理
  * コンポーネントに共通処理かくのがベストだろう
  * それでもし具合が悪かったら、共通コントローラ作って継承する

### 参考ソース
https://github.com/NetCommons3/Wysiwyg/commit/d4ae69514f96b92c0e03ac94a33d639ec63243c3

**Comment by kteraguchi** [comment]
WYSIWYGとアバター対応したやつを3.1.3でリリース

**Comment by akagane99** [comment]
動画15件で一覧表示で計測しました。

### 修正前
| 回数  |  Chrome(Load) | 
| ----- |  -----------: | 
| 1回目 |    15.77s     | 
| 2回目 |    13.74s     | 
| 3回目 |    14.25s     | 
| 4回目 |    15.11s     | 
| 5回目 |    14.16s     | 

### 修正後
| 回数  |  Chrome(Load) | 
| ----- |  -----------: | 
| 1回目 |    13.22s     | 
| 2回目 |    13.15s     | 
| 3回目 |    13.33s     | 
| 4回目 |    13.13s     | 
| 5回目 |    16.74s     |
