### ISSUE TITLE
NetCommonsRouterの処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#918]
https://github.com/NetCommons3/NetCommons/blob/3.1.2/Routing/NetCommonsRouter.php#L98-L103

で少し遅くなっています。

ルーティング処理は、常に動作するので、できるだけ軽いにこしたことはないのですが、
NetCommonsRouter の処理が良く分からなかったので、教えてください。
URLの private,community と Page.permalink を何かしてる感じまでは分かりました。　

NetCommons3/NetCommons3#880
の調査途中で気付きました。

**Comment by kteraguchi** [comment]
あと、NetCommonsRouter::parse の各モデル::find で
'callbacks' => false
を渡すと多少早くなります。

Pages.SlugRoute　も同様か。

**Comment by s-nakajima** [comment]
基本、CakePHPでは、/announcements/announcements/view/1/xxxxxxというURLなのですが、
/ページ１/ページ２/announcements/announcements/view/1/xxxxxxとしても、動作するようにした処理です。

**Comment by kteraguchi** [comment]
なるほどです。
試したところ、Missing Controller Error になりました。サブディレクトリが影響してるようです。

NetCommonsRouter の処理は、Pages.SlugRoute::parse にまとめられそうな気がしてます。

とりあえず、現状
/ページ１/ページ２/announcements/announcements/view/1/xxxxxx
のリンクがないので、NetCommonsRouter の処理を消しときます。

/ページ１/ページ２/announcements/announcements/view/1/xxxxxx
のリンクが発生するときに、再検討しましょう。

**Comment by kteraguchi** [comment]
参考までに NetCommonsRouter 処理をなくした場合を計測。


前回計測(https://github.com/NetCommons3/NetCommons3/issues/880#issuecomment-308001747)
を抜粋しようと思ったが、差が少しあったので、改めた。
（Chromeのバージョン,
　localhost での接続より、127.0.0.1 で接続した方がConnection Start 時間が安定する
　などなど。）

## お知らせ(NetCommonsRouter 有り)
　500文字程度(1,424 Byte)
　装飾、添付等なし


| 回数  | DebugKit.Timer | Chrome(TTFB) | Chrome(Load) |
| ----- | -------------: | -----------: | -----------: |
| 1回目 | 293ms          | 314.03ms     | 0.97s        |
| 2回目 | 276ms          | 294.70ms     | 1.03s        |
| 3回目 | 245ms          | 265.26ms     | 1,02s        |
| 4回目 | 255ms          | 279.05ms     | 1,03s        |
| 5回目 | 262ms          | 281.83ms     | 1.02s        |



## お知らせ(NetCommonsRouter 無し)
| 回数  | DebugKit.Timer | Chrome(TTFB) | Chrome(Load) |
| ----- | -------------: | -----------: | -----------: |
| 1回目 | 250ms          | 272.30ms     | 0.97s        |
| 2回目 | 202ms          | 221.94ms     | 0.90s        |
| 3回目 | 245ms          | 266.98ms     | 1,00s        |
| 4回目 | 215ms          | 235.42ms     | 0,92s        |
| 5回目 | 222ms          | 242.61ms     | 0.97s        |


50ms ほど速くなる。微々たることだが、画像のリクエストが連続した場合の影響は結構ある気がする。
