### ISSUE TITLE
Ver3.1.2　ページ設定でページ移動したらエラー発生

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#922]
パブリック空間にルームを作成し、そのルームの下にもページを作る。

TOPページにいるときにページ設定を開くと、パブリックにあるページが全てツリー状に表示される。
このときパブリックルーム下のページも表示されている。
が、パブリック下のページの「↓」「↑」をクリックするとエラー発生する。

**Comment by RikaFujiwara** [comment]
該当のパブリックルームに行って、そこでページ設定を開くとパブリックルーム下のページのみが一覧に表示され、そこでの移動は問題なくできる。

**Comment by RikaFujiwara** [comment]
TOPページで見たときの「ページ設定」でルーム下のページまで表示してるのが誤りでは？

**Comment by kteraguchi** [comment]
https://github.com/NetCommons3/Pages/commit/8aaf9fde7119973e12199d670f9702ec029af58f
https://github.com/NetCommons3/Pages/commit/fae3764847a16a71192db32d6f691ab56ed9432b
https://github.com/NetCommons3/Pages/commit/94a25e9355718f9c94db3bb805f0a61d4b61f1ff

で修正した影響っぽいです。

> TOPページで見たときの「ページ設定」でルーム下のページまで表示してるのが誤りでは？

上記修正の履歴をみると、エラーチェックの誤りのような気もします。
https://github.com/NetCommons3/Pages/blob/3.1.2/Controller/PagesEditController.php#L397-L413
https://github.com/NetCommons3/Pages/blob/3.1.2/Model/Page.php#L397-L426
この辺り。

サブルーム下を表示しないようするか、エラーチェックを修正するかの2択ですね。

影響少ないのは、表示しないようする方ですかね。
https://github.com/NetCommons3/Pages/blob/3.1.2/Controller/PagesEditController.php#L465-L514
のループ内で、親のルームが違うページデータを除外するようにすれば良いのかな。

表示しない方で修正します。

**Comment by kteraguchi** [comment]
1ページもないサブルームにページ追加しようとすると、サブルーム名が表示されなくなりました。。。
見直します。
