### ISSUE TITLE
カレンダーの日付移動のリンクがわかりにくい

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#929]
マウスオーバーで下線やハイライトなどが表示されないため、クリックできることがわかりにくく、下記の日付移動カレンダー表示が迷う

![image.png](https://zube.io/files/netcommons3/6bf61ec5eb7a0baf5d600e0a035024a5.png)

**Comment by to-hashimoto-3** [comment]
ご指摘は、添付画像でいうところの、「２０１７年６月」の箇所に、下線かハイライトがあったほうがよい、ということと理解しましたが、あっておりますでしょうか？

**Comment by s-nakajima** [comment]
はい。その認識であってます。

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Calendars/commit/837bbdb15eb5c09d54f509eb5b6f60317954f050

上記Commitにて対応済み。
ハイライト方式とした。
