### ISSUE TITLE
カレンダー入力の際の日付のデフォルト設定がおかしい

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#931]
新井先生からの指摘：

この現象は、大きなカレンダーではなく、カレンダーをスケジュール表示にし、日付の上のプラスボタンを押したときに起こります。
ああ、スケジュール表示にしたときには、日付のプラスボタンはその日の予定を入れるために置かれているんですね。未来の予定を入れるには、大カレンダーでそこに移動するのが正しいということ？

**Comment by to-hashimoto-3** [comment]
「この現象」とは、
「今日（例：６月21日）に未来の予定を入れよう（例：8月2日）としたときに、
日時指定をクリックすると、デフォルトで始まりと終わりに6月21日が入力され、
始まりを8月2日にしても、終わりが6月21日のままで、そちらも変更しなければならない」
という現象のこととおもいます。
＞手動で変更するのではなく、始まりを編集すると、終わりが過去ひづけだと、
はじまりの同日時以降（例１時間後）になる、
といった改良をさすとおもわれるので、改良見直しをかけたいとおもいます。

**Comment by kteraguchi** [comment]
終日予定（期間・時間の指定チェックなし）を作成した後、
編集画面で、期間・時間の指定チェックをONにすると、
開始が、前日の23:00になっています。

[カレンダー入力の際の日付のデフォルト設定のUIを良くするように対処](https://github.com/NetCommons3/Calendars/commit/205d3a4e7b718466ed9a6f1ea48dbbf3aa2100a6)

の影響かと思います。

開始の変更に、終了が連動するのは良いかと思いますが、
終了の変更に開始を連動させなくて良いかと思います。

**Comment by kteraguchi** [comment]
予定の新規作成の場合、開始が現在時から直近の時間が表示されないです。（00:00です）

処理を見てみたのですが、
https://github.com/NetCommons3/Calendars/blob/205d3a4e7b718466ed9a6f1ea48dbbf3aa2100a6/webroot/js/calendars.js#L492

```
var momentStart = moment($scope.detailStartDate);
```
↓
```
var momentStart = moment($scope.detailStartDatetime);
```
でいけそうな気もしてます。。。。

しかしながら、
HTML要素の
CalendarActionPlanForDispDetailStartDatetime × 2 (hh:mm 有と無)
CalendarActionPlanForDispDetailEndDatetime × 2 (hh:mm 有と無)

calendar.js の
$scope.changeDetailStartDate
$scope.changeDetailStartDatetime
$scope.changeDetailEndDate
$scope.changeDetailEndDatetime
$scope.fixStartTime
$scope.fixEndTime

が複雑に絡んでいて、良いのかどうか判断できなかったです。

**Comment by kteraguchi** [comment]
> 終日予定（期間・時間の指定チェックなし）を作成した後、
> 編集画面で、期間・時間の指定チェックをONにすると、
> 開始が、前日の23:00になっています。

が直ってないです。

**Comment by RikaFujiwara** [comment]
終日予定の場合、再編集の画面では、予備情報の開始時刻、終了時刻の部分は予定日＋現在時刻、＋１時間の時刻にする改修を入れました

https://github.com/NetCommons3/Calendars/commit/b3464d9de03aca4db41df4bb3623e819c19f021f
