### ISSUE TITLE
スケジュール表示で＋をクリックしても追加画面に遷移しない

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#932]

**Comment by to-hashimoto-3** [comment]
この件、画面にカレンダーを配置してから、再現確認してみましたが、スケジュール表示で＋クリックすると、追加画面が表示されした。再現しないので、発生したときの環境か条件が分かればおしえていただけますでしょうか？

**Comment by s-nakajima** [comment]
ごめんなさい。日にちが開閉されて追加画面に遷移してないと思ったら、遅かっただけでした。
日にちが開閉されるのも微妙ですが、追加画面行きました。

**Comment by RikaFujiwara** [comment]
ではこちらのISSUEはCloseとしてよいですか？

**Comment by RikaFujiwara** [comment]
カレンダーの表示全般が遅い#925 というISSUEにまとめるということで、こちらはCloseとさせてもらいます
