### ISSUE TITLE
カレンダー（拡大）で帯表示された予定が隣に重なることがある。

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#933]
カレンダー（拡大）で、帯表示された予定で、予定のタイトルが長い場合、隣の日まで重なってしまう。
（当予定の内容）
タイトル：福島県平田村蓬田小学校
予定日：2017年06月27日(火) 00:00－2017年06月28日(水) 00:00

![image.png](https://zube.io/files/netcommons3/88d2ee74bad954997758fdd9f2f2785c.png)

**Comment by RikaFujiwara** [comment]
https://github.com/NetCommons3/Calendars/commit/995ca3c9201b2f198e0b77463d576da9c35292e1

上記コミットで対応済み

**Comment by RikaFujiwara** [comment]
#914 duplicate
