### ISSUE TITLE
サイト管理：入会・退会設定で「予期せぬTokenエラー」が発生する

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/NetCommons3#935]
以下の状況の場合のみ発生する。
（１）入会・退会設定で、任意に表示のON/OFFが切り替えられる状態の「項目A」を表示ONにして決定
（２）会員項目設定で　先ほど入会退会設定で表示ONの項目として設定していた「項目A」を「必須」項目として設定する
（３）再度、入会退会設定を開く。このとき「項目A」は（必須なので）切り替えはdisabledになって表示ONで固定されている。
　　このとき、決定するとTokenエラーが発生する。
　　「最初は意図的に表示ON設定だが、現在はDisabledで表示ON固定」の項目が存在するときのみ発生する模様。

デフォルト表示ON固定のものは value=''でPOSTされている
意図的に表示ONに操作されたものはvalue=1でPOSTされている
意図的に表示OFFに操作されたものはvalue=0でPOSTされている
最初に意図的に表示ON設定されて、その後必須項目に変更されたものは　value=’true'でPOSTされている
disabledであるにも関わらず有意な値がPOSTされているのがTokenエラーの原因なのか？

**Comment by RikaFujiwara** [comment]
項目A　は　「名前」の項目しか相当しないみたい。
デフォルト設定されている値がもんだいなのかも

**Comment by akagane99** [comment]
facebookから修正待ってるわ〜との声がありました
