### ISSUE TITLE
PHP 7.1.4だと、お知らせプラグインに記事を書けない

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#938]
さくらのレンタルサーバにNetCommons 3.1.2をインストールしました。
同レンタルサーバで PHP 7.1.4 を選択すると、お知らせプラグインに記事が書けません。
PHP 5.6.30 を選択すると、記事が書けます。
[公式サイトのヘルプデスクへも投稿しました](http://nc2.netcommons.org/bb1sc01e0-18477/#_18477) ←スクリーンショットあります。

> ラベルの付け方がわからない...w

**Comment by kteraguchi** [comment]
#942 
で吸収すると思われます。

**Comment by akagane99** [comment]
原因なんだろ？

・お知らせのphp7.1のテスト結果、正常でした。
https://travis-ci.org/NetCommons3/Announcements/builds/247822636

・xampp7.1.6でNetCommons3(2017/6/16時点)のgithubソースをインストールして、お知らせ編集したところ、クルクルをちょっと長めに待ってから以下のエラーになりました。
（追記）php7.1.6です。
```
予期しないトークンにより、登録が正常にできませんでした。
ページが自動的に更新されない場合はこちらをクリックしてください。
```

とりあえずここまで

**Comment by akagane99** [comment]
xamppでのerror.logを追記
```
2017-06-30 10:51:39 Error: [BadRequestException] The request has been black-holed
Request URL: /announcements/announcements/edit/1?frame_id=1
Stack Trace:
#0 C:\projects\xampp7.1.6\htdocs\vendors\cakephp\cakephp\lib\Cake\Controller\Component\SecurityComponent.php(243): SecurityComponent->blackHole(Object(AnnouncementsController), 'csrf')
#1 C:\projects\xampp7.1.6\htdocs\vendors\cakephp\cakephp\lib\Cake\Utility\ObjectCollection.php(128): SecurityComponent->startup(Object(AnnouncementsController))
#2 C:\projects\xampp7.1.6\htdocs\vendors\cakephp\cakephp\lib\Cake\Event\CakeEventManager.php(243): ObjectCollection->trigger('startup')
#3 C:\projects\xampp7.1.6\htdocs\vendors\cakephp\cakephp\lib\Cake\Controller\Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#4 C:\projects\xampp7.1.6\htdocs\vendors\cakephp\cakephp\lib\Cake\Routing\Dispatcher.php(189): Controller->startupProcess()
#5 C:\projects\xampp7.1.6\htdocs\vendors\cakephp\cakephp\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(AnnouncementsController), Object(CakeRequest))
#6 C:\projects\xampp7.1.6\htdocs\app\webroot\index.php(106): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
```

* 再度お知らせを編集したところ、正常に編集できた。
* 新しいページを作り、お知らせプラグインを配置、お知らせ登録→正常に登録できた。
  * 1回目だけエラーになる？？謎です。

**Comment by akagane99** [comment]
* xampp7.1.6
  * php7.1.6
  * NetCommons3.1.2
    * 新規インストール
    * プライベートルームにお知らせを配置、お知らせの内容を登録→正常に登録できた。
    * その後、TOPページの「NetCommonsへようこそ」お知らせも編集→正常に編集できた。

（追記）トラビステストとxamppのお知らせ書き込みできる状況から、php7.1は問題なさそう。

うーん、さくらレンサバで試さないと原因わからそうです。

**Comment by akagane99** [comment]
さくらレンサバの2週間無償期間を利用して動作確認してみました。

・お知らせの登録、編集、動画の登録をした所、php7.1だとクルクルで処理返ってこない。
・・1度でもやると、TOPページに再度アクセスしても、読み込んだまま何も表示されない。
・・サーバのプロセスを確認した処、phpのプロセスがCPU100%に。
・・Announcementのmodelで`$this->validates()`するとCPU100%で返ってこなくなる。
・・・（推測）Announcementのvalidateか、behaviorsのどっかで止まってるけど特定できず。

・初期インストール、ページの追加、プラグインの配置はphp7.1でできるのでDB書き込みはできる

(7/3追記)
以下推測
・phpの問題であることは確か
・・xamppのphp7.1.6で問題ない事から、もしかしたらphp7.1.4のバグかも
・・もしくはさくらインターネットのphp7.1.4のライブラリに何か原因がある？

うーん原因特定までいたらず、ギブアップ。

**Comment by kteraguchi** [comment]
原因特定の糸口見つけました。

https://github.com/NetCommons3/Wysiwyg/blob/3.1.2/Model/Behavior/PurifiableBehavior.php#L392

HTMLPurifier::purify で何かがおこっているらしい。

まずは、ここまで。

**Comment by kteraguchi** [comment]
https://github.com/ezyang/htmlpurifier/releases

htmlpurifierでv4.9.3 が出てたので、差し替えたら登録できました。

次回リリースでは、v4.9.3 になります。

**Comment by kteraguchi** [comment]
参考までに、デバッグ方法書いときます。

```
var_dump(999);exit;
```
を
AnnouncementsController::edit の Announcement::saveAnnouncement 前に書いたら、999 が出力された。
Announcement::saveAnnouncement の Announcement::validates の前に書いても、999 が出力された。
Announcement::saveAnnouncement の Announcement::validates の後に書いたら、クルクルが終わらなくなった。
Announcement::beforeValidate の先頭に書いてもクルクルが終わらない。

ということは、Announcement のアソシエーションモデル、
もしくは、利用しているBehaviorの beforeValidate  で何かが起こっている。

アソシエーション、Behavior の定義を順番に消して試す方法もあるかと思いますが、消すことで別の問題発生することもあるので、別の方法でデバッグしました。

問題のない環境(PHP5.6)でCakeEventManager で beforeValidate を呼び出す順番を確認
https://github.com/cakephp/cakephp/blob/2.9.9/lib/Cake/Event/CakeEventManager.php#L240
の前に
```
if ($event->name() == 'Model.beforeValidate') {
	var_Dump($listener['callable']);
}
```
https://github.com/cakephp/cakephp/blob/2.9.9/lib/Cake/Utility/ObjectCollection.php#L129
の前に
```
if ($callback == 'beforeValidate') {
	var_dump($this->modelName, $name);
}
```
を書いてお知らせを登録すると以下が出力されます（内容は省略してあります。）
```
array (size=2)
  0 => 
    object(BehaviorCollection)[240]
      public 'modelName' => string 'Announcement' (length=12)
  1 => string 'trigger' (length=7)
array (size=2)
  0 => 
    object(BehaviorCollection)[198]
      public 'modelName' => string 'Block' (length=5)
  1 => string 'trigger' (length=7)
string 'Block' (length=5)
string 'OriginalKey' (length=11)
string 'Block' (length=5)
string 'Trackable' (length=9)
string 'Block' (length=5)
string 'NetCommonsValidationRule' (length=24)
array (size=2)
  0 => 
    object(Block)[196]
  1 => string 'beforeValidate' (length=14)
string 'Announcement' (length=12)
string 'Block' (length=5)
string 'Announcement' (length=12)
string 'OriginalKey' (length=11)
string 'Announcement' (length=12)
string 'M17n' (length=4)
string 'Announcement' (length=12)
string 'Workflow' (length=8)
string 'Announcement' (length=12)
string 'Trackable' (length=9)
string 'Announcement' (length=12)
string 'NetCommonsValidationRule' (length=24)
string 'Announcement' (length=12)
string 'WorkflowComment' (length=15)
string 'Announcement' (length=12)
string 'MailQueue' (length=9)
string 'Announcement' (length=12)
string 'Topics' (length=6)
string 'Announcement' (length=12)
string 'Purifiable' (length=10)
string 'Announcement' (length=12)
string 'Wysiwyg' (length=7)
array (size=2)
  0 => 
    object(Announcement)[239]
  1 => string 'beforeValidate' (length=14)
array (size=2)
  0 => 
    object(BehaviorCollection)[663]
      public 'modelName' => string 'Topic' (length=5)
  1 => string 'trigger' (length=7)
string 'Topic' (length=5)
string 'Trackable' (length=9)
string 'Topic' (length=5)
string 'NetCommonsValidationRule' (length=24)
string 'Topic' (length=5)
string 'Purifiable' (length=10)
array (size=2)
  0 => 
    object(Topic)[659]
  1 => string 'beforeValidate' (length=14)
array (size=2)
  0 => 
    object(BehaviorCollection)[663]
      public 'modelName' => string 'Topic' (length=5)
  1 => string 'trigger' (length=7)
string 'Topic' (length=5)
string 'Trackable' (length=9)
string 'Topic' (length=5)
string 'NetCommonsValidationRule' (length=24)
string 'Topic' (length=5)
string 'Purifiable' (length=10)
array (size=2)
  0 => 
    object(Topic)[659]
  1 => string 'beforeValidate' (length=14)
```

次に、問題のあるサイトでデバッグ
https://github.com/cakephp/cakephp/blob/2.9.9/lib/Cake/Utility/ObjectCollection.php#L129
の前に
```
if (get_class($this) == 'BehaviorCollection' &&
	$this->modelName == 'Announcement' &&
	$callback == 'beforeValidate'
) {
	var_dump($name,$result);

	if ($name == 'Purifiable') {
		exit;
	}
```

$name == 'Purifiable' の部分を、呼び出す順番から、ちょこちょこ変えていくと、
PurifiableBehavior で クルクルが終わらなくなったため、
PurifiableBehavior::beforeValidate をデバッグしたどり着きました、
