### ISSUE TITLE
日付指定がおかしくなる

### ISSUE THREAD

**Issue by ryu818** [NetCommons3/NetCommons3#945]
カレンダーで、二日間にわたった予定をいれる際に
「2017年07月06日(木) 00:00	  －  2017年07月07日(金) 00:00」として登録した。
そうすると、カレンダーで７日の予定にはないと判断されます。
23:59分と記載しないといけないという仕様だとすると不親切すぎます。

それからそこで7日まで表示しようとしてToを「2017年07月07日(金) 23:59」に編集しようとすると、Toを編集しようとしているのになぜかFromが７日にもどされます。

これだと気づかないうちにまったく異なった日付の予定が編集されてしまうことになり
カレンダーとしては思い通りに予定の追加もできない致命的なものだと思います。

**Comment by A11creATor-** [comment]
すいません、こちら少し誤解があるかと。
まずは、仕様を説明させていただきます。
カレンダーは、以上ー未満でみています（ＮＣ２の仕様を踏襲）
7/6,7/7の２日間のデータを入れる場合、内部的には、7/6 （木）00:00以上,  7/8(金) 00:00未満、です。
(23:59といれられうことを、想定して「いません」。ＮＣ２のデータも2359以下ではなく、翌日0000未満としては入っていますので、ＮＣ３もそれに倣っています）
できれば、見た目はＮＣ２の、7/6 （木）00:00以上,  7/7(金) 24:00　とい２４時表記にしたかったのですが、
datetimepickerに～7/7(金) 24:00という表記がないので、整合性をとるため、～7/8(土) 00:00
としております。また、datetimepickerのメモリも１分刻みだと、煩雑になるので、５分刻みできってorimasu.

23:59といれることを想定していないのは、datetimepickerの５分刻みから
ユーザーには理解できるとおもっていたのですが、、、
誤解を生むようなので、、なんらかの工夫は必要かとおもいました。検討してみます。

そこの仕様

**Comment by ryu818** [comment]
あまり理解できておりませんが、
2日にわたる終日の予定をいれる場合、1日先まで記入しなければならない仕様と理解しました。
よくわかりませんが、最初の終日の予定を最初からFrom-Toを表示すればよいのではと思いました。

あと、後者の内容（勝手に日時が戻される）の仕様も検討お願いいたします。

**Comment by RikaFujiwara** [comment]
現在は、終了時刻を変更しているときに開始時刻よりも前の時刻を指定すると、開始時刻を終了時刻よりも前の時刻に自動的になるようなロジックにしています。
これは余計なお世話仕様になっちゃうかな

**Comment by RikaFujiwara** [comment]
FROMを修正したときはFROMの１時間後にTOがなるように自動修正入るようにして、
TOを修正したときは、何も勝手に変えない（Like GoogleCalendar）という仕様の方向で進めます

**Comment by ryu818** [comment]
2日にわたる終日の予定をいれる場合、1日先まで記入しなければならない仕様についてではなく、勝手に日時が戻される仕様については承知しました。
