### ISSUE TITLE
ページ設定、追加したパブリックルームのページを上下移動させると不正なリクエスト

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#948]
* github最新ソース（2017/7/3 10:00）で動作確認
* パブリックルーム[パブ２ルーム]を追加する
* TOPページから、ページ設定に入る
  * [パブ２ルーム]にページを2個追加
  * [パブ２ルーム]のページを上下移動させると不正なリクエストになる

```
不正なリクエストの可能性があります。
ページが自動的に更新されない場合はこちらをクリックしてください。
```

ページ追加はできたので、上下移動もさせて良いかと思います。
とりあえず報告まで。

**Comment by RikaFujiwara** [comment]
確かページ並び替えの仕様検討時にいたときの話し合いで、
「ルーム内のページの並びかえは、そのルームにいるときしかできない」＝（ルーム内ページの操作は、そのルームに行かないとできない）
って決まった記憶があります。

この問題は、どっちかっていうと
TOPページ（＝パブリックスペース親ルーム）にいるのに、その中にあるパブリックルームの中のページをそこで開いてしまって居ることにあるんじゃないかな？
実際、パブリックルームの中に行ったら、そこでページの並び替えとかできたので。

**Comment by akagane99** [comment]
> TOPページ（＝パブリックスペース親ルーム）にいるのに、その中にあるパブリックルームの中のページをそこで開いてしまって居ることにあるんじゃないかな？
> 実際、パブリックルームの中に行ったら、そこでページの並び替えとかできたので。

ルールベースで言えばその通りっすね。
パブリックのサブルームのみ特殊な感じがしていて、安直にバグ修正なら

* パブリックのサブルームは、親パブリックで「ルーム名」は表示するけど、サブルームへのページ追加、サブルーム配下のページ上下移動はできなくする。

でしょうか。

将来的にはページ設定の中で、各ルームに直移動してページ設定が出来るのが良いかなぁと思いました。
（ページ設定、他のルームも並べ替えたい時にちょっと操作しずらいんですよね。
ルーム毎にページ移動→セッティングモードON→ページ設定で、目的のルームのページ設定にたどり着く。しかし、上記手順を踏めば設定できるので優先事項じゃないと思います）

**Comment by akagane99** [comment]
同じバグのissueあったため、クローズ
https://github.com/NetCommons3/NetCommons3/issues/922
