### ISSUE TITLE
施設設定の説明WYSIWYGが英語

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#949]
多分、これと同様の処理がいるのかと思います。（未確認ですみません。）

https://github.com/NetCommons3/Announcements/blob/3.1.2/webroot/js/announcements.js#L21

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Reservations/pull/32/files
対応しました。

修正後画面
![image](https://user-images.githubusercontent.com/2756509/47158490-c01acd00-d326-11e8-9b82-308c608c83a7.png)
