### ISSUE TITLE
一般権限の会員が他の会員情報を閲覧できない

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#952]
NetCommons 3.1.2（以下NC3）にシステム管理者として、一般権限の会員を複数名登録した上で、「権限管理」→「一般」→「個人情報の確認」で氏名などを「他の会員の情報も閲覧できる」と設定しました。

ここで、一般権限の会員としてNC3にログインし、「管理」→「会員管理」と操作して他の会員情報を閲覧したいのに、「管理」メニューがないため「会員管理」にたどりつけず、他の会員情報を閲覧できません。（あるいは操作方法が間違っている?）
　※会社などの組織でNCを使う場合、社員の情報を相互に閲覧できる必要があります。

↓にスクリーンショット付きで説明しました（ご参考まで）
https://nc2.netcommons.org/bbikqxs0a-18477/#_18477

**Comment by ghost** [comment]
例えば、赤沢と小林というふたりの一般会員を同じルームに所属させた状態で、赤沢でNCにログインしても小林は見えてきません。というか、他の会員を閲覧するためのメニュー（入り口）そのものが存在しません。今回はNetCommons 3.1.3で確認しました。
![ippan-members](https://user-images.githubusercontent.com/7931689/28500046-26ac680a-6ffd-11e7-943c-5dbeebce746d.png)

**Comment by akagane99** [comment]
nc2から3になって変わった仕様のように思えます。

https://github.com/NetCommons3/NetCommons3/issues/953#issuecomment-315960202
nc3の場合、会員管理を使えると他人の編集までできるようになった。と読み取れました。

なので一般の他人が見れるとは、他人が投稿したブログ記事等に表示される、投稿者のリンクで見れるもの。かと思えました。

**Comment by ghost** [comment]
うむむ、仕様なら仕方ないですね。
でも、そうすると、なぜ「権限管理」の画面で細かに非公開／閲覧可／編集可の設定をできるようにしてあるのか理解できないですね。

いずれにしても私のタスクとしては会員一覧プラグインを作らねばならないですね（汎用DBで作るという手もありですが）。

**Comment by ToshiAkaz** [comment]
00inbox:

**Comment by akagane99** [comment]
> でも、そうすると、なぜ「権限管理」の画面で細かに非公開／閲覧可／編集可の設定をできるようにしてあるのか理解できないですね。

さわったみてわかったのは、一般は他ユーザの「非公開／閲覧可」いずれか項目ごとに設定可能。
管理者は「編集可」のみ固定でした。
なので実質は、一般の「非公開／閲覧可」の設定のみできるようです。

細かい設定が残ったおかげで、nc2の時にあった会員一覧プラグインを作れる余地があるのは良いですね。

**Comment by ghost** [comment]
ユーザカンファレンスのワークショップではこのこともお伝えしたいと思います。
