### ISSUE TITLE
「会員管理プラグイン」という表記が理解しにくい

### ISSUE THREAD

**Issue by ghost** [NetCommons3/NetCommons3#953]
システム管理者として NetCommons 3.1.2にログインし、「権限管理」→〈一般〉右横の「編集」→「個人情報の設定」と進むと、説明書きの箇所に「ただし、会員管理プラグインが使用できる場合は」とありますが、「会員管理プラグイン」というプラグインをセッティングモードで配置できるかのような誤解を招きます。

セッティングモードで「会員管理プラグインを配置すると会員情報を閲覧できるようになる」のかなと考えましたが、会員管理プラグインというのは、セッティングモードではプラグインの一覧に表示されませんでした。

説明書きに「会員管理プラグイン」と表記されているのは、NC開発時の用語が残ったものではないでしょうか。実際に指し示しているものは「管理」→「会員管理」メニューではないでしょうか。もし、そうであれば「会員管理メニュー」など実際のものとして感じ取れる表記にすることを提案します。

**Comment by akagane99** [comment]
確かに改めて説明読んでみると、ちょっと意味が判りずらいですね。
ここ確認してみたら、「権限の追加」でベース権限をサイト管理者にする時も同じ文を表示してました。
そうなると中々言葉に迷いますね。。

とりあえず修正案考えてみました。
問題なければプルリクエスト作成かなぁと思います。

### 修正案
他の会員の情報を閲覧させるかどうか設定できます。ただし、会員管理メニューを使用できる場合は、すべての会員のパスワードを除く全項目の閲覧及び編集、パスワードを編集できます。

### 現在
他の会員の情報を閲覧させるかどうか設定できます。ただし、会員管理プラグインが使用できる場合は、すべての会員のパスワードを除く全項目の閲覧及び編集、すべての会員のパスワードを編集できるため、ここでは、設定できません。

![image](https://user-images.githubusercontent.com/2756509/28301164-873258b6-6bbf-11e7-9ec5-a0b3eb53a1da.png)

**Comment by ghost** [comment]
日本語表現では係り受けがわかりにくいのと、例外的なことを含めて一文に収めようとすると理解に困難を来します。そこで修正案2を提案します。

**修正案2**
他の会員の情報を閲覧させるかどうか設定できます。ただし、ここで設定したとしても、会員管理メニューを使用できる権限を持つ会員は、すべての会員の全項目の閲覧と編集ができます（パスワードについては閲覧はできず編集だけができます）。

**Comment by akagane99** [comment]
おお！既にプルリク投げましたが、いい修正案ですね。
こっちでまた作り直そうと思います。

**Comment by akagane99** [comment]
あっ、修正の入ったissueはクローズせず、正式リリースした後にまとめてクローズしていく運用をしていたりします。
なので再オープンさせてもらいますね。
