### ISSUE TITLE
cakeコマンドで実行されるプログラムのエラー

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#954]
メール送信機能、Migration 機能　など、cake コマンドで実行されるプログラムについてですが、
cake シェルで、実行される php コマンド(cgiのやつ) の設定をチェックした方がよいかもです。

インストール時にいろんなチェックをしてるっぽいので、そこで一緒にできないものかと思います。

たまたま、発生した問題を上げときます。
・apacheのmoduleで組み込まれている環境は問題なし
・phpコマンドのパスが古いPHPを指している（php-mysqlのライブラリなし）
インストール時のチェックはOKだけど、MigrationでDBに接続できずエラーになる。

とりあえず情報として上げときます。

**Comment by akagane99** [comment]
nc3.1.3で確認しました。
インストール画面で対応されてるような気がするんだけど、どうなんだろう？

### 環境
xampp1.8.3
  + PHP 5.5.15 (VC11 X86 32bit thread safe) + PEAR 
  ↑こっちには

バージョンチェック（CLI）でphp7.0.3って出るのは、windowsに直インストールしたphp
php_mysql入ってなくてエラーになってる。
（ここのバージョンチェック、cakeコマンドで確認しているらしく、cakeコマンドのバッチの中身を修正して、xamppのphpコマンドのパスを直書きすると通ります）

![-](https://user-images.githubusercontent.com/2756509/28298984-73492324-6bb1-11e7-8760-a8b8180a9427.png)

**Comment by kteraguchi** [comment]
あぁ、対応してました。勘違いです。すみません。
