### ISSUE TITLE
プラグイン管理とシステム管理、アップデートすると不正なリクエスト

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#956]

**Comment by akagane99** [comment]
管理画面から、プラグイン管理とシステム管理のアップデートを押すと不正なリクエストエラーになった。

nc3.1.3で確認。

**Comment by kteraguchi** [comment]
https://github.com/NetCommons3/PluginManager/blob/3.1.3/Controller/PluginManagerController.php#L78-L80

で
$plugins['type2'] のデータの中に、Plugin.type が 3 のデータが存在する。

んで、
https://github.com/NetCommons3/PluginManager/blob/3.1.3/View/Elements/PluginManager/plugins.ctp#L75

で、
plugin_manager/plugin_manager/view/2/plugin_manager
のリクエストが送信され、
https://github.com/NetCommons3/PluginManager/blob/3.1.3/Controller/PluginManagerController.php#L179

で、Plugin.type:2 AND Plugin.key:plugin_manager のデータが取得できずエラー。

Plugin.type:3 AND Plugin.key:plugin_manager が正しいと思うので、
```
<a href="" ng-click="showView('<?php echo $pluginType; ?>', plugin.plugin.key)">
```
↓
```
<a href="" ng-click="showView(plugin.plugin.type, plugin.plugin.key)">
```
で良い気がするが、わざわざ
```
'<?php echo $pluginType; ?>',
```
にした経緯がありそうなので、要確認。

**Comment by kteraguchi** [comment]
https://github.com/NetCommons3/PluginManager/commit/b5afa28aead1d62c9dd31b1fa65440974cc3727f

で、Plugin.type:3(PLUGIN_TYPE_FOR_SYSTEM_MANGER) が追加された際の、修正漏れと思われるので、
上記修正でOKと思います。
