### ISSUE TITLE
汎用DBの項目追加時に選択肢の追加ができない

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#962]
https://github.com/NetCommons3/Multidatabases/blob/3.1.3/webroot/js/edit_multi_database_metadatas.js#L163

で、currentMetadata.selections が配列じゃないのでエラーになっています。

https://github.com/NetCommons3/Multidatabases/blob/3.1.3/Model/MultidatabaseMetadataEdit.php#L227

```
'selections' => '',
```
↓
```
'selections' => [],
```

で直ると思います。
pushしちゃっても良いです？

**Comment by rs-ohno-tomoyuki** [comment]
修正しました。後ほどCommit/Pushします。
