### ISSUE TITLE
汎用DBでエクスポートタブのリンク切れ

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#963]
https://github.com/NetCommons3/Multidatabases/commit/c6cca8a8f1d417111f2b223f84781aadfac710c7#diff-f250678f8b5f2e92dbb11db327c2f045L88

で、edit action がなくなってます。
戻せばOKと思います。

**Comment by rs-ohno-tomoyuki** [comment]
確認しました。ご指摘の通りedit actionが無くなったことによるものでした。
修正しましたので、次回commit/pushで反映されます。
