### ISSUE TITLE
汎用DBのインポート処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#964]
４点あります。

### 1.NetCommonsTimeの使用でNotice Error が発生します。
https://github.com/NetCommons3/Multidatabases/blob/3.1.3/Controller/MultidatabaseContentImportsController.php#L203

NetCommonsTime::getUserTimezone がstaticじゃなくなってます。
https://github.com/NetCommons3/NetCommons/commit/c9eab81b12b2826666253fe04d596f1c30e25a64#diff-67400687a5b9c35c0efdc968bf716ba4

```
$commonDat['_NetCommonsTime']['user_timezone'] = NetCommonsTime::getUserTimezone();
```
↓
```
$commonDat['_NetCommonsTime']['user_timezone'] = (new NetCommonsTime())->getUserTimezone();
```
で直りますが、$commonDat['_NetCommonsTime']['user_timezone']　は使ってない気がします。
使ってなければ削除しましょう。

### 2.AttachmentBehaviorの使用でNotice Error が発生します。
https://github.com/NetCommons3/Multidatabases/blob/3.1.3/Model/MultidatabaseContent.php#L85

DBに登録しないと思うので、AttachmentBehavior は使わなくて良いと思います。

### 3.Vlidationされてない気がします。
https://github.com/NetCommons3/Multidatabases/blob/master/Model/MultidatabaseContent.php#L296

の前に
```
$this->set($data);
if (! $this->validates()) {
    return 継続するならtrue,止めるならfalse;
}
```
な感じですかね。

### 4.csvデータの最後の1件のみ登録されます。
http://www.kaasan.info/archives/2543
の件だと思います。

https://github.com/NetCommons3/Multidatabases/blob/master/Model/MultidatabaseContent.php#L296
の前に
```
$this->create();
```
で直ると思います。

**Comment by rs-ohno-tomoyuki** [comment]
1と2は、次回Commit/Pushにて修正予定です。
3は、対応予定です。行うValidationは、必須チェック程度です。
4は、現在対応中です。

**Comment by rs-ohno-tomoyuki** [comment]
1,2,4は、次回Commit/Pushにて反映されます。

**Comment by tabimoba** [comment]
全てCommit/Pushし、リポジトリへ反映しました。
