### ISSUE TITLE
施設予約の時間割表示でtable要素の罫線がずれる

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#965]
![image](https://user-images.githubusercontent.com/3079266/28655533-7d9ad408-72d7-11e7-842d-988f0705dd4f.png)

~~https://github.com/NetCommons3/Reservations/blob/3.1.3/webroot/css/reservations.css#L834~~
https://github.com/NetCommons3/Reservations/blob/3.1.3/webroot/css/reservations.css#L835
を消すとうまくいきました。

**Comment by kteraguchi** [comment]
施設別の週表示で発生しました。
windows10
Chrome,FireFox,Microsoft で発生しました。

時間枠のデータは、
1時限目:9:00 ~ 10:00
2時限目:10:00 ~ 11:00

![image](https://user-images.githubusercontent.com/3079266/28701765-51fa2df0-7393-11e7-91e7-7b95805095ad.png)

追加情報まで。

**Comment by RyujiAMANO** [comment]
ありがとうございます。MacChromeでは発生しないので気づきませんでした。

**Comment by RyujiAMANO** [comment]
https://github.com/NetCommons3/Reservations/blob/3.1.3/webroot/css/reservations.css#L835 を消すとズレはなくなるが、タイムラインのスクロールができなくなる
