### ISSUE TITLE
繰返し予定の編集で sending=true

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#966]
繰り返し予定の編集で、
〇 この予定のみ
〇 これ以降に指定した全ての予定
〇 設定した全ての予定
のラジオボタンがあります。

スペック低いサーバーだと、ラジオボタンを変更してResponseが返ってくるまでちょっとかかります。
その間に、決定をクリックすると SecurityComponent::blackHole になります。

https://github.com/NetCommons3/Calendars/blob/3.1.3/View/Helper/CalendarPlanEditRepeatOptionHelper.php#L103-L109
```
'ng-click' => ’sending=true’,
```
追加すれば決定がdisabledになるので、解決です。

施設予約も同様です。

**Comment by kteraguchi** [comment]
```
'ng-click' => ’sending=true’,
```
やって動作確認してみたら、見た目はdisabledになるが、clickできた。。。。
ボタンの属性見てみたら、
```
ng-class="{disabled: sending}"
```
おぉ、見た目だけ変えてる。

https://github.com/NetCommons3/NetCommons/blob/3.1.3/webroot/js/base.js#L166-L168
```
if ($scope.sending) {
          $event.preventDefault();
}
```
で、$scope.sending がtrueになってないっぽい。
お知らせでも、キャンセルクリック後、すぐ一時保存クリックすると、一時保存された。

ちょっと、ややこしくなってきたので、とりあえず
```
'ng-click' => ’sending=true’,
```
を追加してpushしときます。

**Comment by RikaFujiwara** [comment]
sending=true ではなく、「changeEditRrule」の中でボタンなど、変に操作されないように直接的にdisabledに属性変更をしてみました。この対応でいかがでしょう？
