### ISSUE TITLE
ウィジウィグで画像アップロードしてもupload_filesテーブルにセットされてない項目がある

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/NetCommons3#969]
なんかへんなデータなのでバグかなぁと思いました。

対象プラグインは、ウィジウィグ使ってるプラグインで、全プラグインチェックしてないです。
確認したお知らせ、ブログにラベル付けました。
とりあえず報告まで。

### お知らせ、ブログ

* ウィジウィグで画像アップロードしても`upload_files.content_key`が`NULL`になる。
* ウィジウィグで画像アップロードしても`upload_files_contents`にデータできない。

### お知らせ
* ウィジウィグで画像アップロードしても`upload_files.block_key`が空でセットされてる。
  * ブログでは`upload_files.block_key`に値セットされてました。

**Comment by s-nakajima** [comment]
> ウィジウィグで画像アップロードしてもupload_files.block_keyが空でセットされてる。

編集で新たにアップロードしたときは、正しくセットされる
