### ISSUE TITLE
環境チェック処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#97]
PHP5.3環境でアクセスしたところ、
Fatal error: Exception thrown without a stack frame in Unknown on line 0
のエラーが発生しました。

何かしらの、環境チェック処理が必要なのですが、
上記エラーの発生個所が
https://github.com/NetCommons3/NetCommons3/blob/32726c8cd902e9b8099510e7b7da78e02459e798/app/Config/bootstrap.php#L27

/vendors/autoload.phpで発生しているため、環境チェック処理について要検討です。

**Comment by s-nakajima** [comment]
多少のライブラリチェックはInstallで行うように改修済み

ただ、このエラーは、対処できない気がする。対処方法があれば良いけど、無ければCloseでも良いと思う。
