### ISSUE TITLE
ダウンロードパスワードがつけられない？

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#973]

**Comment by rs-ohno-tomoyuki** [comment]
確認しましたが、ダウンロードパスワードの設定は行えました。どのような条件下で発生しましたでしょうか。

**Comment by s-nakajima** [comment]
パスワード入力欄がないのですが。どうやって、パスワードを入力するのですか？


![image.png](https://zube.io/files/netcommons3/e0376c4ad202110ba9e05fcb8bd26a0f.png)

**Comment by rs-ohno-tomoyuki** [comment]
新規登録時には発生しませんので、アップロード済みファイルが存在する状態において当該問題が発生しているものと思います。状況を確認します。

**Comment by rs-ohno-tomoyuki** [comment]
確認しました。こちらでは現象再現できませんでした。
NC3のバージョンによる影響もあるかもしれませんので、最新版で確認します。
（こちらで開発に利用しているNC3が古いため、現象が発生していない可能性も考えられます）
![image](https://user-images.githubusercontent.com/23375820/28754398-76320b28-757f-11e7-88c4-ca586cfa8dd8.png)

**Comment by rs-ohno-tomoyuki** [comment]
開発版の最新版と思われる環境(myshellのinstall.sh実行後の状態)で確認しました。現象再現しませんでした。

NetCommon3のバージョン：
NetCommons: dev-master	(5cbc1eb357)

Webブラウザは、Google Chrome（バージョン: 60.0.3112.78（Official Build） （64 ビット））を使用しています。
他のブラウザでの挙動を含め、引き続き確認してみます。

**Comment by rs-ohno-tomoyuki** [comment]
wysiwygをなくすと現象発生を確認

**Comment by rs-ohno-tomoyuki** [comment]
調整を行いました。次回Commit/Pushにて反映されます。
wysiwygプラグインは、wysiwygフィールド（フォーム部品）が１つもないとエラーになるようです。
このため、Wysiwygの有無をチェックし、Wysiwyg有りと無しで読み込まれるjsを分けました。
