### ISSUE TITLE
コンテンツとの区切りがわかりにくい

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#975]
それぞれの段の間隔と、次のコンテンツとの間隔に差がほとんどなく、わかりにくい。
以前（先生が検収した際）は、もっと、段と段の間隔がなく、一体感があったが、いまは、一体感がなく、変。

![スライド1.PNG](https://zube.io/files/netcommons3/f82362c17b5b1c34ddb5b47ad114e33f.png)

**Comment by rs-ohno-tomoyuki** [comment]
段の間隔については、次回commit/pushにて修正を反映します。
「詳細を表示」の下は検収時と同じ間隔ですので、そのままとなります。
