### ISSUE TITLE
項目列の幅が広すぎる

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/NetCommons3#977]
最長、今ぐらいで、あとは文字数に応じて、成り行きになるのが良いです。文字数が少ないと少し変です。

![スライド3.PNG](https://zube.io/files/netcommons3/2330772ced2db3a6ff2f96d967c444c6.png)

**Comment by rs-ohno-tomoyuki** [comment]
項目列とは、「概要」「カテゴリ」の部分でしょうか。 
列幅は、#976 と同様の理由となりますが、現状BootstrapのGridの幅を採用しています。
列幅を固定することは可能ですので、それでいかがでしょうか。（対応は #976 と重複します）

文字数に合わせて項目列の幅を調整することは可能ですが、可変とすると、段ごとに異なる幅となり、表示がガタガタになります。

**Comment by rs-ohno-tomoyuki** [comment]
項目列の幅を150px固定にする方針で対応予定です。表示結果は以下の通りとなります。
![image](https://user-images.githubusercontent.com/23375820/29149381-b820806e-7dae-11e7-87bb-08ab0d52bdf4.png)
![image](https://user-images.githubusercontent.com/23375820/29149387-c5506632-7dae-11e7-8c79-4b0ce607520b.png)

**Comment by s-nakajima** [comment]
min-widthやmax-widthを使って調整することは厳しかったってことですか？
でも、このIssueも考慮すると、固定にしないとダメかもしれませんね。https://github.com/NetCommons3/NetCommons3/issues/976

固定なら、8文字ぐらいで調整してください。

**Comment by rs-ohno-tomoyuki** [comment]
文字数に合わせて見出し幅を調整するようにしました。
（最大文字数を取得し、各フィールドのthのwidthを最大文字数に合わせるようにしました）
なお、最小文字数は全角４文字(8rem)としました。
次回commit/pushにて反映されます。
