### ISSUE TITLE
WYSIWYGのdl,dt,dd タグ

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons3#981]
WYSIWYGでdl,dt,dd タグが除去されます。

https://github.com/NetCommons3/Wysiwyg/blob/3.1.3/Model/Behavior/PurifiableBehavior.php#L249
にolタグの設定があるので、同様に
```
'dl[compact|start|type],' .
'dt[compact|start|type],' .
'dd[compact|start|type],' .
```
を追加すれば、大丈夫ですが、dl,dt,dd タグって何かありましたっけ？

単純な定義漏れなら追加しときます。

**Comment by kteraguchi** [comment]
定義の書き方が
```
要素名[属性名|・・・]
```
でした。
なので、追加するなら
```
'dl[compact],' .
'dt,' .
'dd,' .
```
ですね。

**Comment by akagane99** [comment]
`<video>`タグの`controlsList="nodownload"`でクロームのダウンロード不可の対応~~も、WYSIWYGのタグ除去で消えちゃってました。~~
https://github.com/NetCommons3/NetCommons3/issues/783#issuecomment-298300216
→ （追記）上記埋め込みタグは'<iframe>'タグだったから大丈夫でした。失礼！でも`<video>`タグ対応したいなぁ。

修正は多分下記に追記っぽい。
https://github.com/NetCommons3/Wysiwyg/blob/3.1.3/Model/Behavior/PurifiableBehavior.php#L419

```php
			$def->addElement('video', 'Block',
				'Optional: (source, Flow) | (Flow, source) | Flow', 'Common', array(
					'src' => 'URI',
					'type' => 'Text',
					'width' => 'Length',
					'height' => 'Length',
					'poster' => 'URI',
					'preload' => 'Enum#auto,metadata,none',
					'controls' => 'Bool',
					'controlsList' => 'Text',  // ←ここ追記
				)
			);
```

**Comment by akagane99** [comment]
お知らせのウィジウィグで書けたけど、何か手順違うのかなぁ。
```html
<dl compact="compact">
<dt>項目をここに書きます</dt>
<dd>ここに項目の説明などを書きます</dd>
<dt>項目２</dt>
<dd>サンプルサンプルサンプル</dd>
<dt>項目３</dt>
<dd>サンプルサンプルサンプルサンプル</dd>
<dt>項目４</dt>
<dd>サンプルサンプルサンプルサンプルサンプル</dd>
</dl>
```

### 画像
![image](https://user-images.githubusercontent.com/2756509/29505758-135f72c8-8683-11e7-90ce-333092e928b3.png)

**Comment by akagane99** [comment]
HTMLタグ使用権限がない場合（一般とか）で、dlとか書き込めませんでした。
一般でdlを書いても問題ないと思いますので、書けるように修正プルリクエスト投げました。
２，３日で問題なければ、マージしようと思ってます。

HTMLタグ使用権限がある場合（システム管理者でルームでスクリプト書き込み許可とか）は、修正前でもdlタグかけてました。
