### ISSUE TITLE
管理画面のお知らせの表示内容

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#982]
管理画面に表示されるお知らせの内容は何が表示されているのでしょうか？
現在NC2のときの内容がのっているようなのですが、おそらくNC2のURLがかわっているため、NC3のトップに飛んでしまいます。
またNC3になってから投稿したブログなどの内容は載っていないです。
よく見ると掲示板などの内容も飛んでいるように見えます。

今の画面が正解ではないようなきがするのですが、どの画面が表示されるのが正しいのでしょうか？

**Comment by s-nakajima** [comment]
NC3のお知らせが表示されるのが正しいです。修正します。
