### ISSUE TITLE
テンプレートをダウンロード→インポートができない

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#985]
アンケートのテンプレートをダウンロードし、テンプレートを読み込んでアンケートを作成しようとしても読み込みができません。
ダウンロードしたファイルはzipが永遠に続いている感じで、文字化けしているような感じがします。
正しい手順をご教授いただきたく、またはバグなのであれば修正願います。

**Comment by RikaFujiwara** [comment]
すみません、どのようなテンプレートでしたでしょうか。
もしよかったらテンプレートをいただけますか？
なお、小テストのエクスポート、インポートで、うまくいかない事象が出て、調べてみたら、WysiswygプラグインのUtility側に問題が発生していたことがわかりました。
その問題には対応し、最新ソースはGitにUPしています。

**Comment by onozaki** [comment]
ご返信ありがとうございます。
投稿からだいぶバージョンが上がって、再度検証してみた結果無事にテンプレートを読み込むことができました。
なので、こちらのissueはクローズで良いかとおもいます。

ただ一つ確認したいのですが、テンプレートタイトルが日本語だとダウンロードした際に文字ばけします。
アンケートの際英語のタイトルのケースは少ないと思うので、日本語も保持されると良いかと思ったのですが、これは難しいのでしょうか？
（ただダウンロードして文字化けしたものでも、日本語に再度書き換えてインポートが可能だったので、対策としてはひと手間かければ大丈夫ですが）

**Comment by RikaFujiwara** [comment]
うーん？いま、ローカルで試してみたのですが、アンケートのテンプレート、日本語で化けずにZIPファイルがダウンロードされました。何か環境？でしょうか
化けてしまったファイル名や、NC3のバージョンは何でしょうか

**Comment by onozaki** [comment]
ご返信ありがとうございます。
NC3のバージョンは最新の3.1.8です。
化けてしまったファイル名は添付した画像の真ん中の「甘いものリサーチ」というもので、上下にある「sese」や「tesy」に関しては文字化けしません。
macだからか？とwinでも試してみましたが、日本語は文字化けします。
![2018-05-29 9 05 12](https://user-images.githubusercontent.com/30645702/40632362-0852c3e6-6321-11e8-924c-3a36cdfa44ea.png)

また、これは別スレッドがすでにあるか立てる必要があるかと思いますが、IEの場合、pdfなども日本語のファイル名だと、macだろうがwinだろうがダウンロードする際に文字化けしてしまいます。
![moji](https://user-images.githubusercontent.com/30645702/40632406-c0264380-6321-11e8-9e87-c031c6c9efd7.png)

**Comment by onozaki** [comment]
追記です！
pdfDLの文字化けの件、もしかして#1232と同じ内容ですかね？
3.1.9でリリースされそうな感じなので、そちらで確認してみます。

**Comment by onozaki** [comment]
さらに追記です。
文字化けのあるアンケートの「甘いものリサーチ」というもの、機種別ブラウザ別でも確認したので以下にまとめます。
×が文字化けしたものです。

＜mac＞
FireFox　→　×
クロム　→　×
safari　→　○

＜win＞
FireFox　→　×
クロム　→　○
IE　→　○

**Comment by RikaFujiwara** [comment]
これはまさに #1232 と同じ現象ですので、こちらもCloseとさせていただきます
