### ISSUE TITLE
汎用DBのメタデータ編集がわかりにくい

### ISSUE THREAD

**Issue by rs-ohno-tomoyuki** [NetCommons3/NetCommons3#986]

**Comment by rs-ohno-tomoyuki** [comment]
メタデータ編集時、どこをクリックすれば編集できるのかがわかりにくい。
閉じているときは「＞」、開いているときは「∨」で検討する。
※カレンダーのスケジュール表示を参考に

![image](https://user-images.githubusercontent.com/23375820/28914415-88ff3af6-7876-11e7-98b4-5c0502f70588.png)

**Comment by s-nakajima** [comment]
忘れないように補足。
1段目の1行目を最初から展開させておく。

**Comment by rs-ohno-tomoyuki** [comment]
調整しました。commit&push済
