### ISSUE TITLE
ページ内リンク（ジャンプ）の設定方法

### ISSUE THREAD

**Issue by onozaki** [NetCommons3/NetCommons3#992]
NC2ではページ内リンク（ジャンプ）を設定することができたのですが、NC3ではそういったことは設定できるのでしょうか？
また、仕様としてできない場合、つける方法などあるのでしょうか？
現在NC3公式サイトを作成中につき、どなたかわかる方、早めのご回答お願いできれば助かります。

**Comment by akagane99** [comment]
リンクならこのボタンで出来ますよ～。これであってるのかなぁ？
もしくは`<A>タグ`のnameで飛ぶやつかなぁ。
nc2でどうやってたのか判れば、他の人も回答しやすいと思います。
![image](https://user-images.githubusercontent.com/2756509/29161862-c28f9154-7df2-11e7-8ca3-dcdaf567d3be.png)

**Comment by onozaki** [comment]
ご回答ありがとうございます、またご指摘ありがとうございます。
おっしゃるとおりです、言葉足らずでした。
まさにその「<A>タグのnameで飛ぶやつ」です。

あまりhtmlに詳しくないので専門用語でご説明ができないのですが、NC2では飛ばしたい場所のモジュールのtable IDをみて、そのIDをURLの最後にくっつけて、以下のようなアドレスにして指定のモジュールに飛ばすようにしていました。

http://www.netcommons.org/【#_123】←この部分にIDを入れていました。

その方法と同様のリンクの仕方をNC3でも行いたいのですが、方法がわからずご質問しました。
再度ご回答いただけますと助かります。

**Comment by RikaFujiwara** [comment]
NC3でもできますよ。

＞NC2では飛ばしたい場所のモジュールのtable IDをみて
これはデベロッパーツールとか使って、HTMLのタグ内のIDを見てらっしゃったんですかね？

NC3ではFrameのところに 
```
<section id="frame-7">
```
 とか書かれてるんで、frame-7 を＃以降に書くイメージです

**Comment by onozaki** [comment]
ご回答ありがとうございます。
#　の以下にframe-7などを書くと飛ばすことができました。
ありがとうございます。
